begin

delete from p#busfw_t_uitable t where t.key in('/pmkpi/index/list');
insert into busfw_t_uitable (GUID, KEY, TABLECODE, PAGENUM, TOTALTAG, LOCKNUM, ORDERBY, DEFQUERY, APPID, CONFIG)
values ('FF7631A4CBDA48DAB46CEE6A84AA1C5F', '/pmkpi/index/list', 'V_BAS_PERF_INDICATOR', 0, 0, 0, null, null, 'pmkpi', null);

delete from p#busfw_t_uicolumn t where t.key in('/pmkpi/index/list');

insert into busfw_t_uicolumn (GUID, KEY, COLUMNCODE, NAME, ORDERNUM, ISVISIABLE, ISEDIT, TOTALTAG, SHOWLEVEL, REQUIREMENT, COLTYPE, HEAD, FORMAT, DEFAULTVALUE, LEVELCONTROL, COLWIDTH, ISSOURCE, TYPE, CONFIG, BOTTOMCONTRL)
values ('F2134EFF507A49A9AC95E12597983F16', '/pmkpi/index/list', 'COMPUTESIGN', '计算符号', 4, 1, 0, null, '', null, null, '', '#name', '', null, null, 1, 'tree', '{}', '');

insert into busfw_t_uicolumn (GUID, KEY, COLUMNCODE, NAME, ORDERNUM, ISVISIABLE, ISEDIT, TOTALTAG, SHOWLEVEL, REQUIREMENT, COLTYPE, HEAD, FORMAT, DEFAULTVALUE, LEVELCONTROL, COLWIDTH, ISSOURCE, TYPE, CONFIG, BOTTOMCONTRL)
values ('BC4232A45CEF4E8E9B93D37A24A5D5B7', '/pmkpi/index/list', 'FINDEX', '一级指标', 1, 1, 0, null, '', 1, null, '', '#name', '', null, null, 1, 'tree', '{}', '');

insert into busfw_t_uicolumn (GUID, KEY, COLUMNCODE, NAME, ORDERNUM, ISVISIABLE, ISEDIT, TOTALTAG, SHOWLEVEL, REQUIREMENT, COLTYPE, HEAD, FORMAT, DEFAULTVALUE, LEVELCONTROL, COLWIDTH, ISSOURCE, TYPE, CONFIG, BOTTOMCONTRL)
values ('E26282C70E394D2881C6C3AB47D24E8C', '/pmkpi/index/list', 'INDEXVALUE', '指标值', 5, 1, 0, null, '', null, null, '', '#name', '', null, null, 1, 'tree', '{}', '');

insert into busfw_t_uicolumn (GUID, KEY, COLUMNCODE, NAME, ORDERNUM, ISVISIABLE, ISEDIT, TOTALTAG, SHOWLEVEL, REQUIREMENT, COLTYPE, HEAD, FORMAT, DEFAULTVALUE, LEVELCONTROL, COLWIDTH, ISSOURCE, TYPE, CONFIG, BOTTOMCONTRL)
values ('B008A6728D77452DBB9B35B14204A6FF', '/pmkpi/index/list', 'METERUNIT', '计量单位', 6, 1, 0, null, '', null, null, '', '', '', null, null, 0, 's', '{}', '');

insert into busfw_t_uicolumn (GUID, KEY, COLUMNCODE, NAME, ORDERNUM, ISVISIABLE, ISEDIT, TOTALTAG, SHOWLEVEL, REQUIREMENT, COLTYPE, HEAD, FORMAT, DEFAULTVALUE, LEVELCONTROL, COLWIDTH, ISSOURCE, TYPE, CONFIG, BOTTOMCONTRL)
values ('609681BE782B4A1BB174AC0EEF813E90', '/pmkpi/index/list', 'NAME', '三级指标', 3, 1, 0, 0, '', 1, null, '', '', '', null, 220, 0, 's', '', '');

insert into busfw_t_uicolumn (GUID, KEY, COLUMNCODE, NAME, ORDERNUM, ISVISIABLE, ISEDIT, TOTALTAG, SHOWLEVEL, REQUIREMENT, COLTYPE, HEAD, FORMAT, DEFAULTVALUE, LEVELCONTROL, COLWIDTH, ISSOURCE, TYPE, CONFIG, BOTTOMCONTRL)
values ('88117A63F1264C9CAF48427DA5B16933', '/pmkpi/index/list', 'SINDEX', '二级指标', 2, 1, 0, null, '', null, null, '', '#name', '', null, null, 1, 'tree', '{}', '');


delete from p#busfw_t_uieditform t where t.key in('/pmkpi/index/edit');
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('B412538A82D562E3E0535164A8C0C98B', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 'textarea', '指标值说明', 'VALUE_DESC', 1, null, 1, null, 40, 3, '3', 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('B412538A833962E3E0535164A8C0C98B', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', '单位id', 'AGENCY_CODE', 0, null, 0, null, 51, null, null, 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('B412538A833A62E3E0535164A8C0C98B', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', '年度', 'FISCAL_YEAR', 0, null, 0, null, 53, null, null, 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('B412538A833B62E3E0535164A8C0C98B', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', '区划', 'MOF_DIV_CODE', 0, null, 0, null, 58, null, null, 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('B412538A839D62E3E0535164A8C0C98B', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', '创建时间', 'CREATETIME', 0, null, 0, null, 41, null, null, 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('B412538A839E62E3E0535164A8C0C98B', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', '是否共性指标', 'IS_COMMON_IND', 0, null, 0, null, 42, null, null, 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('B412538A839F62E3E0535164A8C0C98B', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', '是否删除', 'IS_DELETED', 0, null, 0, '2', 43, null, null, 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('B412538A83A062E3E0535164A8C0C98B', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', '是否启用', 'IS_ENABLED', 0, null, 0, '1', 44, null, null, 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('B412538A83A162E3E0535164A8C0C98B', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', '启用日期', 'START_DATE', 0, null, 0, null, 45, null, null, 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('B412538A83A262E3E0535164A8C0C98B', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', '停用日期', 'END_DATE', 0, null, 0, null, 46, null, null, 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('B412538A83A362E3E0535164A8C0C98B', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', '绩效指标主键', 'IND_ID', 0, null, 0, null, 47, null, null, 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('B412538A83A762E3E0535164A8C0C98B', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', '编码', 'PERF_IND_CODE', 0, null, 0, null, 59, null, null, 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('A8028459A1DF4DF2965D67EA00F63892', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 'tree', '层次分类', 'SINDEX', 1, null, 1, null, 3, null, null, 'pmkpi', 1, 0, '{format:''#name''}', 0, 1, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('49F4832CBDE44739B09E23F1C41A0E1C', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', '指标名称', 'PERF_IND_NAME', 0, null, 0, null, 1, null, null, 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BF5EB36C5FCE937FE053B11FA8C04F08', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 'tree', '指标体系', 'FRAMESYSTEM', 1, null, 1, null, 2, null, null, 'pmkpi', 1, null, '{format:''#name''}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('A8028459A1DF4DF2965D67EA00F63892', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 'tree', '一级指标', 'FINDEX', 0, null, 0, null, 18, null, null, 'pmkpi', 1, 0, '{format:''#name''}', 0, 1, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('85236C46012F45E39B26ED4038C65785', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', '计量单位', 'METERUNIT', 1, null, 1, null, 5, null, null, 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('099DFA0B1EAD4565A67D3273B6C5BFA2', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 'tree', '计算符号', 'COMPUTESIGN', 1, null, 1, null, 4, null, null, 'pmkpi', 1, null, '{format:''#name''}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('13402A2269A542CE9C521727DDC8BE1F', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', '指标值', 'KPI_VAL', 0, null, 1, null, 6, null, null, 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('9475C52455BA460CAF0CD3A886C062CC', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', '创建人', 'CREATER', 0, null, 0, null, 11, null, null, 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('5083E22FA16943F091D62225970DF9DC', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', '创建时间', 'CREATE_TIME', 0, null, 0, null, 52, null, null, 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('550B81FFC3094B88BEF801DCEF5A9CEF', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', '状态', 'STATUS', 0, null, 0, null, 13, null, null, 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('11B37377E8AE4C4E92D03E136CD7FAA8', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', '单位id', 'AGENCYGUID', 0, null, 0, null, 50, null, null, 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('E0AA52EBB458485386335B33406C2D0C', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', '年度', 'YEAR', 0, null, 0, null, 15, null, null, 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('C862D1C2BB014801A2512D25A35D7980', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', '区划', 'PROVINCE', 0, null, 0, null, 16, null, null, 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('2AB703247CF9449B93B2639CC6E5B8BA', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', 'guid', 'GUID', 0, null, 0, null, 17, null, null, 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('B412538AA09362E3E0535164A8C0C98B', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', '指标名称', 'NAME', 1, null, 1, null, 1, null, null, 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('B412538AA09462E3E0535164A8C0C98B', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', '编码', 'CODE', 0, null, 0, null, 59, null, null, 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('B412538AA09562E3E0535164A8C0C98B', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', '指标值', 'INDEXVALUE', 1, null, 1, null, 6, null, null, 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('B412538AA09662E3E0535164A8C0C98B', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 'textarea', '指标值说明', 'INDEXREMARK', 0, null, 0, null, 40, 3, '3', 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('B412538AA09362E3E0535164A8C0C98B', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', '父级id', 'PARENT_ID', 0, null, 0, null, 60, null, null, 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('B412538AA09462E3E0535164A8C0C98B', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', '级次', 'LEVEL_NO', 0, null, 0, null, 61, null, null, 'pmkpi', 1, null, '{}', null, null, null);
insert into BUSFW_T_UIEDITFORM (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('B412538AA09562E3E0535164A8C0C98B', '/pmkpi/index/edit', 'V_BAS_PERF_INDICATOR', 's', '是否末级', 'IS_LEAF', 0, null, 0, null, 62, null, null, 'pmkpi', 1, null, '{}', null, null, null);
delete from busfw_t_uiqueryform t where t.key in('/pmkpi/index/list');
insert into busfw_t_uiqueryform (GUID, KEY, COLUMNCODE, NAME, ORDERNUM, ISVISIABLE, TYPE, DEFAULTVALUE, LINKCHILD, LINKPARENT, APPID, TABLECODE, CONFIG, BOTTOMCONTRL)
values ('F4E6E6C2791D464E88234DFBE509303D', '/pmkpi/index/list', 'NAME', '名称', 1, 1, 's', null, null, null, 'pmkpi', 'V_BAS_PERF_INDICATOR', null, null);

