begin

delete from bus_t_diccolumn t where t.tablecode='PERF_T_CASE' and t.columncode in('AGENCYGUID','FRAMESYSTEM','BUSTYPE','ISADJUST','FININTORGGUID','WFSTATUS','ADJUSTGUID','WFID','LASTUPDATETIME','IS_DELETED','AUDITOR','CASETYPE','STATUS');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '1', 'AGENCYGUID', '1', '2016', '87', '3BA168DAEA384A71A23FC10A0BC33B35', 'AGENCYGUID', 'PERF_T_CASE', '单位', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ADJUSTGUID', '1', '2016', '87', 'E2A5CA708BFC131DE0533315A8C01809', 'ADJUSTGUID', 'PERF_T_CASE', '调整前guid', 'S', '40', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AUDITOR', '1', '2016', '87', 'E2A5CA708BF2131DE0533315A8C01809', 'AUDITOR', 'PERF_T_CASE', '审核人', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIFRAMESYSTEM', null, '1', 'BUSTYPE', '1', '2016', '87', '56655D90192B49B4B89D649635CFF58A', 'BUSTYPE', 'PERF_T_CASE', '指标体系', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PERFGXCLASSIFICATION', null, '1', 'CASETYPE', '1', '2016', '87', '3AEAB74080584B968B424104B4FC0467', 'CASETYPE', 'PERF_T_CASE', '案例类型', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '099003', null, '1', 'FININTORGGUID', '1', '2016', '87', 'E2A5CA708BF5131DE0533315A8C01809', 'FININTORGGUID', 'PERF_T_CASE', '处室', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ISADJUST', '1', '2016', '87', 'E2F5483E6B402CBAE0533315A8C00CB1', 'ISADJUST', 'PERF_T_CASE', '是否调整', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_DELETED', '1', '2016', '87', 'E2A5CA708BFD131DE0533315A8C01809', 'IS_DELETED', 'PERF_T_CASE', '是否删除', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LASTUPDATETIME', '1', '2016', '87', 'E2A5CA708BF6131DE0533315A8C01809', 'LASTUPDATETIME', 'PERF_T_CASE', '时间戳', 'S', '17', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PERFDATATYPE', null, '1', 'STATUS', '1', '2016', '87', '626C53272A494EC7882535E9C81574BA', 'STATUS', 'PERF_T_CASE', '状态', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WFID', '1', '2016', '87', 'E2A5CA708BF9131DE0533315A8C01809', 'WFID', 'PERF_T_CASE', '工作流id', 'S', '40', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIWFSTATUS', null, '1', 'WFSTATUS', '1', '2016', '87', 'E2A5CA708BFA131DE0533315A8C01809', 'WFSTATUS', 'PERF_T_CASE', '工作流状态', 'S', '40', null, 1, 1, null, sysdate);

delete from bus_t_diccolumn t where t.tablecode='PERF_T_CASEMODELINDEX' and t.columncode in('IS_DELETED','ADJUSTINDEXGUID','STATUS','VALUE_CHANGE','INDUSTRYCATEGORY','REMARK');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ADJUSTINDEXGUID', '1', '2016', '87', 'E2F5483E6CCC2CBAE0533315A8C00CB1', 'ADJUSTINDEXGUID', 'PERF_T_CASEMODELINDEX', '调整前指标guid', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_DELETED', '1', '2016', '87', 'E2F5483E6A792CBAE0533315A8C00CB1', 'IS_DELETED', 'PERF_T_CASEMODELINDEX', '是否删除', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PERFDATATYPE', null, '1', 'STATUS', '1', '2016', '87', '2BB4E0BFABAD4D4AB759381EEA0CDB62', 'STATUS', 'PERF_T_CASEMODELINDEX', '状态', 'S', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'INDEXCOMFUNC', null, '1', 'INDUSTRYCATEGORY', '1', '2016', '87', 'E37F581A53002C17E0533315A8C0BDDA', 'INDUSTRYCATEGORY', 'PERF_T_CASEMODELINDEX', '功能科目', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'REMARK', '1', '2016', '87', 'E37F581A535A2C17E0533315A8C0BDDA', 'REMARK', 'PERF_T_CASEMODELINDEX', '备注', 'S', '2000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PERFVALUECHANGE', null, '1', 'VALUE_CHANGE', '1', '2016', '87', 'E2F5FB4E3BDA3BC7E0533315A8C0582E', 'VALUE_CHANGE', 'PERF_T_CASEMODELINDEX', '指标值变动情况', 'S', '40', null, 1, 0, null, sysdate);

delete from bus_t_diccolumn t where t.tablecode='PERF_T_CASEMODELGOAL' and t.columncode in('IS_DELETED');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_DELETED', '1', '2016', '87', 'E2F5483E6ADD2CBAE0533315A8C00CB1', 'IS_DELETED', 'PERF_T_CASEMODELGOAL', '是否删除', 'N', '1', null, 1, 1, null, sysdate);
