begin
  
delete from bus_t_diccolumn t where t.tablecode in('PERF_T_SELFPERFINDEX') and t.columncode in('FILENAME','IND_REMARK');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FILENAME', '1', '2025', '87', '2F7BA1279A917D7CE063020011ACEBDE', 'FILENAME', 'PERF_T_SELFPERFINDEX', '附件名称', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IND_REMARK', '1', '2025', '87', '3033E518D85E3E31E063020011AC88E3', 'IND_REMARK', 'PERF_T_SELFPERFINDEX', '指标情况完成说明', 'S', '4000', null, 1, 1, null, sysdate);