
 i number;
begin

select count(*) into i from user_tables t where t.table_name ='PM_PERF_GOAL_INFO_LOG';
if i=0 then
  execute immediate '
create table PM_PERF_GOAL_INFO_LOG
(
  guid                 VARCHAR2(40) not null,
  agencyguid           VARCHAR2(40),
  zqgoal               VARCHAR2(4000),
  ndgoal               VARCHAR2(4000),
  mainguid             VARCHAR2(40),
  createtime           VARCHAR2(17),
  updatetime           VARCHAR2(17),
  creater              VARCHAR2(40),
  province             VARCHAR2(40) not null,
  year                 NUMBER(4) not null,
  kpi_per_id           VARCHAR2(38) not null,
  mof_div_code         VARCHAR2(9) not null,
  fiscal_year          VARCHAR2(4),
  pro_code             VARCHAR2(21) not null,
  kpi_target           VARCHAR2(2000) not null,
  version              VARCHAR2(38) default 1 not null,
  version_name         VARCHAR2(400) default 1,
  sub_mof_div_code     VARCHAR2(9),
  update_time          VARCHAR2(17) not null,
  is_deleted           NUMBER(1) default 2 not null,
  create_time          VARCHAR2(17) not null,
  agency_code          VARCHAR2(21) not null,
  proguid              VARCHAR2(32),
  fromguid             VARCHAR2(32),
  yearflag             VARCHAR2(9),
  adj_batch_no         VARCHAR2(6),
  fromisdel            NUMBER(1),
  goalname             VARCHAR2(100),
  status               NUMBER(1),
  transguid            VARCHAR2(40),
  is_last_inst         NUMBER(1) not null,
  mof_div_name         VARCHAR2(360) not null,
  agency_name          NVARCHAR2(300) not null,
  pro_name             VARCHAR2(180) not null,
  sub_mof_div_name     VARCHAR2(360),
  perf_obj_type_code   VARCHAR2(1) not null,
  perf_obj_type_name   VARCHAR2(60) not null,
  spe_pro_code         VARCHAR2(21),
  spe_pro_name         VARCHAR2(180),
  mof_aud_opinion_code VARCHAR2(1),
  mof_aud_opinion_name VARCHAR2(60),
  fin_perf_code        VARCHAR2(4),
  fin_perf_name        VARCHAR2(100),
  bgt_id               VARCHAR2(38),
  ori_div_code         VARCHAR2(9),
  ori_div_name         VARCHAR2(360),
  versiontype          NUMBER(1) default 0,
  is_backup            NUMBER(1) default 2,
  ratio                NUMBER(4,1),
  is_adj               NUMBER(1) default 2,
  applyfinamt          NUMBER(20,2),
  logguid			   VARCHAR2(40)
)';

end if;

select count(*) into i from user_tables t where t.table_name ='PM_PERF_INDICATOR_LOG';
if i=0 then
  execute immediate '
create table PM_PERF_INDICATOR_LOG
(
  guid                 VARCHAR2(40) not null,
  code                 VARCHAR2(300),
  explain              VARCHAR2(500),
  weight               NUMBER(5,2),
  islinked             NUMBER(1),
  agencyguid           VARCHAR2(40),
  wfstatus             VARCHAR2(40),
  status               NUMBER(1),
  createtime           VARCHAR2(17) not null,
  updatetime           VARCHAR2(17),
  creater              VARCHAR2(40) not null,
  province             VARCHAR2(32) not null,
  year                 NUMBER(4) not null,
  ordernum             NUMBER(9),
  finintorgguid        VARCHAR2(40),
  mainguid             VARCHAR2(40),
  superid              VARCHAR2(40),
  levelno              NUMBER(2),
  rule                 VARCHAR2(200),
  computesign          VARCHAR2(40),
  meterunit            VARCHAR2(200),
  tindex               VARCHAR2(300),
  wfid                 VARCHAR2(40),
  proguid              VARCHAR2(40),
  targetvalue          VARCHAR2(1000),
  kpi_id               VARCHAR2(38) not null,
  mof_div_code         VARCHAR2(9) not null,
  fiscal_year          VARCHAR2(4),
  pro_code             VARCHAR2(21) not null,
  lv1_perf_ind_code    VARCHAR2(300) not null,
  lv2_perf_ind_code    VARCHAR2(300) not null,
  lv3_perf_ind_code    VARCHAR2(300),
  kpi_content          VARCHAR2(2000),
  kpi_evalstd          VARCHAR2(2000),
  kpi_val              VARCHAR2(1000) not null,
  kpi_remark           VARCHAR2(2000),
  version              VARCHAR2(38) default 1 not null,
  version_name         VARCHAR2(400) default 1,
  sub_mof_div_code     VARCHAR2(9),
  update_time          VARCHAR2(17) not null,
  is_deleted           NUMBER(1) default 2 not null,
  create_time          VARCHAR2(17) not null,
  agency_code          VARCHAR2(21) not null,
  findex               VARCHAR2(300),
  sindex               VARCHAR2(300),
  name                 VARCHAR2(1000),
  indexval             VARCHAR2(1000),
  fromguid             VARCHAR2(32),
  yearflag             VARCHAR2(9),
  kpivalsource         VARCHAR2(40),
  value_remark         VARCHAR2(2000),
  value_desc           VARCHAR2(4000),
  is_add               VARCHAR2(2),
  opinion_remark       VARCHAR2(4000),
  fromisdel            NUMBER(1),
  goalguid             VARCHAR2(40),
  indexstandards       VARCHAR2(2000),
  isstandpush          VARCHAR2(4000),
  computetype          VARCHAR2(4000),
  referenceval         VARCHAR2(1000),
  referencestandards   VARCHAR2(2000),
  snindexval           VARCHAR2(1000),
  qnindexval           VARCHAR2(1000),
  endvaltype           VARCHAR2(40),
  endvalsource         VARCHAR2(40),
  valrule              VARCHAR2(40),
  evidencefile         VARCHAR2(40),
  value_change         VARCHAR2(40),
  transguid            VARCHAR2(40),
  isunmod              VARCHAR2(40),
  is_last_inst         NUMBER(1) not null,
  mof_div_name         VARCHAR2(360) not null,
  agency_name          NVARCHAR2(300) not null,
  pro_name             VARCHAR2(180) not null,
  lv1_perf_ind_name    VARCHAR2(1000) not null,
  lv2_perf_ind_name    VARCHAR2(1000) not null,
  lv3_perf_ind_name    VARCHAR2(1000) not null,
  sub_mof_div_name     VARCHAR2(360),
  perf_obj_type_code   VARCHAR2(1) not null,
  perf_obj_type_name   VARCHAR2(60) not null,
  spe_pro_code         VARCHAR2(21),
  spe_pro_name         VARCHAR2(180),
  mof_aud_opinion_code VARCHAR2(1),
  mof_aud_opinion_name VARCHAR2(60),
  bgt_id               VARCHAR2(38),
  ori_div_code         VARCHAR2(9),
  ori_div_name         VARCHAR2(360),
  versiontype          NUMBER(1) default 0,
  is_backup            NUMBER(1) default 2,
  is_adj               NUMBER(1) default 2,
  indexcategories      VARCHAR2(40),
  industrycategory     VARCHAR2(40),
  indexcategory        VARCHAR2(40),
  filed                VARCHAR2(40),
  occupation           VARCHAR2(40),
  isfixed              NUMBER(1),
  isfromparent         NUMBER(1),
  isapply              NUMBER(1) default 1,
  isallowedit          NUMBER(1),
  onlyself             NUMBER(1),
  logguid			   VARCHAR2(40)
)';

end if;


execute immediate '
create or replace view v_pm_perf_goal_info_log as select
guid,
kpi_per_id,
fiscal_year,
mof_div_code,
mof_div_name,
agency_code,
agency_name,
pro_code,
pro_name,
kpi_target,
sub_mof_div_code,
sub_mof_div_name,
perf_obj_type_code,
perf_obj_type_name,
spe_pro_code,
spe_pro_name,
mof_aud_opinion_code,
mof_aud_opinion_name,
fin_perf_code,
fin_perf_name,
bgt_id,
ori_div_code,
ori_div_name,
version,
version_name,
is_last_inst,
is_deleted,
update_time,
create_time,
is_backup,
province,
mainguid,
yearflag,
logguid,
11 as opttype
from pm_perf_goal_info_log';


execute immediate '
create or replace view v_pm_perf_indicator_log as select
guid,
kpi_id,
fiscal_year,
mof_div_code,
mof_div_name,
agency_code,
agency_name,
pro_code,
pro_name,
lv1_perf_ind_code,
lv1_perf_ind_name,
lv2_perf_ind_code,
lv2_perf_ind_name,
lv3_perf_ind_code,
lv3_perf_ind_name,
kpi_content,
kpi_evalstd,
kpi_val,
kpi_remark,
sub_mof_div_code,
sub_mof_div_name,
perf_obj_type_code,
perf_obj_type_name,
spe_pro_code,
spe_pro_name,
mof_aud_opinion_code,
mof_aud_opinion_name,
bgt_id,
ori_div_code,
ori_div_name,
version,
version_name,
is_last_inst,
is_deleted,
update_time,
create_time,
computesign,
meterunit,
is_backup,
province,
mainguid,
yearflag,
ordernum,
logguid,
11 as opttype
from pm_perf_indicator_log';