begin
  
delete from bus_t_diccolumn t where t.tablecode='PERF_TRANSFER_INDICATOR' and t.columncode in('FILED','INDEXCATEGORIES','INDEXCATEGORY','INDUSTRYCATEGORY','ISALLOWEDIT','ISAPPLY','ISFIXED','ISFROMPARENT','IS_ADJ','IS_BACKUP','OCCUPATION','ONLYSELF','VERSIONTYPE');

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FILED', '1', '2016', '87', '2AC4D50AF13262C2E0638516A8C08A7E', 'FILED', 'PERF_TRANSFER_INDICATOR', '职能', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'INDEXCATEGORIES', '1', '2016', '87', '2AC4D50AF13362C2E0638516A8C08A7E', 'INDEXCATEGORIES', 'PERF_TRANSFER_INDICATOR', '行业大类', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'INDEXCATEGORY', '1', '2016', '87', '2AC4D50AF13462C2E0638516A8C08A7E', 'INDEXCATEGORY', 'PERF_TRANSFER_INDICATOR', '资金用途', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'INDUSTRYCATEGORY', '1', '2016', '87', '2AC4D50AF13562C2E0638516A8C08A7E', 'INDUSTRYCATEGORY', 'PERF_TRANSFER_INDICATOR', '行业类别', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '1', 'ISALLOWEDIT', '1', '2016', '87', '2AC4D50AF13662C2E0638516A8C08A7E', 'ISALLOWEDIT', 'PERF_TRANSFER_INDICATOR', '是否允许编辑', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '1', 'ISAPPLY', '1', '2016', '87', '2AC4D50AF13F62C2E0638516A8C08A7E', 'ISAPPLY', 'PERF_TRANSFER_INDICATOR', '是否适用', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ISFIXED', '1', '2016', '87', '2AC4D50AF13E62C2E0638516A8C08A7E', 'ISFIXED', 'PERF_TRANSFER_INDICATOR', '是否为固化指标', 'N', '22', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ISFROMPARENT', '1', '2016', '87', '2AC4D50AF13C62C2E0638516A8C08A7E', 'ISFROMPARENT', 'PERF_TRANSFER_INDICATOR', '是否为继承一级项目指标', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_ADJ', '1', '2016', '87', '2AC4D50AF13D62C2E0638516A8C08A7E', 'IS_ADJ', 'PERF_TRANSFER_INDICATOR', '调整是否终审 2终审 1没有终审', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_BACKUP', '1', '2016', '87', '2AC4D50AF13B62C2E0638516A8C08A7E', 'IS_BACKUP', 'PERF_TRANSFER_INDICATOR', '1 版本记录 2 日常动态', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'OCCUPATION', '1', '2016', '87', '2AC4D50AF13A62C2E0638516A8C08A7E', 'OCCUPATION', 'PERF_TRANSFER_INDICATOR', '活动', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '1', 'ONLYSELF', '1', '2016', '87', '2AC4D50AF13962C2E0638516A8C08A7E', 'ONLYSELF', 'PERF_TRANSFER_INDICATOR', '仅本级适用', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'VERSIONTYPE', '1', '2016', '87', '2AC4D50AF13862C2E0638516A8C08A7E', 'VERSIONTYPE', 'PERF_TRANSFER_INDICATOR', '0 日常动态 1 编制 2 批复，3执行', 'N', '1', null, 1, 1, null, sysdate);

delete from bus_t_diccolumn t where t.tablecode='PERF_TRANSFER_GOAL' and t.columncode in('APPLYFINAMT','IS_ADJ','IS_BACKUP','VERSIONTYPE');

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'APPLYFINAMT', '1', '2016', '87', '2AC4D50AF16362C2E0638516A8C08A7E', 'APPLYFINAMT', 'PERF_TRANSFER_GOAL', '申请财政资金', 'N', '20', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_ADJ', '1', '2016', '87', '2AC4D50AF16462C2E0638516A8C08A7E', 'IS_ADJ', 'PERF_TRANSFER_GOAL', '调整是否终审 2终审 1没有终审', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_BACKUP', '1', '2016', '87', '2AC4D50AF16562C2E0638516A8C08A7E', 'IS_BACKUP', 'PERF_TRANSFER_GOAL', '1 版本记录 2 日常动态', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'VERSIONTYPE', '1', '2016', '87', '2AC4D50AF16662C2E0638516A8C08A7E', 'VERSIONTYPE', 'PERF_TRANSFER_GOAL', '0 日常动态 1 编制 2 批复，3执行', 'N', '1', null, 1, 1, null, sysdate);
