begin
  delete FROM Bus_t_Dictable t where t.tablecode in ('PERF_T_DEPTPROEXP','PERF_T_DEPTAMT');
  delete FROM Bus_t_Diccolumn t where t.tablecode in ('PERF_T_DEPTPROEXP','PERF_T_DEPTAMT');
  
  insert into Bus_t_Dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
  values ('2016', '87', 'PERF_T_DEPTAMT', '部门总体资金情况', null, 1, 1, 'PERF_T_DEPTAMT', 'pmkpi', null, '0', 1, '0', 0, 1, null, sysdate, 1, 1, null, '1');

  insert into Bus_t_Dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
  values ('2016', '87', 'PERF_T_DEPTPROEXP', '部门项目支出情况', null, 1, 1, 'PERF_T_DEPTPROEXP', 'pmkpi', null, '0', 1, '0', 0, 1, null, sysdate, 1, 1, null, '1');
  
  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'AGENCYGUID', '1', '2016', '87', 'DE8C2F4CF3CF48E2E0533315A8C040AF', 'AGENCYGUID', 'PERF_T_DEPTAMT', '单位', 'S', '40', null, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'AGENCYNAME', '1', '2016', '87', 'DE8C2F4C03CF48E2E0533315A8C040AF', 'AGENCYNAME', 'PERF_T_DEPTAMT', '项目名称', 'S', '200', null, null, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'CREATER', '1', '2016', '87', 'DE8C2F4C23CF48E2E0533315A8C040AF', 'CREATER', 'PERF_T_DEPTAMT', '创建人', 'S', '40', null, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'CREATETIME', '1', '2016', '87', 'DE8C2F4C33CF48E2E0533315A8C040AF', 'CREATETIME', 'PERF_T_DEPTAMT', '新增时间', 'S', '17', null, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'FAMT', '1', '2016', '87', 'DE8C2F4C73CF48E2E0533315A8C040AF', 'FAMT', 'PERF_T_DEPTAMT', '上年金额', 'N', '20', 2, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'FUNDNAME', '1', '2016', '87', 'DE8C2F4CF5CF48E2E0533315A8C040AF', 'FUNDNAME', 'PERF_T_DEPTAMT', '资金来源名称', 'S', '100', null, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'GUID', '1', '2016', '87', 'DE8C2F4C43CF48E2E0533315A8C040AF', 'GUID', 'PERF_T_DEPTAMT', '主键', 'S', '40', null, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'IS_DELETED', '1', '2016', '87', 'DE8C2F4C53CF48E2E0533315A8C040AF', 'IS_DELETED', 'PERF_T_DEPTAMT', '是否删除', 'N', '1', null, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'MAINGUID', '1', '2016', '87', 'DE8C2F4C63CF48E2E0533315A8C040AF', 'MAINGUID', 'PERF_T_DEPTAMT', '主单guid', 'S', '40', null, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'ORDERNUM', '1', '2016', '87', 'DE917D4A64E64104E0533315A8C09CB7', 'ORDERNUM', 'PERF_T_DEPTAMT', '排序', 'N', '4', null, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'PROVINCE', '1', '2016', '87', 'DE8C2F4CF4CF48E2E0533315A8C040AF', 'PROVINCE', 'PERF_T_DEPTAMT', '区划', 'S', '40', null, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'RATE', '1', '2016', '87', 'DE8C2F4C94CF48E2E0533315A8C040AF', 'RATE', 'PERF_T_DEPTAMT', '占比', 'N', '20', 4, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'SAMT', '1', '2016', '87', 'DE8C2F4C83CF48E2E0533315A8C040AF', 'SAMT', 'PERF_T_DEPTAMT', '前年金额', 'N', '20', 2, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'TYPENAME', '1', '2016', '87', 'DE8C2F4C13CF48E2E0533315A8C040AF', 'TYPENAME', 'PERF_T_DEPTAMT', '资金分类名称', 'S', '100', null, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'UPDATETIME', '1', '2016', '87', 'DE8C2F4CF6CF48E2E0533315A8C040AF', 'UPDATETIME', 'PERF_T_DEPTAMT', '修改时间', 'S', '17', null, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'YEAR', '1', '2016', '87', 'DE8C2F4CF7CF48E2E0533315A8C040AF', 'YEAR', 'PERF_T_DEPTAMT', '年度', 'N', '4', null, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'YEARAMT', '1', '2016', '87', 'DE8C2F4C93CF48E2E0533315A8C040AF', 'YEARAMT', 'PERF_T_DEPTAMT', '当年金额', 'N', '20', 2, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'AGENCYGUID', '1', '2016', '87', 'DE8BF8072C094398E0533315A8C00B63', 'AGENCYGUID', 'PERF_T_DEPTPROEXP', '单位', 'S', '40', null, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'CREATER', '1', '2016', '87', 'DE8BF8072C0943C8E0533315A8C00B63', 'CREATER', 'PERF_T_DEPTPROEXP', '创建人', 'S', '40', null, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'CREATETIME', '1', '2016', '87', 'DE8BF8072C0943D8E0533315A8C00B63', 'CREATETIME', 'PERF_T_DEPTPROEXP', '新增时间', 'S', '17', null, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'EXPUSAGE', '1', '2016', '87', 'DE8BF8072C0943K8E0533315A8C00B63', 'EXPUSAGE', 'PERF_T_DEPTPROEXP', '支出方向与用途', 'S', '2000', null, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'GUID', '1', '2016', '87', 'DE8BF8072C0943E8E0533315A8C00B63', 'GUID', 'PERF_T_DEPTPROEXP', '主键', 'S', '40', null, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'IS_DELETED', '1', '2016', '87', 'DE8BF8072C0943N8E0533315A8C00B63', 'IS_DELETED', 'PERF_T_DEPTPROEXP', '是否删除', 'N', '1', null, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'MAINGUID', '1', '2016', '87', 'DE8BF8072C0943F8E0533315A8C00B63', 'MAINGUID', 'PERF_T_DEPTPROEXP', '主单guid', 'S', '40', null, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'ORDERNUM', '1', '2016', '87', 'DE917D4A64E54104E0533315A8C09CB7', 'ORDERNUM', 'PERF_T_DEPTPROEXP', '排序', 'N', '4', null, null, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'PROTYPE', '1', '2016', '87', 'DE8BF8072C0943B8E0533315A8C00B63', 'PROTYPE', 'PERF_T_DEPTPROEXP', '项目类型', 'S', '200', null, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'PROVINCE', '1', '2016', '87', 'DE8BF8072C0943J8E0533315A8C00B63', 'PROVINCE', 'PERF_T_DEPTPROEXP', '区划', 'S', '40', null, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'PRO_NAME', '1', '2016', '87', 'DE8BF8072C0943A8E0533315A8C00B63', 'PRO_NAME', 'PERF_T_DEPTPROEXP', '项目名称', 'S', '200', null, null, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'TOTALAMT', '1', '2016', '87', 'DE8BF8072C0943G8E0533315A8C00B63', 'TOTALAMT', 'PERF_T_DEPTPROEXP', '总金额', 'N', '20', 2, null, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'UPDATETIME', '1', '2016', '87', 'DE8BF8072C0943L8E0533315A8C00B63', 'UPDATETIME', 'PERF_T_DEPTPROEXP', '修改时间', 'S', '17', null, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'YEAR', '1', '2016', '87', 'DE8BF8072C0943M8E0533315A8C00B63', 'YEAR', 'PERF_T_DEPTPROEXP', '年度', 'N', '4', null, 1, 1, null, sysdate);

  insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
  values (null, null, null, '1', 'YEARAMT', '1', '2016', '87', 'DE8BF8072C0943H8E0533315A8C00B63', 'YEARAMT', 'PERF_T_DEPTPROEXP', '年度预算', 'N', '20', 2, null, 1, null, sysdate);
