begin
delete FROM Bus_t_Diccolumn t where t.tablecode in 
('V_PERF_V_SELFEVALPROGRAMS','V_PERF_V_SELFEVALTASK','PERF_T_SELFEVALTASK','PERF_T_SELFPERFINDEX',
'V_PERF_SELFPERFDESC','PERF_T_SELFPERFDESC','V_PERF_DEPT_SELFEVALTASK','V_PERF_V_SELFEVALDEPT');
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIAGENCYALLPAY', null, '1', 'AGENCYGUID', '1', '2021', '87', 'PD6CF90C361749A0A3DDF94802DC2A50', 'AGENCYGUID', 'PERF_T_SELFEVALTASK', '单位', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'AUDITOR', '1', '2021', '87', 'PA6C1502AD5545C9BED6CCC521901E47', 'AUDITOR', 'PERF_T_SELFEVALTASK', '审核人', 'S', '32', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BUDGETAMOUNT', '1', '2021', '87', 'Pd056062966532a9a5478b42c29b37ca', 'BUDGETAMOUNT', 'PERF_T_SELFEVALTASK', '预算金额', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BUSTYPE', '1', '2021', '87', 'P930D693F9AC4ED8B89C1789E2272608', 'BUSTYPE', 'PERF_T_SELFEVALTASK', '绩效类型', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CODE', '1', '2021', '87', 'P7BAA2A7102A45C2B6313B8FF92AF750', 'CODE', 'PERF_T_SELFEVALTASK', '编码', 'S', '200', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '61006100UEw5VQ8y', null, '1', 'CREATER', '1', '2021', '87', 'P8F7447E2C724EE8A54A293150C2D015', 'CREATER', 'PERF_T_SELFEVALTASK', '创建人', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATETIME', '1', '2021', '87', 'PEBEF81BCDBD4768B97A0BF0BEA14CE2', 'CREATETIME', 'PERF_T_SELFEVALTASK', '创建时间', 'S', '17', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EVALEND', '1', '2021', '87', 'PED104B76BF9434A9D6014F04838A6AE', 'EVALEND', 'PERF_T_SELFEVALTASK', '自评结束时间', 'S', '4', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EVALSTART', '1', '2021', '87', 'PA649CE7A6F441FBB1E6ECD094EDCA5E', 'EVALSTART', 'PERF_T_SELFEVALTASK', '自评开始时间', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EVALSTATUS', '1', '2021', '87', 'P273C96FD211485D874D33238DF2B41C', 'EVALSTATUS', 'PERF_T_SELFEVALTASK', '自评状态', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '099003', null, '1', 'FININTORGGUID', '1', '2021', '87', 'PC6B157FC6094ACF9A78D4F6DEBDB8A8', 'FININTORGGUID', 'PERF_T_SELFEVALTASK', '处室', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2021', '87', 'P7433F04D0C947E389163564A66D2AAA', 'GUID', 'PERF_T_SELFEVALTASK', '主键', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_DELETED', '1', '2021', '87', 'BCDB1FC6643C3ADEE053B11FA8C03E71', 'IS_DELETED', 'PERF_T_SELFEVALTASK', '是否删除', 'N', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'LASTUPDATETIME', '1', '2021', '87', 'P03B18FFECF046E6A57AB5D09C8542B0', 'LASTUPDATETIME', 'PERF_T_SELFEVALTASK', '时间戳', 'S', '17', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'TASKMONTH', null, '1', 'MONTH', '1', '2021', '87', 'PD239C15FDF745FCB4BA534E7A9551DC', 'MONTH', 'PERF_T_SELFEVALTASK', '月份', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'NAME', '1', '2021', '87', 'P5C6E2412F8F40469AC8E0A4675E9038', 'NAME', 'PERF_T_SELFEVALTASK', '名称', 'S', '200', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ORDERNUM', '1', '2021', '87', 'P4f33fe2348f03a913dae4b9cc179f65', 'ORDERNUM', 'PERF_T_SELFEVALTASK', '排序', 'S', '9', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERFGOALGUID', '1', '2021', '87', 'P69D9B0F2254485CBD2A17DF22F53C7F', 'PERFGOALGUID', 'PERF_T_SELFEVALTASK', '绩效数据guid', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROJGUID', '1', '2021', '87', 'PAA4B8893B014F4989596FD3C2CC0E34', 'PROJGUID', 'PERF_T_SELFEVALTASK', '项目id', 'S', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROKIND', '1', '2021', '87', 'PAA4B8893B014F4989596FD3C2CC1E39', 'PROKIND', 'PERF_T_SELFEVALTASK', '项目类型', 'S', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2021', '87', 'Pe924be0d94317edf34ecd4609b80e88', 'PROVINCE', 'PERF_T_SELFEVALTASK', '省', 'S', '32', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'REMAININGDAYS', '1', '2021', '87', 'Pd056575966532a9a5478b42c29b37ca', 'REMAININGDAYS', 'PERF_T_SELFEVALTASK', '截止天数', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'STATUS', '1', '2021', '87', 'P222829409A14510B8C7B5CD3E2937F3', 'STATUS', 'PERF_T_SELFEVALTASK', '状态', 'S', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UPDATETIME', '1', '2021', '87', 'P02FEA9940ED4254B92836B9A5B82767', 'UPDATETIME', 'PERF_T_SELFEVALTASK', '更新时间', 'S', '17', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WFID', '1', '2021', '87', 'P3f1064e2547b7172f89b14c9e97d872', 'WFID', 'PERF_T_SELFEVALTASK', '工作流id', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIWFSTATUS', null, '1', 'WFSTATUS', '1', '2021', '87', 'P350ad6da70d6d3da409118302551261', 'WFSTATUS', 'PERF_T_SELFEVALTASK', '工作流状态', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2021', '87', 'Pd056075966532a9a5478b42c29b37ca', 'YEAR', 'PERF_T_SELFEVALTASK', '年度', 'S', '4', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AGENCYGUID', '1', '2021', '87', 'S5285SD8935644B4806FCF3E76395CA6', 'AGENCYGUID', 'PERF_T_SELFPERFDESC', '单位', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ALLYEARGOAL', '1', '2021', '87', 'SAA4B8893B014F4989596FD3C2CC0E34', 'ALLYEARGOAL', 'PERF_T_SELFPERFDESC', '全年目标完成情况', 'S', '2000', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATER', '1', '2021', '87', 'S312S1E679C84F1BB80302782C385855', 'CREATER', 'PERF_T_SELFPERFDESC', '创建人', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATETIME', '1', '2021', '87', 'SEE2S7360ADA4E7C9FCA0DBE876296C7', 'CREATETIME', 'PERF_T_SELFPERFDESC', '创建时间', 'S', '17', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'DEVIATIONANALY', '1', '2021', '87', 'S222829409A14510B8C7B5CD3E2937F3', 'DEVIATIONANALY', 'PERF_T_SELFPERFDESC', '绩效目标偏离原因分析', 'S', '2000', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2021', '87', 'SDf33fe2348f03a913dae4b9cc179f65', 'GUID', 'PERF_T_SELFPERFDESC', '主键', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MAINGUID', '1', '2021', '87', 'S69D9B0F2254485CBD2A17DF22F53C7F', 'MAINGUID', 'PERF_T_SELFPERFDESC', '关联id', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROJGUID', '1', '2021', '87', 'SDf1064e2547b7172f89b14c9e97d872', 'PROJGUID', 'PERF_T_SELFPERFDESC', '项目id', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2021', '87', 'SD50ad6da70d6d3da409118302551261', 'PROVINCE', 'PERF_T_SELFPERFDESC', '省', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'RECTIFICATION', '1', '2021', '87', 'S02FEA9940ED4254B92836B9A5B82767', 'RECTIFICATION', 'PERF_T_SELFPERFDESC', '整改措施及建议', 'S', '2000', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SCORE', '1', '2021', '87', 'BD665860AC366A53E053B11FA8C0D3C6', 'SCORE', 'PERF_T_SELFPERFDESC', '自评得分', 'N', '5', 2, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SELFADDINFO', '1', '2021', '87', 'SD924be0d94317edf34ecd4609b80e88', 'SELFADDINFO', 'PERF_T_SELFPERFDESC', '自评补充信息', 'S', '2000', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SELFRESULT', '1', '2021', '87', 'BD665860AC386A53E053B11FA8C0D3C6', 'SELFRESULT', 'PERF_T_SELFPERFDESC', '自评结论', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WARN', '1', '2021', '87', 'BD665860AC376A53E053B11FA8C0D3C6', 'WARN', 'PERF_T_SELFPERFDESC', '偏差预警', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WFID', '1', '2021', '87', 'SS4C93C04E884C2D97BA3289F33B6BC6', 'WFID', 'PERF_T_SELFPERFDESC', '工作流id', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WFSTATUS', '1', '2021', '87', 'SSBAE609B5294F538C7B81B4DF5FDD95', 'WFSTATUS', 'PERF_T_SELFPERFDESC', '工作流状态', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2021', '87', 'SD056075966532a9a5478b42c29b37ca', 'YEAR', 'PERF_T_SELFPERFDESC', '年度', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEARGOAL', '1', '2021', '87', 'S930D693F9AC4ED8B89C1789E2272608', 'YEARGOAL', 'PERF_T_SELFPERFDESC', '绩效目标', 'S', '2000', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPISJDXZB1', null, '1', 'ACTUALVALUE', '1', '2021', '87', 'P484S0861D224348BE04CC4C08231249', 'ACTUALVALUE', 'PERF_T_SELFPERFINDEX', '实际完成值', 'S', '1000', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AGENCYGUID', '1', '2021', '87', 'P5285SD8935644B4806FCF3E76395CA6', 'AGENCYGUID', 'PERF_T_SELFPERFINDEX', '单位', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CODE', '1', '2021', '87', 'BD635723E782341AE053B11FA8C0A85C', 'CODE', 'PERF_T_SELFPERFINDEX', '编码', 'S', '200', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIZBXS', null, '1', 'COMPUTESIGN', '1', '2021', '87', 'P443S181BE204B8DA23587D697059C87', 'COMPUTESIGN', 'PERF_T_SELFPERFINDEX', '计算符号', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATER', '1', '2021', '87', 'P312S1E679C84F1BB80302782C385855', 'CREATER', 'PERF_T_SELFPERFINDEX', '创建人', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATETIME', '1', '2021', '87', 'PEE2S7360ADA4E7C9FCA0DBE876296C7', 'CREATETIME', 'PERF_T_SELFPERFINDEX', '创建时间', 'S', '17', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FINDEX', '1', '2021', '87', 'P174S195C31148FDBAAB990420F5BA07', 'FINDEX', 'PERF_T_SELFPERFINDEX', '一级指标', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '099003', null, '1', 'FININTORGGUID', '1', '2021', '87', 'P1A89S4FBF9445619238A32745C4BA99', 'FININTORGGUID', 'PERF_T_SELFPERFINDEX', '处室', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2021', '87', 'PBCS913D52444C259B6C860809FAF752', 'GUID', 'PERF_T_SELFPERFINDEX', '主键', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'INDEXVAL', '1', '2021', '87', 'P04D89S385164C818D5AA83AF663B03E', 'INDEXVAL', 'PERF_T_SELFPERFINDEX', '指标值', 'S', '1000', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ISLEAF', '1', '2021', '87', 'PS0A7BB1B58E4B45AC840A69EBDDFD77', 'ISLEAF', 'PERF_T_SELFPERFINDEX', '是否叶子节点', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_DELETED', '1', '2021', '87', 'BD568677E72A46F7E053B11FA8C0E21E', 'IS_DELETED', 'PERF_T_SELFPERFINDEX', '是否删除', 'N', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'KPIVALSOURCE', '1', '2021', '87', 'BD57686FD6DCA736E053B11FA8C0DC93', 'KPIVALSOURCE', 'PERF_T_SELFPERFINDEX', '值集来源', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'KPI_EVALSTD', '1', '2021', '87', 'BD568677E72B46F7E053B11FA8C0E21E', 'KPI_EVALSTD', 'PERF_T_SELFPERFINDEX', '评分标准', 'S', '200', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'KPI_REMARK', '1', '2021', '87', 'PS0A5BB1B98E4B45AC840A69EBDDFD77', 'KPI_REMARK', 'PERF_T_SELFPERFINDEX', '备注', 'S', '4', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LEVELNO', '1', '2021', '87', 'PS0A8BB1B58E4B47AC840A69EBDDFD77', 'LEVELNO', 'PERF_T_SELFPERFINDEX', '级别', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MAINGUID', '1', '2021', '87', 'PSCS913D52444C259B6C860809FAF752', 'MAINGUID', 'PERF_T_SELFPERFINDEX', '关联id', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'METERUNIT', '1', '2021', '87', 'PFD00S28C6E148A7BB7423ED467A53FC', 'METERUNIT', 'PERF_T_SELFPERFINDEX', '单位', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'NAME', '1', '2021', '87', 'PCF85SF2491C423FA0D6AB4BE4449195', 'NAME', 'PERF_T_SELFPERFINDEX', '指标名称', 'S', '200', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'OPERATION', '1', '2021', '87', 'BD568677E72946F7E053B11FA8C0E21E', 'OPERATION', 'PERF_T_SELFPERFINDEX', '选项', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ORDERNUM', '1', '2021', '87', 'P5FDS294145244CD93816C8790C74399', 'ORDERNUM', 'PERF_T_SELFPERFINDEX', '排序', 'S', '9', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROJGUID', '1', '2021', '87', 'BD671E26F9FF8435E053B11FA8C0D2E3', 'PROJGUID', 'PERF_T_SELFPERFINDEX', '项目GUID', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2021', '87', 'P2DES150169545C6B7A7D59787F0223D', 'PROVINCE', 'PERF_T_SELFPERFINDEX', '区划', 'S', '32', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'RULE', '1', '2021', '87', 'BD568677E72C46F7E053B11FA8C0E21E', 'RULE', 'PERF_T_SELFPERFINDEX', '赋分原则', 'S', '2000', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SCORE', '1', '2021', '87', 'P483C0861D224348BE04CC4C08231249', 'SCORE', 'PERF_T_SELFPERFINDEX', '得分', 'S', '1000', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SINDEX', '1', '2021', '87', 'P1C1S5DE4EC54F32BD3F0F6BEAF4B5DB', 'SINDEX', 'PERF_T_SELFPERFINDEX', '二级指标', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'STATUS', '1', '2021', '87', 'PE0FS5846E6C4E4EAFCFB5ADFAFE76C0', 'STATUS', 'PERF_T_SELFPERFINDEX', '状态', 'S', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SUPERID', '1', '2021', '87', 'PS0A8BB1B58E4B45AC840A69EBDDFD77', 'SUPERID', 'PERF_T_SELFPERFINDEX', '父级id', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TINDEX', '1', '2021', '87', 'P4640S3F832D4F02AAE80687CE875AB6', 'TINDEX', 'PERF_T_SELFPERFINDEX', '指标id', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UPDATETIME', '1', '2021', '87', 'PS70578EB2504B4E885616A4C4410187', 'UPDATETIME', 'PERF_T_SELFPERFINDEX', '更新时间', 'S', '17', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WEIGHT', '1', '2021', '87', 'PS84C0861D224348BE04CC4C08231249', 'WEIGHT', 'PERF_T_SELFPERFINDEX', '权重', 'S', '1000', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WFID', '1', '2021', '87', 'PS4C93C04E884C2D97BA3289F33B6BC6', 'WFID', 'PERF_T_SELFPERFINDEX', '工作流id', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WFSTATUS', '1', '2021', '87', 'PSBAE609B5294F538C7B81B4DF5FDD95', 'WFSTATUS', 'PERF_T_SELFPERFINDEX', '工作流状态', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2021', '87', 'PS0A5BB1B58E4B45AC840A69EBDDFD77', 'YEAR', 'PERF_T_SELFPERFINDEX', '年度', 'S', '4', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIAGENCYALLPAY', null, '1', 'AGENCYGUID', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun001', 'AGENCYGUID', 'V_PERF_DEPT_SELFEVALTASK', '单位', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'AUDITOR', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun002', 'AUDITOR', 'V_PERF_DEPT_SELFEVALTASK', '审核人', 'S', '32', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BUDGETAMOUNT', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun003', 'BUDGETAMOUNT', 'V_PERF_DEPT_SELFEVALTASK', '预算金额', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BUSTYPE', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun004', 'BUSTYPE', 'V_PERF_DEPT_SELFEVALTASK', '绩效类型', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CODE', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun005', 'CODE', 'V_PERF_DEPT_SELFEVALTASK', '编码', 'S', '200', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '61006100UEw5VQ8y', null, '1', 'CREATER', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun006', 'CREATER', 'V_PERF_DEPT_SELFEVALTASK', '创建人', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATETIME', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun007', 'CREATETIME', 'V_PERF_DEPT_SELFEVALTASK', '创建时间', 'S', '17', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EVALEND', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun008', 'EVALEND', 'V_PERF_DEPT_SELFEVALTASK', '自评结束时间', 'S', '4', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EVALSTART', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun009', 'EVALSTART', 'V_PERF_DEPT_SELFEVALTASK', '自评开始时间', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EVALSTATUS', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun011', 'EVALSTATUS', 'V_PERF_DEPT_SELFEVALTASK', '自评状态', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EXECAMOUNT', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun029', 'EXECAMOUNT', 'V_PERF_DEPT_SELFEVALTASK', '去年执行数', 'N', '20', 2, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '099003', null, '1', 'FININTORGGUID', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun012', 'FININTORGGUID', 'V_PERF_DEPT_SELFEVALTASK', '处室', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun013', 'GUID', 'V_PERF_DEPT_SELFEVALTASK', '主键', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'LASTUPDATETIME', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun015', 'LASTUPDATETIME', 'V_PERF_DEPT_SELFEVALTASK', '时间戳', 'S', '17', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'TASKMONTH', null, '1', 'MONTH', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun016', 'MONTH', 'V_PERF_DEPT_SELFEVALTASK', '月份', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'NAME', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun017', 'NAME', 'V_PERF_DEPT_SELFEVALTASK', '名称', 'S', '200', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ORDERNUM', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun018', 'ORDERNUM', 'V_PERF_DEPT_SELFEVALTASK', '排序', 'S', '9', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERFGOALGUID', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun019', 'PERFGOALGUID', 'V_PERF_DEPT_SELFEVALTASK', '绩效数据guid', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROJGUID', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun020', 'PROJGUID', 'V_PERF_DEPT_SELFEVALTASK', '项目id', 'S', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROKIND', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun021', 'PROKIND', 'V_PERF_DEPT_SELFEVALTASK', '项目类型', 'S', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun022', 'PROVINCE', 'V_PERF_DEPT_SELFEVALTASK', '省', 'S', '32', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'REMAININGDAYS', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun023', 'REMAININGDAYS', 'V_PERF_DEPT_SELFEVALTASK', '截止天数', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SCORE', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun031', 'SCORE', 'V_PERF_DEPT_SELFEVALTASK', '自评得分', 'N', '5', 2, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SELFRESULT', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun033', 'SELFRESULT', 'V_PERF_DEPT_SELFEVALTASK', '自评结论', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'STATUS', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun024', 'STATUS', 'V_PERF_DEPT_SELFEVALTASK', '状态', 'S', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UPDATETIME', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun025', 'UPDATETIME', 'V_PERF_DEPT_SELFEVALTASK', '更新时间', 'S', '17', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WARN', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun032', 'WARN', 'V_PERF_DEPT_SELFEVALTASK', '预警规则', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WFID', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun026', 'WFID', 'V_PERF_DEPT_SELFEVALTASK', '工作流id', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIWFSTATUS', null, '1', 'WFSTATUS', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun027', 'WFSTATUS', 'V_PERF_DEPT_SELFEVALTASK', '工作流状态', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2021', '87', 'PERFDEPTSELFEVALTASKcolun028', 'YEAR', 'V_PERF_DEPT_SELFEVALTASK', '年度', 'S', '4', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AGENCYGUID', '1', '2021', '87', 'V_PERF_SELFPERFDESC0001', 'AGENCYGUID', 'V_PERF_SELFPERFDESC', '单位', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ALLYEARGOAL', '1', '2021', '87', 'V_PERF_SELFPERFDESC0002', 'ALLYEARGOAL', 'V_PERF_SELFPERFDESC', '全年目标完成情况', 'S', '2000', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATER', '1', '2021', '87', 'V_PERF_SELFPERFDESC0003', 'CREATER', 'V_PERF_SELFPERFDESC', '创建人', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATETIME', '1', '2021', '87', 'V_PERF_SELFPERFDESC0004', 'CREATETIME', 'V_PERF_SELFPERFDESC', '创建时间', 'S', '17', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'DEVIATIONANALY', '1', '2021', '87', 'V_PERF_SELFPERFDESC0005', 'DEVIATIONANALY', 'V_PERF_SELFPERFDESC', '绩效目标偏离原因分析', 'S', '2000', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2021', '87', 'V_PERF_SELFPERFDESC0006', 'GUID', 'V_PERF_SELFPERFDESC', '主键', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MAINGUID', '1', '2021', '87', 'V_PERF_SELFPERFDESC0007', 'MAINGUID', 'V_PERF_SELFPERFDESC', '关联id', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROJGUID', '1', '2021', '87', 'V_PERF_SELFPERFDESC0008', 'PROJGUID', 'V_PERF_SELFPERFDESC', '项目id', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2021', '87', 'V_PERF_SELFPERFDESC0009', 'PROVINCE', 'V_PERF_SELFPERFDESC', '省', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'RECTIFICATION', '1', '2021', '87', 'V_PERF_SELFPERFDESC0011', 'RECTIFICATION', 'V_PERF_SELFPERFDESC', '整改措施及建议', 'S', '2000', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SCORE', '1', '2021', '87', 'V_PERF_SELFPERFDESC0017', 'SCORE', 'V_PERF_SELFPERFDESC', '自评得分', 'N', '5', 2, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SELFADDINFO', '1', '2021', '87', 'V_PERF_SELFPERFDESC0012', 'SELFADDINFO', 'V_PERF_SELFPERFDESC', '自评补充信息', 'S', '2000', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WARN', '1', '2021', '87', 'V_PERF_SELFPERFDESC0018', 'WARN', 'V_PERF_SELFPERFDESC', '预警规则', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WFID', '1', '2021', '87', 'V_PERF_SELFPERFDESC0013', 'WFID', 'V_PERF_SELFPERFDESC', '工作流id', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WFSTATUS', '1', '2021', '87', 'V_PERF_SELFPERFDESC0014', 'WFSTATUS', 'V_PERF_SELFPERFDESC', '工作流状态', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2021', '87', 'V_PERF_SELFPERFDESC0015', 'YEAR', 'V_PERF_SELFPERFDESC', '年度', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEARGOAL', '1', '2021', '87', 'V_PERF_SELFPERFDESC0016', 'YEARGOAL', 'V_PERF_SELFPERFDESC', '绩效目标', 'S', '2000', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIAGENCYALLPAY', null, '1', 'AGENCYGUID', '1', '2021', '87', 'PERFSELFEVALDEPT001', 'AGENCYGUID', 'V_PERF_V_SELFEVALDEPT', '单位', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BUDGETAMOUNT', '1', '2021', '87', 'PERFSELFEVALDEPT002', 'BUDGETAMOUNT', 'V_PERF_V_SELFEVALDEPT', '预算金额', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BUSTYPE', '1', '2021', '87', 'PERFSELFEVALDEPT003', 'BUSTYPE', 'V_PERF_V_SELFEVALDEPT', '绩效类型', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EVALEND', '1', '2021', '87', 'PERFSELFEVALDEPT004', 'EVALEND', 'V_PERF_V_SELFEVALDEPT', '自评结束时间', 'S', '4', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EVALSTART', '1', '2021', '87', 'PERFSELFEVALDEPT005', 'EVALSTART', 'V_PERF_V_SELFEVALDEPT', '自评开始时间', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EXECAMOUNT', '1', '2021', '87', 'PERFSELFEVALDEPT006', 'EXECAMOUNT', 'V_PERF_V_SELFEVALDEPT', '执行金额', 'N', '18', 2, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EXECRATE', '1', '2021', '87', 'PERFSELFEVALDEPT007', 'EXECRATE', 'V_PERF_V_SELFEVALDEPT', '预算执行率', 'N', '18', 2, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '099003', null, '1', 'FININTORGGUID', '1', '2021', '87', 'PERFSELFEVALDEPT008', 'FININTORGGUID', 'V_PERF_V_SELFEVALDEPT', '处室', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2021', '87', 'PERFSELFEVALDEPT011', 'GUID', 'V_PERF_V_SELFEVALDEPT', '主键', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'NAME', '1', '2021', '87', 'PERFSELFEVALDEPT012', 'NAME', 'V_PERF_V_SELFEVALDEPT', '名称', 'S', '200', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROJCODE', '1', '2021', '87', 'PERFSELFEVALDEPT013', 'PROJCODE', 'V_PERF_V_SELFEVALDEPT', '编码', 'S', '200', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROJGUID', '1', '2021', '87', 'PERFSELFEVALDEPT014', 'PROJGUID', 'V_PERF_V_SELFEVALDEPT', '项目id', 'S', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROKIND', '1', '2021', '87', 'PERFSELFEVALDEPT015', 'PROKIND', 'V_PERF_V_SELFEVALDEPT', '项目类型', 'S', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2021', '87', 'PERFSELFEVALDEPT016', 'PROVINCE', 'V_PERF_V_SELFEVALDEPT', '省', 'S', '32', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'REMAININGDAYS', '1', '2021', '87', 'PERFSELFEVALDEPT017', 'REMAININGDAYS', 'V_PERF_V_SELFEVALDEPT', '截止天数', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UPDATETIME', '1', '2021', '87', 'PERFSELFEVALDEPT018', 'UPDATETIME', 'V_PERF_V_SELFEVALDEPT', '更新时间', 'S', '17', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WFID', '1', '2021', '87', 'PERFSELFEVALDEPT021', 'WFID', 'V_PERF_V_SELFEVALDEPT', '工作流id', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIWFSTATUS', null, '1', 'WFSTATUS', '1', '2021', '87', 'PERFSELFEVALDEPT022', 'WFSTATUS', 'V_PERF_V_SELFEVALDEPT', '工作流状态', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2021', '87', 'PERFSELFEVALDEPT023', 'YEAR', 'V_PERF_V_SELFEVALDEPT', '年度', 'S', '4', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIAGENCYALLPAY', null, '1', 'AGENCYGUID', '1', '2021', '87', 'BCB59A7C05F2A02F1053B11FA8C0D3A3', 'AGENCYGUID', 'V_PERF_V_SELFEVALPROGRAMS', '单位', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BUDGETAMOUNT', '1', '2021', '87', 'BCB59A7C05F2A02F2053B11FA8C0D3A3', 'BUDGETAMOUNT', 'V_PERF_V_SELFEVALPROGRAMS', '预算金额', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BUSTYPE', '1', '2021', '87', 'BCB59A7C05F2A02F3053B11FA8C0D3A3', 'BUSTYPE', 'V_PERF_V_SELFEVALPROGRAMS', '绩效类型', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EVALEND', '1', '2021', '87', 'BCB59A7C05F2A02F5053B11FA8C0D3A3', 'EVALEND', 'V_PERF_V_SELFEVALPROGRAMS', '自评结束时间', 'S', '4', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EVALSTART', '1', '2021', '87', 'BCB59A7C05F2A02F6053B11FA8C0D3A3', 'EVALSTART', 'V_PERF_V_SELFEVALPROGRAMS', '自评开始时间', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EXECAMOUNT', '1', '2021', '87', 'BCB59A7C05F3A02FE053B11FA8C0D3A3', 'EXECAMOUNT', 'V_PERF_V_SELFEVALPROGRAMS', '执行金额', 'N', '18', 2, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EXECRATE', '1', '2021', '87', 'BCB59A7C05F2A02FE053B11FA8C0D3A3', 'EXECRATE', 'V_PERF_V_SELFEVALPROGRAMS', '预算执行率', 'N', '18', 2, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '099003', null, '1', 'FININTORGGUID', '1', '2021', '87', 'BCB59A7C05F2A02F7053B11FA8C0D3A3', 'FININTORGGUID', 'V_PERF_V_SELFEVALPROGRAMS', '处室', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2021', '87', 'BCB59A7C05F2A02F8053B11FA8C0D3A3', 'GUID', 'V_PERF_V_SELFEVALPROGRAMS', '主键', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'NAME', '1', '2021', '87', 'BCB59A7C05F2A02F9053B11FA8C0D3A3', 'NAME', 'V_PERF_V_SELFEVALPROGRAMS', '名称', 'S', '200', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROJCODE', '1', '2021', '87', 'BCB59A7C05F2A02F4053B11FA8C0D3A3', 'PROJCODE', 'V_PERF_V_SELFEVALPROGRAMS', '编码', 'S', '200', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROJGUID', '1', '2021', '87', 'BCB59A7C05F2A0211053B11FA8C0D3A3', 'PROJGUID', 'V_PERF_V_SELFEVALPROGRAMS', '项目id', 'S', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROKIND', '1', '2021', '87', 'BCB59A7C05F2A0212053B11FA8C0D3A3', 'PROKIND', 'V_PERF_V_SELFEVALPROGRAMS', '项目类型', 'S', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2021', '87', 'BCB59A7C05F2A0213053B11FA8C0D3A3', 'PROVINCE', 'V_PERF_V_SELFEVALPROGRAMS', '省', 'S', '32', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'REMAININGDAYS', '1', '2021', '87', 'BCB59A7C05F2A0214053B11FA8C0D3A3', 'REMAININGDAYS', 'V_PERF_V_SELFEVALPROGRAMS', '截止天数', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UPDATETIME', '1', '2021', '87', 'BCB59A7C05F2A0215053B11FA8C0D3A3', 'UPDATETIME', 'V_PERF_V_SELFEVALPROGRAMS', '更新时间', 'S', '17', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WFID', '1', '2021', '87', 'BCB59A7C05F2A0216053B11FA8C0D3A3', 'WFID', 'V_PERF_V_SELFEVALPROGRAMS', '工作流id', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIWFSTATUS', null, '1', 'WFSTATUS', '1', '2021', '87', 'BCB59A7C05F2A0217053B11FA8C0D3A3', 'WFSTATUS', 'V_PERF_V_SELFEVALPROGRAMS', '工作流状态', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2021', '87', 'BCB59A7C05F2A0218053B11FA8C0D3A3', 'YEAR', 'V_PERF_V_SELFEVALPROGRAMS', '年度', 'S', '4', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIAGENCYALLPAY', null, '1', 'AGENCYGUID', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun001', 'AGENCYGUID', 'V_PERF_V_SELFEVALTASK', '单位', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'AUDITOR', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun002', 'AUDITOR', 'V_PERF_V_SELFEVALTASK', '审核人', 'S', '32', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BUDGETAMOUNT', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun003', 'BUDGETAMOUNT', 'V_PERF_V_SELFEVALTASK', '预算金额', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BUSTYPE', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun004', 'BUSTYPE', 'V_PERF_V_SELFEVALTASK', '绩效类型', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CODE', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun005', 'CODE', 'V_PERF_V_SELFEVALTASK', '编码', 'S', '200', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '61006100UEw5VQ8y', null, '1', 'CREATER', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun006', 'CREATER', 'V_PERF_V_SELFEVALTASK', '创建人', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATETIME', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun007', 'CREATETIME', 'V_PERF_V_SELFEVALTASK', '创建时间', 'S', '17', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EVALEND', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun008', 'EVALEND', 'V_PERF_V_SELFEVALTASK', '自评结束时间', 'S', '4', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EVALSTART', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun009', 'EVALSTART', 'V_PERF_V_SELFEVALTASK', '自评开始时间', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EVALSTATUS', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun011', 'EVALSTATUS', 'V_PERF_V_SELFEVALTASK', '自评状态', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EXECAMOUNT', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun029', 'EXECAMOUNT', 'V_PERF_V_SELFEVALTASK', '去年执行数', 'N', '20', 2, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '099003', null, '1', 'FININTORGGUID', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun012', 'FININTORGGUID', 'V_PERF_V_SELFEVALTASK', '处室', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun013', 'GUID', 'V_PERF_V_SELFEVALTASK', '主键', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'LASTUPDATETIME', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun015', 'LASTUPDATETIME', 'V_PERF_V_SELFEVALTASK', '时间戳', 'S', '17', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'TASKMONTH', null, '1', 'MONTH', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun016', 'MONTH', 'V_PERF_V_SELFEVALTASK', '月份', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'NAME', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun017', 'NAME', 'V_PERF_V_SELFEVALTASK', '名称', 'S', '200', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ORDERNUM', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun018', 'ORDERNUM', 'V_PERF_V_SELFEVALTASK', '排序', 'S', '9', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERFGOALGUID', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun019', 'PERFGOALGUID', 'V_PERF_V_SELFEVALTASK', '绩效数据guid', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROJGUID', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun020', 'PROJGUID', 'V_PERF_V_SELFEVALTASK', '项目id', 'S', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROKIND', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun021', 'PROKIND', 'V_PERF_V_SELFEVALTASK', '项目类型', 'S', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun022', 'PROVINCE', 'V_PERF_V_SELFEVALTASK', '省', 'S', '32', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'REMAININGDAYS', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun023', 'REMAININGDAYS', 'V_PERF_V_SELFEVALTASK', '截止天数', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SCORE', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun031', 'SCORE', 'V_PERF_V_SELFEVALTASK', '自评得分', 'N', '5', 2, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SELFRESULT', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun033', 'SELFRESULT', 'V_PERF_V_SELFEVALTASK', '自评结论', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'STATUS', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun024', 'STATUS', 'V_PERF_V_SELFEVALTASK', '状态', 'S', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UPDATETIME', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun025', 'UPDATETIME', 'V_PERF_V_SELFEVALTASK', '更新时间', 'S', '17', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WARN', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun032', 'WARN', 'V_PERF_V_SELFEVALTASK', '预警规则', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WFID', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun026', 'WFID', 'V_PERF_V_SELFEVALTASK', '工作流id', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIWFSTATUS', null, '1', 'WFSTATUS', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun027', 'WFSTATUS', 'V_PERF_V_SELFEVALTASK', '工作流状态', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2021', '87', 'PERF_V_SELFEVALTASKcolun028', 'YEAR', 'V_PERF_V_SELFEVALTASK', '年度', 'S', '4', null, 1, 0, null, sysdate);

