begin
--财政评价主表
delete from bus_t_dictable t where t.tablecode='PERF_T_FINEVALUATION';
insert into bus_t_dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2016', '87', 'PERF_T_FINEVALUATION', '财政重点评价表', '财政重点评价表', 2, 1, 'PERF_T_FINEVALUATION', 'pmkpi', null, '0', 1, null, 1, 1, null, sysdate, 1, 1, null, '1');

delete from bus_t_diccolumn t where t.tablecode in('PERF_T_FINEVALUATION');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '1', 'AGENCYGUID', '1', '2016', '87', 'BD25F32C9E7577B9E053B11FA8C041F0', 'AGENCYGUID', 'PERF_T_FINEVALUATION', '单位guid', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AUDITOR', '1', '2016', '87', 'BD25F32C9E7777B9E053B11FA8C041F0', 'AUDITOR', 'PERF_T_FINEVALUATION', null, 'S', '10', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BUDGETGOALCREATOR', '1', '2016', '87', 'BD25F32C9E7877B9E053B11FA8C041F0', 'BUDGETGOALCREATOR', 'PERF_T_FINEVALUATION', '填报人', 'S', '20', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BUSTYPE', '1', '2016', '87', 'BD25F32C9E7977B9E053B11FA8C041F0', 'BUSTYPE', 'PERF_T_FINEVALUATION', '绩效类型', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPICATEGORY', null, '1', 'CATEGORY', '1', '2016', '87', 'BD8C08690B202973E053B11FA8C01253', 'CATEGORY', 'PERF_T_FINEVALUATION', '绩效类别', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CODE', '1', '2016', '87', 'BD25F32C9E8677B9E053B11FA8C041F0', 'CODE', 'PERF_T_FINEVALUATION', '项目编码', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '61006100UEw5VQ8y', null, '1', 'CREATER', '1', '2016', '87', 'BD25F32C9E7B77B9E053B11FA8C041F0', 'CREATER', 'PERF_T_FINEVALUATION', '创建人', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATETIME', '1', '2016', '87', 'BD25F32C9E7C77B9E053B11FA8C041F0', 'CREATETIME', 'PERF_T_FINEVALUATION', '创建时间', 'S', '17', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ENDTIME', '1', '2016', '87', 'BD25F32C9E7D77B9E053B11FA8C041F0', 'ENDTIME', 'PERF_T_FINEVALUATION', '截止日期', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIDEPARTMENT', null, '1', 'EVALMEACH', '1', '2016', '87', 'BD25F32C9E7E77B9E053B11FA8C041F0', 'EVALMEACH', 'PERF_T_FINEVALUATION', '组织评价机构', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EVALMEACH', '1', '2016', '87', 'BD25F32C9E8777B9E053B11FA8C041F0', 'EVALMEACH', 'PERF_T_FINEVALUATION', '委托机构id', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EXISTQUESTION', '1', '2016', '87', 'BD53D19B028C2359E053B11FA8C0BCA2', 'EXISTQUESTION', 'PERF_T_FINEVALUATION', '存在问题', 'S', '4000', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FEEDBACK', '1', '2016', '87', 'BD53D19B028D2359E053B11FA8C0BCA2', 'FEEDBACK', 'PERF_T_FINEVALUATION', '整改措施和建议', 'S', '4000', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '099003', null, '1', 'FININTORGGUID', '1', '2016', '87', 'BD25F32C9E7F77B9E053B11FA8C041F0', 'FININTORGGUID', 'PERF_T_FINEVALUATION', '处室guid', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2016', '87', 'BD25F32C9E8077B9E053B11FA8C041F0', 'GUID', 'PERF_T_FINEVALUATION', 'GUID', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ISENTRUST', '1', '2016', '87', 'BD25F32C9E8177B9E053B11FA8C041F0', 'ISENTRUST', 'PERF_T_FINEVALUATION', '是否委托', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '1', 'ISNOTICE', '1', '2016', '87', 'BD67888481F095E8E053B11FA8C0447E', 'ISNOTICE', 'PERF_T_FINEVALUATION', '是否接收通知', 'N', '1', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ISOBJECT', '1', '2016', '87', 'BD25F32C9E8277B9E053B11FA8C041F0', 'ISOBJECT', 'PERF_T_FINEVALUATION', '是否确定', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '1', 'ISRELEASE', '1', '2016', '87', 'BD25F32C9E8377B9E053B11FA8C041F0', 'ISRELEASE', 'PERF_T_FINEVALUATION', '是否下达', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ISRESULT', '1', '2016', '87', 'BD25F32C9E8477B9E053B11FA8C041F0', 'ISRESULT', 'PERF_T_FINEVALUATION', '是否上传', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LASTUPDATETIME', '1', '2016', '87', 'BD25F32C9E8577B9E053B11FA8C041F0', 'LASTUPDATETIME', 'PERF_T_FINEVALUATION', '更新时间', 'S', '17', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LEADER_NAME', '1', '2016', '87', 'BD25F32C9E8977B9E053B11FA8C041F0', 'LEADER_NAME', 'PERF_T_FINEVALUATION', '项目负责人', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LEADER_PHONE', '1', '2016', '87', 'BD25F32C9E7A77B9E053B11FA8C041F0', 'LEADER_PHONE', 'PERF_T_FINEVALUATION', '联系人电话', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'NAME', '1', '2016', '87', 'BD25F32C9E8C77B9E053B11FA8C041F0', 'NAME', 'PERF_T_FINEVALUATION', '项目名称', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'OPINION', '1', '2016', '87', 'BD672DCCF3B28602E053B11FA8C0BE47', 'OPINION', 'PERF_T_FINEVALUATION', '反馈意见', 'S', '4000', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROGUID', '1', '2016', '87', 'BD25F32C9E8B77B9E053B11FA8C041F0', 'PROGUID', 'PERF_T_FINEVALUATION', '项目guid', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROJAMT', '1', '2016', '87', 'BD25F32C9E8877B9E053B11FA8C041F0', 'PROJAMT', 'PERF_T_FINEVALUATION', '当年预算金额', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROJECTCON', '1', '2016', '87', 'BD25F32C9E8A77B9E053B11FA8C041F0', 'PROJECTCON', 'PERF_T_FINEVALUATION', '项目联系人', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2016', '87', 'BD25F32C9E8D77B9E053B11FA8C041F0', 'PROVINCE', 'PERF_T_FINEVALUATION', '区划', 'S', '10', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_START_YEAR', '1', '2016', '87', 'BD25F32C9E8E77B9E053B11FA8C041F0', 'PRO_START_YEAR', 'PERF_T_FINEVALUATION', '开始日期', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_TOTAL_AMT', '1', '2016', '87', 'BD25F32C9E7677B9E053B11FA8C041F0', 'PRO_TOTAL_AMT', 'PERF_T_FINEVALUATION', '项目总金额', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'STATUS', '1', '2016', '87', 'BD25F32C9E8F77B9E053B11FA8C041F0', 'STATUS', 'PERF_T_FINEVALUATION', '数据状态', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WFID', '1', '2016', '87', 'BD25F32C9E9077B9E053B11FA8C041F0', 'WFID', 'PERF_T_FINEVALUATION', '工作流id', 'S', '40', null, null, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '099076', null, '1', 'WFSTATUS', '1', '2016', '87', 'BD25F32C9E9177B9E053B11FA8C041F0', 'WFSTATUS', 'PERF_T_FINEVALUATION', '工作流状态', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2016', '87', 'BD25F32C9E9277B9E053B11FA8C041F0', 'YEAR', 'PERF_T_FINEVALUATION', '年份', 'S', '10', null, null, 1, null, sysdate);

delete from bus_t_dictable t where t.tablecode='PERF_T_FINEVALCATEGORY';
insert into bus_t_dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2016', '87', 'PERF_T_FINEVALCATEGORY', '绩效评价类别', '绩效评价类别', 2, 1, 'PERF_T_FINEVALCATEGORY', 'pmkpi', null, '0', 1, null, 1, 1, null, sysdate, 1, 1, null, '1');

delete from bus_t_diccolumn t where t.tablecode in('PERF_T_FINEVALCATEGORY');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CODE', '1', '2016', '87', 'BD8C08690AF22973E053B11FA8C01253', 'CODE', 'PERF_T_FINEVALCATEGORY', '编码', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATETIME', '1', '2016', '87', 'BD8C08690AF32973E053B11FA8C01253', 'CREATETIME', 'PERF_T_FINEVALCATEGORY', '创建时间', 'S', '17', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2016', '87', 'BD8C08690AF42973E053B11FA8C01253', 'GUID', 'PERF_T_FINEVALCATEGORY', 'GUID', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ISLEAF', '1', '2016', '87', 'BD8C08690AFC2973E053B11FA8C01253', 'ISLEAF', 'PERF_T_FINEVALCATEGORY', '是否末级', 'S', '2', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LEVELNO', '1', '2016', '87', 'BD8C08690AFB2973E053B11FA8C01253', 'LEVELNO', 'PERF_T_FINEVALCATEGORY', '级次', 'S', '1', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'NAME', '1', '2016', '87', 'BD8C08690AF52973E053B11FA8C01253', 'NAME', 'PERF_T_FINEVALCATEGORY', '名称', 'S', '200', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ORDERNUM', '1', '2016', '87', 'BD8C08690AFD2973E053B11FA8C01253', 'ORDERNUM', 'PERF_T_FINEVALCATEGORY', '排序', 'N', '9', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2016', '87', 'BD8C08690AF62973E053B11FA8C01253', 'PROVINCE', 'PERF_T_FINEVALCATEGORY', '区划', 'S', '10', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'REMARK', '1', '2016', '87', 'BD8C08690AF92973E053B11FA8C01253', 'REMARK', 'PERF_T_FINEVALCATEGORY', '备注', 'S', '200', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'STATUS', '1', '2016', '87', 'BD8C08690AF72973E053B11FA8C01253', 'STATUS', 'PERF_T_FINEVALCATEGORY', '数据状态', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SUPERGUID', '1', '2016', '87', 'BD8C08690AFA2973E053B11FA8C01253', 'SUPERGUID', 'PERF_T_FINEVALCATEGORY', '父级guid', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2016', '87', 'BD8C08690AF82973E053B11FA8C01253', 'YEAR', 'PERF_T_FINEVALCATEGORY', '年份', 'S', '10', null, null, 1, null, sysdate);


delete from bus_t_dictable t where t.tablecode='PMKPI_FASP_T_PUBAGENCY';
insert into bus_t_dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2021', '87', 'PMKPI_FASP_T_PUBAGENCY', '绩效单位表', null, 2, 1, 'PMKPI_FASP_T_PUBAGENCY', 'pmkpi', null, null, 1, null, 1, 1, null, null, null, null, null, '1');

delete from bus_t_diccolumn t where t.tablecode in('PMKPI_FASP_T_PUBAGENCY');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '099003', null, '1', 'FININTORGGUID', '1', '2016', '87', 'BD2A3B90E52E3AC1E053B11FA8C06F54', 'FININTORGGUID', 'PMKPI_FASP_T_PUBAGENCY', '处室guid', 'S', '40', null, null, 1, null, sysdate);
