begin
  
delete from bus_t_dictable t where t.tablecode='PERF_T_PAGEMENU';

insert into bus_t_dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2016', '87', 'PERF_T_PAGEMENU', '页面配置菜单表', '页面配置菜单表', 2, 1, 'PERF_T_PAGEMENU', 'pmkpi', null, '0', 1, '0', 0, 1, null, sysdate, 1, 1, null, '1');

delete from bus_t_diccolumn t where t.tablecode in('PERF_T_PAGEMENU');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CODE', '1', '2021', '87', 'BFDA42136268FD6CE053B11FA8C02A04', 'CODE', 'PERF_T_PAGEMENU', '编码', 'S', '50', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATER', '1', '2021', '87', 'BFDA42136269FD6CE053B11FA8C02A04', 'CREATER', 'PERF_T_PAGEMENU', '创建人', 'S', '40', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATETIME', '1', '2021', '87', 'BFDA4213626AFD6CE053B11FA8C02A04', 'CREATETIME', 'PERF_T_PAGEMENU', '创建时间', 'S', '17', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2021', '87', 'BFDA4213626BFD6CE053B11FA8C02A04', 'GUID', 'PERF_T_PAGEMENU', '主键', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ISLEAF', '1', '2021', '87', 'BFDA4213627BFD6CE053B11FA8C02A04', 'ISLEAF', 'PERF_T_PAGEMENU', '是否末级', 'N', '1', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LEVELNO', '1', '2021', '87', 'BFDA4213626CFD6CE053B11FA8C02A04', 'LEVELNO', 'PERF_T_PAGEMENU', '级次', 'N', '2', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'NAME', '1', '2016', '87', 'BFDA4213626DFD6CE053B11FA8C02A04', 'NAME', 'PERF_T_PAGEMENU', '三级指标名称', 'S', '200', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ORDERNUM', '1', '2021', '87', 'BFDA4213626EFD6CE053B11FA8C02A04', 'ORDERNUM', 'PERF_T_PAGEMENU', '排序', 'N', '9', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2021', '87', 'BFDA4213626FFD6CE053B11FA8C02A04', 'PROVINCE', 'PERF_T_PAGEMENU', '省', 'S', '9', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'STATUS', '1', '2021', '87', 'BFDA42136270FD6CE053B11FA8C02A04', 'STATUS', 'PERF_T_PAGEMENU', '状态', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SUPERGUID', '1', '2021', '87', 'BFDA42136271FD6CE053B11FA8C02A04', 'SUPERGUID', 'PERF_T_PAGEMENU', '父级', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UIKEY', '1', '2021', '87', 'BFDA42136274FD6CE053B11FA8C02A04', 'UIKEY', 'PERF_T_PAGEMENU', '页面key', 'S', '2000', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UPDATETIME', '1', '2021', '87', 'BFDA42136272FD6CE053B11FA8C02A04', 'UPDATETIME', 'PERF_T_PAGEMENU', '更新时间', 'S', '17', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2021', '87', 'BFDA42136273FD6CE053B11FA8C02A04', 'YEAR', 'PERF_T_PAGEMENU', '年度', 'S', '4', null, 1, 0, null, sysdate);

delete from bus_t_dictable t where t.tablecode='BUS_T_PAGECONSOLECOMCONFIG';
insert into bus_t_dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2021', '87', 'BUS_T_PAGECONSOLECOMCONFIG', '框架组件引用表', null, 2, 1, 'BUS_T_PAGECONSOLECOMCONFIG', 'pmkpi', null, null, 1, null, 1, 1, null, sysdate, null, null, null, '1');

delete from bus_t_diccolumn t where t.tablecode in('BUS_T_PAGECONSOLECOMCONFIG');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'APPID', '1', '2016', '87', 'BFC6A35D57A4520DE053B11FA8C0963C', 'APPID', 'BUS_T_PAGECONSOLECOMCONFIG', 'appid', 'S', '400', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'COMPONENTID', '1', '2016', '87', 'BFC6A35D57A1520DE053B11FA8C0963C', 'COMPONENTID', 'BUS_T_PAGECONSOLECOMCONFIG', '组件', 'S', '200', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CONFIG', '1', '2016', '87', 'BFC6A35D57A2520DE053B11FA8C0963C', 'CONFIG', 'BUS_T_PAGECONSOLECOMCONFIG', 'config', 'S', '4000', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ID', '1', '2016', '87', 'BFC6A35D57A3520DE053B11FA8C0963C', 'ID', 'BUS_T_PAGECONSOLECOMCONFIG', 'id', 'S', '200', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'REGION', '1', '2016', '87', 'BFC6A35D57A5520DE053B11FA8C0963C', 'REGION', 'BUS_T_PAGECONSOLECOMCONFIG', 'region', 'S', '200', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'URL', '1', '2016', '87', 'BFC6A35D57A0520DE053B11FA8C0963C', 'URL', 'BUS_T_PAGECONSOLECOMCONFIG', 'url', 'S', '200', null, null, 1, null, sysdate);
