begin
  
DELETE FROM bus_t_Diccolumn t where t.tablecode='PM_PERF_INDICATOR_TEMP' and 
t.columncode in ('KPI_CONTENT','FISCAL_YEAR','KPI_LV1','KPI_LV2','KPI_LV3','KPI_VAL',
'BUSI_TYPE','VERSION','SUB_MOF_CODE','UPDATE_TIME','IS_DELETED','KPI_ID','PRO_CODE','MOF_DIV_CODE',
'KPI_REMARK','CREATE_TIME','VERSION_NAME','KPI_EVALSTD','FROMGUID','KPIVALSOURCE');
insert into bus_t_Diccolumn (COLUMNID, DBCOLUMNCODE, COLUMNCODE, NAME, TABLECODE, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, DEID, CSID, ISSYS, ISUSES, VERSION)
values ('AE7A505688392B55E0530603A8C08935', 'KPI_CONTENT', 'KPI_CONTENT', '指标内容', 'PM_PERF_INDICATOR_TEMP', 'S', '2000', null, null, null, 'BE10031', null, '0', '1', '1');

insert into bus_t_Diccolumn (COLUMNID, DBCOLUMNCODE, COLUMNCODE, NAME, TABLECODE, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, DEID, CSID, ISSYS, ISUSES, VERSION)
values ('AE7A505688152B55E0530603A8C08935', 'FISCAL_YEAR', 'FISCAL_YEAR', '预算年度', 'PM_PERF_INDICATOR_TEMP', 'S', '4', null, null, null, 'BE00029', null, '0', '1', '1');

insert into bus_t_Diccolumn (COLUMNID, DBCOLUMNCODE, COLUMNCODE, NAME, TABLECODE, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, DEID, CSID, ISSYS, ISUSES, VERSION)
values ('AE7A505688172B55E0530603A8C08935', 'KPI_LV1', 'KPI_LV1', '一级指标', 'PM_PERF_INDICATOR_TEMP', 'S', '30', null, null, null, 'BE09101', 'VD08120', '0', '1', '1');

insert into bus_t_Diccolumn (COLUMNID, DBCOLUMNCODE, COLUMNCODE, NAME, TABLECODE, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, DEID, CSID, ISSYS, ISUSES, VERSION)
values ('AE7A505688372B55E0530603A8C08935', 'KPI_LV2', 'KPI_LV2', '二级指标', 'PM_PERF_INDICATOR_TEMP', 'S', '30', null, null, null, 'BE09101', 'VD08120', '0', '1', '1');

insert into bus_t_Diccolumn (COLUMNID, DBCOLUMNCODE, COLUMNCODE, NAME, TABLECODE, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, DEID, CSID, ISSYS, ISUSES, VERSION)
values ('AE7A505688382B55E0530603A8C08935', 'KPI_LV3', 'KPI_LV3', '三级指标', 'PM_PERF_INDICATOR_TEMP', 'S', '30', null, null, null, 'BE09101', 'VD08120', '0', '1', '1');

insert into bus_t_Diccolumn (COLUMNID, DBCOLUMNCODE, COLUMNCODE, NAME, TABLECODE, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, DEID, CSID, ISSYS, ISUSES, VERSION)
values ('AE7A5056883B2B55E0530603A8C08935', 'KPI_VAL', 'KPI_VAL', '指标值', 'PM_PERF_INDICATOR_TEMP', 'S', '60', null, null, null, 'BE10033', null, '0', '1', '1');

insert into bus_t_Diccolumn (COLUMNID, DBCOLUMNCODE, COLUMNCODE, NAME, TABLECODE, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, DEID, CSID, ISSYS, ISUSES, VERSION)
values ('AE7A5056883D2B55E0530603A8C08935', 'BUSI_TYPE', 'BUSI_TYPE', '业务类型代码', 'PM_PERF_INDICATOR_TEMP', 'S', '6', null, null, null, 'BE10029', 'VD09006', '0', '1', '1');

insert into bus_t_Diccolumn (COLUMNID, DBCOLUMNCODE, COLUMNCODE, NAME, TABLECODE, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, DEID, CSID, ISSYS, ISUSES, VERSION)
values ('AE7A5056883E2B55E0530603A8C08935', 'VERSION', 'VERSION', '版本号', 'PM_PERF_INDICATOR_TEMP', 'S', '38', null, null, null, 'BE00001', null, '0', '1', '1');

insert into bus_t_Diccolumn (COLUMNID, DBCOLUMNCODE, COLUMNCODE, NAME, TABLECODE, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, DEID, CSID, ISSYS, ISUSES, VERSION)
values ('AE7A505688402B55E0530603A8C08935', 'SUB_MOF_CODE', 'SUB_MOF_CODE', '下级财政区划代码', 'PM_PERF_INDICATOR_TEMP', 'S', '9', null, null, null, 'BE00017', 'VD08001', '0', '1', '1');

insert into bus_t_Diccolumn (COLUMNID, DBCOLUMNCODE, COLUMNCODE, NAME, TABLECODE, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, DEID, CSID, ISSYS, ISUSES, VERSION)
values ('AE7A505688412B55E0530603A8C08935', 'UPDATE_TIME', 'UPDATE_TIME', '更新时间', 'PM_PERF_INDICATOR_TEMP', 'D', null, null, null, null, 'BE00023', null, '0', '1', '1');

insert into bus_t_Diccolumn (COLUMNID, DBCOLUMNCODE, COLUMNCODE, NAME, TABLECODE, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, DEID, CSID, ISSYS, ISUSES, VERSION)
values ('AE7A505688422B55E0530603A8C08935', 'IS_DELETED', 'IS_DELETED', '是否删除', 'PM_PERF_INDICATOR_TEMP', 'N', '1', null, null, null, 'BE00030', null, '0', '1', '1');

insert into bus_t_Diccolumn (COLUMNID, DBCOLUMNCODE, COLUMNCODE, NAME, TABLECODE, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, DEID, CSID, ISSYS, ISUSES, VERSION)
values ('AE7A505688132B55E0530603A8C08935', 'KPI_ID', 'KPI_ID', '项目绩效指标主键', 'PM_PERF_INDICATOR_TEMP', 'S', '38', null, null, null, 'BE00001', null, '0', '1', '1');

insert into bus_t_Diccolumn (COLUMNID, DBCOLUMNCODE, COLUMNCODE, NAME, TABLECODE, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, DEID, CSID, ISSYS, ISUSES, VERSION)
values ('AE7A505688162B55E0530603A8C08935', 'PRO_CODE', 'PRO_CODE', '项目代码', 'PM_PERF_INDICATOR_TEMP', 'S', '21', null, null, null, 'BE10002', null, '0', '1', '1');

insert into bus_t_Diccolumn (COLUMNID, DBCOLUMNCODE, COLUMNCODE, NAME, TABLECODE, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, DEID, CSID, ISSYS, ISUSES, VERSION)
values ('AE7A505688142B55E0530603A8C08935', 'MOF_DIV_CODE', 'MOF_DIV_CODE', '财政区划代码', 'PM_PERF_INDICATOR_TEMP', 'S', '9', null, null, null, 'BE00017', 'VD08001', '0', '1', '1');

insert into bus_t_Diccolumn (COLUMNID, DBCOLUMNCODE, COLUMNCODE, NAME, TABLECODE, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, DEID, CSID, ISSYS, ISUSES, VERSION)
values ('AE7A5056883C2B55E0530603A8C08935', 'KPI_REMARK', 'KPI_REMARK', '备注', 'PM_PERF_INDICATOR_TEMP', 'S', '2000', null, null, null, 'BE10034', null, '0', '1', '1');

insert into bus_t_Diccolumn (COLUMNID, DBCOLUMNCODE, COLUMNCODE, NAME, TABLECODE, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, DEID, CSID, ISSYS, ISUSES, VERSION)
values ('AE7A505688432B55E0530603A8C08935', 'CREATE_TIME', 'CREATE_TIME', '创建时间', 'PM_PERF_INDICATOR_TEMP', 'D', null, null, null, null, 'BE00036', null, '0', '1', '1');

insert into bus_t_Diccolumn (COLUMNID, DBCOLUMNCODE, COLUMNCODE, NAME, TABLECODE, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, DEID, CSID, ISSYS, ISUSES, VERSION)
values ('AE7A5056883F2B55E0530603A8C08935', 'VERSION_NAME', 'VERSION_NAME', '版本说明', 'PM_PERF_INDICATOR_TEMP', 'S', '400', null, null, null, 'BE11056', null, '0', '1', '1');

insert into bus_t_Diccolumn (COLUMNID, DBCOLUMNCODE, COLUMNCODE, NAME, TABLECODE, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, DEID, CSID, ISSYS, ISUSES, VERSION)
values ('BFEDD90AE55D1869E053470A050A5B72', 'KPI_EVALSTD', 'KPI_EVALSTD', '评（扣）分标准', 'PM_PERF_INDICATOR_TEMP', 'S', '2000', null, null, null, 'BE10032', null, '0', '1', '1');

insert into bus_t_Diccolumn (COLUMNID, DBCOLUMNCODE, COLUMNCODE, NAME, TABLECODE, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, DEID, CSID, ISSYS, ISUSES, VERSION)
values ('BFEDD90AE55E1869E053470A050A5B72', 'KPIVALSOURCE', 'KPIVALSOURCE', '定量其他值', 'PM_PERF_INDICATOR_TEMP', 'S', '40', null, 0, null, null, 'KPIVALSOURCE', '1', '1', '1');
