begin

delete from bus_t_dictable t where t.tablecode='PERF_IMPTMP_CASEMODELINDEX';
insert into bus_t_dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2016', '87', 'PERF_IMPTMP_CASEMODELINDEX', '案例导入虚拟表', '案例导入虚拟表', 2, 1, 'PERF_IMPTMP_CASEMODELINDEX', 'pmkpi', null, '0', 1, null, 1, 1, 'PERF_IMPTMP_CASEMODELINDEX', sysdate, 1, 1, null, '1');

delete from bus_t_diccolumn t where t.tablecode='PERF_IMPTMP_CASEMODELINDEX';
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ADJUSTINDEXGUID', '1', '2016', '87', 'FD08BDD28C732EC1E0533315A8C0C983', 'ADJUSTINDEXGUID', 'PERF_IMPTMP_CASEMODELINDEX', '调整前指标guid', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '1', 'AGENCYGUID', '1', '2016', '87', 'FD08BDD28C742EC1E0533315A8C0C983', 'AGENCYGUID', 'PERF_IMPTMP_CASEMODELINDEX', '预算单位（部门）', 'S', '32', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AGENCYNAME', '1', '2016', '87', 'FD08BDD28CDC2EC1E0533315A8C0C983', 'AGENCYNAME', 'PERF_IMPTMP_CASEMODELINDEX', '预算单位（部门）名称', 'S', '32', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CALCDISPLAY', '1', '2016', '87', 'FD08BDD28C752EC1E0533315A8C0C983', 'CALCDISPLAY', 'PERF_IMPTMP_CASEMODELINDEX', '业绩值公式显示', 'S', '500', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CALCEXPLAIN', '1', '2016', '87', 'FD08BDD28C762EC1E0533315A8C0C983', 'CALCEXPLAIN', 'PERF_IMPTMP_CASEMODELINDEX', '业绩值公式解释', 'S', '1000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CALCFORMULA', '1', '2016', '87', 'FD08BDD28C772EC1E0533315A8C0C983', 'CALCFORMULA', 'PERF_IMPTMP_CASEMODELINDEX', '业绩值公式', 'S', '500', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CALCTYPE', '1', '2016', '87', 'FD08BDD28C782EC1E0533315A8C0C983', 'CALCTYPE', 'PERF_IMPTMP_CASEMODELINDEX', '业绩公式类型', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CALCULATEBY', '1', '2016', '87', 'FD08BDD28C792EC1E0533315A8C0C983', 'CALCULATEBY', 'PERF_IMPTMP_CASEMODELINDEX', '测算依据', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CASENAME', '1', '2016', '87', 'FD08BDD28CD62EC1E0533315A8C0C983', 'CASENAME', 'PERF_IMPTMP_CASEMODELINDEX', '案例名称', 'S', '100', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIZBXS', null, '1', 'COMPUTESIGN', '1', '2016', '87', 'FD08BDD28C7A2EC1E0533315A8C0C983', 'COMPUTESIGN', 'PERF_IMPTMP_CASEMODELINDEX', '计算符号', 'S', '32', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FILLYEAR', '1', '2016', '87', 'FD08BDD28C7B2EC1E0533315A8C0C983', 'FILLYEAR', 'PERF_IMPTMP_CASEMODELINDEX', '目标年度', 'S', '4', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIINDEXFRAME', null, '1', 'FINDEX', '1', '2016', '87', 'FD08BDD28C7C2EC1E0533315A8C0C983', 'FINDEX', 'PERF_IMPTMP_CASEMODELINDEX', '一级指标', 'S', '32', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FRAME', '1', '2016', '87', 'FD08BDD28C7D2EC1E0533315A8C0C983', 'FRAME', 'PERF_IMPTMP_CASEMODELINDEX', '模板', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FRAMESYSTEM', '1', '2016', '87', 'FD08BDD28C7E2EC1E0533315A8C0C983', 'FRAMESYSTEM', 'PERF_IMPTMP_CASEMODELINDEX', '体系', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'INDEXREMARK', '1', '2016', '87', 'FD08BDD28C7F2EC1E0533315A8C0C983', 'INDEXREMARK', 'PERF_IMPTMP_CASEMODELINDEX', '指标说明', 'S', '1000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'INDEXTYPE', '1', '2016', '87', 'FD08BDD28C802EC1E0533315A8C0C983', 'INDEXTYPE', 'PERF_IMPTMP_CASEMODELINDEX', '指标值类型', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'INDEXVALUE', '1', '2016', '87', 'FD08BDD28C812EC1E0533315A8C0C983', 'INDEXVALUE', 'PERF_IMPTMP_CASEMODELINDEX', '指标值', 'S', '500', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'INDEXCOMFUNC', null, '1', 'INDUSTRYCATEGORY', '1', '2016', '87', 'FD08BDD28C822EC1E0533315A8C0C983', 'INDUSTRYCATEGORY', 'PERF_IMPTMP_CASEMODELINDEX', '行业类别', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ISTEMP', '1', '2016', '87', 'FD08BDD28C832EC1E0533315A8C0C983', 'ISTEMP', 'PERF_IMPTMP_CASEMODELINDEX', '是否模板', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'METERUNIT', '1', '2016', '87', 'FD08BDD28C842EC1E0533315A8C0C983', 'METERUNIT', 'PERF_IMPTMP_CASEMODELINDEX', '计量单位', 'S', '100', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MIDDLEVALUE', '1', '2016', '87', 'FD08BDD28C852EC1E0533315A8C0C983', 'MIDDLEVALUE', 'PERF_IMPTMP_CASEMODELINDEX', '中期指标值', 'S', '500', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'NAME', '1', '2016', '87', 'FD08BDD28C862EC1E0533315A8C0C983', 'NAME', 'PERF_IMPTMP_CASEMODELINDEX', '三级指标名称', 'S', '200', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'NDGOAL', '1', '2016', '87', 'FD08BDD28CD72EC1E0533315A8C0C983', 'NDGOAL', 'PERF_IMPTMP_CASEMODELINDEX', '年度目标', 'S', '2000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ORDERNUM', '1', '2016', '87', 'FD08BDD28C872EC1E0533315A8C0C983', 'ORDERNUM', 'PERF_IMPTMP_CASEMODELINDEX', '排序编码', 'S', '9', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'REMARK', '1', '2016', '87', 'FD08BDD28C882EC1E0533315A8C0C983', 'REMARK', 'PERF_IMPTMP_CASEMODELINDEX', '指标及指标值来源', 'S', '2000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SCOREDISPLAY', '1', '2016', '87', 'FD08BDD28C892EC1E0533315A8C0C983', 'SCOREDISPLAY', 'PERF_IMPTMP_CASEMODELINDEX', '评分公式显示', 'S', '500', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SCOREEXPLAIN', '1', '2016', '87', 'FD08BDD28C8A2EC1E0533315A8C0C983', 'SCOREEXPLAIN', 'PERF_IMPTMP_CASEMODELINDEX', '评分公式解释', 'S', '1000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SCOREFORMULA', '1', '2016', '87', 'FD08BDD28C8B2EC1E0533315A8C0C983', 'SCOREFORMULA', 'PERF_IMPTMP_CASEMODELINDEX', '评分值公式', 'S', '500', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SCORETYPE', '1', '2016', '87', 'FD08BDD28C8C2EC1E0533315A8C0C983', 'SCORETYPE', 'PERF_IMPTMP_CASEMODELINDEX', '评分公式类型', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIINDEXFRAME', null, '1', 'SINDEX', '1', '2016', '87', 'FD08BDD28C8D2EC1E0533315A8C0C983', 'SINDEX', 'PERF_IMPTMP_CASEMODELINDEX', '二级指标', 'S', '32', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TARGETREMARK', '1', '2016', '87', 'FD08BDD28C8E2EC1E0533315A8C0C983', 'TARGETREMARK', 'PERF_IMPTMP_CASEMODELINDEX', '目标值说明', 'S', '1000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TARGETTYPE', '1', '2016', '87', 'FD08BDD28C8F2EC1E0533315A8C0C983', 'TARGETTYPE', 'PERF_IMPTMP_CASEMODELINDEX', '年度目标类型', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TARGETUNIT', '1', '2016', '87', 'FD08BDD28C902EC1E0533315A8C0C983', 'TARGETUNIT', 'PERF_IMPTMP_CASEMODELINDEX', '目标值量度单位', 'S', '200', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TARGETVALUE', '1', '2016', '87', 'FD08BDD28C912EC1E0533315A8C0C983', 'TARGETVALUE', 'PERF_IMPTMP_CASEMODELINDEX', '目标值', 'S', '200', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TINDEX', '1', '2016', '87', 'FD08BDD28C922EC1E0533315A8C0C983', 'TINDEX', 'PERF_IMPTMP_CASEMODELINDEX', '三级指标', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PERFVALUECHANGE', null, '1', 'VALUE_CHANGE', '1', '2016', '87', 'FD08BDD28C932EC1E0533315A8C0C983', 'VALUE_CHANGE', 'PERF_IMPTMP_CASEMODELINDEX', '指标值变动情况', 'S', '40', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'VALUE_DESC', '1', '2021', '87', 'FD08BDD28C942EC1E0533315A8C0C983', 'VALUE_DESC', 'PERF_IMPTMP_CASEMODELINDEX', '参考指标值', 'S', '2000', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WEIGHT', '1', '2016', '87', 'FD08BDD28C952EC1E0533315A8C0C983', 'WEIGHT', 'PERF_IMPTMP_CASEMODELINDEX', '权重', 'S', '5', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ZQGOAL', '1', '2016', '87', 'FD08BDD28CD82EC1E0533315A8C0C983', 'ZQGOAL', 'PERF_IMPTMP_CASEMODELINDEX', '中期目标', 'S', '2000', null, 1, 1, null, sysdate);
