begin
  
delete from bus_t_diccolumn t where t.tablecode='PERF_T_MANCEOPEN' and t.columncode in('DEPT_CODE','BGTAMT','APPROVEDBGTAMT','APPROVALRATE','APPROVALTIME','OPENTIME','OPENRATE','REMARK','OPENPROAMT','OPENPRONUM','EVALUATEDPRONUM');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'APPROVALRATE', '1', '2020', '87', '4E61346CB8516697E063030011AC0401', 'APPROVALRATE', 'PERF_T_MANCEOPEN', '批复率', 'N', '16', 2, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'APPROVALTIME', '1', '2020', '87', '4E61346CB8526697E063030011AC0401', 'APPROVALTIME', 'PERF_T_MANCEOPEN', '批复时间', 'S', '17', 2, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'APPROVEDBGTAMT', '1', '2020', '87', '4E61346CB8506697E063030011AC0401', 'APPROVEDBGTAMT', 'PERF_T_MANCEOPEN', '批复预算资金', 'N', '16', 2, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BGTAMT', '1', '2020', '87', '4E61346CB84F6697E063030011AC0401', 'BGTAMT', 'PERF_T_MANCEOPEN', '预算资金', 'N', '16', 2, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIDEPT', null, '1', 'DEPT_CODE', '1', '2020', '87', '18F1BEA460582E5EE0635B03A8C098AC', 'DEPT_CODE', 'PERF_T_MANCEOPEN', '部门', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EVALUATEDPRONUM', '1', '2020', '87', '4E61346CB8586697E063030011AC0401', 'EVALUATEDPRONUM', 'PERF_T_MANCEOPEN', '参评项目个数', 'N', '9', 2, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'OPENPROAMT', '1', '2020', '87', '4E61346CB8566697E063030011AC0401', 'OPENPROAMT', 'PERF_T_MANCEOPEN', '公开项目资金', 'N', '16', 2, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'OPENPRONUM', '1', '2020', '87', '4E61346CB8576697E063030011AC0401', 'OPENPRONUM', 'PERF_T_MANCEOPEN', '公开项目个数', 'N', '9', 2, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'OPENRATE', '1', '2020', '87', '4E61346CB8546697E063030011AC0401', 'OPENRATE', 'PERF_T_MANCEOPEN', '公开率', 'N', '5', 2, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'OPENTIME', '1', '2020', '87', '4E61346CB8536697E063030011AC0401', 'OPENTIME', 'PERF_T_MANCEOPEN', '公开时间', 'S', '17', 2, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'REMARK', '1', '2020', '87', '4E61346CB8556697E063030011AC0401', 'REMARK', 'PERF_T_MANCEOPEN', '备注', 'S', '4000', 2, null, 1, null, sysdate);
