
i number;
begin
select count(*) into i from user_tables  t where t.TABLE_NAME='PM_PROJECT_INFO';
if i=1 then
  execute immediate '
create or replace view v_perf_project_info as
select t.PRO_ID,t.PRO_CODE,t.PRO_NAME,t.PRO_CAT_CODE,t.AGENCY_CODE,t.MOF_DEP_CODE,t.FININTORGGUID,t.DEPT_CODE,t.MANAGE_DEPT_CODE,t.MANAGE_MOF_DEP_CODE,t.TRAOBJ_AGENCY_CODE,t.CEN_TRA_PRO_CODE,t.PRO_SOURCE_CODE,t.SETUP_YEAR,t.PRO_START_YEAR,t.PRO_TERM,t.DISTRI_TYPE_CODE,t.DRAFT_TEMPLATE_CODE,t.PRO_DESC,t.EXP_FUNC_CODE,t.PRO_TOTAL_AMT,t.SCOI_INVEST_FUND,t.FUN_RES_CODE,t.IS_USESET,t.IS_TRACK,t.IS_END,t.IS_CAPTIAL_CONS_PRO,t.IS_SCIENTIFIC,t.PRO_DEPREVIEW,t.PRO_BGTREVIEW,t.DEP_AUD_OPINION_CODE,t.MOF_AUD_OPINION_CODE,t.CREATE_TIME,t.UPDATE_TIME,t.VERSION,t.VERSION_NAME,t.IS_DELETED,t.GUID,t.MOF_DIV_CODE,t.LASTAUDIT,t.STORE_PHASE,t.PRO_PHASE,t.PRO_LEVONE_ID,t.PRO_LEVONE_CODE,t.PRO_LEVONE_NAME,t.PRO_LEV,t.LEADER_NAME,t.LEADER_TEL,t.LEADER_PHONE,t.IS_PERFORM,t.IS_ATTACH,t.IS_GOVPUR,t.IS_BGT,t.IS_THIN,t.IS_OTHER_EDIT,t.IS_WAIT_DIVIDE,t.IS_DIVIDE_PRO,t.IS_TO_DOWN,t.MID_PLAN_YEAR,t.ORDERNO1,t.ORDERNO2,t.ORDERNO3,t.ORDERNO4,t.VCHTYPEID,t.WFSTATUS,t.WFID,t.CREATER,t.LASTUPDATETIME,t.AUDITOR,t.V_COL1,t.V_COL2,t.V_COL3,t.V_COL4,t.V_COL5,t.V_COL6,t.V_COL7,t.V_COL8,t.V_COL9,t.V_COL10,t.V_COL11,t.V_COL12,t.V_COL13,t.V_COL14,t.V_COL15,t.V_COL16,t.V_COL17,t.V_COL18,t.V_COL19,t.V_COL20,t.V_COL21,t.V_COL22,t.V_COL23,t.V_COL24,t.V_COL25,t.V_COL26,t.V_COL27,t.V_COL28,t.V_COL29,t.V_COL30,t.N_COL1,t.N_COL2,t.N_COL3,t.N_COL4,t.N_COL5,t.N_COL6,t.N_COL7,t.N_COL8,t.PROVINCE,t.YEAR,t.ADJSTATUS,t.FROMGUID,t.ISHISTORY,t.ISPUBLISH,
t.AGENCY_CODE as AGENCYGUID,t.PROJECTKIND,t.IS_FROMUP,t.PRO_TRA_STATUS,t.SUB_AGENCY_NAME,t.IS_URGENT,t.QKSFBS,t.ZDZJJQPT,t.DIRECTFUNDS,t.SUBSIDY,t.SUB_MOF_DIV_CODE,t.PRO_GRADE,t.PRO_BASES,t.PRO_OTHER,t.PRO_BASES_TYPE,t.IS_INCREASE_PEOPLE_MONEY,t.INTEGRATE_CATEGORY,t.IS_OUTSAVE,t.BANK_LOAN_FUND,t.PRO_TOTAL_AMT_OLD,t.IS_BGT_APPEND,t.GENERATE_FLAG
  from pm_project_info t
 where province = global_multyear_cz.Secu_f_GLOBAL_PARM(''DIVID'') 
 and nvl(t.lastaudit, 2) = 1 and t.is_deleted=2';
 
 execute immediate '
create or replace view v_perf_allproject_info as
select t.PRO_ID,t.PRO_CODE,t.PRO_NAME,t.PRO_CAT_CODE,t.AGENCY_CODE,t.MOF_DEP_CODE,t.FININTORGGUID,t.DEPT_CODE,t.MANAGE_DEPT_CODE,t.MANAGE_MOF_DEP_CODE,t.TRAOBJ_AGENCY_CODE,t.CEN_TRA_PRO_CODE,t.PRO_SOURCE_CODE,t.SETUP_YEAR,t.PRO_START_YEAR,t.PRO_TERM,t.DISTRI_TYPE_CODE,t.DRAFT_TEMPLATE_CODE,t.PRO_DESC,t.EXP_FUNC_CODE,t.PRO_TOTAL_AMT,t.SCOI_INVEST_FUND,t.FUN_RES_CODE,t.IS_USESET,t.IS_TRACK,t.IS_END,t.IS_CAPTIAL_CONS_PRO,t.IS_SCIENTIFIC,t.PRO_DEPREVIEW,t.PRO_BGTREVIEW,t.DEP_AUD_OPINION_CODE,t.MOF_AUD_OPINION_CODE,t.CREATE_TIME,t.UPDATE_TIME,t.VERSION,t.VERSION_NAME,t.IS_DELETED,t.GUID,t.MOF_DIV_CODE,t.LASTAUDIT,t.STORE_PHASE,t.PRO_PHASE,t.PRO_LEVONE_ID,t.PRO_LEVONE_CODE,t.PRO_LEVONE_NAME,t.PRO_LEV,t.LEADER_NAME,t.LEADER_TEL,t.LEADER_PHONE,t.IS_PERFORM,t.IS_ATTACH,t.IS_GOVPUR,t.IS_BGT,t.IS_THIN,t.IS_OTHER_EDIT,t.IS_WAIT_DIVIDE,t.IS_DIVIDE_PRO,t.IS_TO_DOWN,t.MID_PLAN_YEAR,t.ORDERNO1,t.ORDERNO2,t.ORDERNO3,t.ORDERNO4,t.VCHTYPEID,t.WFSTATUS,t.WFID,t.CREATER,t.LASTUPDATETIME,t.AUDITOR,t.V_COL1,t.V_COL2,t.V_COL3,t.V_COL4,t.V_COL5,t.V_COL6,t.V_COL7,t.V_COL8,t.V_COL9,t.V_COL10,t.V_COL11,t.V_COL12,t.V_COL13,t.V_COL14,t.V_COL15,t.V_COL16,t.V_COL17,t.V_COL18,t.V_COL19,t.V_COL20,t.V_COL21,t.V_COL22,t.V_COL23,t.V_COL24,t.V_COL25,t.V_COL26,t.V_COL27,t.V_COL28,t.V_COL29,t.V_COL30,t.N_COL1,t.N_COL2,t.N_COL3,t.N_COL4,t.N_COL5,t.N_COL6,t.N_COL7,t.N_COL8,t.PROVINCE,t.YEAR,t.ADJSTATUS,t.FROMGUID,t.ISHISTORY,t.ISPUBLISH,
t.AGENCY_CODE as AGENCYGUID,t.PROJECTKIND,t.IS_FROMUP,t.PRO_TRA_STATUS,t.SUB_AGENCY_NAME,t.IS_URGENT,t.QKSFBS,t.ZDZJJQPT,t.DIRECTFUNDS,t.SUBSIDY,t.SUB_MOF_DIV_CODE,t.PRO_GRADE,t.PRO_BASES,t.PRO_OTHER,t.PRO_BASES_TYPE,t.IS_INCREASE_PEOPLE_MONEY,t.INTEGRATE_CATEGORY,t.IS_OUTSAVE,t.BANK_LOAN_FUND,t.PRO_TOTAL_AMT_OLD,t.IS_BGT_APPEND,t.GENERATE_FLAG
  from pm_project_info t
 where province = global_multyear_cz.Secu_f_Global_Parm(''DIVID'')
 and nvl(t.ishistory,2)=2 and t.is_deleted=2';

end if;