begin

delete FROM BUS_T_DICCOLUMN T WHERE T.TABLECODE='PERF_T_ADJUST' AND T.COLUMNCODE in('MANAGE_DEPT_CODE','MANAGE_MOF_DEP_CODE','MOF_DEP_CODE','DEPT_CODE','AGENCY_CODE');
insert into BUS_T_DICCOLUMN (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '0', 'AGENCY_CODE', '1', '2020', '87', 'CFB0962F961C4925E0533315A8C009D9', 'AGENCY_CODE', 'PERF_T_ADJUST', '单位', 'S', '40', null, null, 1, null, sysdate);

insert into BUS_T_DICCOLUMN (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '0', 'DEPT_CODE', '1', '2020', '87', 'CFB0962F96184925E0533315A8C009D9', 'DEPT_CODE', 'PERF_T_ADJUST', '单位主管部门', 'S', '40', null, null, 1, null, sysdate);

insert into BUS_T_DICCOLUMN (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '0', 'MANAGE_DEPT_CODE', '1', '2020', '87', 'CFB0962F96624925E0533315A8C009D9', 'MANAGE_DEPT_CODE', 'PERF_T_ADJUST', '资金主管部门', 'S', '40', null, null, 1, null, sysdate);

insert into BUS_T_DICCOLUMN (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '099003', null, '0', 'MANAGE_MOF_DEP_CODE', '1', '2020', '87', 'CFB0962F96634925E0533315A8C009D9', 'MANAGE_MOF_DEP_CODE', 'PERF_T_ADJUST', '资金主管处室', 'S', '40', null, null, 1, null, sysdate);

insert into BUS_T_DICCOLUMN (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '099003', null, '0', 'MOF_DEP_CODE', '1', '2020', '87', 'CFB0962F96674925E0533315A8C009D9', 'MOF_DEP_CODE', 'PERF_T_ADJUST', '单位归口处室', 'S', '40', null, null, 1, null, sysdate);
