begin
 

-- 部门评价
delete from bus_t_diccolumn  where tablecode='PERF_T_DEPTEVALUATION' and columncode in('DEPT_CODE','MANAGE_DEPT_CODE','MANAGE_MOF_DEP_CODE','MOF_DEP_CODE');

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE,DBVERSION)
values (null, null, null, '1', 'DEPT_CODE', '1', '2016', '87', 'BDPPPP2B028D2359E053B11FA8C0BCA5', 'DEPT_CODE', 'PERF_T_DEPTEVALUATION', '单位主管部门', 'S', '200', null, null, 1, null,sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE,DBVERSION)
values (null, null, null, '1', 'MANAGE_DEPT_CODE', '1', '2016', '87', 'BDPPPP2B028D2359E053B11FA8C0BCA1', 'MANAGE_DEPT_CODE', 'PERF_T_DEPTEVALUATION', '资金主管部门', 'S', '200', null, null, 1, null,sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE,DBVERSION)
values (null, null, null, '1', 'MANAGE_MOF_DEP_CODE', '1', '2016', '87', 'BDPPPP2B028D2359E053B11FA8C0BCA3', 'MANAGE_MOF_DEP_CODE', 'PERF_T_DEPTEVALUATION', '资金主管处室', 'S', '200', null, null, 1, null,sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE,DBVERSION)
values (null, null, null, '1', 'MOF_DEP_CODE', '1', '2016', '87', 'BDPPPP2B028D2359E053B11FA8C0BCA4', 'MOF_DEP_CODE', 'PERF_T_DEPTEVALUATION', '单位归口处室', 'S', '200', null, null, 1, null,sysdate);



-- 年度追加
delete from bus_t_diccolumn  where tablecode='PERF_T_DEPTPERFMIDDECLARE' and columncode in('DEPT_CODE','MANAGE_DEPT_CODE','MANAGE_MOF_DEP_CODE','MOF_DEP_CODE');

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE,DBVERSION)
values (null, null, null, '1', 'DEPT_CODE', '1', '2016', '87', '5e3a0377def68dfefd0a10U00a1b05a5', 'DEPT_CODE', 'PERF_T_DEPTPERFMIDDECLARE', '单位主管部门', 'S', '200', null, 1, 0, null,sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE,DBVERSION)
values (null, null, null, '1', 'MANAGE_DEPT_CODE', '1', '2016', '87', '5e3a0377def68dfefd0a10U00a1b05a2', 'MANAGE_DEPT_CODE', 'PERF_T_DEPTPERFMIDDECLARE', '资金主管部门', 'S', '200', null, 1, 0, null,sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE,DBVERSION)
values (null, null, null, '1', 'MANAGE_MOF_DEP_CODE', '1', '2016', '87', '5e3a0377def68dfefd0a10U00a1b05a3', 'MANAGE_MOF_DEP_CODE', 'PERF_T_DEPTPERFMIDDECLARE', '资金主管处室', 'S', '200', null, 1, 0, null,sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE,DBVERSION)
values (null, null, null, '1', 'MOF_DEP_CODE', '1', '2016', '87', '5e3a0377def68dfefd0a10U00a1b05a4', 'MOF_DEP_CODE', 'PERF_T_DEPTPERFMIDDECLARE', '单位归口处室', 'S', '200', null, 1, 0, null,sysdate);


--任务下达

delete from bus_t_diccolumn  where tablecode='PERF_T_SELFEVALTASK' and columncode in('DEPT_CODE','MANAGE_DEPT_CODE','MANAGE_MOF_DEP_CODE','MOF_DEP_CODE');

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE,DBVERSION)
values (null, null, null, '1', 'DEPT_CODE', '1', '2021', '87', 'P02FEA9940ED4254B92836B9A5B82764', 'DEPT_CODE', 'PERF_T_SELFEVALTASK', '单位主管部门', 'S', '200', null, 1, 1, null,sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE,DBVERSION)
values (null, null, null, '1', 'MANAGE_DEPT_CODE', '1', '2021', '87', 'P02FEA9940ED4254B92836B9A5B82761', 'MANAGE_DEPT_CODE', 'PERF_T_SELFEVALTASK', '资金主管部门', 'S', '200', null, 1, 1, null,sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE,DBVERSION)
values (null, null, null, '1', 'MANAGE_MOF_DEP_CODE', '1', '2021', '87', 'P02FEA9940ED4254B92836B9A5B82762', 'MANAGE_MOF_DEP_CODE', 'PERF_T_SELFEVALTASK', '资金主管处室', 'S', '200', null, 1, 1, null,sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE,DBVERSION)
values (null, null, null, '1', 'MOF_DEP_CODE', '1', '2021', '87', 'P02FEA9940ED4254B92836B9A5B82763', 'MOF_DEP_CODE', 'PERF_T_SELFEVALTASK', '单位归口处室', 'S', '200', null, 1, 1, null,sysdate);

-- 财政评价确认
delete from bus_t_diccolumn  where tablecode='PERF_T_FINEVALUATION' and columncode in('DEPT_CODE','MANAGE_DEPT_CODE','MANAGE_MOF_DEP_CODE','MOF_DEP_CODE');

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE,DBVERSION)
values (null, null, null, '1', 'DEPT_CODE', '1', '2016', '87', 'BD25F32C9E7777B9EPP3B11FA8C051F0', 'DEPT_CODE', 'PERF_T_FINEVALUATION', '单位主管部门', 'S', '200', null, null, 1, null,sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE,DBVERSION)
values (null, null, null, '1', 'MANAGE_DEPT_CODE', '1', '2016', '87', 'BD25F31C9E7777B9EPP3B11FA8C011F0', 'MANAGE_DEPT_CODE', 'PERF_T_FINEVALUATION', '资金主管部门', 'S', '200', null, null, 1, null,sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE,DBVERSION)
values (null, null, null, '1', 'MANAGE_MOF_DEP_CODE', '1', '2016', '87', 'BD25F32C9E7777B9EPP3B11FA8C021F0', 'MANAGE_MOF_DEP_CODE', 'PERF_T_FINEVALUATION', '资金主管处室', 'S', '200', null, null, 1, null,sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE,DBVERSION)
values (null, null, null, '1', 'MOF_DEP_CODE', '1', '2016', '87', 'BD25F32C9E7777B9EPP3B11FA8C031F0', 'MOF_DEP_CODE', 'PERF_T_FINEVALUATION', '单位归口处室', 'S', '200', null, null, 1, null,sysdate);


--项目库

delete from bus_t_diccolumn  where tablecode='PERF_PROJECT_INFO' and columncode in('DEPT_CODE','MANAGE_DEPT_CODE','MANAGE_MOF_DEP_CODE','MOF_DEP_CODE');


insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '1', 'DEPT_CODE', '1', null, null, 'B61B314BC2165271E0530100007F17EC', 'DEPT_CODE', 'PERF_PROJECT_INFO', '部门代码', 'S', null, null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '1', 'MANAGE_DEPT_CODE', '1', null, null, 'B61B314BC2355271E0530100007F17EC', 'MANAGE_DEPT_CODE', 'PERF_PROJECT_INFO', '主管部门代码', 'S', null, null, 1, 1, null,sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values ('DE03026', '099003', null, '1', 'MANAGE_MOF_DEP_CODE', '1', null, null, 'B61B314BC2365271E0530100007F17EC', 'MANAGE_MOF_DEP_CODE', 'PERF_PROJECT_INFO', '主管处室代码', 'S', null, null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values ('DE03026', '099003', null, '1', 'MOF_DEP_CODE', '1', null, null, 'B61B314BC2395271E0530100007F17EC', 'MOF_DEP_CODE', 'PERF_PROJECT_INFO', '财政内部机构代码', 'S', '6', null, 1, 1, null, sysdate);