begin
--自评布置表字段注册
delete from Bus_t_Diccolumn where tablecode = 'V_PERF_V_SELFEVALPROGRAMS';
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2016', '87', 'BCB59A7C05F2A02F8053B11FA8C0D3A3', 'GUID', 'V_PERF_V_SELFEVALPROGRAMS', '主键', 'S', '40', null, 1, 1, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROJGUID', '1', '2016', '87', 'BCB59A7C05F2A0211053B11FA8C0D3A3', 'PROJGUID', 'V_PERF_V_SELFEVALPROGRAMS', '项目id', 'S', '1', null, 1, 1, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_CODE', '1', '2016', '87', 'BCB59A7C05F2A02F4053B11FA8C0D3A3', 'PRO_CODE', 'V_PERF_V_SELFEVALPROGRAMS', '项目编码', 'S', '200', null, 1, 1, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROJCODE', '1', '2016', '87', '1CB59A7C05F2A02F4053B11FA8C0D3A3', 'PROJCODE', 'V_PERF_V_SELFEVALPROGRAMS', '项目编码', 'S', '200', null, 1, 1, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'NAME', '1', '2016', '87', 'BCB59A7C05F2A02F9053B11FA8C0D3A3', 'NAME', 'V_PERF_V_SELFEVALPROGRAMS', '名称', 'S', '200', null, 1, 1, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIAGENCYALLPAY', null, '1', 'AGENCYGUID', '1', '2016', '87', 'BCB59A7C05F2A02F1053B11FA8C0D3A3', 'AGENCYGUID', 'V_PERF_V_SELFEVALPROGRAMS', '单位', 'S', '40', null, 1, 1, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '099003', null, '1', 'FININTORGGUID', '1', '2016', '87', 'BCB59A7C05F2A02F7053B11FA8C0D3A3', 'FININTORGGUID', 'V_PERF_V_SELFEVALPROGRAMS', '处室', 'S', '40', null, 1, 1, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2016', '87', 'BCB59A7C05F2A0218053B11FA8C0D3A3', 'YEAR', 'V_PERF_V_SELFEVALPROGRAMS', '年度', 'S', '4', null, 1, 1, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2016', '87', 'BCB59A7C05F2A0213053B11FA8C0D3A3', 'PROVINCE', 'V_PERF_V_SELFEVALPROGRAMS', '省', 'S', '32', null, 1, 1, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROKIND', '1', '2016', '87', 'BCB59A7C05F2A0212053B11FA8C0D3A3', 'PROKIND', 'V_PERF_V_SELFEVALPROGRAMS', '项目类型', 'S', '1', null, 1, 1, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BUSTYPE', '1', '2016', '87', 'BCB59A7C05F2A02F3053B11FA8C0D3A3', 'BUSTYPE', 'V_PERF_V_SELFEVALPROGRAMS', '绩效类型', 'S', '40', null, 1, 1, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROCATEGORY', '1', '2016', '87', 'CCF16B4354C96519E0530B4B050A695B', 'PROCATEGORY', 'V_PERF_V_SELFEVALPROGRAMS', '项目类别', 'S', '40', null, 1, 1, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FUNC', '1', '2016', '87', 'CCF16B4354CC6519E0530B4B050A695B', 'FUNC', 'V_PERF_V_SELFEVALPROGRAMS', '支出功能分类科目代码', 'S', '40', null, 1, 1, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIWFSTATUS', null, '1', 'WFSTATUS', '1', '2016', '87', 'BCB59A7C05F2A0217053B11FA8C0D3A3', 'WFSTATUS', 'V_PERF_V_SELFEVALPROGRAMS', '工作流状态', 'S', '40', null, 1, 1, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'REMAININGDAYS', '1', '2016', '87', 'BCB59A7C05F2A0214053B11FA8C0D3A3', 'REMAININGDAYS', 'V_PERF_V_SELFEVALPROGRAMS', '截止天数', 'S', '40', null, 1, 1, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EVALEND', '1', '2016', '87', 'BCB59A7C05F2A02F5053B11FA8C0D3A3', 'EVALEND', 'V_PERF_V_SELFEVALPROGRAMS', '自评结束时间', 'S', '4', null, 1, 1, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EVALSTART', '1', '2016', '87', 'BCB59A7C05F2A02F6053B11FA8C0D3A3', 'EVALSTART', 'V_PERF_V_SELFEVALPROGRAMS', '自评开始时间', 'S', '40', null, 1, 1, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EVALSTATUS', '1', '2016', '87', '89CDCF6AA9AC44A69B8A28EAB571DD57', 'EVALSTATUS', 'V_PERF_V_SELFEVALPROGRAMS', '自评状态', 'S', '40', null, 1, 1, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UPDATETIME', '1', '2016', '87', 'BCB59A7C05F2A0215053B11FA8C0D3A3', 'UPDATETIME', 'V_PERF_V_SELFEVALPROGRAMS', '更新时间', 'S', '17', null, 1, 1, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WFID', '1', '2016', '87', 'BCB59A7C05F2A0216053B11FA8C0D3A3', 'WFID', 'V_PERF_V_SELFEVALPROGRAMS', '工作流id', 'S', '40', null, 1, 1, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BUDGETAMOUNT', '1', '2016', '87', 'BCB59A7C05F2A02F2053B11FA8C0D3A3', 'BUDGETAMOUNT', 'V_PERF_V_SELFEVALPROGRAMS', '全年预算数', 'S', '40', null, 1, 1, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EXECRATENUM', '1', '2016', '87', 'CD1D4315733D4BCB9479583B914CA12F', 'EXECRATENUM', 'V_PERF_V_SELFEVALPROGRAMS', '调整后预算数', 'S', '40', null, 1, 1, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EXECAMOUNT', '1', '2016', '87', 'BCB59A7C05F3A02FE053B11FA8C0D3A3', 'EXECAMOUNT', 'V_PERF_V_SELFEVALPROGRAMS', '预算执行数', 'N', '18', 2, 1, 1, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EXECRATE', '1', '2016', '87', 'BCB59A7C05F2A02FE053B11FA8C0D3A3', 'EXECRATE', 'V_PERF_V_SELFEVALPROGRAMS', '预算执行率', 'N', '18', 2, 1, 1, null, sysdate);

























