begin

DELETE FROM bus_t_Diccolumn t WHERE t.tablecode in ('PERF_EXPERTREVIEW','V_PERF_EXPERTREVIEW');
insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CODE', '1', '2016', '87', 'B9EE4152C835535BE053B11FA8C083B2', 'CODE', 'PERF_EXPERTREVIEW', '机构编码', 'S', '100', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATER', '1', '2016', '87', 'B9EE4152C836535BE053B11FA8C083B2', 'CREATER', 'PERF_EXPERTREVIEW', '创建人', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATETIME', '1', '2016', '87', 'B9EE4152C837535BE053B11FA8C083B2', 'CREATETIME', 'PERF_EXPERTREVIEW', '创建时间', 'S', '17', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EXPERTGUID', '1', '2016', '87', 'B9EE4152C841535BE053B11FA8C083B2', 'EXPERTGUID', 'PERF_EXPERTREVIEW', '专家guid', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2016', '87', 'B9EE4152C838535BE053B11FA8C083B2', 'GUID', 'PERF_EXPERTREVIEW', '主键', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'ISGROUP', null, '1', 'ISGROUP', '1', '2016', '87', 'B9EE4152C83D535BE053B11FA812a212', 'ISGROUP', 'PERF_EXPERTREVIEW', '是否组长', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MAINGUID', '1', '2016', '87', 'B9EE4152C840535BE053B11FA8C083B2', 'MAINGUID', 'PERF_EXPERTREVIEW', '评审guid', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'NAME', '1', '2016', '87', 'B9EE4152C839535BE053B11FA8C083B2', 'NAME', 'PERF_EXPERTREVIEW', '机构名称', 'S', '200', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ORDERNUM', '1', '2016', '87', 'B9EE4152C83E535BE053B11FA8C083B2', 'ORDERNUM', 'PERF_EXPERTREVIEW', '排序', 'N', '9', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROGUID', '1', '2016', '87', 'B9EE4152C83F535BE053B11FA8C083B2', 'PROGUID', 'PERF_EXPERTREVIEW', '项目guid', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2016', '87', 'B9EE4152C83A535BE053B11FA8C083B2', 'PROVINCE', 'PERF_EXPERTREVIEW', '区划', 'S', '9', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'STATUS', '1', '2016', '87', 'B9EE4152C83B535BE053B11FA8C083B2', 'STATUS', 'PERF_EXPERTREVIEW', '状态', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UPDATETIME', '1', '2016', '87', 'B9EE4152C83C535BE053B11FA8C083B2', 'UPDATETIME', 'PERF_EXPERTREVIEW', '更新时间', 'S', '17', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2016', '87', 'B9EE4152C83D535BE053B11FA8C083B2', 'YEAR', 'PERF_EXPERTREVIEW', '年度', 'N', '4', null, 1, 1, null, sysdate);

