begin

DELETE FROM Bus_t_Diccolumn t WHERE t.tablecode='PERF_V_PROMONITOR_HB';
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '1', 'AGENCYGUID', '1', '2020', '87', '2C830DC6AE94413FBA6803DCA1D1B450', 'AGENCYGUID', 'PERF_V_PROMONITOR_HB', '单位', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '1', 'AGENCY_CODE', '1', '2020', '87', '157734E7773C48958E31F57F8E27C6FF', 'AGENCY_CODE', 'PERF_V_PROMONITOR_HB', '单位', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AUDITOR', '1', '2020', '87', '0BC4F9E556244506A5CFC37C78BE340E', 'AUDITOR', 'PERF_V_PROMONITOR_HB', '审核人', 'S', '32', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIBGTWARN', null, '1', 'BGTWARN', '1', '2020', '87', 'C4BB84C3A16744EC8C530CE01F5E1288', 'BGTWARN', 'PERF_V_PROMONITOR_HB', '预算执行预警', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATER', '1', '2020', '87', '010EF5D6A378496F9BCBDB6901C4889F', 'CREATER', 'PERF_V_PROMONITOR_HB', '创建人', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATE_TIME', '1', '2020', '87', '4B146E56C052454D88451D5388B9D4D9', 'CREATE_TIME', 'PERF_V_PROMONITOR_HB', '创建时间', 'S', '17', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '1', 'DEPTTASK', '1', '2020', '87', 'E95C2402329D4D73B69012729E3CC723', 'DEPTTASK', 'PERF_V_PROMONITOR_HB', '部门任务下达1是2否', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '1', 'DEPT_CODE', '1', '2020', '87', '186FEA885D9941F58264C8FA60D27C84', 'DEPT_CODE', 'PERF_V_PROMONITOR_HB', '主管部门', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '099003', null, '1', 'FININTORGGUID', '1', '2020', '87', '9B2B3B4DC6DF41889DD3EF000C45A56B', 'FININTORGGUID', 'PERF_V_PROMONITOR_HB', '处室', 'N', '20', 5, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FISCAL_YEAR', '1', '2020', '87', 'A88A41A15D2F4BE69182F4FE68FDBF0A', 'FISCAL_YEAR', 'PERF_V_PROMONITOR_HB', '年度', 'S', '4', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FPRONAME', '1', '2020', '87', 'F194F64E3F1A403EB4BE165802F234D4', 'FPRONAME', 'PERF_V_PROMONITOR_HB', '一级项目名称', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIGOALWARN', null, '1', 'GOALWARN', '1', '2020', '87', '693F560F14F446D49E5E67C095735A37', 'GOALWARN', 'PERF_V_PROMONITOR_HB', '目标完成预警', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2020', '87', '3045DAD619C644518BB354044A3F94D1', 'GUID', 'PERF_V_PROMONITOR_HB', '主建', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ISLAST', '1', '2020', '87', '49C03F1DDBB14AAA84EFE7AA74AF30EF', 'ISLAST', 'PERF_V_PROMONITOR_HB', '是否最后一次', 'N', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_DELETED', '1', '2020', '87', 'D38A52174E384783845B06488DC9E18F', 'IS_DELETED', 'PERF_V_PROMONITOR_HB', '是否删除', 'N', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LASTUPDATETIME', '1', '2020', '87', '0449ADC38D8E411DAA02A7E3EC41F0E7', 'LASTUPDATETIME', 'PERF_V_PROMONITOR_HB', '时间戳', 'S', '17', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MOF_DIV_CODE', '1', '2020', '87', 'D5E5FAF7D9FB49BAA0B4979F3AB5D07A', 'MOF_DIV_CODE', 'PERF_V_PROMONITOR_HB', '区划', 'S', '9', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'NAME', '1', '2020', '87', '1C5D5FEC729040F9BC6099462D9ACC97', 'NAME', 'PERF_V_PROMONITOR_HB', '名称', 'S', '200', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROGUID', '1', '2020', '87', 'FEBF7941523E4FFEB81753E880108CDE', 'PROGUID', 'PERF_V_PROMONITOR_HB', '项目guid', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2020', '87', '00BC814E6D34402B8B375A10957857B4', 'PROVINCE', 'PERF_V_PROMONITOR_HB', '区划', 'S', '9', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '1', 'PROVINCETASK', '1', '2020', '87', 'F09C3A9DBFAF46B1ADDD032F29D8B021', 'PROVINCETASK', 'PERF_V_PROMONITOR_HB', '财政任务下达1是2否', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIHBPROCATCODE', null, '1', 'PRO_CAT_CODE', '1', '2020', '87', '7D8CD56CB58443049BF08ABF9EBF9411', 'PRO_CAT_CODE', 'PERF_V_PROMONITOR_HB', '项目类别', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_CODE', '1', '2020', '87', '2A64956A55C646B3A044C46636FABBB0', 'PRO_CODE', 'PERF_V_PROMONITOR_HB', '项目编码', 'S', '21', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_NAME', '1', '2020', '87', 'C85A7BCDB52B4FC382A3A7E98DDBB887', 'PRO_NAME', 'PERF_V_PROMONITOR_HB', '项目名称', 'S', '100', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'STATUS', '1', '2020', '87', 'A74467DFACA645A6ACAF0BB88C3F7953', 'STATUS', 'PERF_V_PROMONITOR_HB', '状态', 'N', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPITRACETASK', null, '1', 'TASKGUID', '1', '2020', '87', 'B92A83C6D57A4343AB336057DF13E874', 'TASKGUID', 'PERF_V_PROMONITOR_HB', '任务guid', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPITASKSTAGE', null, '1', 'TASKSTAGE', '1', '2020', '87', 'F22B77B56F80417AB6F2BDC77B82CBA5', 'TASKSTAGE', 'PERF_V_PROMONITOR_HB', '任务阶段', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIPERFTASK', null, '1', 'TASKTYPE', '1', '2020', '87', 'D71AF7C0D96B46C9A79E26959941FAB0', 'TASKTYPE', 'PERF_V_PROMONITOR_HB', '任务类型', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TRACENUM', '1', '2020', '87', '9BC92BD4AFC84F61809EB524F3EE9F81', 'TRACENUM', 'PERF_V_PROMONITOR_HB', '下达次数', 'N', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TRACESTATUS', '1', '2020', '87', 'D4A0C3AAB2EE4E50BEDF0BB2B042E526', 'TRACESTATUS', 'PERF_V_PROMONITOR_HB', '是否下达', 'N', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UPDATE_TIME', '1', '2020', '87', '13DC9F488DBB46368634FB29231494C0', 'UPDATE_TIME', 'PERF_V_PROMONITOR_HB', '修改时间', 'S', '17', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WFID', '1', '2020', '87', '50CD0141036B41B5AA50CDF8A8E37C18', 'WFID', 'PERF_V_PROMONITOR_HB', '工作流id', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIHBWFSTATUS', null, '1', 'WFSTATUS', '1', '2020', '87', 'A185927F4D4F4E4AAFEB4EC76F93660E', 'WFSTATUS', 'PERF_V_PROMONITOR_HB', '工作流状态', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2020', '87', '92B1B7054C5F47B0BED8831D44AE123A', 'YEAR', 'PERF_V_PROMONITOR_HB', '年度', 'S', '4', null, 1, 1, null, sysdate);

