begin
  
DELETE FROM Bus_t_Dictable t WHERE t.tablecode='V_PERF_PROJECT_YEAR';
insert into Bus_t_Dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2016', '87', 'V_PERF_PROJECT_YEAR', '项目年度绩效', '项目年度绩效', 2, 1, 'V_PERF_PROJECT_YEAR', 'pmkpi', null, '0', 1, '0', 0, 1, 'V_PERF_PROJECT_YEAR', sysdate, 1, 1, null, '1');


DELETE FROM Bus_t_Diccolumn t WHERE t.tablecode='V_PERF_PROJECT_YEAR';
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ADJ_AMT', '1', null, null, 'D0419BBF1A2D23B8E0533315A8C0FC8D', 'ADJ_AMT', 'V_PERF_PROJECT_YEAR', '调整金额', 'N', null, null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '1', 'AGENCYGUID', '1', null, null, 'D0419BBF1B4D23B8E0533315A8C0FC8D', 'AGENCYGUID', 'V_PERF_PROJECT_YEAR', '单位信息', 'S', null, null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values ('DE03002', 'VD00010', null, '0', 'AGENCY_CODE', '1', null, null, 'D0419BBF19BD23B8E0533315A8C0FC8D', 'AGENCY_CODE', 'V_PERF_PROJECT_YEAR', '单位代码', 'S', '21', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'APPLY_LINK', '1', null, null, 'D0419BBF1A2B23B8E0533315A8C0FC8D', 'APPLY_LINK', 'V_PERF_PROJECT_YEAR', '申报环节', 'S', '1', null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'APPLY_UP', '1', null, null, 'D0419BBF1A2923B8E0533315A8C0FC8D', 'APPLY_UP', 'V_PERF_PROJECT_YEAR', '申报数', 'N', null, null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BGT_PMAN_ID', '1', null, null, 'D0419BBF1A2423B8E0533315A8C0FC8D', 'BGT_PMAN_ID', 'V_PERF_PROJECT_YEAR', '项目年度预算主键', 'S', '38', null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD10008', null, '1', 'BUDGET_LEVEL_CODE', '1', null, null, 'D0419BBF1A2223B8E0533315A8C0FC8D', 'BUDGET_LEVEL_CODE', 'V_PERF_PROJECT_YEAR', '预算级次代码', 'S', '1', null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'CEN_TRA_PRO_CODE', '1', null, null, 'D0419BBF19BE23B8E0533315A8C0FC8D', 'CEN_TRA_PRO_CODE', 'V_PERF_PROJECT_YEAR', '上级转移支付项目代码', 'S', '21', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '61006100UEw5VQ8y', null, '0', 'CREATER', '1', null, null, 'D0419BBF19BF23B8E0533315A8C0FC8D', 'CREATER', 'V_PERF_PROJECT_YEAR', '建单人', 'S', null, null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'CREATE_TIME', '1', null, null, 'D0419BBF19C023B8E0533315A8C0FC8D', 'CREATE_TIME', 'V_PERF_PROJECT_YEAR', '创建时间', 'S', null, null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CUR_AMT', '1', null, null, 'D0419BBF1A2E23B8E0533315A8C0FC8D', 'CUR_AMT', 'V_PERF_PROJECT_YEAR', '变动后预算数', 'N', null, null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '1', 'DEPT_CODE', '1', null, null, 'D0419BBF19C123B8E0533315A8C0FC8D', 'DEPT_CODE', 'V_PERF_PROJECT_YEAR', '部门代码', 'S', null, null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD10006', null, '1', 'DEP_BGT_ECO_CODE', '1', null, null, 'D0419BBF1A2723B8E0533315A8C0FC8D', 'DEP_BGT_ECO_CODE', 'V_PERF_PROJECT_YEAR', '部门支出经济分类代码', 'S', '7', null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD09002', null, '0', 'DISTRI_TYPE_CODE', '1', null, null, 'D0419BBF19C223B8E0533315A8C0FC8D', 'DISTRI_TYPE_CODE', 'V_PERF_PROJECT_YEAR', '分配方式', 'S', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'DIS_AMT', '1', null, null, 'D0419BBF1A3023B8E0533315A8C0FC8D', 'DIS_AMT', 'V_PERF_PROJECT_YEAR', '调剂金额', 'N', null, null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'DRAFT_TEMPLATE_CODE', '1', null, null, 'D0419BBF19C323B8E0533315A8C0FC8D', 'DRAFT_TEMPLATE_CODE', 'V_PERF_PROJECT_YEAR', '编报模板代码', 'S', '32', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD10004', null, '1', 'EXP_FUNC_CODE', '1', null, null, 'D0419BBF1A2F23B8E0533315A8C0FC8D', 'EXP_FUNC_CODE', 'V_PERF_PROJECT_YEAR', '支出功能分类科目代码', 'S', '7', null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '099003', null, '1', 'FININTORGGUID', '1', null, null, 'D0419BBF19C423B8E0533315A8C0FC8D', 'FININTORGGUID', 'V_PERF_PROJECT_YEAR', '财政处室', 'S', null, null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FISCAL_YEAR', '1', null, null, 'D0419BBF1A3123B8E0533315A8C0FC8D', 'FISCAL_YEAR', 'V_PERF_PROJECT_YEAR', '预算年度', 'S', '4', null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD10013', null, '1', 'FOUND_TYPE_CODE', '1', null, null, 'D0419BBF1A2323B8E0533315A8C0FC8D', 'FOUND_TYPE_CODE', 'V_PERF_PROJECT_YEAR', '资金来源代码', 'S', '6', null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD10001', null, '1', 'FUND_TYPE_CODE', '1', null, null, 'D0419BBF1A2823B8E0533315A8C0FC8D', 'FUND_TYPE_CODE', 'V_PERF_PROJECT_YEAR', '资金性质代码', 'S', '3', null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'FUN_RES_CODE', '1', null, null, 'D0419BBF19C523B8E0533315A8C0FC8D', 'FUN_RES_CODE', 'V_PERF_PROJECT_YEAR', '职能职责代码', 'S', '6', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD10005', null, '1', 'GOV_BGT_ECO_CODE', '1', null, null, 'D0419BBF1A2623B8E0533315A8C0FC8D', 'GOV_BGT_ECO_CODE', 'V_PERF_PROJECT_YEAR', '政府支出经济分类代码', 'S', '7', null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', null, null, 'D0419BBF19C623B8E0533315A8C0FC8D', 'GUID', 'V_PERF_PROJECT_YEAR', '业务主键', 'S', null, null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'IS_CAPTIAL_CONS_PRO', '1', null, null, 'D0419BBF19C723B8E0533315A8C0FC8D', 'IS_CAPTIAL_CONS_PRO', 'V_PERF_PROJECT_YEAR', '是否基建项目', 'N', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'IS_DELETED', '1', null, null, 'D0419BBF19C823B8E0533315A8C0FC8D', 'IS_DELETED', 'V_PERF_PROJECT_YEAR', '是否删除', 'N', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'IS_END', '1', null, null, 'D0419BBF19C923B8E0533315A8C0FC8D', 'IS_END', 'V_PERF_PROJECT_YEAR', '是否终止', 'N', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'IS_SCIENTIFIC', '1', null, null, 'D0419BBF19CA23B8E0533315A8C0FC8D', 'IS_SCIENTIFIC', 'V_PERF_PROJECT_YEAR', '是否科研项目', 'N', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'IS_TRACK', '1', null, null, 'D0419BBF19CB23B8E0533315A8C0FC8D', 'IS_TRACK', 'V_PERF_PROJECT_YEAR', '是否追踪', 'N', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'IS_USESET', '1', null, null, 'D0419BBF19CC23B8E0533315A8C0FC8D', 'IS_USESET', 'V_PERF_PROJECT_YEAR', '是否设置使用范围', 'N', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '099003', null, '1', 'MANAGE_MOF_DEP_CODE', '1', null, null, 'D0419BBF1A2A23B8E0533315A8C0FC8D', 'MANAGE_MOF_DEP_CODE', 'V_PERF_PROJECT_YEAR', '业务主管处室代码', 'S', '6', null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values ('DE03026', '099003', null, '1', 'MOF_DEP_CODE', '1', null, null, 'D0419BBF19CD23B8E0533315A8C0FC8D', 'MOF_DEP_CODE', 'V_PERF_PROJECT_YEAR', '财政内部机构代码', 'S', '6', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD08001', null, '1', 'MOF_DIV_CODE', '1', null, null, 'D0419BBF19CE23B8E0533315A8C0FC8D', 'MOF_DIV_CODE', 'V_PERF_PROJECT_YEAR', '财政区划代码', 'S', '9', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', null, null, 'D0419BBF1B4E23B8E0533315A8C0FC8D', 'PROVINCE', 'V_PERF_PROJECT_YEAR', '区划', 'S', null, null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_CAT_CODE', '1', null, null, 'D0419BBF19CF23B8E0533315A8C0FC8D', 'PRO_CAT_CODE', 'V_PERF_PROJECT_YEAR', '项目类别', 'S', '2', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_CODE', '1', null, null, 'D0419BBF19D023B8E0533315A8C0FC8D', 'PRO_CODE', 'V_PERF_PROJECT_YEAR', '项目代码', 'S', '21', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_DESC', '1', null, null, 'D0419BBF19D123B8E0533315A8C0FC8D', 'PRO_DESC', 'V_PERF_PROJECT_YEAR', '项目概述', 'S', '300', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_ID', '1', null, null, 'D0419BBF19D223B8E0533315A8C0FC8D', 'PRO_ID', 'V_PERF_PROJECT_YEAR', '项目主键', 'S', '38', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD09001', null, '1', 'PRO_KIND_CODE', '1', null, null, 'D0419BBF1A2523B8E0533315A8C0FC8D', 'PRO_KIND_CODE', 'V_PERF_PROJECT_YEAR', '项目类别代码', 'S', '2', null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_NAME', '1', null, null, 'D0419BBF19D323B8E0533315A8C0FC8D', 'PRO_NAME', 'V_PERF_PROJECT_YEAR', '项目名称', 'S', '180', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD09007', null, '0', 'PRO_SOURCE_CODE', '1', null, null, 'D0419BBF19D423B8E0533315A8C0FC8D', 'PRO_SOURCE_CODE', 'V_PERF_PROJECT_YEAR', '项目来源代码', 'S', '1', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_START_YEAR', '1', null, null, 'D0419BBF19D523B8E0533315A8C0FC8D', 'PRO_START_YEAR', 'V_PERF_PROJECT_YEAR', '起始时间', 'S', '4', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_TERM', '1', null, null, 'D0419BBF19D623B8E0533315A8C0FC8D', 'PRO_TERM', 'V_PERF_PROJECT_YEAR', '项目期限', 'S', '2', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_TOTAL_AMT', '1', null, null, 'D0419BBF19D723B8E0533315A8C0FC8D', 'PRO_TOTAL_AMT', 'V_PERF_PROJECT_YEAR', '项目总额', 'N', null, null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'REPLY_AMT', '1', null, null, 'D0419BBF1A2C23B8E0533315A8C0FC8D', 'REPLY_AMT', 'V_PERF_PROJECT_YEAR', '年初批复数', 'N', null, null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'SCOI_INVEST_FUND', '1', null, null, 'D0419BBF19D823B8E0533315A8C0FC8D', 'SCOI_INVEST_FUND', 'V_PERF_PROJECT_YEAR', '其中：社会投入资金', 'N', null, null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'SETUP_YEAR', '1', null, null, 'D0419BBF19D923B8E0533315A8C0FC8D', 'SETUP_YEAR', 'V_PERF_PROJECT_YEAR', '设立年度', 'S', '4', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values ('DE03002', 'VD00010', null, '0', 'TRAOBJ_AGENCY_CODE', '1', null, null, 'D0419BBF19DA23B8E0533315A8C0FC8D', 'TRAOBJ_AGENCY_CODE', 'V_PERF_PROJECT_YEAR', '去向单位代码', 'S', '21', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'UPDATE_TIME', '1', null, null, 'D0419BBF19DB23B8E0533315A8C0FC8D', 'UPDATE_TIME', 'V_PERF_PROJECT_YEAR', '更新时间', 'S', null, null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'VERSION', '1', null, null, 'D0419BBF19DC23B8E0533315A8C0FC8D', 'VERSION', 'V_PERF_PROJECT_YEAR', '版本号', 'S', null, null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'VERSION_NAME', '1', null, null, 'D0419BBF19DD23B8E0533315A8C0FC8D', 'VERSION_NAME', 'V_PERF_PROJECT_YEAR', '版本说明', 'S', null, null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'WFID', '1', null, null, 'D0419BBF1B4F23B8E0533315A8C0FC8D', 'WFID', 'V_PERF_PROJECT_YEAR', '流程编码', 'S', null, null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values ('092004', '099076', null, '0', 'WFSTATUS', '1', null, null, 'D0419BBF1B5023B8E0533315A8C0FC8D', 'WFSTATUS', 'V_PERF_PROJECT_YEAR', '流程状态', 'S', null, null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', null, null, 'D0419BBF1B5123B8E0533315A8C0FC8D', 'YEAR', 'V_PERF_PROJECT_YEAR', '年度', 'S', null, null, 1, 1, null, sysdate);



