begin

delete from bus_t_diccolumn t where tablecode = 'PERF_PROJECT_INFODP' AND T.COLUMNCODE in('MANAGE_DEPT_CODE','MANAGE_MOF_DEP_CODE','MOF_DEP_CODE','DEPT_CODE','AGENCY_CODE','FININTORGGUID');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '0', 'AGENCY_CODE', '1', '2020', '87', 'EA07150BF50DC76D865AA3D2E7C6B327', 'AGENCY_CODE', 'PERF_PROJECT_INFODP', '单位', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '0', 'DEPT_CODE', '1', '2020', '87', 'E10296B0734131F15C6AC6E7ED297098', 'DEPT_CODE', 'PERF_PROJECT_INFODP', '单位主管部门', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values ('10923', 'VD10001', null, '0', 'FININTORGGUID', '1', '2020', '87', 'A177A88DD1B5E007696086265DA6439F', 'FININTORGGUID', 'PERF_PROJECT_INFODP', '管理处室', 'S', '50', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '0', 'MANAGE_DEPT_CODE', '1', '2020', '87', '3BFA1A40DB5B35BA26A38060E36F0B05', 'MANAGE_DEPT_CODE', 'PERF_PROJECT_INFODP', '资金主管部门', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '099003', null, '0', 'MANAGE_MOF_DEP_CODE', '1', '2020', '87', '9A1065FF50F290FC36B2C0CA64135FD9', 'MANAGE_MOF_DEP_CODE', 'PERF_PROJECT_INFODP', '资金主管处室', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '099003', null, '0', 'MOF_DEP_CODE', '1', '2020', '87', 'E2ACC52EC564D953F8EB89DEA354C1EE', 'MOF_DEP_CODE', 'PERF_PROJECT_INFODP', '单位归口处室', 'S', '40', null, null, 1, null, sysdate);
