begin

delete from bus_t_diccolumn t where tablecode = 'PERF_T_REVIEW' AND T.COLUMNCODE in('MANAGE_DEPT_CODE','MANAGE_MOF_DEP_CODE','MOF_DEP_CODE','DEPT_CODE','AGENCY_CODE');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '0', 'AGENCY_CODE', '1', '2020', '87', '5FC4F1EA4086A13AE568668A7AAAF79B', 'AGENCY_CODE', 'PERF_T_REVIEW', '单位', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '0', 'DEPT_CODE', '1', '2020', '87', '51AC3636B982DB3E1603825DCD41D0AD', 'DEPT_CODE', 'PERF_T_REVIEW', '单位主管部门', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '0', 'MANAGE_DEPT_CODE', '1', '2020', '87', '28E571C4BF81171CDCBFD91539A23436', 'MANAGE_DEPT_CODE', 'PERF_T_REVIEW', '资金主管部门', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '099003', null, '0', 'MANAGE_MOF_DEP_CODE', '1', '2020', '87', '94FDE06918BFFAD9BF03B6F43BE0C9B3', 'MANAGE_MOF_DEP_CODE', 'PERF_T_REVIEW', '资金主管处室', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '099003', null, '0', 'MOF_DEP_CODE', '1', '2020', '87', 'A45E8E1235E43F7C337BEFBBA6F24858', 'MOF_DEP_CODE', 'PERF_T_REVIEW', '单位归口处室', 'S', '40', null, null, 1, null, sysdate);
