begin
  
DELETE FROM Bus_t_Diccolumn t where t.tablecode='BUSFW_T_UITABPAGE' and t.columncode='COMPONENTID';
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'COMPONENTID', '1', '2016', '87', 'C296814F6656B384E053B11FA8C09E71', 'COMPONENTID', 'BUSFW_T_UITABPAGE', '×é¼þID', 'S', '500', null, 1, 1, null, sysdate);

