  i integer;
begin
  
execute immediate'create or replace view v_perf_selexpert as
select t."GUID",
       t."CODE",
       t."NAME",
       t."STATUS",
       t."CREATER",
       t."CREATETIME",
       t."UPDATETIME",
       t."YEAR",
       t."PROVINCE",
       t."ORDERNUM",
       t."PROGUID",
       t."MAINGUID",
       t."EXPERTGUID",
       t."ISGROUP",
       m."SEX",
       m."WORKPLACE",
       m."IDCARD",
       m."NATION",
       m."POLITICAL",
       m."BIRTH",
       m."EDUCATION",
       m."GRADUATE",
       m."PROFESSIONAL",
       m."REGION",
       m."SPECIALTY",
       m."CERTIFICATE",
       m."CREDITNO",
       m."PHONE",
       m."TEL",
       m."EMAIL",
       m."RECOMMENDER",
       m."WORKEXPERIE",
       m."CATEGORY",
       m."INSTITUTIONS",
       m."CATEGORY01",
       m."CATEGORY02",
       m."CATEGORY03",
       m."ADDRESS",
       m."EMPLOYDATA",
       m."PERFPRO",
       m."TREATISE",
       m."OPINION",
       m."EVALUATENUM",
       m."LOGINCODE"
  FROM V_PERF_EXPERTREVIEW t left join V_PERF_EXPERTINIFO m on t.EXPERTGUID = m.GUID';
