begin 
  
delete from bus_t_dictable where tablecode = 'PERF_V_RANDOMRESULTIMP';
insert into bus_t_dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2016', '87', 'PERF_V_RANDOMRESULTIMP', '绩效抽评评价结果导入视图', '绩效抽评评价结果导入视图', 2, 1, 'PERF_V_RANDOMRESULTIMP', 'pmkpi', null, '0', 1, null, 1, 1, null, sysdate, 1, 1, null, '1');


delete from bus_t_diccolumn where tablecode = 'PERF_V_RANDOMRESULTIMP';
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values ('BE01001', 'VD00010', null, '1', 'AGENCY_CODE', '1', '2021', '87', 'E88373B2B7163A3BCDF963FE0C6C5146', 'AGENCY_CODE', 'PERF_V_RANDOMRESULTIMP', '单位编码', 'S', '40', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AGENCY_NAME', '1', '2021', '87', '94DFD99BFCD8311EF2E5483545A7CF04', 'AGENCY_NAME', 'PERF_V_RANDOMRESULTIMP', '单位名称', 'S', '200', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_CODE', '1', '2021', '87', 'CB5A5F00DA952EE35E1137F8E2A2AB86', 'PRO_CODE', 'PERF_V_RANDOMRESULTIMP', '项目编码', 'S', '40', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_NAME', '1', '2021', '87', '250B509EC6A90D435CCB9D779A7F828A', 'PRO_NAME', 'PERF_V_RANDOMRESULTIMP', '项目名称', 'S', '200', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'VCOL1', '1', '2021', '87', '578123042E82E35052DB7998B9C016A4', 'VCOL1', 'PERF_V_RANDOMRESULTIMP', '抽评发现的问题', 'S', '2000', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'VCOL2', '1', '2021', '87', '702EE865FBFC0D9F853E1525E7D95F86', 'VCOL2', 'PERF_V_RANDOMRESULTIMP', '抽评总得分', 'S', '4000', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'RANDOMGRADE', null, '0', 'VCOL3', '1', '2021', '87', '3961F14EF39598DF0E5D833B1CC61A9F', 'VCOL3', 'PERF_V_RANDOMRESULTIMP', '抽评等级', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'VCOL4', '1', '2021', '87', 'D94D2935D42613493162863C71F0E0D9', 'VCOL4', 'PERF_V_RANDOMRESULTIMP', '自评质量得分', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'VCOL5', '1', '2021', '87', '53964B5B16A176B2B387B47DD4F35732', 'VCOL5', 'PERF_V_RANDOMRESULTIMP', '自评质量结果', 'S', '40', null, null, 1, null, sysdate);


delete from bus_t_diccolumn where tablecode = 'PERF_T_RANDOMPROBLEM' and columncode = 'VCOL3';
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'RANDOMGRADE', null, '0', 'VCOL3', '1', '2021', '87', '94941DC6BB4E7E6BF3A6FBB7C8DD3CBD', 'VCOL3', 'PERF_T_RANDOMPROBLEM', '备用字段', 'S', '40', null, 1, 1, null, sysdate);
