begin
  
delete from bus_t_dictable t where t.tablecode IN('PERF_T_DATACOMMUNICATION');
insert into bus_t_dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2026', '87', 'PERF_T_DATACOMMUNICATION', '山西数据交互中心中间表', '山西数据交互中心中间表', 2, 1, 'V_PERF_T_DATACOMMUNICATION', 'pmkpi', null, '0', 1, null, 1, 1, 'V_PERF_SELFPRO_DATACOMMUN', sysdate, 1, 1, null, '1');

delete from bus_t_diccolumn t where t.tablecode IN('PERF_T_DATACOMMUNICATION');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATER', '1', '2016', '87', '54E89421C0285DB0E063030011AC0845', 'CREATER', 'PERF_T_DATACOMMUNICATION', '创建人', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATE_TIME', '1', '2016', '87', '54E89421C0295DB0E063030011AC0845', 'CREATE_TIME', 'PERF_T_DATACOMMUNICATION', '创建时间', 'D', '0', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FILE_ID', '1', '2016', '87', '54E89421C0315DB0E063030011AC0845', 'FILE_ID', 'PERF_T_DATACOMMUNICATION', '附件id', 'S', '32', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FISCAL_YEAR', '1', '2016', '87', '54E89421C02A5DB0E063030011AC0845', 'FISCAL_YEAR', 'PERF_T_DATACOMMUNICATION', '预算年度', 'S', '4', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2016', '87', '54E89421C02B5DB0E063030011AC0845', 'GUID', 'PERF_T_DATACOMMUNICATION', '主键', 'S', '40', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_DELETED', '1', '2016', '87', '54E89421C0305DB0E063030011AC0845', 'IS_DELETED', 'PERF_T_DATACOMMUNICATION', '是否删除', 'N', '1', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD08001', null, '1', 'MOF_DIV_CODE', '1', '2016', '87', '54E89421C02C5DB0E063030011AC0845', 'MOF_DIV_CODE', 'PERF_T_DATACOMMUNICATION', '财政区划代码', 'S', '9', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_CODE', '1', '2016', '87', '54E89421C02D5DB0E063030011AC0845', 'PRO_CODE', 'PERF_T_DATACOMMUNICATION', '项目代码', 'S', '21', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UPDATE_TIME', '1', '2016', '87', '54E89421C02E5DB0E063030011AC0845', 'UPDATE_TIME', 'PERF_T_DATACOMMUNICATION', '更新时间', 'D', '0', null, 1, 0, null, sysdate);


delete from bus_t_dictable t where t.tablecode IN('V_PERF_SELFPRO_DATACOMMUN');
insert into bus_t_dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2026', '87', 'V_PERF_SELFPRO_DATACOMMUN', '绩效自评推送视图', '绩效自评推送视图', 2, 1, 'V_PERF_SELFPRO_DATACOMMUN', 'pmkpi', null, '0', 1, null, 1, 1, 'V_PERF_SELFPRO_DATACOMMUN', sysdate, 1, 1, null, '1');

delete from bus_t_diccolumn t where t.tablecode IN('V_PERF_SELFPRO_DATACOMMUN');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIAGENCYALLPAY', null, '1', 'AGENCYGUID', '1', '2021', '87', '54E89421C0015DB0E063030011AC0845', 'AGENCYGUID', 'V_PERF_SELFPRO_DATACOMMUN', '单位', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIAGENCYALLPAY', null, '1', 'DEPT_CODE', '1', '2021', '87', '54E89421C0025DB0E063030011AC0845', 'DEPT_CODE', 'V_PERF_SELFPRO_DATACOMMUN', '单位主管部门', 'S', '200', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '099003', null, '1', 'FININTORGGUID', '1', '2021', '87', '54E89421C0035DB0E063030011AC0845', 'FININTORGGUID', 'V_PERF_SELFPRO_DATACOMMUN', '处室', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '099003', null, '1', 'MANAGE_MOF_DEP_CODE', '1', '2021', '87', '54E89421C0045DB0E063030011AC0845', 'MANAGE_MOF_DEP_CODE', 'V_PERF_SELFPRO_DATACOMMUN', '资金主管处室', 'S', '200', null, 1, 1, null, sysdate);
