begin

delete from bus_t_diccolumn t where t.tablecode='PERF_T_SELFEVALTASK' and t.columncode in('BGTGET');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BGTGET', '1', '2021', '87', 'D42BA37663362A20E0533315A8C085FA', 'BGTGET', 'PERF_T_SELFEVALTASK', '预算执行率', 'N', '5', null, 1, 0, null, sysdate);

delete from bus_t_diccolumn t where t.tablecode='PERF_T_SELFPERFINDEX' and t.columncode in('SCORE_REMARK','DATATYPE');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'DATATYPE', '1', '2021', '87', 'D42BA37663332A20E0533315A8C085FA', 'DATATYPE', 'PERF_T_SELFPERFINDEX', '数据类型', 'S', '40', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SCORE_REMARK', '1', '2021', '87', 'D42BA376632F2A20E0533315A8C085FA', 'SCORE_REMARK', 'PERF_T_SELFPERFINDEX', '备注', 'S', '2000', null, 1, 0, null, sysdate);

delete from bus_t_dictable t where t.tablecode='PERF_T_SELFPERFOPINION';
insert into bus_t_dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2016', '87', 'PERF_T_SELFPERFOPINION', '自评评审意见表', '自评评审意见表', 2, 1, 'PERF_T_SELFPERFOPINION', 'pmkpi', null, '0', 1, null, 1, 1, null, sysdate, 1, 1, null, '1');

delete from bus_t_diccolumn t where t.tablecode='PERF_T_SELFPERFOPINION';
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CONTENT_REMARK', '1', '2021', '87', 'D42BA37663772A20E0533315A8C085FA', 'CONTENT_REMARK', 'PERF_T_SELFPERFOPINION', '内容完整性', 'S', '4000', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATER', '1', '2021', '87', 'D42BA376637C2A20E0533315A8C085FA', 'CREATER', 'PERF_T_SELFPERFOPINION', '创建人', 'S', '40', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATE_TIME', '1', '2021', '87', 'D42BA37663712A20E0533315A8C085FA', 'CREATE_TIME', 'PERF_T_SELFPERFOPINION', '创建时间', 'S', '17', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'DEMONSTRATION_REMARK', '1', '2021', '87', 'D42BA37663782A20E0533315A8C085FA', 'DEMONSTRATION_REMARK', 'PERF_T_SELFPERFOPINION', '论证充分性', 'S', '4000', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2021', '87', 'D42BA37663722A20E0533315A8C085FA', 'GUID', 'PERF_T_SELFPERFOPINION', '主键', 'S', '40', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_DELETED', '1', '2021', '87', 'D42BA37663732A20E0533315A8C085FA', 'IS_DELETED', 'PERF_T_SELFPERFOPINION', '是否删除', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MAINGUID', '1', '2021', '87', 'D42BA376637B2A20E0533315A8C085FA', 'MAINGUID', 'PERF_T_SELFPERFOPINION', '主单guid', 'S', '40', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'OPINIONSCORE', '1', '2021', '87', 'D42BA376637A2A20E0533315A8C085FA', 'OPINIONSCORE', 'PERF_T_SELFPERFOPINION', '评审得分', 'N', '5', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2021', '87', 'D42BA37663742A20E0533315A8C085FA', 'PROVINCE', 'PERF_T_SELFPERFOPINION', '省', 'S', '32', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'RESULT_REMARK', '1', '2021', '87', 'D42BA37663792A20E0533315A8C085FA', 'RESULT_REMARK', 'PERF_T_SELFPERFOPINION', '结果客观性', 'S', '4000', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UPDATE_TIME', '1', '2021', '87', 'D42BA37663752A20E0533315A8C085FA', 'UPDATE_TIME', 'PERF_T_SELFPERFOPINION', '更新时间', 'S', '17', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2021', '87', 'D42BA37663762A20E0533315A8C085FA', 'YEAR', 'PERF_T_SELFPERFOPINION', '年度', 'S', '4', null, 1, 0, null, sysdate);

delete from bus_t_dictable t where t.tablecode='PERF_V_SELFPERFOPINIONIMP';
insert into bus_t_dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2016', '87', 'PERF_V_SELFPERFOPINIONIMP', '绩效自评信息评审意见导入视图', '绩效自评信息评审意见导入视图', 2, 1, 'PERF_V_SELFPERFOPINIONIMP', 'pmkpi', null, '0', 1, null, 1, 1, null, sysdate, 1, 1, null, '1');

delete from bus_t_diccolumn t where t.tablecode='PERF_V_SELFPERFOPINIONIMP';
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AGENCY_CODE', '1', '2021', '87', 'D42BA37664882A20E0533315A8C085FA', 'AGENCY_CODE', 'PERF_V_SELFPERFOPINIONIMP', '单位编码', 'S', '40', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AGENCY_NAME', '1', '2021', '87', 'D42BA37664892A20E0533315A8C085FA', 'AGENCY_NAME', 'PERF_V_SELFPERFOPINIONIMP', '单位名称', 'S', '200', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CONTENT_REMARK', '1', '2021', '87', 'D42BA37664822A20E0533315A8C085FA', 'CONTENT_REMARK', 'PERF_V_SELFPERFOPINIONIMP', '内容完整性', 'S', '4000', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'DEMONSTRATION_REMARK', '1', '2021', '87', 'D42BA37664832A20E0533315A8C085FA', 'DEMONSTRATION_REMARK', 'PERF_V_SELFPERFOPINIONIMP', '论证充分性', 'S', '4000', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'OPINIONSCORE', '1', '2021', '87', 'D42BA37664842A20E0533315A8C085FA', 'OPINIONSCORE', 'PERF_V_SELFPERFOPINIONIMP', '评审得分', 'N', '5', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_CODE', '1', '2021', '87', 'D42BA37664872A20E0533315A8C085FA', 'PRO_CODE', 'PERF_V_SELFPERFOPINIONIMP', '项目编码', 'S', '40', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_NAME', '1', '2021', '87', 'D42BA37664862A20E0533315A8C085FA', 'PRO_NAME', 'PERF_V_SELFPERFOPINIONIMP', '项目名称', 'S', '200', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'RESULT_REMARK', '1', '2021', '87', 'D42BA37664852A20E0533315A8C085FA', 'RESULT_REMARK', 'PERF_V_SELFPERFOPINIONIMP', '结果客观性', 'S', '4000', null, 1, 0, null, sysdate);
