begin
--已选中介-视图
execute immediate '
CREATE OR REPLACE VIEW V_PERF_SELINTERMEDIARY AS
SELECT 
    M.*, t.REVIEW
FROM 
    PERF_REVIEWINTERMEDIARY T
    LEFT JOIN PERF_INTERMEDIARYINFO M ON M.GUID = T.INTERMEDIARY
';