begin

--已选中介-表字段注册
delete from Bus_t_Diccolumn where tablecode = 'V_PERF_SELINTERMEDIARY';
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'CREDITNO', null, '1', 'CREDITNO', '1', '2016', '87', 'D4BE14B85D786FE8E0533315A8C0CE43', 'CREDITNO', 'V_PERF_SELINTERMEDIARY', '信用等级', 'S', '40', null, 1, 1, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EVALUATENUM', '1', '2016', '87', 'D4BE14B85D796FE8E0533315A8C0CE43', 'EVALUATENUM', 'V_PERF_SELINTERMEDIARY', '评价累计数', 'N', '4', null, 1, 1, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'INSTITUTIONAL', null, '1', 'INSTITUTIONAL', '1', '2016', '87', 'D4BE14B85D776FE8E0533315A8C0CE43', 'INSTITUTIONAL', 'V_PERF_SELINTERMEDIARY', '机构性质', 'S', '40', null, 1, 1, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'NAME', '1', '2016', '87', 'D4BE14B85D766FE8E0533315A8C0CE43', 'NAME', 'V_PERF_SELINTERMEDIARY', '机构名称', 'S', '200', null, 1, 1, null, sysdate);




