  i number;
begin

--dic
delete from Bus_t_Diccolumn where tablecode = 'PERF_PROREVISION_AGENCY' and COLUMNCODE in( 'PROVINCE','YEAR');
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2016', '87', 'D82073968B71397EE0533315A8C03FAC', 'PROVINCE', 'PERF_PROREVISION_AGENCY', 'Ê¡', 'S', '32', null, 1, 0, null, sysdate);
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2016', '87', 'D82073968B72397EE0533315A8C03FAC', 'YEAR', 'PERF_PROREVISION_AGENCY', 'Äê¶È', 'S', '4', null, 1, 0, null, sysdate);
