begin
  --整改通知编制  -- 选择项目  数据源字段不翻译
delete from bus_t_diccolumn where TABLECODE ='PERF_V_PROJECT_INFO';
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '0', 'AGENCYGUID', '1', null, null, 'D7B638A6A8547F18E0533315A8C0556A', 'AGENCYGUID', 'PERF_V_PROJECT_INFO', '单位信息', 'S', null, null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '099003', null, '0', 'FININTORGGUID', '1', null, null, 'D5FDEEA6BA6C0CD8E0533315A8C06C21', 'FININTORGGUID', 'PERF_V_PROJECT_INFO', '财政处室', 'S', null, null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPITASKSTAGE', null, '0', 'TASKSTAGE', '1', null, null, 'D0419BBF1AEA23B8E0533315A8C06982', 'TASKSTAGE', 'PERF_V_PROJECT_INFO', '阶段', 'S', null, null, 1, 1, null, sysdate);

