begin
  
delete from bus_t_dictable t where t.tablecode in('PERF_T_BEFOREVIEW');
insert into bus_t_dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2024', '87', 'PERF_T_BEFOREVIEW', 'ÊÂÇ°¼¨Ð§ÆÀ¹À±¨¸æ', 'ÊÂÇ°¼¨Ð§ÆÀ¹À±¨¸æ', 2, 1, 'PERF_T_BEFOREVIEW', 'pmkpi', null, '0', 1, '0', 1, 1, 'V_PERF_T_BEFOREVIEW', null, 1, null, null, '1');

delete from bus_t_diccolumn t where t.tablecode in('PERF_T_BEFOREVIEW');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AGENCYGUID', '1', '2024', '87', '12F8FEC8CC0B2F54E0630A64A8C0069D', 'AGENCYGUID', 'PERF_T_BEFOREVIEW', 'µ¥Î»', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATER', '1', '2024', '87', '12F8FEC8CC0C2F54E0630A64A8C0069D', 'CREATER', 'PERF_T_BEFOREVIEW', '´´½¨ÈË', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATETIME', '1', '2024', '87', '12F8FEC8CC0D2F54E0630A64A8C0069D', 'CREATETIME', 'PERF_T_BEFOREVIEW', '´´½¨Ê±¼ä', 'S', '17', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2024', '87', '12F8FEC8CC0E2F54E0630A64A8C0069D', 'GUID', 'PERF_T_BEFOREVIEW', 'Ö÷¼ü', 'S', '40', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_DELETED', '1', '2024', '87', '12F8FEC8CC0F2F54E0630A64A8C0069D', 'IS_DELETED', 'PERF_T_BEFOREVIEW', 'ÊÇ·ñÉ¾³ý', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MAINGUID', '1', '2024', '87', '12F8FEC8CC102F54E0630A64A8C0069D', 'MAINGUID', 'PERF_T_BEFOREVIEW', 'ÏîÄ¿Ö÷¼ü', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2024', '87', '12F8FEC8CC112F54E0630A64A8C0069D', 'PROVINCE', 'PERF_T_BEFOREVIEW', 'Ê¡', 'S', '40', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_CODE', '1', '2024', '87', '12F8FEC8CC122F54E0630A64A8C0069D', 'PRO_CODE', 'PERF_T_BEFOREVIEW', 'ÏîÄ¿±àÂë', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'STATUS', '1', '2024', '87', '12F8FEC8CC132F54E0630A64A8C0069D', 'STATUS', 'PERF_T_BEFOREVIEW', '×´Ì¬', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TEXT1', '1', '2024', '87', '12F8FEC8CC162F54E0630A64A8C0069D', 'TEXT1', 'PERF_T_BEFOREVIEW', 'Ô¤Áô×Ö¶Î', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TEXT10', '1', '2024', '87', '12F8FEC8CC1F2F54E0630A64A8C0069D', 'TEXT10', 'PERF_T_BEFOREVIEW', 'Ô¤Áô×Ö¶Î', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TEXT11', '1', '2024', '87', '12F8FEC8CC202F54E0630A64A8C0069D', 'TEXT11', 'PERF_T_BEFOREVIEW', 'Ô¤Áô×Ö¶Î', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TEXT12', '1', '2024', '87', '12F8FEC8CC212F54E0630A64A8C0069D', 'TEXT12', 'PERF_T_BEFOREVIEW', 'Ô¤Áô×Ö¶Î', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TEXT13', '1', '2024', '87', '12F8FEC8CC222F54E0630A64A8C0069D', 'TEXT13', 'PERF_T_BEFOREVIEW', 'Ô¤Áô×Ö¶Î', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TEXT14', '1', '2024', '87', '12F8FEC8CC232F54E0630A64A8C0069D', 'TEXT14', 'PERF_T_BEFOREVIEW', 'Ô¤Áô×Ö¶Î', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TEXT15', '1', '2024', '87', '12F8FEC8CC242F54E0630A64A8C0069D', 'TEXT15', 'PERF_T_BEFOREVIEW', 'Ô¤Áô×Ö¶Î', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TEXT16', '1', '2024', '87', '12F8FEC8CC252F54E0630A64A8C0069D', 'TEXT16', 'PERF_T_BEFOREVIEW', 'Ô¤Áô×Ö¶Î', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TEXT17', '1', '2024', '87', '12F8FEC8CC262F54E0630A64A8C0069D', 'TEXT17', 'PERF_T_BEFOREVIEW', 'Ô¤Áô×Ö¶Î', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TEXT18', '1', '2024', '87', '12F8FEC8CC272F54E0630A64A8C0069D', 'TEXT18', 'PERF_T_BEFOREVIEW', 'Ô¤Áô×Ö¶Î', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TEXT19', '1', '2024', '87', '12F8FEC8CC282F54E0630A64A8C0069D', 'TEXT19', 'PERF_T_BEFOREVIEW', 'Ô¤Áô×Ö¶Î', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TEXT2', '1', '2024', '87', '12F8FEC8CC172F54E0630A64A8C0069D', 'TEXT2', 'PERF_T_BEFOREVIEW', 'Ô¤Áô×Ö¶Î', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TEXT20', '1', '2024', '87', '12F8FEC8CC292F54E0630A64A8C0069D', 'TEXT20', 'PERF_T_BEFOREVIEW', 'Ô¤Áô×Ö¶Î', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TEXT21', '1', '2024', '87', '12F8FEC8CC2A2F54E0630A64A8C0069D', 'TEXT21', 'PERF_T_BEFOREVIEW', 'Ô¤Áô×Ö¶Î', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TEXT22', '1', '2024', '87', '12F8FEC8CC2B2F54E0630A64A8C0069D', 'TEXT22', 'PERF_T_BEFOREVIEW', 'Ô¤Áô×Ö¶Î', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TEXT23', '1', '2024', '87', '12F8FEC8CC2C2F54E0630A64A8C0069D', 'TEXT23', 'PERF_T_BEFOREVIEW', 'Ô¤Áô×Ö¶Î', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TEXT24', '1', '2024', '87', '12F8FEC8CC2D2F54E0630A64A8C0069D', 'TEXT24', 'PERF_T_BEFOREVIEW', 'Ô¤Áô×Ö¶Î', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TEXT25', '1', '2024', '87', '12F8FEC8CC2E2F54E0630A64A8C0069D', 'TEXT25', 'PERF_T_BEFOREVIEW', 'Ô¤Áô×Ö¶Î', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TEXT3', '1', '2024', '87', '12F8FEC8CC182F54E0630A64A8C0069D', 'TEXT3', 'PERF_T_BEFOREVIEW', 'Ô¤Áô×Ö¶Î', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TEXT4', '1', '2024', '87', '12F8FEC8CC192F54E0630A64A8C0069D', 'TEXT4', 'PERF_T_BEFOREVIEW', 'Ô¤Áô×Ö¶Î', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TEXT5', '1', '2024', '87', '12F8FEC8CC1A2F54E0630A64A8C0069D', 'TEXT5', 'PERF_T_BEFOREVIEW', 'Ô¤Áô×Ö¶Î', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TEXT6', '1', '2024', '87', '12F8FEC8CC1B2F54E0630A64A8C0069D', 'TEXT6', 'PERF_T_BEFOREVIEW', 'Ô¤Áô×Ö¶Î', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TEXT7', '1', '2024', '87', '12F8FEC8CC1C2F54E0630A64A8C0069D', 'TEXT7', 'PERF_T_BEFOREVIEW', 'Ô¤Áô×Ö¶Î', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TEXT8', '1', '2024', '87', '12F8FEC8CC1D2F54E0630A64A8C0069D', 'TEXT8', 'PERF_T_BEFOREVIEW', 'Ô¤Áô×Ö¶Î', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TEXT9', '1', '2024', '87', '12F8FEC8CC1E2F54E0630A64A8C0069D', 'TEXT9', 'PERF_T_BEFOREVIEW', 'Ô¤Áô×Ö¶Î', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UPDATETIME', '1', '2024', '87', '12F8FEC8CC142F54E0630A64A8C0069D', 'UPDATETIME', 'PERF_T_BEFOREVIEW', '¸üÐÂÊ±¼ä', 'S', '17', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2024', '87', '12F8FEC8CC152F54E0630A64A8C0069D', 'YEAR', 'PERF_T_BEFOREVIEW', 'Äê¶È', 'N', '4', null, 1, 0, null, sysdate);
