begin

delete from bus_t_dictable where tablecode = 'PERF_T_FINEVARELATION';
insert into bus_t_dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2016', '87', 'PERF_T_FINEVARELATION', '财政评价关联项目表', '财政评价关联项目表', 2, 1, 'V_PERF_T_FINEVARELATION', 'pmkpi', null, '0', 1, null, 1, 1, null, sysdate, 1, 1, null, '1');

delete from bus_t_diccolumn where tablecode = 'PERF_T_FINEVARELATION';
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values ('DE03002', 'VD00010', null, '1', 'AGENCYGUID', '1', '2016', '87', 'DC6CDA3FCA8B298EE0533315A8C0D61D', 'AGENCYGUID', 'PERF_T_FINEVARELATION', '单位代码', 'S', '21', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values ('DE03002', 'VD00010', null, '1', 'AGENCY_CODE', '1', '2016', '87', 'DB95070AF1C707BBE0533315A8C027BC', 'AGENCY_CODE', 'PERF_T_FINEVARELATION', '单位代码', 'S', '21', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '61006100UEw5VQ8y', null, '0', 'CREATER', '1', '2016', '87', 'DB95070AF1D107BBE0533315A8C027BC', 'CREATER', 'PERF_T_FINEVARELATION', '建单人', 'S', '32', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'CREATE_TIME', '1', '2016', '87', 'DB95070AF1D207BBE0533315A8C027BC', 'CREATE_TIME', 'PERF_T_FINEVARELATION', '创建时间', 'S', '17', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'GUID', '1', '2016', '87', 'DB95070AF1C207BBE0533315A8C027BC', 'GUID', 'PERF_T_FINEVARELATION', '主键', 'S', '32', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'IS_DELETED', '1', '2016', '87', 'DB95070AF1CE07BBE0533315A8C027BC', 'IS_DELETED', 'PERF_T_FINEVARELATION', '是否删除', 'N', '1', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'MAINGUID', '1', '2016', '87', 'DB95070AF1CD07BBE0533315A8C027BC', 'MAINGUID', 'PERF_T_FINEVARELATION', '业务主键', 'S', '32', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '1', 'MANAGE_DEPT_CODE', '1', '2016', '87', 'DB95070AF1C807BBE0533315A8C027BC', 'MANAGE_DEPT_CODE', 'PERF_T_FINEVARELATION', '主管部门代码', 'S', '21', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values ('DE03026', '099003', null, '1', 'MANAGE_MOF_DEP_CODE', '1', '2016', '87', 'DB95070AF1C907BBE0533315A8C027BC', 'MANAGE_MOF_DEP_CODE', 'PERF_T_FINEVARELATION', '主管处室代码', 'S', '6', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMPROJECTKINDEXTEND', null, '0', 'PROJECTKIND', '1', '2016', '87', 'DB95070AF1C307BBE0533315A8C027BC', 'PROJECTKIND', 'PERF_T_FINEVARELATION', '支出项目类别', 'S', '32', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2016', '87', 'DB95070AF1D007BBE0533315A8C027BC', 'PROVINCE', 'PERF_T_FINEVARELATION', '区划', 'S', '9', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_CODE', '1', '2016', '87', 'DB95070AF1C407BBE0533315A8C027BC', 'PRO_CODE', 'PERF_T_FINEVARELATION', '项目代码', 'S', '40', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_NAME', '1', '2016', '87', 'DB95070AF1C507BBE0533315A8C027BC', 'PRO_NAME', 'PERF_T_FINEVARELATION', '项目名称', 'S', '500', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_START_YEAR', '1', '2016', '87', 'DB95070AF1CB07BBE0533315A8C027BC', 'PRO_START_YEAR', 'PERF_T_FINEVARELATION', '起始时间', 'S', '4', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_TERM', '1', '2016', '87', 'DB95070AF1CC07BBE0533315A8C027BC', 'PRO_TERM', 'PERF_T_FINEVARELATION', '项目期限', 'S', '8', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_TOTAL_AMT', '1', '2016', '87', 'DB95070AF1C607BBE0533315A8C027BC', 'PRO_TOTAL_AMT', 'PERF_T_FINEVARELATION', '项目总额', 'N', '20', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'SETUP_YEAR', '1', '2016', '87', 'DB95070AF1CA07BBE0533315A8C027BC', 'SETUP_YEAR', 'PERF_T_FINEVARELATION', '设立年度', 'S', '4', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'UPDATE_TIME', '1', '2016', '87', 'DB95070AF1D307BBE0533315A8C027BC', 'UPDATE_TIME', 'PERF_T_FINEVARELATION', '更新时间', 'S', '17', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2016', '87', 'DB95070AF1CF07BBE0533315A8C027BC', 'YEAR', 'PERF_T_FINEVARELATION', '年度', 'S', '4', null, 1, 1, null, sysdate);

update bus_t_diccolumn set csid = 'PDMPROJECTKINDEXTEND' where tablecode = 'PERF_PROJECT_INFO' and columncode = 'PROJECTKIND';
