begin
delete FROM Bus_t_Dictable t where t.TABLECODE = 'PERF_T_INDEXFINAGIVE';
delete FROM bus_t_Diccolumn t where t.TABLECODE = 'PERF_T_INDEXFINAGIVE';

insert into Bus_t_Dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2016', '87', 'PERF_T_INDEXFINAGIVE', '指标分类授权表', '指标分类授权表', 2, 1, 'PERF_T_INDEXFINAGIVE', 'pmkpi', null, '0', 1, '0', 0, 1, 'V_PERF_T_INDEXFINAGIVE', sysdate, 1, 1, null, '1');

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIDEPT', null, '1', 'AGENCYCODE', '1', '2016', '87', 'DC6F753E496A7964E0535164A8C07A89', 'AGENCYCODE', 'PERF_T_INDEXFINAGIVE', '部门编码', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AGENCYGUID', '1', '2016', '87', 'DC6F754E496A7964E0535164A8C07A89', 'AGENCYGUID', 'PERF_T_INDEXFINAGIVE', '部门GUID', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AGENCYNAME', '1', '2016', '87', 'DC6F755E496A7964E0535164A8C07A89', 'AGENCYNAME', 'PERF_T_INDEXFINAGIVE', '部门名称', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATER', '1', '2016', '87', 'DC6F75JE496A7964E0535164A8C07A89', 'CREATER', 'PERF_T_INDEXFINAGIVE', '创建人', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATETIME', '1', '2016', '87', 'DC6F75GE496A7964E0535164A8C07A89', 'CREATETIME', 'PERF_T_INDEXFINAGIVE', '创建时间', 'S', '17', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ELEMENTCODE', '1', '2016', '87', 'DC6F75CE496A7964E0535164A8C07A89', 'ELEMENTCODE', 'PERF_T_INDEXFINAGIVE', '分类编码', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'INDEXCOMFUNC', null, '1', 'ELONECODE', '1', '2016', '87', 'DC6F756E496A7964E0535164A8C07A89', 'ELONECODE', 'PERF_T_INDEXFINAGIVE', '一级编码', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'INDEXCOMFUNC', null, '1', 'ELONEGUID', '1', '2016', '87', 'DC6F757E496A7964E0535164A8C07A89', 'ELONEGUID', 'PERF_T_INDEXFINAGIVE', '一级GUID', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ELONENAME', '1', '2016', '87', 'DC6F758E496A7964E0535164A8C07A89', 'ELONENAME', 'PERF_T_INDEXFINAGIVE', '一级名称', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'INDEXCOMFUNC', null, '1', 'ELTWOCODE', '1', '2016', '87', 'DC6F759E496A7964E0535164A8C07A89', 'ELTWOCODE', 'PERF_T_INDEXFINAGIVE', '二级编码', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'INDEXCOMFUNC', null, '1', 'ELTWOGUID', '1', '2016', '87', 'DC6F75BE496A7964E0535164A8C07A89', 'ELTWOGUID', 'PERF_T_INDEXFINAGIVE', '二级GUID', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ELTWONAME', '1', '2016', '87', 'DC6F75AE496A7964E0535164A8C07A89', 'ELTWONAME', 'PERF_T_INDEXFINAGIVE', '二级编码', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2016', '87', 'DC6F752E496A7964E0535164A8C07A89', 'GUID', 'PERF_T_INDEXFINAGIVE', '主键', 'S', '40', null, 1, 0, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_DELETED', '1', '2016', '87', 'DC6F75FE496A7964E0535164A8C07A89', 'IS_DELETED', 'PERF_T_INDEXFINAGIVE', '是否删除', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2016', '87', 'DC6F75KE496A7964E0535164A8C07A89', 'PROVINCE', 'PERF_T_INDEXFINAGIVE', '省份', 'S', '32', null, 1, 0, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UPDATETIME', '1', '2016', '87', 'DC6F75HE496A7964E0535164A8C07A89', 'UPDATETIME', 'PERF_T_INDEXFINAGIVE', '更新时间', 'S', '17', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WFID', '1', '2016', '87', 'DC6F75DE496A7964E0535164A8C07A89', 'WFID', 'PERF_T_INDEXFINAGIVE', '工作流id', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WFSTATUS', '1', '2016', '87', 'DC6F75EE496A7964E0535164A8C07A89', 'WFSTATUS', 'PERF_T_INDEXFINAGIVE', '工作流状态', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2016', '87', 'DC6F75LE496A7964E0535164A8C07A89', 'YEAR', 'PERF_T_INDEXFINAGIVE', '年度', 'S', '4', null, 1, 1, null, sysdate);
