begin
  delete FROM p#Busfw_t_Uieditform t where t.KEY = '/pmkpi/indexlib/edit' and t.COLUMNCODE in ('VALRULE','ENDVALSOURCE','ENDVALTYPE','EVIDENCEFILE','ISSTANDPUSH','COMPUTETYPE','REMARK');
  insert into Busfw_t_Uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE, PROVINCE, YEAR, HEAD)
  values ('DD0E65893A3H3B87E0533315A8C02648', '/pmkpi/indexlib/edit', 'V_BAS_PERF_INDICATOR', 'tree', '赋值规则', 'VALRULE', 0, null, 0, null, 23, 2, '3', 'pmkpi', 1, null, '{format:''#name''}', null, null, null, '87', '2016', null);

  insert into Busfw_t_Uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE, PROVINCE, YEAR, HEAD)
  values ('DD0E65892A3FD3B87E0533315A8C02648', '/pmkpi/indexlib/edit', 'V_BAS_PERF_INDICATOR', 'tree', '指标完成值数据来源', 'ENDVALSOURCE', 0, null, 0, null, 22, null, null, 'pmkpi', 1, null, '{format:''#name''}', null, null, null, '87', '2016', null);

  insert into Busfw_t_Uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE, PROVINCE, YEAR, HEAD)
  values ('DD0E65891A3E3B87E0533315A8C02648', '/pmkpi/indexlib/edit', 'V_BAS_PERF_INDICATOR', 'tree', '完成值取值方式', 'ENDVALTYPE', 0, null, 0, null, 21, null, null, 'pmkpi', 1, null, '{format:''#name''}', null, null, null, '87', '2016', null);

  insert into Busfw_t_Uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE, PROVINCE, YEAR, HEAD)
  values ('DD0E65894A3J3B87E0533315A8C02648', '/pmkpi/indexlib/edit', 'V_BAS_PERF_INDICATOR', 'tree', '佐证资料要求', 'EVIDENCEFILE', 0, null, 0, null, 24, null, null, 'pmkpi', 1, null, '{format:''#name''}', null, null, null, '87', '2016', null);

  insert into Busfw_t_Uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE, PROVINCE, YEAR, HEAD)
  values ('DD0E65894A3B3B87E0533315A8C02648', '/pmkpi/indexlib/edit', 'V_BAS_PERF_INDICATOR', 'tree', '是否为标准化工作组发布', 'ISSTANDPUSH', 0, null, 0, null, 25, null, null, 'pmkpi', 1, null, '{}', null, null, null, '87', '2016', null);

  insert into Busfw_t_Uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE, PROVINCE, YEAR, HEAD)
  values ('DD0E65894A3N3B87E0533315A8C02648', '/pmkpi/indexlib/edit', 'V_BAS_PERF_INDICATOR', 'textarea', '计算方式', 'COMPUTETYPE', 0, null, 0, null, 53, 3, '3', 'pmkpi', 1, null, '{}', null, null, null, '87', '2016', null);

  insert into Busfw_t_Uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE, PROVINCE, YEAR, HEAD)
  values ('DD0E65894A3M3B87E0533315A8C02648', '/pmkpi/indexlib/edit', 'V_BAS_PERF_INDICATOR', 'textarea', '备注', 'REMARK', 0, null, 0, null, 54, 3, '3', 'pmkpi', 1, null, '{}', null, null, null, '87', '2016', null);
