begin
--评分模板表02
--预算绩效管理-预算绩效配置管理-模板配置-评分表 表字段注册
delete from Bus_t_Diccolumn where tablecode = 'PERF_T_EVALUATETEMP';
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AUDITTYPE', '1', '2016', '87', 'BCAC837A5859A4B3E053B11FA8C0F8B7', 'AUDITTYPE', 'PERF_T_EVALUATETEMP', 'AUDITTYPE', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'BUSSTYPE', null, '1', 'BUSTYPE', '1', '2016', '87', 'BCAC837A4864A4B3E053B11FA8C0F8B7', 'BUSTYPE', 'PERF_T_EVALUATETEMP', 'BUSTYPE', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CODE', '1', '2016', '87', 'BCAC8377F864A4B3E053B11FA8C0F8B7', 'CODE', 'PERF_T_EVALUATETEMP', '编码', 'S', '50', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATETIME', '1', '2016', '87', 'BCAC837A6861A4B3E053B11FA8C0F8B7', 'CREATETIME', 'PERF_T_EVALUATETEMP', '创建时间', 'S', '17', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EVALSTD', '1', '2016', '87', 'BCAC837A1864A4B3E053B11FA8C0F8B7', 'EVALSTD', 'PERF_T_EVALUATETEMP', 'EVALSTD', 'S', '2000', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'BUSSTYPE', null, '1', 'EVALUATIONRULE', '1', '2016', '87', '3A4689BD58B5420A94CFE551036B6D59', 'EVALUATIONRULE', 'PERF_T_EVALUATETEMP', '评扣分细则', 'S', '255', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EXPLAIN', '1', '2016', '87', 'BCAC8379F861A4B3E053B11FA8C0F8B7', 'EXPLAIN', 'PERF_T_EVALUATETEMP', 'EXPLAIN', 'S', '1000', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2016', '87', 'BCAC8376F861A4B3E053B11FA8C0F8B7', 'GUID', 'PERF_T_EVALUATETEMP', 'guid', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'ISLEAF', null, '1', 'ISADD', '1', '2016', '87', 'BCAC8374F864A4B3E053B11FA8C0F111', 'ISADD', 'PERF_T_EVALUATETEMP', '是否可新增', 'S', '3', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'ISLEAF', null, '1', 'ISEDIT', '1', '2016', '87', 'BCAC8374F864A4B3E053B11FA8C0F000', 'ISEDIT', 'PERF_T_EVALUATETEMP', '是否可编辑', 'S', '3', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'ISLEAF', null, '1', 'ISLEAF', '1', '2016', '87', 'BCAC8374F864A4B3E053B11FA8C0F8B7', 'ISLEAF', 'PERF_T_EVALUATETEMP', '是否为末级节点', 'S', '3', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'ISLEAF', null, '1', 'ISTOTAL', '1', '2016', '87', 'BCAC8374PPP4A4B3E053B11FA8C0F8B7', 'ISTOTAL', 'PERF_T_EVALUATETEMP', '是否合计', 'S', '3', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LEVELNO', '1', '2016', '87', 'BCAC8373F861A4B3E053B11FA8C0F8B7', 'LEVELNO', 'PERF_T_EVALUATETEMP', '层级', 'N', '2', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'NAME', '1', '2016', '87', 'BCAC8378F859A4B3E053B11FA8C0F8B7', 'NAME', 'PERF_T_EVALUATETEMP', '名称', 'S', '100', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ORDERNUM', '1', '2016', '87', 'BCAC8371F864A4B3E053B11FA8C0F8B7', 'ORDERNUM', 'PERF_T_EVALUATETEMP', '排序', 'N', '9', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2016', '87', 'BCAC837A9861A4B3E053B11FA8C0F8B7', 'PROVINCE', 'PERF_T_EVALUATETEMP', '区划', 'S', '9', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'QUERYSQL', '1', '2016', '87', 'BCAC837A7777A4B3E053B11FA8C0F8B7', 'QUERYSQL', 'PERF_T_EVALUATETEMP', '查询sql', 'S', '300', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'REMARK', '1', '2016', '87', 'BCAC837A3861A4B3E053B11FA8C0F8B7', 'REMARK', 'PERF_T_EVALUATETEMP', '备注', 'S', '4000', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SCORE', '1', '2016', '87', 'BCAC837A2222A4B3E053B11FA8C0F8B7', 'SCORE', 'PERF_T_EVALUATETEMP', '分值', 'S', '2', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SUPERID', '1', '2016', '87', 'BCAC8375F859A4B3E053B11FA8C0F8B7', 'SUPERID', 'PERF_T_EVALUATETEMP', '父类id', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TARGETVALUE', '1', '2016', '87', 'B9F1727105D84CDCA763CDC24CADA0DC', 'TARGETVALUE', 'PERF_T_EVALUATETEMP', '目标值或目标来源', 'S', '255', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UPDATETIME', '1', '2016', '87', 'BCAC837A7864A4B3E053B11FA8C0F8B7', 'UPDATETIME', 'PERF_T_EVALUATETEMP', '更新时间', 'S', '17', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2016', '87', 'BCAC837A8859A4B3E053B11FA8C0F8B7', 'YEAR', 'PERF_T_EVALUATETEMP', '年度', 'S', '4', null, 1, 1, null, sysdate);
