begin

delete from bus_t_diccolumn t where t.tablecode='PERF_T_PROINDEXTRACE' and t.dbcolumncode in('INDEXVAL','TARGETVALUE','TINDEX');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'INDEXVAL', '1', '2020', '87', 'B785109A5BAC0EC1E0530100007FD5F2', 'INDEXVAL', 'PERF_T_PROINDEXTRACE', '实际完成值', 'S', '1000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TARGETVALUE', '1', '2020', '87', 'B785109A5BAB0EC1E0530100007FD5F2', 'TARGETVALUE', 'PERF_T_PROINDEXTRACE', '年度目标值', 'S', '1000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TINDEX', '1', '2020', '87', 'B785109A5BAA0EC1E0530100007FD5F2', 'TINDEX', 'PERF_T_PROINDEXTRACE', '三级指标', 'S', '40', null, 1, 1, null, sysdate);

delete from bus_t_diccolumn t where t.tablecode='PERF_T_PROINDEXTRACE' and t.dbcolumncode in('DEVIATIONANALYSIS');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIDEVIATIONANALYSIS', null, '1', 'DEVIATIONANALYSIS', '1', '2020', '87', 'B785109A5BB00EC1E0530100007FD5F2', 'DEVIATIONANALYSIS', 'PERF_T_PROINDEXTRACE', '偏差原因分析', 'S', '200', null, 1, 1, null, sysdate);

delete from bus_t_diccolumn t where t.tablecode='PERF_T_PROTRACEANALYSIS' and t.dbcolumncode='ISEXPFUNC';
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ISEXPFUNC', '1', '2020', '87', 'DFA5B5FA76094CC6E0533315A8C01102', 'ISEXPFUNC', 'PERF_T_PROTRACEANALYSIS', '是否达到预计支出进度', 'S', '40', null, 1, 1, null, sysdate);
