module.name=ifmis-pmkpi-service
module.dependencies=ifmis-framework-public
module.xmlresource.appids=pmkpi,datacommon
#hqbpmn-context.xml
module.xmlresource.includes=pmkpi-context.xml,pmkpi-context-server.xml,pmkpi-appupgrade.xml
module.xmlresource.excludes=
