begin
  
delete from Bus_t_Diccolumn t where t.COLUMNCODE in (
'AGENCY_CODE',
'AGENCY_NAME',
'BGT_ID',
'CREATE_TIME',
'FIN_PERF_CODE',
'FIN_PERF_NAME',
'FISCAL_YEAR',
'IS_DELETED',
'IS_LAST_INST',
'KPI_PER_ID',
'KPI_TARGET',
'MOF_AUD_OPINION_CODE',
'MOF_AUD_OPINION_NAME',
'MOF_DIV_CODE',
'MOF_DIV_NAME',
'ORI_DIV_CODE',
'ORI_DIV_NAME',
'PERF_OBJ_TYPE_CODE',
'PERF_OBJ_TYPE_NAME',
'PRO_CODE',
'PRO_NAME',
'SPE_PRO_CODE',
'SPE_PRO_NAME',
'SUB_MOF_DIV_CODE',
'SUB_MOF_DIV_NAME',
'UPDATE_TIME',
'VERSION',
'VERSION_NAME') and t.TABLECODE = 'PM_PERF_GOAL_INFO';
insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE01001', 'VD00010', '0', 'AGENCY_CODE', '1', 2016, '87', sys_guid(), 'AGENCY_CODE', 'PM_PERF_GOAL_INFO', '单位代码', 'S', '21', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE01002', 'VD00010', '0', 'AGENCY_NAME', '1', 2016, '87', sys_guid(), 'AGENCY_NAME', 'PM_PERF_GOAL_INFO', '单位名称', 'S', '300', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE00001', null, '0', 'BGT_ID', '1', 2016, '87', sys_guid(), 'BGT_ID', 'PM_PERF_GOAL_INFO', '指标主键', 'S', '38', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE00036', null, '0', 'CREATE_TIME', '1', 2016, '87', sys_guid(), 'CREATE_TIME', 'PM_PERF_GOAL_INFO', '创建时间', 'D', '0', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE10096', 'VD09021', '0', 'FIN_PERF_CODE', '1', 2016, '87', sys_guid(), 'FIN_PERF_CODE', 'PM_PERF_GOAL_INFO', '财政绩效目标审核结果代码', 'S', '4', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE10097', 'VD09021', '0', 'FIN_PERF_NAME', '1', 2016, '87', sys_guid(), 'FIN_PERF_NAME', 'PM_PERF_GOAL_INFO', '财政绩效目标审核结果名称', 'S', '100', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE00029', null, '0', 'FISCAL_YEAR', '1', 2016, '87', sys_guid(), 'FISCAL_YEAR', 'PM_PERF_GOAL_INFO', '预算年度', 'S', '4', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE00030', null, '0', 'IS_DELETED', '1', 2016, '87', sys_guid(), 'IS_DELETED', 'PM_PERF_GOAL_INFO', '是否删除', 'N', '1', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE00037', 'VD00001', '0', 'IS_LAST_INST', '1', 2016, '87', sys_guid(), 'IS_LAST_INST', 'PM_PERF_GOAL_INFO', '是否终审', 'N', '1', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE00001', null, '0', 'KPI_PER_ID', '1', 2016, '87', sys_guid(), 'KPI_PER_ID', 'PM_PERF_GOAL_INFO', '项目绩效目标主键', 'S', '38', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE10021', null, '0', 'KPI_TARGET', '1', 2016, '87', sys_guid(), 'KPI_TARGET', 'PM_PERF_GOAL_INFO', '绩效目标', 'S', '2000', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE10027', 'VD09005', '0', 'MOF_AUD_OPINION_CODE', '1', 2016, '87', sys_guid(), 'MOF_AUD_OPINION_CODE', 'PM_PERF_GOAL_INFO', '财政审核意见代码', 'S', '1', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE10025', null, '0', 'MOF_AUD_OPINION_NAME', '1', 2016, '87', sys_guid(), 'MOF_AUD_OPINION_NAME', 'PM_PERF_GOAL_INFO', '财政审核意见名称', 'S', '60', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE00017', 'VD08001', '0', 'MOF_DIV_CODE', '1', 2016, '87', sys_guid(), 'MOF_DIV_CODE', 'PM_PERF_GOAL_INFO', '财政区划代码', 'S', '9', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE00016', 'VD08001', '0', 'MOF_DIV_NAME', '1', 2016, '87', sys_guid(), 'MOF_DIV_NAME', 'PM_PERF_GOAL_INFO', '财政区划名称', 'S', '360', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE00017', 'VD08001', '0', 'ORI_DIV_CODE', '1', 2016, '87', sys_guid(), 'ORI_DIV_CODE', 'PM_PERF_GOAL_INFO', '来源方财政区划代码', 'S', '9', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE00016', 'VD08001', '0', 'ORI_DIV_NAME', '1', 2016, '87', sys_guid(), 'ORI_DIV_NAME', 'PM_PERF_GOAL_INFO', '来源方财政区划名称', 'S', '360', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE10063', 'VD09009', '0', 'PERF_OBJ_TYPE_CODE', '1', 2016, '87', sys_guid(), 'PERF_OBJ_TYPE_CODE', 'PM_PERF_GOAL_INFO', '项目绩效类型代码', 'S', '1', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE10064', 'VD09009', '0', 'PERF_OBJ_TYPE_NAME', '1', 2016, '87', sys_guid(), 'PERF_OBJ_TYPE_NAME', 'PM_PERF_GOAL_INFO', '项目绩效类型名称', 'S', '60', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE10002', null, '0', 'PRO_CODE', '1', 2016, '87', sys_guid(), 'PRO_CODE', 'PM_PERF_GOAL_INFO', '项目代码', 'S', '21', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE10001', null, '0', 'PRO_NAME', '1', 2016, '87', sys_guid(), 'PRO_NAME', 'PM_PERF_GOAL_INFO', '项目名称', 'S', '180', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE10002', null, '0', 'SPE_PRO_CODE', '1', 2016, '87', sys_guid(), 'SPE_PRO_CODE', 'PM_PERF_GOAL_INFO', '具体实施项目代码', 'S', '21', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE10001', null, '0', 'SPE_PRO_NAME', '1', 2016, '87', sys_guid(), 'SPE_PRO_NAME', 'PM_PERF_GOAL_INFO', '具体实施项目名称', 'S', '2000', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE00017', 'VD08001', '0', 'SUB_MOF_DIV_CODE', '1', 2016, '87', sys_guid(), 'SUB_MOF_DIV_CODE', 'PM_PERF_GOAL_INFO', '下级财政区划代码', 'S', '9', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE00016', 'VD08001', '0', 'SUB_MOF_DIV_NAME', '1', 2016, '87', sys_guid(), 'SUB_MOF_DIV_NAME', 'PM_PERF_GOAL_INFO', '下级财政区划名称', 'S', '360', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE00023', null, '0', 'UPDATE_TIME', '1', 2016, '87', sys_guid(), 'UPDATE_TIME', 'PM_PERF_GOAL_INFO', '更新时间', 'D', '0', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE00100', null, '0', 'VERSION', '1', 2016, '87', sys_guid(), 'VERSION', 'PM_PERF_GOAL_INFO', '版本号', 'S', '38', null, 1, null, null);

insert into Bus_t_Diccolumn (DEID, CSID, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE)
values ('BE00101', null, '0', 'VERSION_NAME', '1', 2016, '87', sys_guid(), 'VERSION_NAME', 'PM_PERF_GOAL_INFO', '版本说明', 'S', '400', null, 1, null, null);
