begin
--注册表字段
--GUID
delete BUS_T_DICCOLUMN where TABLECODE='PERF_T_IMPEXPSUB';
INSERT INTO BUS_T_DICCOLUMN("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '0', 'GUID', '1', '2016', '87', sys_guid(), 'GUID', 'PERF_T_IMPEXPSUB', NULL, 's', '38', NULL, '1', '0', NULL, SYSDATE);
--COLUMNCODE
INSERT INTO BUS_T_DICCOLUMN("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '0', 'COLUMNCODE', '1', '2016', '87', sys_guid(), 'COLUMNCODE', 'PERF_T_IMPEXPSUB', NULL, 's', '50', NULL, '1', '0', NULL, SYSDATE);
--CSID
INSERT INTO BUS_T_DICCOLUMN("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '0', 'CSID', '1', '2016', '87', sys_guid(), 'CSID', 'PERF_T_IMPEXPSUB', NULL, 's', '100', NULL, '1', '0', NULL, SYSDATE);
--NAME
INSERT INTO BUS_T_DICCOLUMN("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '0', 'NAME', '1', '2016', '87', sys_guid(), 'NAME', 'PERF_T_IMPEXPSUB', NULL, 's', '100', NULL, '1', '0', NULL, SYSDATE);
--ORDERNUM
INSERT INTO BUS_T_DICCOLUMN("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '0', 'ORDERNUM', '1','2016', '87', sys_guid(), 'ORDERNUM', 'PERF_T_IMPEXPSUB', NULL, 'N', NULL, '1', '0', NULL, SYSDATE);
--HEAD
INSERT INTO BUS_T_DICCOLUMN("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH","SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '0', 'HEAD', '1', '2016', '87', sys_guid(), 'HEAD', 'PERF_T_IMPEXPSUB', NULL, 'S','2000', NULL, '1', '0', NULL, SYSDATE);
--FORMAT
INSERT INTO BUS_T_DICCOLUMN("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH","SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '0', 'FORMAT', '1', '2016', '87', sys_guid(), 'FORMAT', 'PERF_T_IMPEXPSUB', NULL, 'S','200', NULL, '1', '0', NULL, SYSDATE);
--TYPE
INSERT INTO BUS_T_DICCOLUMN("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH","SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, 'PMKPI_CODETYPE',NULL, '0', 'TYPE', '1', '2016', '87', sys_guid(), 'TYPE', 'PERF_T_IMPEXPSUB', NULL, 'S','50', NULL, '1', '0', NULL, SYSDATE);
--MAINGUID
INSERT INTO BUS_T_DICCOLUMN("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH","SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '0', 'MAINGUID', '1', '2016', '87', sys_guid(), 'MAINGUID', 'PERF_T_IMPEXPSUB', NULL, 'S','32', NULL, '1', '0', NULL, SYSDATE);
--COLWIDTH
INSERT INTO BUS_T_DICCOLUMN("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE","SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '0', 'COLWIDTH', '1', '2016', '87', sys_guid(), 'COLWIDTH', 'PERF_T_IMPEXPSUB', NULL, 'S', NULL, '1', '0', NULL, SYSDATE);
--PROVINCE
INSERT INTO BUS_T_DICCOLUMN("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '0', 'PROVINCE', '1','2016', '87', sys_guid(), 'PROVINCE', 'PERF_T_IMPEXPSUB', NULL, 'S','9',NULL, '1', '0', NULL, SYSDATE);
--YEAR
INSERT INTO BUS_T_DICCOLUMN("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '0', 'YEAR', '1','2016', '87', sys_guid(), 'YEAR', 'PERF_T_IMPEXPSUB', NULL, 'S','9',NULL, '1', '0', NULL, SYSDATE);
--配置页面脚本
DELETE  Bus_t_Pageconsole where URL='/pmkpi/setting/impexpsub';
INSERT INTO Bus_t_Pageconsole("URL", "TEMPLATE", "PAGE", "JSLIB", "CSSLIB", "OBJLIB", "APPID", "CONSOLESERVICE", "METHOD", "CONFIG", "SUPCONSOLE", "REGION", "ISEXPAND") VALUES ('/pmkpi/setting/impexpsub', 'template8', '/pmkpi/common/template/template_defautl.jsp', '/pmkpi/common/template/template_default.js', NULL, NULL, 'pmkpi', 'gov.mof.fasp2.pmkpi.setting.impexpsub.PerfTImpexpsubPage', 'index', '{header:[header],left:lefttree,main:[toolbutton,uidatatable]}', NULL, NULL, '0');
delete Bus_t_Pagecomponent where id='pmkpi_impexpsub';
INSERT INTO Bus_t_Pagecomponent("ID", "NAME", "TYPE", "REMARK", "JSLIB", "JSOBJECTNAME", "APPID", "SERVICE") VALUES ('pmkpi_impexpsub', '导出模板配置', NULL, '导出模板配置', '/pmkpi/setting/impexp/impexpsubservice.js', 'Ext.lt.pmkpi.impexpsub', 'pmkpi', 'pmkpi.setting.impexpsub.PerfTImpexpsubService');
DELETE  Bus_t_Pageconsolecomconfig  where URL='/pmkpi/setting/impexpsub';
INSERT INTO Bus_t_Pageconsolecomconfig("URL", "COMPONENTID", "CONFIG", "ID", "APPID", "REGION") VALUES ('/pmkpi/setting/impexpsub', 'busqueryform', '{name:''查询区'',fastquery:true,uidatatable:''V_PERF_T_IMPEXPSUB'',drawmode:''div'',label:''快速查询'',labelwidth:''120''}', 'queryform', 'pmkpi', NULL);
INSERT INTO Bus_t_Pageconsolecomconfig("URL", "COMPONENTID", "CONFIG", "ID", "APPID", "REGION") VALUES ('/pmkpi/setting/impexpsub', 'header', '{}', 'header', 'pmkpi', NULL);
INSERT INTO Bus_t_Pageconsolecomconfig("URL", "COMPONENTID", "CONFIG", "ID", "APPID", "REGION") VALUES ('/pmkpi/setting/impexpsub', 'bustoolbutton', '{}', 'toolbutton', 'pmkpi', NULL);
INSERT INTO Bus_t_Pageconsolecomconfig("URL", "COMPONENTID", "CONFIG", "ID", "APPID", "REGION") VALUES ('/pmkpi/setting/impexpsub', 'pmkpi_impexpsub', '{}', 'impexpsub', 'pmkpi', NULL);
INSERT INTO Bus_t_Pageconsolecomconfig("URL", "COMPONENTID", "CONFIG", "ID", "APPID", "REGION") VALUES ('/pmkpi/setting/impexpsub', 'buslefttree', '{}', 'lefttree', 'pmkpi', NULL);
INSERT INTO Bus_t_Pageconsolecomconfig("URL", "COMPONENTID", "CONFIG", "ID", "APPID", "REGION") VALUES ('/pmkpi/setting/impexpsub', 'busuidatatable', '{name:''导出模板配置'',checkbox:true,title:''导出模板配置'',edit:true,addrow:true,delcols:[''guid'',''province'',''year''],updatecols:[''guid'',''province'',''year'']}', 'uidatatable', 'pmkpi', NULL);
--注册表格
delete p#Busfw_t_Uitable where KEY='/pmkpi/setting/impexpsub';
INSERT INTO Busfw_t_Uitable("GUID", "KEY", "TABLECODE", "PAGENUM", "TOTALTAG", "LOCKNUM", "ORDERBY", "DEFQUERY", "APPID", "CONFIG", "PROVINCE", "YEAR") VALUES (sys_guid(), '/pmkpi/setting/impexpsub', 'V_PERF_T_IMPEXPSUB', '0', '0', '0', NULL, NULL, 'pmkpi', NULL,'87', '2016');
--注册查询区
delete p#Busfw_t_Uiqueryform where KEY='/pmkpi/setting/impexpsub';
INSERT INTO Busfw_t_Uiqueryform("GUID", "KEY", "COLUMNCODE", "NAME", "ORDERNUM", "ISVISIABLE", "TYPE", "DEFAULTVALUE", "LINKCHILD", "LINKPARENT", "APPID", "TABLECODE", "CONFIG", "BOTTOMCONTRL", "PROVINCE", "YEAR") VALUES (sys_guid()， '/pmkpi/setting/impexpsub', 'NAME', '名称', '1', '1', 's', NULL, '0', '0', 'pmkpi', 'V_PERF_T_IMPEXPSUB', '{}', NULL, '87', '2016');
--注册按钮
delete p#Busfw_t_Uifunction where KEY='/pmkpi/setting/impexpsub';
INSERT INTO Busfw_t_Uifunction("GUID", "KEY", "NAME", "ISVISIABLE", "ORDERNUM", "CLASSNAME", "ACTION", "DISABLED", "TITLE", "APPID", "CODE", "PARAM", "CONFIG", "PROVINCE", "YEAR") VALUES (sys_guid(), '/pmkpi/setting/impexpsub', '初始化', '1', '2', 'openstat', 'impexpsub.initset', NULL, '初始化', 'pmkpi', 'initset', '1', '{}', '87', '2016');
INSERT INTO Busfw_t_Uifunction("GUID", "KEY", "NAME", "ISVISIABLE", "ORDERNUM", "CLASSNAME", "ACTION", "DISABLED", "TITLE", "APPID", "CODE", "PARAM", "CONFIG", "PROVINCE", "YEAR") VALUES (sys_guid(), '/pmkpi/setting/impexpsub', '保存', '1', '1', 'searchicon', 'impexpsub.savemajorkey', NULL, '保存', 'pmkpi', 'savemajorkey', NULL, '{}', '87', '2016');
INSERT INTO Busfw_t_Uifunction("GUID", "KEY", "NAME", "ISVISIABLE", "ORDERNUM", "CLASSNAME", "ACTION", "DISABLED", "TITLE", "APPID", "CODE", "PARAM", "CONFIG", "PROVINCE", "YEAR") VALUES (sys_guid(), '/pmkpi/setting/impexpsub', '新增模板', '1', '3', 'searchicon', 'impexpsub.addleft', NULL, '新增模板', 'pmkpi', 'addleft', NULL, '{}', '87', '2016');
INSERT INTO Busfw_t_Uifunction("GUID", "KEY", "NAME", "ISVISIABLE", "ORDERNUM", "CLASSNAME", "ACTION", "DISABLED", "TITLE", "APPID", "CODE", "PARAM", "CONFIG", "PROVINCE", "YEAR") VALUES (sys_guid(), '/pmkpi/setting/impexpsub', '修改模板', '1', '4', 'searchicon', 'impexpsub.editleft', NULL, '修改模板', 'pmkpi', 'editleft', NULL, '{}', '87', '2016');
INSERT INTO Busfw_t_Uifunction("GUID", "KEY", "NAME", "ISVISIABLE", "ORDERNUM", "CLASSNAME", "ACTION", "DISABLED", "TITLE", "APPID", "CODE", "PARAM", "CONFIG", "PROVINCE", "YEAR") VALUES (sys_guid(), '/pmkpi/setting/impexpsub', '删除模板', '1', '5', 'searchicon', 'impexpsub.delleft', NULL, '删除模板', 'pmkpi', 'delleft', NULL, '{}', '87', '2016');
--注册列表字段
DELETE  p#Busfw_t_Uicolumn where  KEY='/pmkpi/setting/impexpsub';
INSERT INTO Busfw_t_Uicolumn ("GUID", "KEY", "COLUMNCODE", "NAME", "ORDERNUM", "ISVISIABLE", "ISEDIT", "TOTALTAG", "SHOWLEVEL", "REQUIREMENT", "COLTYPE", "HEAD", "FORMAT", "DEFAULTVALUE", "LEVELCONTROL", "COLWIDTH", "ISSOURCE", "TYPE", "CONFIG", "BOTTOMCONTRL", "PROVINCE", "YEAR") VALUES (sys_guid(), '/pmkpi/setting/impexpsub', 'GUID', '主键', '1', '0', '0', '0', NULL, '1', NULL, NULL, NULL, NULL, NULL, '38', NULL, 's', NULL, NULL, '87', '2016');
INSERT INTO Busfw_t_Uicolumn("GUID", "KEY", "COLUMNCODE", "NAME", "ORDERNUM", "ISVISIABLE", "ISEDIT", "TOTALTAG", "SHOWLEVEL", "REQUIREMENT", "COLTYPE", "HEAD", "FORMAT", "DEFAULTVALUE", "LEVELCONTROL", "COLWIDTH", "ISSOURCE", "TYPE", "CONFIG", "BOTTOMCONTRL", "PROVINCE", "YEAR") VALUES (sys_guid(), '/pmkpi/setting/impexpsub', 'COLUMNCODE', '字段编码', '1', '1', '1', '0', NULL, '1', NULL, NULL, '#code-#name', NULL, NULL, '50', '1', 'tree', NULL, NULL, '87', '2016');
INSERT INTO Busfw_t_Uicolumn("GUID", "KEY", "COLUMNCODE", "NAME", "ORDERNUM", "ISVISIABLE", "ISEDIT", "TOTALTAG", "SHOWLEVEL", "REQUIREMENT", "COLTYPE", "HEAD", "FORMAT", "DEFAULTVALUE", "LEVELCONTROL", "COLWIDTH", "ISSOURCE", "TYPE", "CONFIG", "BOTTOMCONTRL", "PROVINCE", "YEAR") VALUES (sys_guid(), '/pmkpi/setting/impexpsub', 'CSID', '数据源', '3', '1', '1', '0', NULL, '0', NULL, NULL, NULL, NULL, NULL, '100', NULL, 's', NULL, NULL,'87', '2016');
INSERT INTO Busfw_t_Uicolumn("GUID", "KEY", "COLUMNCODE", "NAME", "ORDERNUM", "ISVISIABLE", "ISEDIT", "TOTALTAG", "SHOWLEVEL", "REQUIREMENT", "COLTYPE", "HEAD", "FORMAT", "DEFAULTVALUE", "LEVELCONTROL", "COLWIDTH", "ISSOURCE", "TYPE", "CONFIG", "BOTTOMCONTRL", "PROVINCE", "YEAR") VALUES (sys_guid(), '/pmkpi/setting/impexpsub', 'NAME', '名称', '2', '1', '1', '0', NULL, '1', NULL, NULL, NULL, NULL, NULL, '100', NULL, 's', NULL, NULL, '87', '2016');
INSERT INTO Busfw_t_Uicolumn("GUID", "KEY", "COLUMNCODE", "NAME", "ORDERNUM", "ISVISIABLE", "ISEDIT", "TOTALTAG", "SHOWLEVEL", "REQUIREMENT", "COLTYPE", "HEAD", "FORMAT", "DEFAULTVALUE", "LEVELCONTROL", "COLWIDTH", "ISSOURCE", "TYPE", "CONFIG", "BOTTOMCONTRL", "PROVINCE", "YEAR") VALUES (sys_guid(), '/pmkpi/setting/impexpsub', 'ORDERNUM', '排序', '4', '1', '1', '0', NULL, '0', NULL, NULL, NULL, NULL, NULL, '9', NULL, 's', NULL, NULL, '87', '2016');
INSERT INTO Busfw_t_Uicolumn("GUID", "KEY", "COLUMNCODE", "NAME", "ORDERNUM", "ISVISIABLE", "ISEDIT", "TOTALTAG", "SHOWLEVEL", "REQUIREMENT", "COLTYPE", "HEAD", "FORMAT", "DEFAULTVALUE", "LEVELCONTROL", "COLWIDTH", "ISSOURCE", "TYPE", "CONFIG", "BOTTOMCONTRL", "PROVINCE", "YEAR") VALUES (sys_guid(), '/pmkpi/setting/impexpsub', 'HEAD', '头部', '5', '1', '1', '0', NULL, '0', NULL, NULL, NULL, NULL, NULL, '200', NULL, 's', NULL, NULL, '87', '2016');
INSERT INTO Busfw_t_Uicolumn("GUID", "KEY", "COLUMNCODE", "NAME", "ORDERNUM", "ISVISIABLE", "ISEDIT", "TOTALTAG", "SHOWLEVEL", "REQUIREMENT", "COLTYPE", "HEAD", "FORMAT", "DEFAULTVALUE", "LEVELCONTROL", "COLWIDTH", "ISSOURCE", "TYPE", "CONFIG", "BOTTOMCONTRL", "PROVINCE", "YEAR") VALUES (sys_guid(), '/pmkpi/setting/impexpsub', 'FORMAT', '格式', '6', '1', '1', '0', NULL, '0', NULL, NULL, NULL, NULL, NULL, '50', NULL, 's', NULL, NULL, '87', '2016');
INSERT INTO Busfw_t_Uicolumn("GUID", "KEY", "COLUMNCODE", "NAME", "ORDERNUM", "ISVISIABLE", "ISEDIT", "TOTALTAG", "SHOWLEVEL", "REQUIREMENT", "COLTYPE", "HEAD", "FORMAT", "DEFAULTVALUE", "LEVELCONTROL", "COLWIDTH", "ISSOURCE", "TYPE", "CONFIG", "BOTTOMCONTRL", "PROVINCE", "YEAR") VALUES (sys_guid(), '/pmkpi/setting/impexpsub', 'TYPE', '字段类型', '7', '1', '1', '0', NULL, '1', NULL, NULL, '#code-#name', NULL, NULL, '50', '1', 'tree', '{}', NULL, '87', '2016');
INSERT INTO Busfw_t_Uicolumn("GUID", "KEY", "COLUMNCODE", "NAME", "ORDERNUM", "ISVISIABLE", "ISEDIT", "TOTALTAG", "SHOWLEVEL", "REQUIREMENT", "COLTYPE", "HEAD", "FORMAT", "DEFAULTVALUE", "LEVELCONTROL", "COLWIDTH", "ISSOURCE", "TYPE", "CONFIG", "BOTTOMCONTRL", "PROVINCE", "YEAR") VALUES (sys_guid(), '/pmkpi/setting/impexpsub', 'MAINGUID', '模板类型', '8', '0', '0', '0', NULL, '0', NULL, NULL, NULL, NULL, NULL, '32', NULL, 's', NULL, NULL, '87', '2016');
INSERT INTO Busfw_t_Uicolumn("GUID", "KEY", "COLUMNCODE", "NAME", "ORDERNUM", "ISVISIABLE", "ISEDIT", "TOTALTAG", "SHOWLEVEL", "REQUIREMENT", "COLTYPE", "HEAD", "FORMAT", "DEFAULTVALUE", "LEVELCONTROL", "COLWIDTH", "ISSOURCE", "TYPE", "CONFIG", "BOTTOMCONTRL", "PROVINCE", "YEAR") VALUES (sys_guid(), '/pmkpi/setting/impexpsub', 'COLWIDTH', '列宽', '9', '1', '1', '0', NULL, '1', NULL, NULL, NULL, NULL, NULL, '9', NULL, 's', NULL, NULL,'87', '2016');
INSERT INTO Busfw_t_Uicolumn("GUID", "KEY", "COLUMNCODE", "NAME", "ORDERNUM", "ISVISIABLE", "ISEDIT", "TOTALTAG", "SHOWLEVEL", "REQUIREMENT", "COLTYPE", "HEAD", "FORMAT", "DEFAULTVALUE", "LEVELCONTROL", "COLWIDTH", "ISSOURCE", "TYPE", "CONFIG", "BOTTOMCONTRL", "PROVINCE", "YEAR") VALUES (sys_guid(), '/pmkpi/setting/impexpsub', 'PROVINCE', '区划', '10', '0', '0', '0', NULL, '0', NULL, NULL, NULL, NULL, NULL, '9', NULL, 's', NULL, NULL,'87', '2016');
INSERT INTO Busfw_t_Uicolumn("GUID", "KEY", "COLUMNCODE", "NAME", "ORDERNUM", "ISVISIABLE", "ISEDIT", "TOTALTAG", "SHOWLEVEL", "REQUIREMENT", "COLTYPE", "HEAD", "FORMAT", "DEFAULTVALUE", "LEVELCONTROL", "COLWIDTH", "ISSOURCE", "TYPE", "CONFIG", "BOTTOMCONTRL", "PROVINCE", "YEAR") VALUES (sys_guid(), '/pmkpi/setting/impexpsub', 'YEAR', '年度', '11', '0', '0', '0', NULL, '0', NULL, NULL, NULL, NULL, NULL, '4', NULL, 's', NULL, NULL, '87', '2016');
--添加字段类型表
delete perf_t_datasource where ELEMENTCODE='PMKPI_CODETYPE';
INSERT INTO perf_t_datasource("GUID", "CODE", "NAME", "REMARK", "SUPERGUID", "LEVELNO", "ISLEAF", "ORDERNUM", "ELEMENTCODE", "STATUS", "CREATETIME", "UPDATETIME","YEAR", "PROVINCE") VALUES ('s', 's', 's', NULL, '1', NULL, NULL, '1', 'PMKPI_CODETYPE', '1', '20201229', '20201229','2016','87');
INSERT INTO perf_t_datasource("GUID", "CODE", "NAME", "REMARK", "SUPERGUID", "LEVELNO", "ISLEAF", "ORDERNUM", "ELEMENTCODE", "STATUS", "CREATETIME", "UPDATETIME","YEAR", "PROVINCE") VALUES ('tree', 'tree', 'tree', NULL, '1', NULL, NULL, '2', 'PMKPI_CODETYPE', '1', '20201229', '20201229','2016','87');
INSERT INTO perf_t_datasource("GUID", "CODE", "NAME", "REMARK", "SUPERGUID", "LEVELNO", "ISLEAF", "ORDERNUM", "ELEMENTCODE", "STATUS", "CREATETIME", "UPDATETIME","YEAR", "PROVINCE") VALUES (sys_guid(), 'amt', 'amt', NULL, '1', NULL, NULL, '3', 'PMKPI_CODETYPE', '1', '20201229', '20201229','2016','87');
INSERT INTO perf_t_datasource("GUID", "CODE", "NAME", "REMARK", "SUPERGUID", "LEVELNO", "ISLEAF", "ORDERNUM", "ELEMENTCODE", "STATUS", "CREATETIME", "UPDATETIME","YEAR", "PROVINCE") VALUES ('i', 'i', 'i', NULL, '1', NULL, NULL, '4', 'PMKPI_CODETYPE', '1', '20201229', '20201229','2016','87');
INSERT INTO perf_t_datasource("GUID", "CODE", "NAME", "REMARK", "SUPERGUID", "LEVELNO", "ISLEAF", "ORDERNUM", "ELEMENTCODE", "STATUS", "CREATETIME", "UPDATETIME","YEAR", "PROVINCE") VALUES ('f', 'f', 'f', NULL, '1', NULL, NULL, '5', 'PMKPI_CODETYPE', '1', '20201229', '20201229','2016','87');
INSERT INTO perf_t_datasource("GUID", "CODE", "NAME", "REMARK", "SUPERGUID", "LEVELNO", "ISLEAF", "ORDERNUM", "ELEMENTCODE", "STATUS", "CREATETIME", "UPDATETIME","YEAR", "PROVINCE") VALUES ('d', 'd', 'd', NULL, '1', NULL, NULL, '6', 'PMKPI_CODETYPE', '1', '20201229', '20201229','2016','87');
INSERT INTO perf_t_datasource("GUID", "CODE", "NAME", "REMARK", "SUPERGUID", "LEVELNO", "ISLEAF", "ORDERNUM", "ELEMENTCODE", "STATUS", "CREATETIME", "UPDATETIME","YEAR", "PROVINCE") VALUES ('n', 'n', 'n', NULL, '1', NULL, NULL, '8', 'PMKPI_CODETYPE', '1', '20201229', '20201229','2016','87');
delete Fasp_t_Dicdssource where GUID='PMKPI_CODETYPE';
INSERT INTO Fasp_t_Dicdssource("GUID", "CODE", "ELEMENTCODE", "NAME", "STATUS", "CREATETIME", "STARTTIME", "ENDTIME", "YEAR", "PROVINCE", "CRC", "TYPEGUID", "SHOWSTRUCT", "SOURCETYPE", "DATASOURCE", "DBVERSION", "VERSION", "APPID") VALUES ('PMKPI_CODETYPE', 'TYPE', 'TYPE', '字段类型', '1', '20151015095618892', '20151015', NULL, '2016', '87', NULL, NULL, NULL, '2', 'SELECT * FROM perf_t_datasource t where t.elementcode=''PMKPI_CODETYPE'' order by t.ordernum
', NULL, '1', NULL);