begin
delete from bus_t_diccolumn where tablecode = 'PERF_T_PROINDEXTRACE' and COLUMNCODE = 'COMPLETEANALYSCON';
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'COMPLETEANALYSCON', '1', '2020', '87', '1BAEEDF3BC054656PP7D816582273CA3', 'COMPLETEANALYSCON', 'PERF_T_PROINDEXTRACE', '全年预计完成情况', 'S', '2000', null, 1, 1, null, sysdate);
delete from bus_t_diccolumn where columncode = 'ECONOMIC' and tablecode = 'PERF_T_PROBGTFUND';
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIZJLY', null, '0', 'ECONOMIC', '1', '2016', '87', '18F03oo82A124850B66548AA905B55EF', 'ECONOMIC', 'PERF_T_PROBGTFUND', '经济科目', 's', '32', null, null, 1, null, sysdate);

update bus_t_diccolumn t set t.columnid='C65C6C2D47E11AACE053B11FA8C022C2' where t.COLUMNID='AE7A5056883C2B55E0530603A8C08935';