begin
--自评工作布置项目条件
update p#busfw_T_uitable set config = '{program:" exists(select 1 from v_pm_perf_goal_info gl where gl.pro_code=t.pro_code and gl.yearflag=''0'') and exists (select 1 from (select pro_code,sum(cur_amt) as cur_amt from v_bgt_pm_annual where is_deleted = ''2'' group by pro_code) an where an.pro_code = t.pro_code and an.cur_amt != 0) and exists(SELECT 1 FROM busfw_t_dctableprocess p_1 WHERE p_1.taskguid = (SELECT DECODE( t.paramdata, ''1'', ''9EE3A842793449818960559B00660C1B'', ''A69147082E975D0733386A42C3E5F4B5'') AS decode FROM v_bgt_t_systemset t WHERE t.paramcode = ''ISAUTOINITBDMDATA'')AND p_1.agencyguid = t.agencyguid AND p_1.wfstatus = ''011'' AND p_1.province = t.province) and t.pro_cat_code in(''22'',''3'') and t.is_perform != 1 ",dept:"  t.wfstatus=''011'' and exists(select 1 from v_bgt_perf_goal_info gl where gl.mainguid=t.guid)"}'
where key = '/pmkpi/perfself/taskmanage';
--部门整体自评得分
update perf_t_warnset t set t.warnsql = 'select to_char(nvl(s.score, 0),''FM990.00'') as value FROM v_perf_t_selfevaltask t left join (select c.mainguid, c.agencyguid, sum(c.score) as score from V_PERF_T_SELFPERFINDEX c group by c.mainguid, c.agencyguid) s on t.guid = s.mainguid where t.guid= ''#mainguid#'' ' 
where type = 'selfscoredept';
--部门整体自评结论
update perf_t_warnset t set t.warnsql = 'select case when nvl(s.score,0) >= 90 then ''优'' when nvl(s.score, 0) >= 60 and nvl(s.score, 0)  < 90 then ''良'' when nvl(s.score, 0) < 60 then ''差'' end as value FROM (select c.mainguid, c.agencyguid, sum(c.score) score from V_PERF_T_SELFPERFINDEX c group by c.mainguid, c.agencyguid) s where s.mainguid = ''#mainguid#'' ' 
where type = 'selfresultdept';
--项目自评得分-新增项目指标权重超100的得分逻辑处理
update perf_t_warnset t set t.warnsql = 'select case when (nvl(s.score,0) >= 90 and pro.IS_SCIENTIFIC = 1) or (nvl(s.score,0) >= 90 and a.name = ''其他'') then ''优'' when ((nvl(s.score,0) >= 80 and nvl(s.score,0) < 90) and pro.IS_SCIENTIFIC = 1) or (nvl(s.score,0) >= 80 and nvl(s.score,0) < 90 and a.name = ''其他'') then ''良'' when ((nvl(s.score,0) >= 60 and nvl(s.score,0) < 80) and pro.IS_SCIENTIFIC = 1) or (nvl(s.score,0) >= 60 and nvl(s.score,0) < 80 and a.name = ''其他'') then ''中'' when (nvl(s.score,0) < 60 and pro.IS_SCIENTIFIC = 1) or (nvl(s.score,0) < 60 and a.name = ''其他'') then ''差'' when (nvl(s.score,0) >= 90 and nvl(a.bgtget,0) >= 91 and pro.IS_SCIENTIFIC = 2 and a.name like ''%一般公共预算资金%'') then ''优'' when (nvl(s.score,0) >= 90 and (nvl(a.bgtget,0) < 91 and nvl(a.bgtget,0) >= 50) and pro.IS_SCIENTIFIC = 2 and a.name like ''%一般公共预算资金%'') then ''良'' when (nvl(s.score,0) >= 90 and nvl(a.bgtget,0) < 50 and pro.IS_SCIENTIFIC = 2 and a.name like ''%一般公共预算资金%'') then ''中'' when ((nvl(s.score,0) >= 80 and nvl(s.score,0) < 90) and nvl(a.bgtget,0) >= 50 and pro.IS_SCIENTIFIC = 2 and a.name like ''%一般公共预算资金%'') then ''良'' when ((nvl(s.score,0) >= 80 and nvl(s.score,0) < 90) and nvl(a.bgtget,0) < 50 and pro.IS_SCIENTIFIC = 2 and a.name like ''%一般公共预算资金%'') then ''中'' when (nvl(s.score,0) >= 60 and nvl(s.score,0) < 80 and pro.IS_SCIENTIFIC = 2 and a.name like ''%一般公共预算资金%'') then ''中'' when (nvl(s.score,0) < 60 and pro.IS_SCIENTIFIC = 2 and a.name like ''%一般公共预算资金%'') then ''差'' end as value FROM (select c.mainguid, c.pro_code, case when sum(c.weight) > 100 then round(100*nvl(sum(c.score), 0)/sum(c.weight),2) when sum(c.weight) <= 100 then sum(c.score) end as score from V_PERF_T_SELFPERFINDEX c group by c.mainguid, c.pro_code) s left join (select string_agg(distinct pro_code,'','') as pro_code,string_agg(distinct name,'','') as name,max(bgtget) as bgtget from (select b.pro_code,sum(b.bgtget) as bgtget,''一般公共预算资金'' as name from v_perf_t_selfevaltask a left join perf_t_selfprofund b on a.pro_code = b.pro_code and a.guid =b.mainguid where b.name = ''一般公共预算资金'' group by b.pro_code union select pro_code,0 as bgtget,''其他'' as name from perf_t_selfprofund where name != ''一般公共预算资金'' group by pro_code) group by pro_code)a on a.pro_code = s.pro_code left join v_perf_project_info pro on pro.pro_code = s.pro_code where s.mainguid = ''#mainguid#'' ' 
where type = 'selfresultprogram';
