begin
  
DELETE FROM Bus_t_Diccolumn t WHERE t.tablecode='V_PERF_PROJECT_YEAR' and t.columncode='MANAGE_DEPT_CODE';

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '099003', null, '1', 'MANAGE_DEPT_CODE', '1', null, null, 'C412641FB11C4ED8A005F0AF62F02CDC', 'MANAGE_DEPT_CODE', 'V_PERF_PROJECT_YEAR', '资金主管部门', 'S', null, null, 1, 1, null, sysdate);
