begin

delete from bus_t_diccolumn t where t.tablecode='BGT_PERF_INDICATOR' and t.dbcolumncode in('FINDEX','SINDEX');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIFRAME', null, '1', 'FINDEX', '1', '2016', '87', 'B47721D4F9CA1010E0535164A8C05EF7', 'FINDEX', 'BGT_PERF_INDICATOR', '一级指标', 'S', '300', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIFRAME', null, '1', 'SINDEX', '1', '2016', '87', 'B47721D4F9CB1010E0535164A8C05EF7', 'SINDEX', 'BGT_PERF_INDICATOR', '二级指标', 'S', '300', null, 1, 0, null, sysdate);
