begin

delete FROM BUS_T_DICCOLUMN T WHERE T.TABLECODE='PERF_T_MODEL' AND T.COLUMNCODE='CODE';
insert into BUS_T_DICCOLUMN (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CODE', '1', '2016', '87', '3438567EDAD84343434D0B9A70EFFD35', 'CODE', 'PERF_T_MODEL', '±àÂë', 'S', '40', null, 1, 1, null, sysdate);
