begin
  
delete FROM Bus_t_Dictable t where t.tablecode = 'PERF_BGT_INDEXPRO';

insert into Bus_t_Dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2016', '87', 'PERF_BGT_INDEXPRO', '指标对应项目关系', '指标对应项目关系', 2, 1, 'PERF_BGT_INDEXPRO', 'pmkpi', null, '0', 1, '0', 0, 1, 'V_PERF_BGT_INDEXPRO', sysdate, 1, 1, null, '1');

delete FROM Bus_t_Diccolumn t where t.tablecode = 'PERF_BGT_INDEXPRO';

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AGENCYGUID', '1', '2016', '87', 'C10314B8F30C402CA37C8AC2245082AB', 'AGENCYGUID', 'PERF_BGT_INDEXPRO', '单位', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATER', '1', '2016', '87', '8691848C424645B6B19544D18C11F6C0', 'CREATER', 'PERF_BGT_INDEXPRO', '创建人', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATETIME', '1', '2016', '87', 'D68E7095CDFF41DA8511C024D24A2DC9', 'CREATETIME', 'PERF_BGT_INDEXPRO', '创建时间', 'S', '17', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FININTORGGUID', '1', '2016', '87', 'A9223B77A85641CEAAE6EE3DAC6BD272', 'FININTORGGUID', 'PERF_BGT_INDEXPRO', '处室', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2016', '87', '9C2819C66ECE4B22AE81B5E068B58F61', 'GUID', 'PERF_BGT_INDEXPRO', '主键', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'INDEXGUID', '1', '2016', '87', '2BE738725CB94A2ABF0186D5DAFD62B8', 'INDEXGUID', 'PERF_BGT_INDEXPRO', '来源指标', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_DELETED', '1', '2016', '87', '5754DDC66D284EB4AE0DC9CE9BF52437', 'IS_DELETED', 'PERF_BGT_INDEXPRO', '是否删除', 'N', '1', 0, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MAINGUID', '1', '2016', '87', '012CFD20ACAA496596CDFEB1660C4957', 'MAINGUID', 'PERF_BGT_INDEXPRO', '主表GUID', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ORDERNUM', '1', '2016', '87', '2F55EE461F1A439B8D54D24C19F155AF', 'ORDERNUM', 'PERF_BGT_INDEXPRO', '排序', 'N', '9', 0, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2016', '87', 'BAE3358004CD4432B627A62989811E85', 'PROVINCE', 'PERF_BGT_INDEXPRO', '区划', 'S', '32', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_CODE', '1', '2016', '87', '48FC653ADDC44AF09EABF94494834B0C', 'PRO_CODE', 'PERF_BGT_INDEXPRO', '项目编码', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_ID', '1', '2016', '87', '5122E541C2B44820A85F4667423198E9', 'PRO_ID', 'PERF_BGT_INDEXPRO', '项目主键', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_NAME', '1', '2016', '87', '7702409AD6FB4018AE732990E5756CF6', 'PRO_NAME', 'PERF_BGT_INDEXPRO', '项目名称', 'S', '180', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_TOTAL_AMT', '1', '2016', '87', 'B0ED05C557A244B398E6D106D92E16F8', 'PRO_TOTAL_AMT', 'PERF_BGT_INDEXPRO', '项目金额', 'N', '18', 2, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'REMARK', '1', '2016', '87', '65BA8299BABB40859E0E14B47F487A54', 'REMARK', 'PERF_BGT_INDEXPRO', '备注', 'S', '1000', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'STATUS', '1', '2016', '87', '3915E794EB724A709199983E41ED1DA9', 'STATUS', 'PERF_BGT_INDEXPRO', '状态', 'N', '1', 0, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UPDATETIME', '1', '2016', '87', '47F8CEF677D044D1ADC5AD3A875F4F9E', 'UPDATETIME', 'PERF_BGT_INDEXPRO', '更新时间', 'S', '17', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2016', '87', '61A200FA8AB14F90A653AC814E44B198', 'YEAR', 'PERF_BGT_INDEXPRO', '年度', 'N', '4', 0, 1, 0, null, sysdate);

delete FROM Bus_t_Dictable t where t.tablecode = 'PERF_BGT_LINKBGTINFO';

insert into Bus_t_Dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2016', '87', 'PERF_BGT_LINKBGTINFO', '预算挂钩机制', '预算挂钩机制', 2, 1, 'PERF_BGT_LINKBGTINFO', 'pmkpi', null, '0', 1, '0', 0, 1, 'V_PERF_BGT_LINKBGTINFO', sysdate, 1, 1, null, '1');

delete FROM Bus_t_Diccolumn t where t.tablecode = 'PERF_BGT_LINKBGTINFO';

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AGENCYGUID', '1', '2016', '87', '068BC304EB2F4A2A9A49BF2D861A187C', 'AGENCYGUID', 'PERF_BGT_LINKBGTINFO', '单位', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BASEPERIOD', '1', '2016', '87', '498FC108B19143209BA17138DA387411', 'BASEPERIOD', 'PERF_BGT_LINKBGTINFO', '基期指标值', 'S', '200', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BGTAMT1', '1', '2016', '87', '20C98649107B40A4B592E108F674E957', 'BGTAMT1', 'PERF_BGT_LINKBGTINFO', '历史预算安排金额1', 'N', '18', 2, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BGTAMT2', '1', '2016', '87', '0625A9106E944DBC95137F9CC85B1E6A', 'BGTAMT2', 'PERF_BGT_LINKBGTINFO', '历史预算安排金额2', 'N', '18', 2, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BGTAMT3', '1', '2016', '87', 'D5E0A201C4F54787A8379E8DDF31C299', 'BGTAMT3', 'PERF_BGT_LINKBGTINFO', '历史预算安排金额3', 'N', '18', 2, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIZBXS', null, '1', 'COMPUTESIGN', '1', '2016', '87', '75B267867E6F41348D72431DA5073347', 'COMPUTESIGN', 'PERF_BGT_LINKBGTINFO', '符号', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'COUPLEAMT', '1', '2016', '87', 'AF860AC3254C4D9AAF9D172C1C11FEA6', 'COUPLEAMT', 'PERF_BGT_LINKBGTINFO', '挂钩额', 'N', '18', 2, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'COUPLERATE', '1', '2016', '87', 'E38F45DAE021425DBAD3066D3F0EFFD2', 'COUPLERATE', 'PERF_BGT_LINKBGTINFO', '挂钩增减比例', 'N', '5', 2, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATER', '1', '2016', '87', '45D8262FC2BD4E0BB7A210B7A8C9AEF2', 'CREATER', 'PERF_BGT_LINKBGTINFO', '创建人', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATETIME', '1', '2016', '87', 'EF6FFFA962CE4088A427EB3B4F3B2BD7', 'CREATETIME', 'PERF_BGT_LINKBGTINFO', '创建时间', 'S', '17', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FINDEX', '1', '2016', '87', '73212B11A4D94F5289BB3A03EE1C1410', 'FINDEX', 'PERF_BGT_LINKBGTINFO', '一级指标', 'S', '300', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FININTORGGUID', '1', '2016', '87', '5FD2CF119C434E658845818289AC5B03', 'FININTORGGUID', 'PERF_BGT_LINKBGTINFO', '处室', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2016', '87', 'F1C252C3C8C449A7BB2BDF9E4EB2D275', 'GUID', 'PERF_BGT_LINKBGTINFO', '主键', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'INDEXGUID', '1', '2016', '87', '37CDD8232EE5491287607811A24773E2', 'INDEXGUID', 'PERF_BGT_LINKBGTINFO', '来源指标', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_DELETED', '1', '2016', '87', 'C3529A9C26CD41C4819E9495AE3A7C26', 'IS_DELETED', 'PERF_BGT_LINKBGTINFO', '是否删除', 'N', '1', 0, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'KPI_VAL', '1', '2016', '87', '0B49077878B041868C66DEBB7E956625', 'KPI_VAL', 'PERF_BGT_LINKBGTINFO', '指标值', 'S', '1000', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'KPI_VAL1', '1', '2016', '87', '499A48480E394322891C3125E4FB24EF', 'KPI_VAL1', 'PERF_BGT_LINKBGTINFO', '历史指标值1', 'S', '1000', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'KPI_VAL2', '1', '2016', '87', '60A49748A22142A993D6F67A183C0816', 'KPI_VAL2', 'PERF_BGT_LINKBGTINFO', '历史指标值2', 'S', '1000', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'KPI_VAL3', '1', '2016', '87', '9AFABD960341484F8C9CCD2DC7C307D1', 'KPI_VAL3', 'PERF_BGT_LINKBGTINFO', '历史指标值3', 'S', '1000', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MAINGUID', '1', '2016', '87', 'F53075D0527C4A458D3C21F9710C4D03', 'MAINGUID', 'PERF_BGT_LINKBGTINFO', '主表ID', 'S', '40', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'METERUNIT', '1', '2016', '87', '1B698EBEA16D42D2812F9F6ED33E2BE1', 'METERUNIT', 'PERF_BGT_LINKBGTINFO', '计量单位', 'S', '200', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'NAME', '1', '2016', '87', '6B154EA403EF4D0E9B873ADCCF5E0BA9', 'NAME', 'PERF_BGT_LINKBGTINFO', '指标名称', 'S', '1000', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ORDERNUM', '1', '2016', '87', '00B5BE44070E43D78CEF62F2F46FCAD6', 'ORDERNUM', 'PERF_BGT_LINKBGTINFO', '排序', 'N', '9', 0, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2016', '87', '15E10C33F6CE424DB8761C473C0599C8', 'PROVINCE', 'PERF_BGT_LINKBGTINFO', '区划', 'S', '32', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'REMARK', '1', '2016', '87', '23E7FEB04FC046D2B648AABC1D9CEDFB', 'REMARK', 'PERF_BGT_LINKBGTINFO', '备注', 'S', '1000', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SCORE', '1', '2016', '87', '07A30AE9CA52470FA2A92B3E3165B12D', 'SCORE', 'PERF_BGT_LINKBGTINFO', '权重', 'N', '5', 2, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SINDEX', '1', '2016', '87', 'BB149FFEE45943838D590520D0A6A1B6', 'SINDEX', 'PERF_BGT_LINKBGTINFO', '二级指标', 'S', '300', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'STATUS', '1', '2016', '87', '12E1074A214C4B159411B4D836761451', 'STATUS', 'PERF_BGT_LINKBGTINFO', '状态', 'N', '1', 0, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UPDATETIME', '1', '2016', '87', '4D3D126E98DA4D26918CC8F930C25F71', 'UPDATETIME', 'PERF_BGT_LINKBGTINFO', '更新', 'S', '17', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2016', '87', 'EB6F5453C4634D80A4052253FE2274D2', 'YEAR', 'PERF_BGT_LINKBGTINFO', '年度', 'N', '4', 0, 1, 0, null, sysdate);
