v_sql varchar2(2000);
ln_i integer;
begin
	v_sql :='CREATE OR REPLACE VIEW V_PERF_REVIEWINTERMEDIARY AS
SELECT * FROM PERF_REVIEWINTERMEDIARY
WHERE YEAR = GLOBAL_MULTYEAR_CZ.V_PMYEAR
AND PROVINCE = GLOBAL_MULTYEAR_CZ.V_PMDIVID';
	select fn_alterview('V_PERF_REVIEWINTERMEDIARY',v_sql) into ln_i;
	if ln_i = 0 then
	    return;
	end if;
	
	v_sql :='CREATE OR REPLACE VIEW V_PERF_SELINTERMEDIARY AS
SELECT
    M.CODE,M.NAME,M.INSTITUTIONAL,M.CREDITNO,M.EVALUATENUM, T.REVIEW,T.INTERMEDIARY,T.GUID
FROM V_PERF_REVIEWINTERMEDIARY T
LEFT JOIN V_PERF_INTERMEDIARYINFO M ON M.GUID = T.INTERMEDIARY';
	select fn_alterview('V_PERF_SELINTERMEDIARY',v_sql) into ln_i;
	if ln_i = 0 then
	    return;
	end if;