begin
  
DELETE FROM bus_t_Diccolumn t where t.tablecode='PM_PERF_INDICATOR_TEMP' and t.columncode in ('KPI_L1','KPI_LV1');

insert into bus_t_Diccolumn (COLUMNID, DBCOLUMNCODE, COLUMNCODE, NAME, TABLECODE, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, DEID, CSID, ISSYS, ISUSES, VERSION)
values ('C065517D3C0F4308E053B11FA8C0746D', 'KPI_LV1', 'KPI_LV1', '一级指标', 'PM_PERF_INDICATOR_TEMP', 'S', '30', null, null, null, 'BE09101', 'VD08120', '0', '1', '1');
