begin

delete from bus_t_diccolumn t where t.tablecode in('BAS_PERF_INDICATOR') and t.DBCOLUMNCODE in('FRAMESYSTEM','NAME','INDUSTRYCATEGORY');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIFRAMESYSTEM', null, '1', 'FRAMESYSTEM', '1', '2016', '87', '17A738A2A10A42538A319BBC13E839DA', 'FRAMESYSTEM', 'BAS_PERF_INDICATOR', '指标体系', 'S', '400', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'NAME', '1', '2016', '87', 'B412538AA09062E3E0535164A8C0C98B', 'NAME', 'BAS_PERF_INDICATOR', '指标名称', 'S', '80', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'INDEXCOMFUNC', null, '1', 'INDUSTRYCATEGORY', '1', '2016', '87', 'B686DC99B6E90CCAE0530100007FB3EC', 'INDUSTRYCATEGORY', 'BAS_PERF_INDICATOR', '行业类别', 'S', '40', null, 1, 1, null, sysdate);
