begin 

execute immediate'
CREATE OR REPLACE VIEW V_PERF_DEPT_INFOREVIEW AS
select m.GUID as PROGUID,
       m.NAME,
       m.CODE,
       m.LINKMAN,
       m.TELEPHONE,
       m.GIST,
       m.FUNCDESC,
       m.AGENCYGUID,
       m.PROVINCE,
       m.YEAR,
       m.ORDERNUM,
       m.FININTORGGUID,
       m.SUBAGENCYNUM,
       m.THEJOBNUM,
       m.STAFFNUM,
       m.INSTITUTIONSNUM,
       m.FUNCTION,
       m.PERFGOAL,
       m.BUDGETTOTAL,
       m.FINANCIALFUND,
       m.OTHERFUND,
       m.BASICEXPEND,
       m.THREEPUBLICFUND,
       m.SPECIALFUND,
       m.BUDGETAMT,
       m.GOVEFUNCAMT,
       m.TAXRANAMT,
       m.PROJEXPAMT,
       m.GOVTFUNDS,
       m.OTHERFUNDS,
       m.STATECAPITALBUDGET,
       m.PUBBUDGET,
       m.SUMFUNDS,
       t.GUID,
       t.ISRECHECK,
       t.TYPE,
       t.CONCLUSION,
       t.AUDITOR,
       t.LASTUPDATETIME,
       t.CREATETIME,
       t.UPDATETIME,
       t.WFSTATUS,
       t.WFID,
       t.STATUS,
       t.EXPERT,
       t.INSTITUTION,
       t.ISLAST,
       t.REVIEWNUM,
       t.ISCONFIRM
  from (SELECT * FROM  v_perf_t_review t where  ISLAST=1) t , v_perf_t_deptperfdeclare m   
where t.PROGUID = m.GUID';