version: "2"
services:
 bank:
  image: cloud/ifmis-bank-service:1.0.0-SNAPSHOT
  hostname: ifmis-bank-service
  networks:
   - eureka-net
#  env_file:
#   - ../api.env
  ports:
   - "8033:8033"
  environment:
   - spring.profiles.active=dev-nacos
   - JAVA_OPTS=-Xms512m -Xmx2048m -XX:MaxPermSize=387m -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true
   - RABBITMQ_SERVER=192.168.7.6
   - RABBITMQ_SERVER_PORT=5672
   - RABBITMQ_SERVER_USERNAME=admin
   - RABBITMQ_SERVER_PASSWORD=123456
   - NACOS_NAMESPACE=ifmis
   - NACOS_GROUP=DEFAULT_GROUP
   - CONFIG_SERVER=192.168.7.6
   - CONFIG_SERVER_PORT=8848
 bank-webapp:
  image: cloud/ifmis-bank-webapp:1.0.0-SNAPSHOT
  hostname: ifmis-bank-webapp
  networks:
   - eureka-net
#  env_file:
#   - ../api.env
  ports:
   - "7033:7033"
  environment:
   - spring.profiles.active=dev-nacos
   - RABBITMQ_SERVER=192.168.7.6
   - RABBITMQ_SERVER_PORT=5672
   - RABBITMQ_SERVER_USERNAME=admin
   - RABBITMQ_SERVER_PASSWORD=123456
   - NACOS_NAMESPACE=ifmis
   - NACOS_GROUP=DEFAULT_GROUP
   - CONFIG_SERVER=192.168.7.6
   - CONFIG_SERVER_PORT=8848
networks:
 eureka-net:
  external: true
#docker network create eureka-net