server.port=7035

#页面默认前缀目录
spring.mvc.view.prefix=/WEB-INF/jsp/
#页面默认后缀目录
spring.mvc.view.suffix=.jsp
#关闭默认模板引擎
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=false

#修改jsp页面立即生效
server.servlet.jsp.init-parameters.development=true
server.tomcat.uri-encoding=UTF-8
server.tomcat.basedir=.
tomcat.util.http.parser.HttpParser.requestTargetAllow=|{}
server.tomcat.util.http.parser.HttpParser.requestTargetAllow=|{}
#logging.level.root=debug
#log4j.rootCategory=debug,stdout

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss,SSS} %5p %c{1}:%L - %m%n

#指定zipkin中心
spring.zipkin.base-url=http://127.0.0.1:9411
spring.zipkin.enabled=true
spring.sleuth.web.client.enabled=true
spring.sleuth.sampler.probability=1.0
spring.zipkin.discoveryClientEnabled=true


#从eureka服务器注册表中获取注册信息的时间间隔（s），默认为30秒
eureka.client.registry-fetch-interval-seconds=5