begin

delete from bus_t_diccolumn t where t.tablecode='PERF_T_SELFEVALTASK' and t.columncode in('BGTAMT','BGTGET','BUDGETAMOUNT','EXECAMOUNT');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BGTAMT', '1', '2021', '87', '222B314BC2575271E0530100007F17EC', 'BGTAMT', 'PERF_T_SELFEVALTASK', '当年预算金额', 'N', '20', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BGTGET', '1', '2021', '87', 'D42BA37663362A20E0533315A8C085FA', 'BGTGET', 'PERF_T_SELFEVALTASK', '预算执行率', 'N', '6', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BUDGETAMOUNT', '1', '2023', '87', 'F815B6A363B871F3E0533315A8C011A9', 'BUDGETAMOUNT', 'PERF_T_SELFEVALTASK', '年初预算数', 'N', '20', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EXECAMOUNT', '1', '2023', '87', 'F815B6A363BB71F3E0533315A8C011A9', 'EXECAMOUNT', 'PERF_T_SELFEVALTASK', '全年执行数', 'N', '20', null, 1, 1, null, sysdate);
