begin
  
delete from bus_t_diccolumn where tablecode = 'PERF_T_PROMONITOR' and columncode in ('PRO_LEV','PRO_LEVONE_CODE','PROJECTKIND');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMPROJECTKINDEXTEND', null, '1', 'PROJECTKIND', '1', '2021', '87', '68E9A4EBDA79E1D85F0D284EB8CFC4F1', 'PROJECTKIND', 'PERF_T_PROMONITOR', '支出项目类别', 'S', '200', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_LEV', '1', null, null, '46B514E30857D305BA1D9F3EF0038964', 'PRO_LEV', 'PERF_T_PROMONITOR', '项目级次', 'S', '2', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIPROLEVONECODE', null, '1', 'PRO_LEVONE_CODE', '1', '2021', '87', 'C7386F5E19B813CA2053CAD25BFCB0DB', 'PRO_LEVONE_CODE', 'PERF_T_PROMONITOR', '专项资金', 'S', '200', null, 1, 1, null, sysdate);
