begin
--列表字段注册
delete from bus_t_diccolumn where tablecode ='V_PERF_ADJUSTPROJECT_INFO' and COLUMNCODE in('PROJECTKIND','PRO_LEVONE_CODE');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMPROJECTKINDEXTEND', null, '0', 'PROJECTKIND', '1', null, null, sys_guid(), 'PROJECTKIND', 'V_PERF_ADJUSTPROJECT_INFO', '支出项目类别', 'S', '32', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIPROLEVONECODE', null, '0', 'PRO_LEVONE_CODE', '1', null, null, sys_guid(), 'PRO_LEVONE_CODE', 'V_PERF_ADJUSTPROJECT_INFO', '一级项目编码', 'S', null, null, 1, 1, null, sysdate);


delete from bus_t_diccolumn where tablecode ='PERF_V_SELFEVALTASK' and COLUMNCODE in('PROJECTKIND','PRO_LEVONE_CODE');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMPROJECTKINDEXTEND', null, '1', 'PROJECTKIND', '1', '2021', '87', sys_guid(), 'PROJECTKIND', 'PERF_V_SELFEVALTASK', '支出项目类别', 'S', '200', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIPROLEVONECODE', null, '1', 'PRO_LEVONE_CODE', '1', '2021', '87', sys_guid(), 'PRO_LEVONE_CODE', 'PERF_V_SELFEVALTASK', '一级项目编码', 'S', '200', null, 1, 1, null, sysdate);


delete from bus_t_diccolumn where tablecode ='PERF_T_SELFEVALTASK' and COLUMNCODE in('PROJECTKIND','PRO_LEVONE_CODE');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMPROJECTKINDEXTEND', null, '1', 'PROJECTKIND', '1', '2021', '87', sys_guid(), 'PROJECTKIND', 'PERF_T_SELFEVALTASK', '支出项目类别', 'S', '200', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIPROLEVONECODE', null, '1', 'PRO_LEVONE_CODE', '1', '2021', '87', sys_guid(), 'PRO_LEVONE_CODE', 'PERF_T_SELFEVALTASK', '一级项目编码', 'S', '200', null, 1, 1, null, sysdate);


delete from bus_t_diccolumn where tablecode ='PERF_T_ADJUST' and COLUMNCODE in('PROJECTKIND','PRO_LEVONE_CODE');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMPROJECTKINDEXTEND', null, '0', 'PROJECTKIND', '1', '2020', '87', sys_guid(), 'PROJECTKIND', 'PERF_T_ADJUST', '支出项目类别', 'S', '100', null, null, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIPROLEVONECODE', null, '0', 'PRO_LEVONE_CODE', '1', '2020', '87', sys_guid(), 'PRO_LEVONE_CODE', 'PERF_T_ADJUST', '一级项目编码', 'S', '100', null, null, 1, null, sysdate);


delete from bus_t_diccolumn where tablecode ='PERF_T_DEPTPERFMIDDECLARE' and COLUMNCODE in('PROJECTKIND','PRO_LEVONE_CODE');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMPROJECTKINDEXTEND', null, '0', 'PROJECTKIND', '1', '2016', '87', sys_guid(), 'PROJECTKIND', 'PERF_T_DEPTPERFMIDDECLARE', '支出项目类别', 'S', '100', null, null, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIPROLEVONECODE', null, '0', 'PRO_LEVONE_CODE', '1', '2016', '87', sys_guid(), 'PRO_LEVONE_CODE', 'PERF_T_DEPTPERFMIDDECLARE', '一级项目编码', 'S', '100', null, null, 1, null, sysdate);


delete from bus_t_diccolumn where tablecode ='V_PERF_PROJECT_YEAR' and COLUMNCODE in('PROJECTKIND','PRO_LEVONE_CODE');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMPROJECTKINDEXTEND', null, '0', 'PROJECTKIND', '1', null, null, sys_guid(), 'PROJECTKIND', 'V_PERF_PROJECT_YEAR', '支出项目类别', 'S', '32', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIPROLEVONECODE', null, '1', 'PRO_LEVONE_CODE', '1', null, null, sys_guid(), 'PRO_LEVONE_CODE', 'V_PERF_PROJECT_YEAR', '一级项目编码', 'S', null, null, 1, 1, null, sysdate);


delete from bus_t_diccolumn where tablecode ='V_PERF_TRACEPROJECT_INFO' and COLUMNCODE in('PROJECTKIND','PRO_LEVONE_CODE');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMPROJECTKINDEXTEND', null, '0', 'PROJECTKIND', '1', null, null, sys_guid(), 'PROJECTKIND', 'V_PERF_TRACEPROJECT_INFO', '支出项目类别', 'S', '100', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIPROLEVONECODE', null, '0', 'PRO_LEVONE_CODE', '1', null, null, sys_guid(), 'PRO_LEVONE_CODE', 'V_PERF_TRACEPROJECT_INFO', '一级项目编码', 'S', '200', null, 1, 1, null, sysdate);



delete from bus_t_diccolumn where tablecode ='PERF_V_PROMONITOR' and COLUMNCODE in('PROJECTKIND','PRO_LEVONE_CODE');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMPROJECTKINDEXTEND', null, '0', 'PROJECTKIND', '1', '2020', '87', 'B71F832B83334B0E0530100007FA9FF', 'PROJECTKIND', 'PERF_V_PROMONITOR', '支出项目类别', 'S', '100', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIPROLEVONECODE', null, '0', 'PRO_LEVONE_CODE', '1', '2020', '87', 'B71F832B8B4445B0E0530100007FA9FF', 'PRO_LEVONE_CODE', 'PERF_V_PROMONITOR', '一级项目编码', 'S', '200', null, 1, 1, null, sysdate);
