begin

--监控指标草稿表
delete from bus_t_dictable where tablecode = 'PERF_T_SELFPERFINDEXTEMP';
insert into bus_t_dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2016', '87', 'PERF_T_SELFPERFINDEXTEMP', '自评指标草稿表', '自评指标草稿表', 2, 1, 'PERF_T_SELFPERFINDEXTEMP', 'pmkpi', null, '0', 1, null, 1, 1, 'V_PERF_T_SELFPERFINDEXTEMP', sysdate, 1, 1, null, '1');

--表字段注册
delete from bus_t_diccolumn where tablecode = 'PERF_T_SELFPERFINDEXTEMP';
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPISJDXZB1', null, '1', 'ACTUALVALUE', '1', '2016', '87', 'E528B8489AEF4E2DE0533315A8C09CAA', 'ACTUALVALUE', 'PERF_T_SELFPERFINDEXTEMP', '实际完成值', 'S', '1000', null, 1, 0, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ACTUALWEIGHT', '1', '2016', '87', 'E528B8489AF04E2DE0533315A8C09CAA', 'ACTUALWEIGHT', 'PERF_T_SELFPERFINDEXTEMP', '权重设定值', 'N', '6', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AGENCYGUID', '1', '2016', '87', 'E528B8489AF14E2DE0533315A8C09CAA', 'AGENCYGUID', 'PERF_T_SELFPERFINDEXTEMP', '单位', 'S', '40', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CODE', '1', '2016', '87', 'E528B8489AF24E2DE0533315A8C09CAA', 'CODE', 'PERF_T_SELFPERFINDEXTEMP', '编码', 'S', '300', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIZBXS', null, '1', 'COMPUTESIGN', '1', '2016', '87', 'E528B8489AF34E2DE0533315A8C09CAA', 'COMPUTESIGN', 'PERF_T_SELFPERFINDEXTEMP', '计算符号', 'S', '40', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATER', '1', '2016', '87', 'E528B8489AF44E2DE0533315A8C09CAA', 'CREATER', 'PERF_T_SELFPERFINDEXTEMP', '创建人', 'S', '40', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATETIME', '1', '2016', '87', 'E528B8489AF54E2DE0533315A8C09CAA', 'CREATETIME', 'PERF_T_SELFPERFINDEXTEMP', '创建时间', 'S', '17', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'DATATYPE', '1', '2016', '87', 'E528B8489AF64E2DE0533315A8C09CAA', 'DATATYPE', 'PERF_T_SELFPERFINDEXTEMP', '数据类型', 'S', '40', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FINDEX', '1', '2016', '87', 'E528B8489AF74E2DE0533315A8C09CAA', 'FINDEX', 'PERF_T_SELFPERFINDEXTEMP', '一级指标', 'S', '40', null, 1, 0, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '099003', null, '1', 'FININTORGGUID', '1', '2016', '87', 'E528B8489AF84E2DE0533315A8C09CAA', 'FININTORGGUID', 'PERF_T_SELFPERFINDEXTEMP', '处室', 'S', '40', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2016', '87', 'E528B8489AF94E2DE0533315A8C09CAA', 'GUID', 'PERF_T_SELFPERFINDEXTEMP', '主键', 'S', '40', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'INDEXVAL', '1', '2016', '87', 'E528B8489AFA4E2DE0533315A8C09CAA', 'INDEXVAL', 'PERF_T_SELFPERFINDEXTEMP', '指标值', 'S', '1000', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ISLEAF', '1', '2016', '87', 'E528B8489AFB4E2DE0533315A8C09CAA', 'ISLEAF', 'PERF_T_SELFPERFINDEXTEMP', '是否叶子节点', 'S', '40', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_DELETED', '1', '2016', '87', 'E528B8489AFC4E2DE0533315A8C09CAA', 'IS_DELETED', 'PERF_T_SELFPERFINDEXTEMP', '是否删除', 'N', '1', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'KPIVALSOURCE', '1', '2016', '87', 'E528B8489AFD4E2DE0533315A8C09CAA', 'KPIVALSOURCE', 'PERF_T_SELFPERFINDEXTEMP', '值集来源', 'S', '40', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'KPI_EVALSTD', '1', '2016', '87', 'E528B8489AFE4E2DE0533315A8C09CAA', 'KPI_EVALSTD', 'PERF_T_SELFPERFINDEXTEMP', '评分标准', 'S', '200', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'KPI_REMARK', '1', '2016', '87', 'E528B8489AFF4E2DE0533315A8C09CAA', 'KPI_REMARK', 'PERF_T_SELFPERFINDEXTEMP', '备注', 'S', '2000', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LEVELNO', '1', '2016', '87', 'E528B8489B004E2DE0533315A8C09CAA', 'LEVELNO', 'PERF_T_SELFPERFINDEXTEMP', '级别', 'S', '40', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MAINGUID', '1', '2016', '87', 'E528B8489B014E2DE0533315A8C09CAA', 'MAINGUID', 'PERF_T_SELFPERFINDEXTEMP', '关联id', 'S', '40', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'METERUNIT', '1', '2016', '87', 'E528B8489B024E2DE0533315A8C09CAA', 'METERUNIT', 'PERF_T_SELFPERFINDEXTEMP', '单位', 'S', '40', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'NAME', '1', '2016', '87', 'E528B8489B034E2DE0533315A8C09CAA', 'NAME', 'PERF_T_SELFPERFINDEXTEMP', '指标名称', 'S', '1000', null, 1, 0, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'OPERATION', '1', '2016', '87', 'E528B8489B044E2DE0533315A8C09CAA', 'OPERATION', 'PERF_T_SELFPERFINDEXTEMP', '选项', 'S', '40', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ORDERNUM', '1', '2016', '87', 'E528B8489B054E2DE0533315A8C09CAA', 'ORDERNUM', 'PERF_T_SELFPERFINDEXTEMP', '排序', 'S', '9', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROJGUID', '1', '2016', '87', 'E528B8489B064E2DE0533315A8C09CAA', 'PROJGUID', 'PERF_T_SELFPERFINDEXTEMP', '项目GUID', 'S', '40', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2016', '87', 'E528B8489B074E2DE0533315A8C09CAA', 'PROVINCE', 'PERF_T_SELFPERFINDEXTEMP', '区划', 'S', '32', null, 1, 0, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_CODE', '1', '2016', '87', 'E528B8489B084E2DE0533315A8C09CAA', 'PRO_CODE', 'PERF_T_SELFPERFINDEXTEMP', '项目编码', 'S', '200', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'RULE', '1', '2016', '87', 'E528B8489B094E2DE0533315A8C09CAA', 'RULE', 'PERF_T_SELFPERFINDEXTEMP', '赋分原则', 'S', '2000', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SCORE', '1', '2016', '87', 'E528B8489B0A4E2DE0533315A8C09CAA', 'SCORE', 'PERF_T_SELFPERFINDEXTEMP', '得分', 'N', '6', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SCORE_REMARK', '1', '2016', '87', 'E528B8489B0B4E2DE0533315A8C09CAA', 'SCORE_REMARK', 'PERF_T_SELFPERFINDEXTEMP', '备注', 'S', '2000', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SINDEX', '1', '2016', '87', 'E528B8489B0C4E2DE0533315A8C09CAA', 'SINDEX', 'PERF_T_SELFPERFINDEXTEMP', '二级指标', 'S', '40', null, 1, 0, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'STATUS', '1', '2016', '87', 'E528B8489B0D4E2DE0533315A8C09CAA', 'STATUS', 'PERF_T_SELFPERFINDEXTEMP', '状态', 'S', '1', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SUPERID', '1', '2016', '87', 'E528B8489B0E4E2DE0533315A8C09CAA', 'SUPERID', 'PERF_T_SELFPERFINDEXTEMP', '父级id', 'S', '40', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TINDEX', '1', '2016', '87', 'E528B8489B0F4E2DE0533315A8C09CAA', 'TINDEX', 'PERF_T_SELFPERFINDEXTEMP', '指标id', 'S', '40', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UPDATETIME', '1', '2016', '87', 'E528B8489B104E2DE0533315A8C09CAA', 'UPDATETIME', 'PERF_T_SELFPERFINDEXTEMP', '更新时间', 'S', '17', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WEIGHT', '1', '2016', '87', 'E528B8489B114E2DE0533315A8C09CAA', 'WEIGHT', 'PERF_T_SELFPERFINDEXTEMP', '权重设定值', 'N', '6', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WFID', '1', '2016', '87', 'E528B8489B124E2DE0533315A8C09CAA', 'WFID', 'PERF_T_SELFPERFINDEXTEMP', '工作流id', 'S', '40', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WFSTATUS', '1', '2016', '87', 'E528B8489B134E2DE0533315A8C09CAA', 'WFSTATUS', 'PERF_T_SELFPERFINDEXTEMP', '工作流状态', 'S', '40', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2016', '87', 'E528B8489B144E2DE0533315A8C09CAA', 'YEAR', 'PERF_T_SELFPERFINDEXTEMP', '年度', 'S', '4', null, 1, 1, null, sysdate);

