begin
  
execute immediate '
create or replace view v_perf_dept_infoquery as
select t.GUID proguid,
       t.NAME,
       t.CODE,
       t.LINKMAN,
       t.TELEPHONE,
       t.GIST,
       t.FUNCDESC,
       t.AGENCYGUID,
       t.STATUS,
       t.ORDERNUM,
       t.FININTORGGUID,
       t.SUBAGENCYNUM,
       t.THEJOBNUM,
       t.STAFFNUM,
       t.INSTITUTIONSNUM,
       t.FUNCTION,
       t.PERFGOAL,
       t.BUDGETTOTAL,
       t.FINANCIALFUND,
       t.OTHERFUND,
       t.BASICEXPEND,
       t.THREEPUBLICFUND,
       t.SPECIALFUND,
       t.BUDGETAMT,
       t.GOVEFUNCAMT,
       t.TAXRANAMT,
       t.PROJEXPAMT,
       t.GOVTFUNDS,
       t.OTHERFUNDS,
       t.STATECAPITALBUDGET,
       t.PUBBUDGET,
       t.CREATETIME CREATE_TIME,
       t.SUMFUNDS from v_perf_t_deptperfdeclare t';
