begin
  
delete from bus_t_diccolumn t where t.tablecode='PERF_T_SELFPERFINDEX' and t.columncode in('OPINION_REMARK','AUDIT_SCORE');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AUDIT_SCORE', '1', '2021', '87', 'F44F29263A1C60FBE0533315A8C0693D', 'AUDIT_SCORE', 'PERF_T_SELFPERFINDEX', '审核得分', 'N', '5', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'OPINION_REMARK', '1', '2021', '87', 'F44F29263A1B60FBE0533315A8C0693D', 'OPINION_REMARK', 'PERF_T_SELFPERFINDEX', '审核意见', 'S', '4000', null, 1, 1, null, sysdate);

delete from bus_t_diccolumn t where t.tablecode='PERF_T_SELFPERFINDEX' and t.columncode in('DEDUCT_SCORE');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'DEDUCT_SCORE', '1', '2021', '87', 'F5191274C8C36777E0533315A8C01B34', 'DEDUCT_SCORE', 'PERF_T_SELFPERFINDEX', '扣减得分', 'N', '5', null, 1, 1, null, sysdate);