server.port=9003

microservice.loader.modules=pmkpi

spring.mvc.servlet.load-on-startup=0
#页面默认前缀目录
spring.mvc.view.prefix=/WEB-INF/jsp/
#页面默认后缀目录
spring.mvc.view.suffix=.jsp
#关闭默认模板引擎
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=false
#context.initializer.classes=BusApplicationContextInitializer
#修改jsp页面立即生效
server.servlet.jsp.init-parameters.development=true
server.tomcat.uri-encoding=UTF-8
server.tomcat.basedir=.
tomcat.util.http.parser.HttpParser.requestTargetAllow=|{}
server.tomcat.util.http.parser.HttpParser.requestTargetAllow=|{}
logging.level.root=info
#logging.level.org.apache.jasper.servlet.JspServlet=debug
log4j.rootCategory=info,stdout
#logging.level.gov.mof.fasp2.cloud.framework.start.datasource.MultiDataSource=debug
#logging.level.gov.mof.fasp2.cloud.framework.start.datasource.JdbcDatasource=debug
#logging.level.gov.mof.fasp2.buscore.framework.springexp.LoaderApplicationContextInitializer=debug

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss,SSS} %5p %c{1}:%L - %m%n

#mq相关配置
#spring.rabbitmq.publisher-confirm-type=correlated
#spring.rabbitmq.publisher-returns=true
#spring.rabbitmq.listener.simple.acknowledge-mode=manual
#spring.rabbitmq.listener.simple.concurrency=5
#spring.rabbitmq.listener.simple.max_concurrency=5
#spring.rabbitmq.listener.simple.prefetch=1
#spring.rabbitmq.listener.simple.retry.initial-interval=50000ms
#spring.rabbitmq.listener.simple.retry.enabled=true
#spring.rabbitmq.listener.simple.retry.max-attempts=5
#spring.rabbitmq.listener.simple.default-requeue-rejected=true