begin

delete from p#busfw_t_uieditform t where t.key in('/pmkpi/workevaluate/task/edit');
insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('C31309734CC552A1E053B11FA8C0828D', '/pmkpi/workevaluate/task/edit', 'V_PERF_T_WORKEVALUATETASK', 's', '任务名称', 'NAME', 1, null, 1, null, 1, null, null, 'pmkpi', 1, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('C31309734CC652A1E053B11FA8C0828D', '/pmkpi/workevaluate/task/edit', 'V_PERF_T_WORKEVALUATETASK', 'tree', '考核对象', 'TASKTYPE', 1, '0', 1, null, 2, null, null, 'pmkpi', 1, null, '{format:''#name''}', 0, 1, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('C31309734CC752A1E053B11FA8C0828D', '/pmkpi/workevaluate/task/edit', 'V_PERF_T_WORKEVALUATETASK', 'tree', '任务类型', 'BUSTYPE', 0, null, 1, null, 3, null, null, 'pmkpi', 1, null, '{format:''#name''}', 0, 0, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('C31309734CC852A1E053B11FA8C0828D', '/pmkpi/workevaluate/task/edit', 'V_PERF_T_WORKEVALUATETASK', 'd', '开始时间', 'STARTDATE', 1, null, 1, null, 4, null, null, 'pmkpi', 1, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('C31309734CC952A1E053B11FA8C0828D', '/pmkpi/workevaluate/task/edit', 'V_PERF_T_WORKEVALUATETASK', 'd', '结束时间', 'ENDDATE', 1, null, 1, null, 5, null, null, 'pmkpi', 1, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('C3C0E32D46EAD2FFE053B11FA8C09CE8', '/pmkpi/workevaluate/task/edit', 'V_PERF_T_WORKEVALUATETASK', 's', 'GUID', 'GUID', 0, null, 1, null, 6, null, null, 'pmkpi', 1, null, '{}', 0, 0, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('C31309734CCA52A1E053B11FA8C0828D', '/pmkpi/workevaluate/task/edit', 'V_PERF_T_WORKEVALUATETASK', 's', '考核年度', 'TASKYEAR', 1, null, 1, null, 6, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('C31309734CCB52A1E053B11FA8C0828D', '/pmkpi/workevaluate/task/edit', 'V_PERF_T_WORKEVALUATETASK', 's', '联系人', 'LINKMAN', 1, null, 1, null, 7, null, null, 'pmkpi', 1, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('C31309734CCC52A1E053B11FA8C0828D', '/pmkpi/workevaluate/task/edit', 'V_PERF_T_WORKEVALUATETASK', 's', '联系方式', 'TEL', 1, null, 0, null, 8, null, null, 'pmkpi', 1, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('C31309734CCD52A1E053B11FA8C0828D', '/pmkpi/workevaluate/task/edit', 'V_PERF_T_WORKEVALUATETASK', 'textarea', '备注', 'REMARK', 1, null, 0, null, 9, 3, '3', 'pmkpi', 1, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('C31309734CCE52A1E053B11FA8C0828D', '/pmkpi/workevaluate/task/edit', 'V_PERF_T_WORKEVALUATETASK', 'i', '是否删除', 'IS_DELETED', 0, null, 0, null, 11, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('C31309734CCF52A1E053B11FA8C0828D', '/pmkpi/workevaluate/task/edit', 'V_PERF_T_WORKEVALUATETASK', 's', '主建', 'GUID', 0, null, 1, null, 12, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('C31309734CD052A1E053B11FA8C0828D', '/pmkpi/workevaluate/task/edit', 'V_PERF_T_WORKEVALUATETASK', 's', '年度', 'FISCAL_YEAR', 0, null, 0, null, 13, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('C31309734CD152A1E053B11FA8C0828D', '/pmkpi/workevaluate/task/edit', 'V_PERF_T_WORKEVALUATETASK', 's', '修改时间', 'UPDATE_TIME', 0, null, 0, null, 14, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('C31309734CD252A1E053B11FA8C0828D', '/pmkpi/workevaluate/task/edit', 'V_PERF_T_WORKEVALUATETASK', 'i', '状态', 'STATUS', 0, null, 0, null, 15, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('C31309734CD352A1E053B11FA8C0828D', '/pmkpi/workevaluate/task/edit', 'V_PERF_T_WORKEVALUATETASK', 's', '区划', 'MOF_DIV_CODE', 0, null, 0, null, 16, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('C31309734CD452A1E053B11FA8C0828D', '/pmkpi/workevaluate/task/edit', 'V_PERF_T_WORKEVALUATETASK', 's', '单位', 'AGENCYGUID', 0, null, 0, null, 17, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('C31309734CD552A1E053B11FA8C0828D', '/pmkpi/workevaluate/task/edit', 'V_PERF_T_WORKEVALUATETASK', 's', '单位', 'AGENCY_CODE', 0, null, 0, null, 18, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('C31309734CD652A1E053B11FA8C0828D', '/pmkpi/workevaluate/task/edit', 'V_PERF_T_WORKEVALUATETASK', 's', '创建人', 'CREATER', 0, null, 0, null, 19, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('C31309734CD752A1E053B11FA8C0828D', '/pmkpi/workevaluate/task/edit', 'V_PERF_T_WORKEVALUATETASK', 's', '创建时间', 'CREATE_TIME', 0, null, 0, null, 20, null, null, 'pmkpi', 0, null, '{}', null, null, null);
