begin

DELETE FROM bus_T_diccolumn t where t.tablecode='PERF_T_AUDITMAIN' and t.columncode in ('FOPINION','PROGUID','SOPINION');
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FOPINION', '1', '2016', '87', 'B9C7D80EC0358933E053B11FA8C0A5D6', 'FOPINION', 'PERF_T_AUDITMAIN', '初审意见', 'S', '4000', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROGUID', '1', '2016', '87', 'B9C7D80EC0348933E053B11FA8C0A5D6', 'PROGUID', 'PERF_T_AUDITMAIN', '项目guid', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SOPINION', '1', '2016', '87', 'B9C7D80EC0368933E053B11FA8C0A5D6', 'SOPINION', 'PERF_T_AUDITMAIN', '复审意见', 'S', '4000', null, 1, 0, null, sysdate);


DELETE FROM bus_T_diccolumn t where t.tablecode='PERF_T_AUDITITEMS' and t.columncode in ('FREVIEW','PROGUID','SREVIEW');
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'REVIEW', null, '1', 'FREVIEW', '1', '2016', '87', 'B9C7D80EC0388933E053B11FA8C0A5D6', 'FREVIEW', 'PERF_T_AUDITITEMS', '初审意见', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROGUID', '1', '2016', '87', 'B9C7D80EC0378933E053B11FA8C0A5D6', 'PROGUID', 'PERF_T_AUDITITEMS', '项目guid', 'S', '40', null, 1, 0, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'REVIEW', null, '1', 'SREVIEW', '1', '2016', '87', 'B9C7D80EC0398933E053B11FA8C0A5D6', 'SREVIEW', 'PERF_T_AUDITITEMS', '复审意见', 'S', '40', null, 1, 0, null, sysdate);


DELETE FROM bus_T_dictable t where t.tablecode='PERF_T_REVIEW';
insert into bus_T_dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2019', '87', 'PERF_T_REVIEW', '评审表', null, 2, 1, 'PERF_T_REVIEW', 'pmkpi', null, null, 1, null, 1, 1, 'PERF_T_REVIEW', sysdate, null, null, null, '1');


DELETE FROM bus_T_diccolumn t where t.tablecode='PERF_T_REVIEW';
insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '0', 'AGENCYGUID', '1', '2020', '87', 'B9B81E5FA602B10BE053B11FA8C02292', 'AGENCYGUID', 'PERF_T_REVIEW', '单位', 'S', '40', null, null, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AUDITOR', '1', '2020', '87', 'B9B81E5FA603B10BE053B11FA8C02292', 'AUDITOR', 'PERF_T_REVIEW', '审核人', 'S', '40', null, null, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CONCLUSION', '1', '2020', '87', 'B9B81E5FA601B10BE053B11FA8C02292', 'CONCLUSION', 'PERF_T_REVIEW', '结论', 'S', '50', null, null, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'creater0001', null, '0', 'CREATER', '1', '2020', '87', 'B9B81E5FA606B10BE053B11FA8C02292', 'CREATER', 'PERF_T_REVIEW', '创建人', 'S', '40', null, null, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'CREATETIME', '1', '2020', '87', 'B9B81E5FA607B10BE053B11FA8C02292', 'CREATETIME', 'PERF_T_REVIEW', '创建时间', 'S', '20', null, null, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'EXPERT', '1', '2020', '87', 'B9B84806675DB66CE053B11FA8C03C2F', 'EXPERT', 'PERF_T_REVIEW', '专家', 'S', '40', null, null, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '96B5961EBFF244559FD06E940FB7324A', null, '0', 'FININTORGGUID', '1', '2020', '87', 'B9B81E5FA608B10BE053B11FA8C02292', 'FININTORGGUID', 'PERF_T_REVIEW', '管理处室', 'S', '50', null, null, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2020', '87', 'B9B81E5FA609B10BE053B11FA8C02292', 'GUID', 'PERF_T_REVIEW', 'GUID', 'S', '32', null, null, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'INSTITUTION', '1', '2020', '87', 'B9B84806675EB66CE053B11FA8C03C2F', 'INSTITUTION', 'PERF_T_REVIEW', '机构', 'S', '40', null, null, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ISCONFIRM', '1', '2020', '87', 'B9B81E5FA613B1034FA8C02292343121', 'ISCONFIRM', 'PERF_T_REVIEW', '是否确认评审', 'N', '1', null, null, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'ISLAST', '1', '2020', '87', 'B9B81E5FA60AB10BE053B11FA8C02292', 'ISLAST', 'PERF_T_REVIEW', '是否最后一次调整', 'N', '1', null, null, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'ISRECHECK', '1', '2020', '87', 'B9B81E5FA604B10BE053B11FA8C02292', 'ISRECHECK', 'PERF_T_REVIEW', '是否复审', 'S', '40', 2, null, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LASTUPDATETIME', '1', '2020', '87', 'B9B81E5FA60BB10BE053B11FA8C02292', 'LASTUPDATETIME', 'PERF_T_REVIEW', '最后操作时间', 'S', '20', null, null, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PROGUID', '1', '2020', '87', 'B9B81E5FA60DB10BE053B11FA8C02292', 'PROGUID', 'PERF_T_REVIEW', '项目guid', 'S', '40', null, null, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2020', '87', 'B9B81E5FA60EB10BE053B11FA8C02292', 'PROVINCE', 'PERF_T_REVIEW', '区划', 'S', '9', null, null, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'REVIEWNUM', '1', '2020', '87', 'B9C7D80EC03E8933E053B11FA8C0A5D6', 'REVIEWNUM', 'PERF_T_REVIEW', '评审次数', 'S', '10', null, null, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'STATUS', '1', '2020', '87', 'B9B81E5FA60FB10BE053B11FA8C02292', 'STATUS', 'PERF_T_REVIEW', '状态', 'N', '3', null, null, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'TYPE', '1', '2020', '87', 'B9B81E5FA605B10BE053B11FA8C02292', 'TYPE', 'PERF_T_REVIEW', '评审类型', 'S', '40', null, null, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'UPDATETIME', '1', '2020', '87', 'B9B81E5FA610B10BE053B11FA8C02292', 'UPDATETIME', 'PERF_T_REVIEW', '创建时间', 'S', '20', null, null, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'WFID', '1', '2020', '87', 'B9B81E5FA611B10BE053B11FA8C02292', 'WFID', 'PERF_T_REVIEW', '工作流guid', 'S', '40', null, null, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIWFSTATUS', null, '0', 'WFSTATUS', '1', '2020', '87', 'B9B81E5FA612B10BE053B11FA8C02292', 'WFSTATUS', 'PERF_T_REVIEW', '工作流状态', 'S', '100', null, null, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2020', '87', 'B9B81E5FA613B10BE053B11FA8C02292', 'YEAR', 'PERF_T_REVIEW', '年度', 'S', '4', null, null, 1, null, sysdate);


DELETE FROM bus_T_dictable t where t.tablecode='PERF_EXPERTREVIEW';
insert into bus_T_dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2016', '87', 'PERF_EXPERTREVIEW', '专家评审关联表', '专家评审关联表', 2, 1, 'PERF_EXPERTREVIEW', 'pmkpi', null, '0', 1, '0', 0, 1, 'V_PERF_EXPERTREVIEW', null, 1, 1, null, '1');


DELETE FROM bus_T_diccolumn t where t.tablecode='PERF_EXPERTREVIEW';
insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CODE', '1', '2016', '87', 'B9EE4152C835535BE053B11FA8C083B2', 'CODE', 'PERF_EXPERTREVIEW', '机构编码', 'S', '100', null, 1, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATER', '1', '2016', '87', 'B9EE4152C836535BE053B11FA8C083B2', 'CREATER', 'PERF_EXPERTREVIEW', '创建人', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATETIME', '1', '2016', '87', 'B9EE4152C837535BE053B11FA8C083B2', 'CREATETIME', 'PERF_EXPERTREVIEW', '创建时间', 'S', '17', null, 1, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EXPERTGUID', '1', '2016', '87', 'B9EE4152C841535BE053B11FA8C083B2', 'EXPERTGUID', 'PERF_EXPERTREVIEW', '专家guid', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2016', '87', 'B9EE4152C838535BE053B11FA8C083B2', 'GUID', 'PERF_EXPERTREVIEW', '主键', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MAINGUID', '1', '2016', '87', 'B9EE4152C840535BE053B11FA8C083B2', 'MAINGUID', 'PERF_EXPERTREVIEW', '评审guid', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'NAME', '1', '2016', '87', 'B9EE4152C839535BE053B11FA8C083B2', 'NAME', 'PERF_EXPERTREVIEW', '机构名称', 'S', '200', null, 1, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ORDERNUM', '1', '2016', '87', 'B9EE4152C83E535BE053B11FA8C083B2', 'ORDERNUM', 'PERF_EXPERTREVIEW', '排序', 'N', '9', null, 1, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROGUID', '1', '2016', '87', 'B9EE4152C83F535BE053B11FA8C083B2', 'PROGUID', 'PERF_EXPERTREVIEW', '项目guid', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2016', '87', 'B9EE4152C83A535BE053B11FA8C083B2', 'PROVINCE', 'PERF_EXPERTREVIEW', '区划', 'S', '9', null, 1, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'STATUS', '1', '2016', '87', 'B9EE4152C83B535BE053B11FA8C083B2', 'STATUS', 'PERF_EXPERTREVIEW', '状态', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UPDATETIME', '1', '2016', '87', 'B9EE4152C83C535BE053B11FA8C083B2', 'UPDATETIME', 'PERF_EXPERTREVIEW', '更新时间', 'S', '17', null, 1, 1, null, sysdate);

insert into bus_T_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2016', '87', 'B9EE4152C83D535BE053B11FA8C083B2', 'YEAR', 'PERF_EXPERTREVIEW', '年度', 'N', '4', null, 1, 1, null, sysdate);


DELETE FROM bus_t_dictable  t where t.tablecode='V_PERF_EXPERTREVIEW';
insert into bus_t_dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2016', '87', 'V_PERF_EXPERTREVIEW', '委托专家视图', '委托专家视图', 2, 1, 'V_PERF_EXPERTREVIEW', 'pmkpi', null, '0', 1, '0', 0, 1, 'V_PERF_EXPERTREVIEW', null, 1, 1, null, '1');


DELETE FROM bus_t_diccolumn  t where t.tablecode='V_PERF_EXPERTREVIEW';
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ADDRESS', '1', '2016', '87', 'BA83B6C796C2EED8E053B11FA8C04F1D', 'ADDRESS', 'V_PERF_EXPERTREVIEW', '机构地址', 'S', '1000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BIRTH', '1', '2016', '87', 'BA83B6C796C3EED8E053B11FA8C04F1D', 'BIRTH', 'V_PERF_EXPERTREVIEW', '出生日期', 'S', '17', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'CATEGORY', null, '1', 'CATEGORY', '1', '2016', '87', 'BA83B6C796C4EED8E053B11FA8C04F1D', 'CATEGORY', 'V_PERF_EXPERTREVIEW', '专家类别', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CATEGORY01', '1', '2016', '87', 'BA83B6C796C5EED8E053B11FA8C04F1D', 'CATEGORY01', 'V_PERF_EXPERTREVIEW', '行业门类', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CATEGORY02', '1', '2016', '87', 'BA83B6C796C6EED8E053B11FA8C04F1D', 'CATEGORY02', 'V_PERF_EXPERTREVIEW', '行业大类', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CATEGORY03', '1', '2016', '87', 'BA83B6C796C7EED8E053B11FA8C04F1D', 'CATEGORY03', 'V_PERF_EXPERTREVIEW', '行业小类', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CERTIFICATE', '1', '2016', '87', 'BA83B6C796C8EED8E053B11FA8C04F1D', 'CERTIFICATE', 'V_PERF_EXPERTREVIEW', '注册执业资格', 'S', '400', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CODE', '1', '2016', '87', 'BA83B6C796C9EED8E053B11FA8C04F1D', 'CODE', 'V_PERF_EXPERTREVIEW', '机构编码', 'S', '100', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATER', '1', '2016', '87', 'BA83B6C796CAEED8E053B11FA8C04F1D', 'CREATER', 'V_PERF_EXPERTREVIEW', '创建人', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATETIME', '1', '2016', '87', 'BA83B6C796CBEED8E053B11FA8C04F1D', 'CREATETIME', 'V_PERF_EXPERTREVIEW', '创建时间', 'S', '17', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'CREDITNO', null, '1', 'CREDITNO', '1', '2016', '87', 'BA83B6C796CCEED8E053B11FA8C04F1D', 'CREDITNO', 'V_PERF_EXPERTREVIEW', '信用等级', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'EDUCATION', null, '1', 'EDUCATION', '1', '2016', '87', 'BA83B6C796CDEED8E053B11FA8C04F1D', 'EDUCATION', 'V_PERF_EXPERTREVIEW', '学历', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EMAIL', '1', '2016', '87', 'BA83B6C796CEEED8E053B11FA8C04F1D', 'EMAIL', 'V_PERF_EXPERTREVIEW', '电子邮箱', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EMPLOYDATA', '1', '2016', '87', 'BA83B6C796CFEED8E053B11FA8C04F1D', 'EMPLOYDATA', 'V_PERF_EXPERTREVIEW', '评聘时间', 'S', '17', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EVALUATENUM', '1', '2016', '87', 'BA83B6C796D0EED8E053B11FA8C04F1D', 'EVALUATENUM', 'V_PERF_EXPERTREVIEW', '评价累计数', 'N', '4', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EXPERTGUID', '1', '2016', '87', 'BA83B6C796EDEED8E053B11FA8C04F1D', 'EXPERTGUID', 'V_PERF_EXPERTREVIEW', '专家guid', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GRADUATE', '1', '2016', '87', 'BA83B6C796D1EED8E053B11FA8C04F1D', 'GRADUATE', 'V_PERF_EXPERTREVIEW', '毕业院校', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2016', '87', 'BA83B6C796D2EED8E053B11FA8C04F1D', 'GUID', 'V_PERF_EXPERTREVIEW', '主键', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IDCARD', '1', '2016', '87', 'BA83B6C796D3EED8E053B11FA8C04F1D', 'IDCARD', 'V_PERF_EXPERTREVIEW', '身份证号码', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'INSTITUTIONS', '1', '2016', '87', 'BA83B6C796D4EED8E053B11FA8C04F1D', 'INSTITUTIONS', 'V_PERF_EXPERTREVIEW', '所属机构', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'ISGROUP', null, '1', 'ISGROUP', '1', '2016', '87', 'BA83B6C796EAEED8E053B11FA8C04F1D', 'ISGROUP', 'V_PERF_EXPERTREVIEW', '是否组长', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LOGINCODE', '1', '2016', '87', 'BA83B6C796D5EED8E053B11FA8C04F1D', 'LOGINCODE', 'V_PERF_EXPERTREVIEW', '登录账号', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MAINGUID', '1', '2016', '87', 'BA83B6C796EBEED8E053B11FA8C04F1D', 'MAINGUID', 'V_PERF_EXPERTREVIEW', '评审guid', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'NAME', '1', '2016', '87', 'BA83B6C796D6EED8E053B11FA8C04F1D', 'NAME', 'V_PERF_EXPERTREVIEW', '机构名称', 'S', '200', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'NATION', null, '1', 'NATION', '1', '2016', '87', 'BA83B6C796D7EED8E053B11FA8C04F1D', 'NATION', 'V_PERF_EXPERTREVIEW', '民族', 'S', '100', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'OPINION', '1', '2016', '87', 'BA83B6C796D8EED8E053B11FA8C04F1D', 'OPINION', 'V_PERF_EXPERTREVIEW', '意见', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ORDERNUM', '1', '2016', '87', 'BA83B6C796D9EED8E053B11FA8C04F1D', 'ORDERNUM', 'V_PERF_EXPERTREVIEW', '排序', 'N', '9', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERFPRO', '1', '2016', '87', 'BA83B6C796DAEED8E053B11FA8C04F1D', 'PERFPRO', 'V_PERF_EXPERTREVIEW', '绩效评价项目', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PHONE', '1', '2016', '87', 'BA83B6C796DBEED8E053B11FA8C04F1D', 'PHONE', 'V_PERF_EXPERTREVIEW', '移动电话', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'POLITICAL', null, '1', 'POLITICAL', '1', '2016', '87', 'BA83B6C796DCEED8E053B11FA8C04F1D', 'POLITICAL', 'V_PERF_EXPERTREVIEW', '政治面貌', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PROFESSIONAL', null, '1', 'PROFESSIONAL', '1', '2016', '87', 'BA83B6C796DDEED8E053B11FA8C04F1D', 'PROFESSIONAL', 'V_PERF_EXPERTREVIEW', '专业技术职称', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROGUID', '1', '2016', '87', 'BA83B6C796ECEED8E053B11FA8C04F1D', 'PROGUID', 'V_PERF_EXPERTREVIEW', '项目guid', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2016', '87', 'BA83B6C796DEEED8E053B11FA8C04F1D', 'PROVINCE', 'V_PERF_EXPERTREVIEW', '区划', 'S', '9', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'RECOMMENDER', '1', '2016', '87', 'BA83B6C796DFEED8E053B11FA8C04F1D', 'RECOMMENDER', 'V_PERF_EXPERTREVIEW', '推荐方式', 'S', '100', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'REGION', '1', '2016', '87', 'BA83B6C796E0EED8E053B11FA8C04F1D', 'REGION', 'V_PERF_EXPERTREVIEW', '专家地域', 'S', '400', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SEX', '1', '2016', '87', 'BA83B6C796E1EED8E053B11FA8C04F1D', 'SEX', 'V_PERF_EXPERTREVIEW', '性别', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SPECIALTY', '1', '2016', '87', 'BA83B6C796E2EED8E053B11FA8C04F1D', 'SPECIALTY', 'V_PERF_EXPERTREVIEW', '专业特长', 'S', '400', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'STATUS', '1', '2016', '87', 'BA83B6C796E3EED8E053B11FA8C04F1D', 'STATUS', 'V_PERF_EXPERTREVIEW', '状态', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TEL', '1', '2016', '87', 'BA83B6C796E4EED8E053B11FA8C04F1D', 'TEL', 'V_PERF_EXPERTREVIEW', '固定电话', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TREATISE', '1', '2016', '87', 'BA83B6C796E5EED8E053B11FA8C04F1D', 'TREATISE', 'V_PERF_EXPERTREVIEW', '个人著论', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UPDATETIME', '1', '2016', '87', 'BA83B6C796E6EED8E053B11FA8C04F1D', 'UPDATETIME', 'V_PERF_EXPERTREVIEW', '更新时间', 'S', '17', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'WORKEXPERIE', null, '1', 'WORKEXPERIE', '1', '2016', '87', 'BA83B6C796E7EED8E053B11FA8C04F1D', 'WORKEXPERIE', 'V_PERF_EXPERTREVIEW', '工作经验', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WORKPLACE', '1', '2016', '87', 'BA83B6C796E8EED8E053B11FA8C04F1D', 'WORKPLACE', 'V_PERF_EXPERTREVIEW', '工作单位', 'S', '200', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2016', '87', 'BA83B6C796E9EED8E053B11FA8C04F1D', 'YEAR', 'V_PERF_EXPERTREVIEW', '年度', 'N', '4', null, 1, 1, null, sysdate);


DELETE FROM Bus_t_Dictable t where t.tablecode='V_PERF_DEPT_INFOREVIEW';
insert into Bus_t_Dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2016', '87', 'V_PERF_DEPT_INFOREVIEW', '评审视图（部门）', '评审视图', 2, 1, 'V_PERF_DEPT_INFOREVIEW', 'pmkpi', null, '0', 1, '0', 0, 1, 'V_PERF_DEPT_INFOREVIEW', sysdate, 1, 1, null, '1');

DELETE FROM Bus_t_Dictable t where t.tablecode='V_PERF_PRO_INFOREVIEW';
insert into Bus_t_Dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2016', '87', 'V_PERF_PRO_INFOREVIEW', '评审视图（项目）', '评审视图', 2, 1, 'V_PERF_PRO_INFOREVIEW', 'pmkpi', null, '0', 1, '0', 0, 1, 'V_PERF_PRO_INFOREVIEW', sysdate, 1, 1, null, '1');


DELETE FROM Bus_t_Diccolumn t where t.tablecode='V_PERF_DEPT_INFOREVIEW';
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'ISCONFIRM', '1', '2020', '87', 'BC8DF02C1F1BF3B8E053B11FA8C0D3A1', 'ISCONFIRM', 'V_PERF_DEPT_INFOREVIEW', '是否确认评审', 'N', '1', null, null, 1, null, sysdate);

DELETE FROM Bus_t_Diccolumn t where t.tablecode='V_PERF_PRO_INFOREVIEW';
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '1', 'AGENCYGUID', '1', null, null, 'BA932027FEF1C453E053B11FA8C0D531', 'AGENCYGUID', 'V_PERF_PRO_INFOREVIEW', '单位信息', 'S', '32', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values ('DE03002', 'VD00010', null, '0', 'AGENCY_CODE', '1', null, null, 'BA932027FEF2C453E053B11FA8C0D531', 'AGENCY_CODE', 'V_PERF_PRO_INFOREVIEW', '单位代码', 'S', '21', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'AUDITOR', '1', null, null, 'BA932027FEF3C453E053B11FA8C0D531', 'AUDITOR', 'V_PERF_PRO_INFOREVIEW', '审核人', 'S', '32', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '61006100UEw5VQ8y', null, '0', 'CREATER', '1', null, null, 'BA932027FEF4C453E053B11FA8C0D531', 'CREATER', 'V_PERF_PRO_INFOREVIEW', '建单人', 'S', '32', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'CREATE_TIME', '1', null, null, 'BA932027FEF5C453E053B11FA8C0D531', 'CREATE_TIME', 'V_PERF_PRO_INFOREVIEW', '创建时间', 'S', '14', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '0', 'DEPT_CODE', '1', null, null, 'BA932027FEF6C453E053B11FA8C0D531', 'DEPT_CODE', 'V_PERF_PRO_INFOREVIEW', '部门代码', 'S', '21', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '099003', null, '1', 'FININTORGGUID', '1', null, null, 'BA932027FEF7C453E053B11FA8C0D531', 'FININTORGGUID', 'V_PERF_PRO_INFOREVIEW', '财政处室', 'S', '32', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'ISCONFIRM', '1', '2020', '87', 'BC62D8F43E64669FE053B11FA8C02438', 'ISCONFIRM', 'V_PERF_PRO_INFOREVIEW', '是否确认评审', 'N', '1', null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values ('092004', '099076', null, '0', 'WFSTATUS', '1', null, null, 'BA932027FEF8C453E053B11FA8C0D531', 'WFSTATUS', 'V_PERF_PRO_INFOREVIEW', '流程状态', 'S', '32', null, 1, 1, null, sysdate);
