begin 
  
DELETE FROM Bus_t_Dictable t where t.tablecode='PERF_T_EVALUATEAUDIT';
insert into Bus_t_Dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2019', '87', 'PERF_T_EVALUATEAUDIT', '事前绩效评估审核', null, 2, 1, 'PERF_T_EVALUATEAUDIT', 'pmkpi', null, null, 1, null, 1, 1, 'PERF_T_EVALUATEAUDIT', sysdate, null, null, null, '1');


DELETE FROM Bus_t_Diccolumn t where t.tablecode='PERF_T_EVALUATEAUDIT';
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '0', 'AGENCYGUID', '1', '2020', '87', 'BA47DC3CE65C6613E053B11FA8C036D3', 'AGENCYGUID', 'PERF_T_EVALUATEAUDIT', '单位', 'S', '40', null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'AUDITTYPE', null, '0', 'AUDITTYPE', '1', '2020', '87', 'BA47DC3CE6636613E053B11FA8C036D3', 'AUDITTYPE', 'PERF_T_EVALUATEAUDIT', '审核操作', 'S', '40', null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'creater0001', null, '0', 'CREATER', '1', '2020', '87', 'BA47DC3CE65D6613E053B11FA8C036D3', 'CREATER', 'PERF_T_EVALUATEAUDIT', '创建人', 'S', '40', null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'CREATETIME', '1', '2020', '87', 'BA47DC3CE6686613E053B11FA8C036D3', 'CREATETIME', 'PERF_T_EVALUATEAUDIT', '创建时间', 'S', '20', null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '96B5961EBFF244559FD06E940FB7324A', null, '0', 'FININTORGGUID', '1', '2020', '87', 'BA47DC3CE65E6613E053B11FA8C036D3', 'FININTORGGUID', 'PERF_T_EVALUATEAUDIT', '管理处室', 'S', '50', null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2020', '87', 'BA47DC3CE65F6613E053B11FA8C036D3', 'GUID', 'PERF_T_EVALUATEAUDIT', 'GUID', 'S', '32', null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'ISAUDIT', null, '1', 'ISAUDIT', '1', '2020', '87', 'BA47DC3CE6676613E053B11FA8C036D3', 'ISAUDIT', 'PERF_T_EVALUATEAUDIT', '是否第三方参与审核', 'S', '32', null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'OLDOPINION', null, '1', 'OLDOPINION', '1', '2020', '87', 'BA6A7366C646CC81E053B11FA8C0FE04', 'OLDOPINION', 'PERF_T_EVALUATEAUDIT', '历史意见', 'S', '4000', null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'OPINION', '1', '2020', '87', 'BA47DC3CE6666613E053B11FA8C036D3', 'OPINION', 'PERF_T_EVALUATEAUDIT', '审核意见', 'S', '4000', null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PROGUID', '1', '2020', '87', 'BA47DC3CE6606613E053B11FA8C036D3', 'PROGUID', 'PERF_T_EVALUATEAUDIT', '项目guid', 'S', '40', null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2020', '87', 'BA47DC3CE6616613E053B11FA8C036D3', 'PROVINCE', 'PERF_T_EVALUATEAUDIT', '区划', 'S', '9', null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'STATUS', '1', '2020', '87', 'BA47DC3CE6626613E053B11FA8C036D3', 'STATUS', 'PERF_T_EVALUATEAUDIT', '状态', 'N', '3', null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'UPDATETIME', '1', '2020', '87', 'BA47DC3CE6646613E053B11FA8C036D3', 'UPDATETIME', 'PERF_T_EVALUATEAUDIT', '更新时间', 'S', '20', null, null, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2020', '87', 'BA47DC3CE6656613E053B11FA8C036D3', 'YEAR', 'PERF_T_EVALUATEAUDIT', '年度', 'S', '4', null, null, 1, null, sysdate);
