begin

DELETE FROM bus_t_diccolumn t where t.tablecode='PERF_T_CASEMODELINDEX' and t.columncode='METERUNIT';
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'METERUNIT', '1', '2016', '87', 'BE422AD788C94AAB8AC054AF13112AEF', 'METERUNIT', 'PERF_T_CASEMODELINDEX', '计量单位', 'S', '100', null, 1, 1, null, sysdate);

DELETE FROM bus_t_diccolumn t where t.tablecode='PERF_T_DEPTINDICATOR' and t.columncode='METERUNIT';
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'METERUNIT', '1', '2016', '87', 'C57FC8471FC147D1A4AAEE20D95D9E1D', 'METERUNIT', 'PERF_T_DEPTINDICATOR', '计量单位', 'S', '100', null, 1, 1, null, sysdate);

DELETE FROM bus_t_diccolumn t where t.tablecode='BAS_PERF_INDICATOR' and t.columncode='METERUNIT';
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'METERUNIT', '1', '2016', '87', '3355CD7C6150449AB1F16C4511697744', 'METERUNIT', 'BAS_PERF_INDICATOR', '计量单位', 'S', '100', null, 1, 1, null, sysdate);


