begin

--调整挑选项目
delete from p#busfw_t_uicolumn t where key in('/pmkpi/program/report/list');
insert into busfw_t_uicolumn (GUID, KEY, COLUMNCODE, NAME, ORDERNUM, ISVISIABLE, ISEDIT, TOTALTAG, SHOWLEVEL, REQUIREMENT, COLTYPE, HEAD, FORMAT, DEFAULTVALUE, LEVELCONTROL, COLWIDTH, ISSOURCE, TYPE, CONFIG, BOTTOMCONTRL)
values ('program/report/listcolumn004', '/pmkpi/program/report/list', 'PRO_NAME', '项目名称', 2, 1, 0, null, null, null, 1, null, null, null, null, null, 0, 's', '{}', null);

insert into busfw_t_uicolumn (GUID, KEY, COLUMNCODE, NAME, ORDERNUM, ISVISIABLE, ISEDIT, TOTALTAG, SHOWLEVEL, REQUIREMENT, COLTYPE, HEAD, FORMAT, DEFAULTVALUE, LEVELCONTROL, COLWIDTH, ISSOURCE, TYPE, CONFIG, BOTTOMCONTRL)
values ('program/report/listcolumn003', '/pmkpi/program/report/list', 'MOF_DEP_CODE', '业务科室', 13, 1, 0, null, null, null, null, null, '#name', null, null, null, 1, 'tree', '{}', null);

insert into busfw_t_uicolumn (GUID, KEY, COLUMNCODE, NAME, ORDERNUM, ISVISIABLE, ISEDIT, TOTALTAG, SHOWLEVEL, REQUIREMENT, COLTYPE, HEAD, FORMAT, DEFAULTVALUE, LEVELCONTROL, COLWIDTH, ISSOURCE, TYPE, CONFIG, BOTTOMCONTRL)
values ('program/report/listcolumn006', '/pmkpi/program/report/list', 'CREATE_TIME', '填报时间', 9, 1, 0, null, null, null, 1, null, 'yyyy-MM-dd hh:mm:ss', null, null, null, 0, 'd', '{}', null);

insert into busfw_t_uicolumn (GUID, KEY, COLUMNCODE, NAME, ORDERNUM, ISVISIABLE, ISEDIT, TOTALTAG, SHOWLEVEL, REQUIREMENT, COLTYPE, HEAD, FORMAT, DEFAULTVALUE, LEVELCONTROL, COLWIDTH, ISSOURCE, TYPE, CONFIG, BOTTOMCONTRL)
values ('program/report/listcolumn001', '/pmkpi/program/report/list', 'AGENCYGUID', '预算单位', 3, 1, 0, null, null, null, null, null, '#code-#name', null, null, null, 1, 'tree', '{}', null);

insert into busfw_t_uicolumn (GUID, KEY, COLUMNCODE, NAME, ORDERNUM, ISVISIABLE, ISEDIT, TOTALTAG, SHOWLEVEL, REQUIREMENT, COLTYPE, HEAD, FORMAT, DEFAULTVALUE, LEVELCONTROL, COLWIDTH, ISSOURCE, TYPE, CONFIG, BOTTOMCONTRL)
values ('program/report/listcolumn008', '/pmkpi/program/report/list', 'WFSTATUS', '审核状态', 15, 1, 0, null, null, null, null, null, '#name', null, null, null, 1, 'tree', '{}', null);

insert into busfw_t_uicolumn (GUID, KEY, COLUMNCODE, NAME, ORDERNUM, ISVISIABLE, ISEDIT, TOTALTAG, SHOWLEVEL, REQUIREMENT, COLTYPE, HEAD, FORMAT, DEFAULTVALUE, LEVELCONTROL, COLWIDTH, ISSOURCE, TYPE, CONFIG, BOTTOMCONTRL)
values ('program/report/listcolumn009', '/pmkpi/program/report/list', 'WFID', '工作流id', 20, 0, 0, null, null, null, 1, null, null, null, null, null, 0, 's', '{}', null);

insert into busfw_t_uicolumn (GUID, KEY, COLUMNCODE, NAME, ORDERNUM, ISVISIABLE, ISEDIT, TOTALTAG, SHOWLEVEL, REQUIREMENT, COLTYPE, HEAD, FORMAT, DEFAULTVALUE, LEVELCONTROL, COLWIDTH, ISSOURCE, TYPE, CONFIG, BOTTOMCONTRL)
values ('program/report/listcolumn009', '/pmkpi/program/report/list', 'YEAR', '预算年份', 4, 1, 0, null, null, null, 1, null, null, null, null, null, 0, 's', '{}', null);

insert into busfw_t_uicolumn (GUID, KEY, COLUMNCODE, NAME, ORDERNUM, ISVISIABLE, ISEDIT, TOTALTAG, SHOWLEVEL, REQUIREMENT, COLTYPE, HEAD, FORMAT, DEFAULTVALUE, LEVELCONTROL, COLWIDTH, ISSOURCE, TYPE, CONFIG, BOTTOMCONTRL)
values ('program/report/listcolumn002', '/pmkpi/program/report/list', 'CREATER', '创建人', 14, 1, 0, null, null, null, null, null, '#name', null, null, null, 1, 'tree', '{}', null);

insert into busfw_t_uicolumn (GUID, KEY, COLUMNCODE, NAME, ORDERNUM, ISVISIABLE, ISEDIT, TOTALTAG, SHOWLEVEL, REQUIREMENT, COLTYPE, HEAD, FORMAT, DEFAULTVALUE, LEVELCONTROL, COLWIDTH, ISSOURCE, TYPE, CONFIG, BOTTOMCONTRL)
values ('program/report/listcolumn015', '/pmkpi/program/report/list', 'GUID', '主键', 15, 0, 0, null, null, null, null, null, null, null, null, null, 1, 's', '{}', null);

--项目基本信息
delete from p#busfw_t_uieditform t where key in('/pmkpi/program/report/edit');
insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42CC9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用21', 'V_COL21', 0, null, 0, null, 1310, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42CD9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用22', 'V_COL22', 0, null, 0, null, 1320, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42CE9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用23', 'V_COL23', 0, null, 0, null, 1330, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42CF9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用19', 'V_COL19', 0, null, 0, null, 1290, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42D09ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用2', 'V_COL2', 0, null, 0, null, 1120, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42D19ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用20', 'V_COL20', 0, null, 0, null, 1300, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42D29ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用27', 'V_COL27', 0, null, 0, null, 1370, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42D39ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用28', 'V_COL28', 0, null, 0, null, 1380, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42D49ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用29', 'V_COL29', 0, null, 0, null, 1390, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42D59ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用24', 'V_COL24', 0, null, 0, null, 1340, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42D69ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用25', 'V_COL25', 0, null, 0, null, 1350, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42D79ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用26', 'V_COL26', 0, null, 0, null, 1360, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42D89ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用18', 'V_COL18', 0, null, 0, null, 1280, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42D99ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用1', 'V_COL1', 0, null, 0, null, 1110, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42DA9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用10', 'V_COL10', 0, null, 0, null, 1200, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42DB9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用11', 'V_COL11', 0, null, 0, null, 1210, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42DC9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'i', '预算排序', 'ORDERNO4', 0, null, 0, null, 260, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42DD9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '版本号', 'VERSION', 0, null, 0, null, 795, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42DE9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'textarea', '版本说明', 'VERSION_NAME', 0, null, 0, null, 796, 3, '3', 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42DF9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用15', 'V_COL15', 0, null, 0, null, 1250, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42E09ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用16', 'V_COL16', 0, null, 0, null, 1260, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42E19ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用17', 'V_COL17', 0, null, 0, null, 1270, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42E29ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用12', 'V_COL12', 0, null, 0, null, 1220, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42E39ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用13', 'V_COL13', 0, null, 0, null, 1230, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42E49ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用14', 'V_COL14', 0, null, 0, null, 1240, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42E59ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用3', 'V_COL3', 0, null, 0, null, 1130, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42E69ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '项目阶段', 'PRO_PHASE', 0, null, 0, null, 460, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42E79ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '项目主键', 'PRO_ID', 0, null, 0, null, 470, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42E89ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '扶贫标识', 'QKSFBS', 0, null, 0, null, 2000, 0, '0', 'pmkpi', 0, 0, '{"format":"#code-#name"}', 0, 0, 0);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42E99ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '审核人', 'AUDITOR', 0, null, 0, null, 420, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42EA9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '时间戳', 'LASTUPDATETIME', 0, null, 0, null, 430, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42EB9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '项目级次', 'PRO_LEV', 0, null, 0, null, 450, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42EC9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '是否紧急项目', 'IS_URGENT', 0, null, 0, null, 50, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42ED9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '项目排序', 'PRO_GRADE', 0, null, 0, null, 220, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42EE9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '下级区划', 'SUB_MOF_DIV_CODE', 0, null, 0, null, 2040, 0, '0', 'pmkpi', 0, 0, '{"format":"#code-#name"}', 0, 0, 0);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42EF9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '补贴到人到企业', 'SUBSIDY', 0, null, 0, null, 2030, 0, '0', 'pmkpi', 0, 0, '{"format":"#code-#name"}', 0, 0, 0);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42F09ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '直达资金标识', 'DIRECTFUNDS', 0, null, 0, null, 2020, 0, '0', 'pmkpi', 0, 0, '{"format":"#code-#name"}', 0, 0, 0);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42F19ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '是否直达资金及其地方对应安排', 'ZDZJJQPT', 0, null, 0, null, 2010, 0, '0', 'pmkpi', 0, 0, '{"format":"#code-#name"}', 0, 0, 0);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42F29ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '设立年度', 'SETUP_YEAR', 0, null, 0, null, 180, null, null, 'pmkpi', 0, null, '{format:''#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42F39ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用6', 'V_COL6', 0, null, 0, null, 1160, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42F49ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用7', 'V_COL7', 0, null, 0, null, 1170, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42F59ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用8', 'V_COL8', 0, null, 0, null, 1180, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42F69ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用30', 'V_COL30', 0, null, 0, null, 1400, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42F79ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用4', 'V_COL4', 0, null, 0, null, 1140, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42F89ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用5', 'V_COL5', 0, null, 0, null, 1150, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42F99ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '建单人', 'CREATER', 0, null, 0, null, 360, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42FA9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '流程状态', 'WFSTATUS', 0, null, 0, null, 380, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42FB9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '凭证号', 'VCHTYPEID', 0, null, 0, null, 390, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42FC9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '备用9', 'V_COL9', 0, null, 0, null, 1190, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42FD9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '储备阶段', 'STORE_PHASE', 0, null, 0, null, 300, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42FE9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '创建时间', 'CREATE_TIME', 0, null, 0, null, 310, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC42FF9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'i', '单位排序', 'ORDERNO1', 0, null, 0, null, 220, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43009ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '是否终审', 'LASTAUDIT', 0, null, 0, null, 740, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43019ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '是否终止', 'IS_END', 0, null, 0, null, 750, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43029ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '部门审核意见', 'DEP_AUD_OPINION_CODE', 0, null, 0, null, 550, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43039ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '是否细化', 'IS_THIN', 0, null, 0, null, 730, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43049ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '项目代码', 'PRO_CODE', 0, null, 0, null, 120, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43059ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '一级项目主键', 'PRO_LEVONE_ID', 0, null, 0, null, 510, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43069ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '更新时间', 'UPDATE_TIME', 0, null, 0, null, 350, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43079ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '中期规划年度', 'MID_PLAN_YEAR', 0, null, 0, null, 530, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43089ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '是否填报采购', 'IS_GOVPUR', 0, null, 0, null, 700, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43099ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '是否待分项目', 'IS_WAIT_DIVIDE', 0, null, 0, null, 630, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC430A9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '是否对下项目', 'IS_TO_DOWN', 0, null, 0, null, 640, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC430B9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '是否拆分项目', 'IS_DIVIDE_PRO', 0, null, 0, null, 610, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC430C9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '是否代编', 'IS_OTHER_EDIT', 0, null, 0, null, 620, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC430D9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '是否删除', 'IS_DELETED', 0, null, 0, null, 680, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC430E9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '是否设置使用范围', 'IS_USESET', 0, null, 0, null, 690, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC430F9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '财政审核意见', 'MOF_AUD_OPINION_CODE', 0, null, 0, null, 570, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43109ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '是否纳入', 'IS_BGT', 0, null, 0, null, 670, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43119ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '支出功能分类科目', 'EXP_FUNC_CODE', 0, null, 0, null, 160, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43129ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'amt', '备用5', 'N_COL5', 0, null, 0, null, 1640, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43139ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'amt', '备用6', 'N_COL6', 0, null, 0, null, 1650, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43149ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'amt', '备用3', 'N_COL3', 0, null, 0, null, 1620, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43159ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'amt', '备用4', 'N_COL4', 0, null, 0, null, 1630, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43169ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'amt', '备用7', 'N_COL7', 0, null, 0, null, 1660, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43179ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'i', '处室排序', 'ORDERNO3', 0, null, 0, null, 224, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43189ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '业务主键', 'GUID', 0, null, 0, null, 480, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43199ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'amt', '备用8', 'N_COL8', 0, null, 0, null, 1670, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC431A9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'i', '部门排序', 'ORDERNO2', 0, null, 0, null, 222, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC431B9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'amt', '备用2', 'N_COL2', 0, null, 0, null, 1610, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC431C9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '部门', 'DEPT_CODE', 0, '1', 0, null, 133, null, null, 'pmkpi', 0, null, '{"format":"#code-#name"}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC431D9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '财政评审意见', 'PRO_BGTREVIEW', 0, null, 0, null, 190, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC431E9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '部门评审意见', 'PRO_DEPREVIEW', 0, null, 0, null, 180, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC431F9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '项目类别', 'PRO_CAT_CODE', 0, null, 0, null, 150, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43209ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'amt', '备用1', 'N_COL1', 0, null, 0, null, 1600, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43219ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '一级项目名称', 'PRO_LEVONE_NAME', 0, null, 0, null, 154, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43229ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '去向单位', 'TRAOBJ_AGENCY_CODE', 1, null, 0, null, 175, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43239ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '上级转移支付项目', 'CEN_TRA_PRO_CODE', 1, null, 0, null, 170, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43249ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '一级项目', 'PRO_LEVONE_CODE', 1, null, 0, null, 152, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, 1, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43259ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '职能职责', 'FUN_RES_CODE', 1, null, 0, null, 300, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43269ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '分配方式', 'DISTRI_TYPE_CODE', 1, null, 0, null, 280, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43279ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '支出项目类别', 'PROJECTKIND', 1, null, 0, null, 150, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', 1, 1, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43289ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '财政内部机构', 'MOF_DEP_CODE', 1, null, 0, null, 560, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43299ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '主管部门', 'MANAGE_DEPT_CODE', 1, '1', 0, null, 134, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC432A9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '单位', 'AGENCY_CODE', 1, null, 0, null, 132, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC432B9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'textarea', '项目概述', 'PRO_DESC', 1, null, 0, null, 800, 3, '3', 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC432C9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '项目名称', 'PRO_NAME', 1, null, 0, null, 110, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC432D9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '项目期限', 'PRO_TERM', 1, null, 0, null, 130, null, null, 'pmkpi', 0, null, '{format:''#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC432E9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '是否追踪', 'IS_TRACK', 1, null, 0, '{"value": "0", "text": "0-否"}', 760, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC432F9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '项目来源', 'PRO_SOURCE_CODE', 1, null, 0, null, 500, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43309ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'amt', '项目总额', 'PRO_TOTAL_AMT', 1, null, 0, null, 240, null, null, 'pmkpi', 0, null, '{dot:4}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43319ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'amt', '其中：社会投入资金', 'SCOI_INVEST_FUND', 1, null, 0, null, 250, null, null, 'pmkpi', 0, null, '{dot:4}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43329ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '主管处室', 'MANAGE_MOF_DEP_CODE', 1, null, 0, null, 140, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43339ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '起始时间', 'PRO_START_YEAR', 1, null, 0, null, 122, null, null, 'pmkpi', 0, null, '{format:''#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43349ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '负责人电话', 'LEADER_TEL', 1, null, 0, null, 320, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43359ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '是否基建项目', 'IS_CAPTIAL_CONS_PRO', 1, null, 0, '{"value": "2", "text": "否"}', 650, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43369ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '负责人姓名', 'LEADER_NAME', 1, null, 0, null, 340, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43379ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 's', '负责人手机', 'LEADER_PHONE', 1, null, 0, null, 330, null, null, 'pmkpi', 0, null, '{}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43389ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '是否填报附件', 'IS_ATTACH', 1, null, 0, '{"value": "1", "text": "1-是"}', 710, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC43399ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '是否填报绩效', 'IS_PERFORM', 1, null, 0, '{"value": "1", "text": "1-是"}', 720, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC433A9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '编报模板', 'DRAFT_TEMPLATE_CODE', 1, null, 0, null, 290, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, 1, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC433B9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '是否科研项目', 'IS_SCIENTIFIC', 1, null, 0, '{"value": "2", "text": "否"}', 660, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC433C9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '编报模板', 'DRAFT_TEMPLATE_CODE', 1, null, 0, null, 290, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, 1, null);

insert into busfw_t_uieditform (GUID, KEY, TABLECODE, TYPE, NAME, COLUMNCODE, ISVISIABLE, SHOWLEVEL, REQUIREMENT, DEFAULTVALUE, ORDERNUM, COLSPANNUM, TEXTAREAROWS, APPID, ISEDIT, LEVELCONTROL, CONFIG, FROMSOURCE, BOTTOMCONTRL, SETVALUE)
values ('BCB2D3DC433D9ECBE053470A050A6189', '/pmkpi/program/report/edit', 'V_PERF_PROJECT_INFO', 'tree', '是否科研项目', 'IS_SCIENTIFIC', 1, null, 0, '{"value": "2", "text": "否"}', 660, null, null, 'pmkpi', 0, null, '{format:''#code-#name''}', null, null, null);
