begin

delete from bus_t_diccolumn t where t.tablecode in('PERF_PROJECT_INFO');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ADJSTATUS', '1', null, null, 'BCB2D3DC43B59ECBE053470A050A6189', 'ADJSTATUS', 'PERF_PROJECT_INFO', '调整状态', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '1', 'AGENCYGUID', '1', null, null, 'BCB2D3DC43B69ECBE053470A050A6189', 'AGENCYGUID', 'PERF_PROJECT_INFO', '单位信息', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values ('DE03002', 'PDMAGENCYALL', null, '0', 'AGENCY_CODE', '1', null, null, 'BCB2D3DC43B79ECBE053470A050A6189', 'AGENCY_CODE', 'PERF_PROJECT_INFO', '单位代码', 'S', '21', null, 1, 0, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values ('092006', '61006100UEw5VQ8y', null, '0', 'AUDITOR', '1', null, null, 'BCB2D3DC43B89ECBE053470A050A6189', 'AUDITOR', 'PERF_PROJECT_INFO', '审核人', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMTRAIN', null, '0', 'CEN_TRA_PRO_CODE', '1', null, null, 'BCB2D3DC43B99ECBE053470A050A6189', 'CEN_TRA_PRO_CODE', 'PERF_PROJECT_INFO', '上级转移支付项目代码', 'S', '21', null, 1, 1, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'CREATER', '1', null, null, 'BCB2D3DC43BA9ECBE053470A050A6189', 'CREATER', 'PERF_PROJECT_INFO', '建单人', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'CREATE_TIME', '1', null, null, 'BCB2D3DC43BB9ECBE053470A050A6189', 'CREATE_TIME', 'PERF_PROJECT_INFO', '创建时间', 'S', '14', null, 1, 0, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '0', 'DEPT_CODE', '1', null, null, 'BCB2D3DC43BC9ECBE053470A050A6189', 'DEPT_CODE', 'PERF_PROJECT_INFO', '部门代码', 'S', '21', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD09004', null, '0', 'DEP_AUD_OPINION_CODE', '1', null, null, 'BCB2D3DC43BD9ECBE053470A050A6189', 'DEP_AUD_OPINION_CODE', 'PERF_PROJECT_INFO', '部门审核意见', 'S', '1', null, 1, 1, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMBLANK', null, '0', 'DIRECTFUNDS', '1', null, null, 'BCB2D3DC43BE9ECBE053470A050A6189', 'DIRECTFUNDS', 'PERF_PROJECT_INFO', '直达资金标识', 'S', '10', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD09002', null, '0', 'DISTRI_TYPE_CODE', '1', null, null, 'BCB2D3DC43BF9ECBE053470A050A6189', 'DISTRI_TYPE_CODE', 'PERF_PROJECT_INFO', '分配方式', 'S', '1', null, 1, 0, '1', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMDRAFTTEMPLATEDIC', null, '0', 'DRAFT_TEMPLATE_CODE', '1', null, null, 'BCB2D3DC43C09ECBE053470A050A6189', 'DRAFT_TEMPLATE_CODE', 'PERF_PROJECT_INFO', '编报模板代码', 'S', '32', null, 1, 1, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values ('DE05004', 'VD10004', null, '0', 'EXP_FUNC_CODE', '1', null, null, 'BCB2D3DC43C19ECBE053470A050A6189', 'EXP_FUNC_CODE', 'PERF_PROJECT_INFO', '支出功能分类科目代码', 'S', '7', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FININTORGGUID', '1', null, null, 'BCB2D3DC43C29ECBE053470A050A6189', 'FININTORGGUID', 'PERF_PROJECT_INFO', '财政处室', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FROMGUID', '1', null, null, 'BCB2D3DC43C39ECBE053470A050A6189', 'FROMGUID', 'PERF_PROJECT_INFO', '来源guid', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMFUNCRESP', null, '0', 'FUN_RES_CODE', '1', null, null, 'BCB2D3DC43C49ECBE053470A050A6189', 'FUN_RES_CODE', 'PERF_PROJECT_INFO', '职能职责代码', 'S', '6', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', null, null, 'BCB2D3DC43C59ECBE053470A050A6189', 'GUID', 'PERF_PROJECT_INFO', '业务主键', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ISHISTORY', '1', null, null, 'BCB2D3DC43C69ECBE053470A050A6189', 'ISHISTORY', 'PERF_PROJECT_INFO', '是否历史数据', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ISPUBLISH', '1', null, null, 'BCB2D3DC43C79ECBE053470A050A6189', 'ISPUBLISH', 'PERF_PROJECT_INFO', '是否发布', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'IS_ATTACH', '1', null, null, 'BCB2D3DC43C89ECBE053470A050A6189', 'IS_ATTACH', 'PERF_PROJECT_INFO', '是否填报附件', 'N', '22', null, 1, 0, '2', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'IS_BGT', '1', null, null, 'BCB2D3DC43C99ECBE053470A050A6189', 'IS_BGT', 'PERF_PROJECT_INFO', '是否纳入', 'N', '22', null, 1, 0, '2', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'IS_CAPTIAL_CONS_PRO', '1', null, null, 'BCB2D3DC43CA9ECBE053470A050A6189', 'IS_CAPTIAL_CONS_PRO', 'PERF_PROJECT_INFO', '是否基建项目', 'N', '1', null, 1, 0, '2', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'IS_DELETED', '1', null, null, 'BCB2D3DC43CB9ECBE053470A050A6189', 'IS_DELETED', 'PERF_PROJECT_INFO', '是否删除', 'N', '1', null, 1, 0, '2', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'IS_DIVIDE_PRO', '1', null, null, 'BCB2D3DC43CC9ECBE053470A050A6189', 'IS_DIVIDE_PRO', 'PERF_PROJECT_INFO', '是否收转支项目', 'N', '22', null, 1, 0, '2', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'IS_END', '1', null, null, 'BCB2D3DC43CD9ECBE053470A050A6189', 'IS_END', 'PERF_PROJECT_INFO', '是否终止', 'N', '1', null, 1, 0, '2', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'IS_FROMUP', '1', null, null, 'BCB2D3DC43CE9ECBE053470A050A6189', 'IS_FROMUP', 'PERF_PROJECT_INFO', '是否来源上级', 'N', '1', null, 1, 0, '2', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'IS_GOVPUR', '1', null, null, 'BCB2D3DC43CF9ECBE053470A050A6189', 'IS_GOVPUR', 'PERF_PROJECT_INFO', '是否填报采购', 'N', '22', null, 1, 0, '2', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'IS_OTHER_EDIT', '1', null, null, 'BCB2D3DC43D09ECBE053470A050A6189', 'IS_OTHER_EDIT', 'PERF_PROJECT_INFO', '是否代编', 'N', '22', null, 1, 0, '2', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'IS_PERFORM', '1', null, null, 'BCB2D3DC43D19ECBE053470A050A6189', 'IS_PERFORM', 'PERF_PROJECT_INFO', '是否填报绩效', 'N', '22', null, 1, 0, '2', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'IS_SCIENTIFIC', '1', null, null, 'BCB2D3DC43D29ECBE053470A050A6189', 'IS_SCIENTIFIC', 'PERF_PROJECT_INFO', '是否科研项目', 'N', '1', null, 1, 0, '2', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'IS_THIN', '1', null, null, 'BCB2D3DC43D39ECBE053470A050A6189', 'IS_THIN', 'PERF_PROJECT_INFO', '是否细化', 'N', '22', null, 1, 0, '2', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'IS_TO_DOWN', '1', null, null, 'BCB2D3DC43D49ECBE053470A050A6189', 'IS_TO_DOWN', 'PERF_PROJECT_INFO', '是否对下项目', 'N', '22', null, 1, 0, '2', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'IS_TRACK', '1', null, null, 'BCB2D3DC43D59ECBE053470A050A6189', 'IS_TRACK', 'PERF_PROJECT_INFO', '是否追踪', 'N', '1', null, 1, 1, '2', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'IS_URGENT', '1', null, null, 'BCB2D3DC43D69ECBE053470A050A6189', 'IS_URGENT', 'PERF_PROJECT_INFO', '是否紧急项目', 'N', '1', null, 1, 0, '2', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'IS_USESET', '1', null, null, 'BCB2D3DC43D79ECBE053470A050A6189', 'IS_USESET', 'PERF_PROJECT_INFO', '是否设置使用范围', 'N', '1', null, 1, 0, '2', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'IS_WAIT_DIVIDE', '1', null, null, 'BCB2D3DC43D89ECBE053470A050A6189', 'IS_WAIT_DIVIDE', 'PERF_PROJECT_INFO', '是否待安排项目', 'N', '22', null, 1, 0, '2', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'LASTAUDIT', '1', null, null, 'BCB2D3DC43D99ECBE053470A050A6189', 'LASTAUDIT', 'PERF_PROJECT_INFO', '是否终审', 'N', '22', null, 1, 0, '2', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LASTUPDATETIME', '1', null, null, 'BCB2D3DC43DA9ECBE053470A050A6189', 'LASTUPDATETIME', 'PERF_PROJECT_INFO', '时间戳', 'S', '17', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'LEADER_NAME', '1', null, null, 'BCB2D3DC43DB9ECBE053470A050A6189', 'LEADER_NAME', 'PERF_PROJECT_INFO', '负责人姓名', 'S', '100', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'LEADER_PHONE', '1', null, null, 'BCB2D3DC43DC9ECBE053470A050A6189', 'LEADER_PHONE', 'PERF_PROJECT_INFO', '负责人手机', 'S', '20', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'LEADER_TEL', '1', null, null, 'BCB2D3DC43DD9ECBE053470A050A6189', 'LEADER_TEL', 'PERF_PROJECT_INFO', '负责人电话', 'S', '20', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '0', 'MANAGE_DEPT_CODE', '1', null, null, 'BCB2D3DC43DE9ECBE053470A050A6189', 'MANAGE_DEPT_CODE', 'PERF_PROJECT_INFO', '主管部门代码', 'S', '21', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values ('DE03026', '099003', null, '0', 'MANAGE_MOF_DEP_CODE', '1', null, null, 'BCB2D3DC43DF9ECBE053470A050A6189', 'MANAGE_MOF_DEP_CODE', 'PERF_PROJECT_INFO', '主管处室代码', 'S', '6', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'MID_PLAN_YEAR', '1', null, null, 'BCB2D3DC43E09ECBE053470A050A6189', 'MID_PLAN_YEAR', 'PERF_PROJECT_INFO', '中期规划年度', 'S', '4', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD09005', null, '0', 'MOF_AUD_OPINION_CODE', '1', null, null, 'BCB2D3DC43E19ECBE053470A050A6189', 'MOF_AUD_OPINION_CODE', 'PERF_PROJECT_INFO', '财政审核意见', 'S', '1', null, 1, 1, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values ('DE03026', '099003', null, '0', 'MOF_DEP_CODE', '1', null, null, 'BCB2D3DC43E29ECBE053470A050A6189', 'MOF_DEP_CODE', 'PERF_PROJECT_INFO', '财政内部机构代码', 'S', '6', null, 1, 1, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD08001', null, '1', 'MOF_DIV_CODE', '1', null, null, 'BCB2D3DC43E39ECBE053470A050A6189', 'MOF_DIV_CODE', 'PERF_PROJECT_INFO', '财政区划代码', 'S', '9', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'N_COL1', '1', null, null, 'BCB2D3DC43E49ECBE053470A050A6189', 'N_COL1', 'PERF_PROJECT_INFO', '备用1', 'N', '22', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'N_COL2', '1', null, null, 'BCB2D3DC43E59ECBE053470A050A6189', 'N_COL2', 'PERF_PROJECT_INFO', '备用2', 'N', '22', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'N_COL3', '1', null, null, 'BCB2D3DC43E69ECBE053470A050A6189', 'N_COL3', 'PERF_PROJECT_INFO', '备用3', 'N', '22', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'N_COL4', '1', null, null, 'BCB2D3DC43E79ECBE053470A050A6189', 'N_COL4', 'PERF_PROJECT_INFO', '备用4', 'N', '22', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'N_COL5', '1', null, null, 'BCB2D3DC43E89ECBE053470A050A6189', 'N_COL5', 'PERF_PROJECT_INFO', '备用5', 'N', '22', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'N_COL6', '1', null, null, 'BCB2D3DC43E99ECBE053470A050A6189', 'N_COL6', 'PERF_PROJECT_INFO', '备用6', 'N', '22', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'N_COL7', '1', null, null, 'BCB2D3DC43EA9ECBE053470A050A6189', 'N_COL7', 'PERF_PROJECT_INFO', '备用7', 'N', '22', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'N_COL8', '1', null, null, 'BCB2D3DC43EB9ECBE053470A050A6189', 'N_COL8', 'PERF_PROJECT_INFO', '备用8', 'N', '22', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'ORDERNO1', '1', null, null, 'BCB2D3DC43EC9ECBE053470A050A6189', 'ORDERNO1', 'PERF_PROJECT_INFO', '单位排序', 'N', '22', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'ORDERNO2', '1', null, null, 'BCB2D3DC43ED9ECBE053470A050A6189', 'ORDERNO2', 'PERF_PROJECT_INFO', '部门排序', 'N', '22', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'ORDERNO3', '1', null, null, 'BCB2D3DC43EE9ECBE053470A050A6189', 'ORDERNO3', 'PERF_PROJECT_INFO', '处室排序', 'N', '22', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'ORDERNO4', '1', null, null, 'BCB2D3DC43EF9ECBE053470A050A6189', 'ORDERNO4', 'PERF_PROJECT_INFO', '预算排序', 'N', '22', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMPROJECTKINDEXTEND', null, '0', 'PROJECTKIND', '1', null, null, 'BCB2D3DC43F09ECBE053470A050A6189', 'PROJECTKIND', 'PERF_PROJECT_INFO', '支出项目类别', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_BGTREVIEW', '1', null, null, 'BCB2D3DC43F19ECBE053470A050A6189', 'PRO_BGTREVIEW', 'PERF_PROJECT_INFO', '财政评审意见', 'S', '2000', null, 1, 1, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMVD09001', null, '0', 'PRO_CAT_CODE', '1', null, null, 'BCB2D3DC43F29ECBE053470A050A6189', 'PRO_CAT_CODE', 'PERF_PROJECT_INFO', '项目类别', 'S', '2', null, 1, 0, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_CODE', '1', null, null, 'BCB2D3DC43F39ECBE053470A050A6189', 'PRO_CODE', 'PERF_PROJECT_INFO', '项目代码', 'S', '21', null, 1, 0, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_DEPREVIEW', '1', null, null, 'BCB2D3DC43F49ECBE053470A050A6189', 'PRO_DEPREVIEW', 'PERF_PROJECT_INFO', '部门评审意见', 'S', '2000', null, 1, 1, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_DESC', '1', null, null, 'BCB2D3DC43F59ECBE053470A050A6189', 'PRO_DESC', 'PERF_PROJECT_INFO', '项目概述', 'S', '300', null, 1, 1, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PROGRADE', null, '1', 'PRO_GRADE', '1', null, null, 'BCB2D3DC43F69ECBE053470A050A6189', 'PRO_GRADE', 'PERF_PROJECT_INFO', '项目排序', 'N', '9', null, 1, 0, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_ID', '1', null, null, 'BCB2D3DC43F79ECBE053470A050A6189', 'PRO_ID', 'PERF_PROJECT_INFO', '项目主键', 'S', '38', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_LEV', '1', null, null, 'BCB2D3DC43F89ECBE053470A050A6189', 'PRO_LEV', 'PERF_PROJECT_INFO', '项目级次', 'S', '2', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMDICPROJECTLEVONE', null, '0', 'PRO_LEVONE_CODE', '1', null, null, 'BCB2D3DC43F99ECBE053470A050A6189', 'PRO_LEVONE_CODE', 'PERF_PROJECT_INFO', '一级项目编码', 'S', '21', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_LEVONE_ID', '1', null, null, 'BCB2D3DC43FA9ECBE053470A050A6189', 'PRO_LEVONE_ID', 'PERF_PROJECT_INFO', '一级项目主键', 'S', '38', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_LEVONE_NAME', '1', null, null, 'BCB2D3DC43FB9ECBE053470A050A6189', 'PRO_LEVONE_NAME', 'PERF_PROJECT_INFO', '一级项目名称', 'S', '180', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_NAME', '1', null, null, 'BCB2D3DC43FC9ECBE053470A050A6189', 'PRO_NAME', 'PERF_PROJECT_INFO', '项目名称', 'S', '180', null, 1, 0, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PROPHASE', null, '0', 'PRO_PHASE', '1', null, null, 'BCB2D3DC43FD9ECBE053470A050A6189', 'PRO_PHASE', 'PERF_PROJECT_INFO', '是否年初项目', 'S', '2', null, 1, 0, '1', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD09007', null, '0', 'PRO_SOURCE_CODE', '1', null, null, 'BCB2D3DC43FE9ECBE053470A050A6189', 'PRO_SOURCE_CODE', 'PERF_PROJECT_INFO', '项目来源代码', 'S', '1', null, 1, 0, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMBDGYEAR', null, '0', 'PRO_START_YEAR', '1', null, null, 'BCB2D3DC43FF9ECBE053470A050A6189', 'PRO_START_YEAR', 'PERF_PROJECT_INFO', '起始时间', 'S', '4', null, 1, 0, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMPROTERM', null, '0', 'PRO_TERM', '1', null, null, 'BCB2D3DC44009ECBE053470A050A6189', 'PRO_TERM', 'PERF_PROJECT_INFO', '项目期限', 'S', '2', null, 1, 0, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_TOTAL_AMT', '1', null, null, 'BCB2D3DC44019ECBE053470A050A6189', 'PRO_TOTAL_AMT', 'PERF_PROJECT_INFO', '项目总额', 'N', '20', 2, 1, 1, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMTRASTATUS', null, '0', 'PRO_TRA_STATUS', '1', null, null, 'BCB2D3DC44029ECBE053470A050A6189', 'PRO_TRA_STATUS', 'PERF_PROJECT_INFO', '项目转移状态', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMBLANK', null, '0', 'QKSFBS', '1', null, null, 'BCB2D3DC44039ECBE053470A050A6189', 'QKSFBS', 'PERF_PROJECT_INFO', '扶贫标识', 'S', '10', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'SCOI_INVEST_FUND', '1', null, null, 'BCB2D3DC44049ECBE053470A050A6189', 'SCOI_INVEST_FUND', 'PERF_PROJECT_INFO', '其中：社会投入资金', 'N', '20', 2, 1, 1, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMBDGYEAR', null, '0', 'SETUP_YEAR', '1', null, null, 'BCB2D3DC44059ECBE053470A050A6189', 'SETUP_YEAR', 'PERF_PROJECT_INFO', '设立年度', 'S', '4', null, 1, 0, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'STORE_PHASE', '1', null, null, 'BCB2D3DC44069ECBE053470A050A6189', 'STORE_PHASE', 'PERF_PROJECT_INFO', '储备阶段', 'S', '2', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMBLANK', null, '0', 'SUBSIDY', '1', null, null, 'BCB2D3DC44079ECBE053470A050A6189', 'SUBSIDY', 'PERF_PROJECT_INFO', '是否补贴到人到企业', 'S', '10', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'SUB_AGENCY_NAME', '1', null, null, 'BCB2D3DC44089ECBE053470A050A6189', 'SUB_AGENCY_NAME', 'PERF_PROJECT_INFO', '下级单位名称', 's', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD08001', null, '0', 'SUB_MOF_DIV_CODE', '1', null, null, 'BCB2D3DC44099ECBE053470A050A6189', 'SUB_MOF_DIV_CODE', 'PERF_PROJECT_INFO', '下级区划编码', 'S', '10', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values ('DE03002', 'VD00010', null, '0', 'TRAOBJ_AGENCY_CODE', '1', null, null, 'BCB2D3DC440A9ECBE053470A050A6189', 'TRAOBJ_AGENCY_CODE', 'PERF_PROJECT_INFO', '去向单位代码', 'S', '21', null, 1, 1, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'UPDATE_TIME', '1', null, null, 'BCB2D3DC440B9ECBE053470A050A6189', 'UPDATE_TIME', 'PERF_PROJECT_INFO', '更新时间', 'S', '14', null, 1, 0, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMPAVOUCHER', null, '0', 'VCHTYPEID', '1', null, null, 'BCB2D3DC440C9ECBE053470A050A6189', 'VCHTYPEID', 'PERF_PROJECT_INFO', '凭证号', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'VERSION', '1', null, null, 'BCB2D3DC440D9ECBE053470A050A6189', 'VERSION', 'PERF_PROJECT_INFO', '版本号', 'S', '38', null, 1, 1, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'VERSION_NAME', '1', null, null, 'BCB2D3DC440E9ECBE053470A050A6189', 'VERSION_NAME', 'PERF_PROJECT_INFO', '版本说明', 'S', '400', null, 1, 1, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'V_COL1', '1', null, null, 'BCB2D3DC440F9ECBE053470A050A6189', 'V_COL1', 'PERF_PROJECT_INFO', '备用1', 'N', '300', null, 1, 0, '2', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMZDZXSX', null, '0', 'V_COL10', '1', null, null, 'BCB2D3DC44109ECBE053470A050A6189', 'V_COL10', 'PERF_PROJECT_INFO', '备用10', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMZDZXSX', null, '0', 'V_COL11', '1', null, null, 'BCB2D3DC44119ECBE053470A050A6189', 'V_COL11', 'PERF_PROJECT_INFO', '备用11', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMZC', null, '0', 'V_COL12', '1', null, null, 'BCB2D3DC44129ECBE053470A050A6189', 'V_COL12', 'PERF_PROJECT_INFO', '备用12', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMZCTK', null, '0', 'V_COL13', '1', null, null, 'BCB2D3DC44139ECBE053470A050A6189', 'V_COL13', 'PERF_PROJECT_INFO', '备用13', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMBDGYEAR', null, '0', 'V_COL14', '1', null, null, 'BCB2D3DC44149ECBE053470A050A6189', 'V_COL14', 'PERF_PROJECT_INFO', '备用14', 'N', '300', null, 1, 0, '2', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'V_COL15', '1', null, null, 'BCB2D3DC44159ECBE053470A050A6189', 'V_COL15', 'PERF_PROJECT_INFO', '备用15', 'N', '22', null, 1, 0, '2', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'V_COL16', '1', null, null, 'BCB2D3DC44169ECBE053470A050A6189', 'V_COL16', 'PERF_PROJECT_INFO', '备用16', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'V_COL17', '1', null, null, 'BCB2D3DC44179ECBE053470A050A6189', 'V_COL17', 'PERF_PROJECT_INFO', '备用17', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'V_COL18', '1', null, null, 'BCB2D3DC44189ECBE053470A050A6189', 'V_COL18', 'PERF_PROJECT_INFO', '备用18', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'V_COL19', '1', null, null, 'BCB2D3DC44199ECBE053470A050A6189', 'V_COL19', 'PERF_PROJECT_INFO', '备用19', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'EW75iBtj', null, '0', 'V_COL2', '1', null, null, 'BCB2D3DC441A9ECBE053470A050A6189', 'V_COL2', 'PERF_PROJECT_INFO', '备用2', 'N', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'V_COL20', '1', null, null, 'BCB2D3DC441B9ECBE053470A050A6189', 'V_COL20', 'PERF_PROJECT_INFO', '备用20', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'V_COL21', '1', null, null, 'BCB2D3DC441C9ECBE053470A050A6189', 'V_COL21', 'PERF_PROJECT_INFO', '备用21', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'V_COL22', '1', null, null, 'BCB2D3DC441D9ECBE053470A050A6189', 'V_COL22', 'PERF_PROJECT_INFO', '备用22', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'V_COL23', '1', null, null, 'BCB2D3DC441E9ECBE053470A050A6189', 'V_COL23', 'PERF_PROJECT_INFO', '备用23', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'V_COL24', '1', null, null, 'BCB2D3DC441F9ECBE053470A050A6189', 'V_COL24', 'PERF_PROJECT_INFO', '备用24', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'V_COL25', '1', null, null, 'BCB2D3DC44209ECBE053470A050A6189', 'V_COL25', 'PERF_PROJECT_INFO', '备用25', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'V_COL26', '1', null, null, 'BCB2D3DC44219ECBE053470A050A6189', 'V_COL26', 'PERF_PROJECT_INFO', '备用26', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'V_COL27', '1', null, null, 'BCB2D3DC44229ECBE053470A050A6189', 'V_COL27', 'PERF_PROJECT_INFO', '备用27', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'V_COL28', '1', null, null, 'BCB2D3DC44239ECBE053470A050A6189', 'V_COL28', 'PERF_PROJECT_INFO', '备用28', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'V_COL29', '1', null, null, 'BCB2D3DC44249ECBE053470A050A6189', 'V_COL29', 'PERF_PROJECT_INFO', '备用29', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'V_COL3', '1', null, null, 'BCB2D3DC44259ECBE053470A050A6189', 'V_COL3', 'PERF_PROJECT_INFO', '备用3', 'N', '300', null, 1, 0, '2', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'V_COL30', '1', null, null, 'BCB2D3DC44269ECBE053470A050A6189', 'V_COL30', 'PERF_PROJECT_INFO', '备用30', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'bdg002', null, '0', 'V_COL4', '1', null, null, 'BCB2D3DC44279ECBE053470A050A6189', 'V_COL4', 'PERF_PROJECT_INFO', '备用4', 'N', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'bdg003', null, '0', 'V_COL5', '1', null, null, 'BCB2D3DC44289ECBE053470A050A6189', 'V_COL5', 'PERF_PROJECT_INFO', '备用5', 'N', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'V_COL6', '1', null, null, 'BCB2D3DC44299ECBE053470A050A6189', 'V_COL6', 'PERF_PROJECT_INFO', '备用6', 'N', '300', null, 1, 0, '2', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '0', 'V_COL7', '1', null, null, 'BCB2D3DC442A9ECBE053470A050A6189', 'V_COL7', 'PERF_PROJECT_INFO', '备用7', 'N', '300', null, 1, 0, '2', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMZDZXSX', null, '0', 'V_COL8', '1', null, null, 'BCB2D3DC442B9ECBE053470A050A6189', 'V_COL8', 'PERF_PROJECT_INFO', '备用8', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMZDZXSX', null, '0', 'V_COL9', '1', null, null, 'BCB2D3DC442C9ECBE053470A050A6189', 'V_COL9', 'PERF_PROJECT_INFO', '备用9', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WFID', '1', null, null, 'BCB2D3DC442D9ECBE053470A050A6189', 'WFID', 'PERF_PROJECT_INFO', '流程编码', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values ('092004', '099076', null, '0', 'WFSTATUS', '1', null, null, 'BCB2D3DC442E9ECBE053470A050A6189', 'WFSTATUS', 'PERF_PROJECT_INFO', '流程状态', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PDMBLANK', null, '0', 'ZDZJJQPT', '1', null, null, 'BCB2D3DC442F9ECBE053470A050A6189', 'ZDZJJQPT', 'PERF_PROJECT_INFO', '是否直达资金及其地方对应安排', 'S', '10', null, 1, 1, null, sysdate);

