begin

delete from bus_t_diccolumn t where t.tablecode='V_PM_PERF_INDICATOR' and t.columncode in('AGENCY_CODE','YEARFLAG');

delete from CFS_LTABLE_FIELD t where t.table_name='PM_PERF_INDICATOR' and t.field_name IN('SUB_MOF_CODE','KPI_LV1','KPI_LV2','KPI_LV3');

delete from bus_t_diccolumn t where t.tablecode='PM_PERF_INDICATOR' and t.columncode in('SUB_MOF_CODE','KPI_LV1','KPI_LV2','KPI_LV3','AGENCY_NAME','BGT_ID','PRO_NAME','LV1_PERF_IND_CODE','LV1_PERF_IND_NAME','LV2_PERF_IND_CODE','LV2_PERF_IND_NAME','LV3_PERF_IND_CODE','LV3_PERF_IND_NAME','MOF_AUD_OPINION_CODE','MOF_DIV_NAME','ORI_DIV_CODE','ORI_DIV_NAME','PERF_OBJ_TYPE_CODE','PERF_OBJ_TYPE_NAME','SPE_PRO_CODE','SPE_PRO_NAME','SUB_MOF_DIV_CODE','SUB_MOF_DIV_NAME','MOF_AUD_OPINION_NAME','IS_LAST_INST','IS_BACKUP','VERSIONTYPE','IS_ADJ');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AGENCY_NAME', '1', '2016', '87', 'E8124E96C79F5BCEE0535064A8C0B0CC', 'AGENCY_NAME', 'PM_PERF_INDICATOR', '部门（单位）名称', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BGT_ID', '1', '2016', '87', 'E8124E96C7A05BCEE0535064A8C0B0CC', 'BGT_ID', 'PM_PERF_INDICATOR', '指标主键', 'S', '38', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIFRAME', null, '1', 'LV1_PERF_IND_CODE', '1', '2016', '87', 'E8124E96C7AD5BCEE0535064A8C0B0CC', 'LV1_PERF_IND_CODE', 'PM_PERF_INDICATOR', '一级绩效指标代码', 'S', '20', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LV1_PERF_IND_NAME', '1', '2016', '87', 'E8124E96C7B05BCEE0535064A8C0B0CC', 'LV1_PERF_IND_NAME', 'PM_PERF_INDICATOR', '一级绩效指标名称', 'S', '1000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIFRAME', null, '1', 'LV2_PERF_IND_CODE', '1', '2016', '87', 'E8124E96C7AE5BCEE0535064A8C0B0CC', 'LV2_PERF_IND_CODE', 'PM_PERF_INDICATOR', '二级绩效指标代码', 'S', '20', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LV2_PERF_IND_NAME', '1', '2016', '87', 'E8124E96C7B15BCEE0535064A8C0B0CC', 'LV2_PERF_IND_NAME', 'PM_PERF_INDICATOR', '二级绩效指标名称', 'S', '1000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LV3_PERF_IND_CODE', '1', '2016', '87', 'E8124E96C7AF5BCEE0535064A8C0B0CC', 'LV3_PERF_IND_CODE', 'PM_PERF_INDICATOR', '三级绩效指标代码', 'S', '20', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LV3_PERF_IND_NAME', '1', '2016', '87', 'E8124E96C7B25BCEE0535064A8C0B0CC', 'LV3_PERF_IND_NAME', 'PM_PERF_INDICATOR', '三级绩效指标名称', 'S', '1000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MOF_AUD_OPINION_CODE', '1', '2016', '87', 'E8124E96C7A15BCEE0535064A8C0B0CC', 'MOF_AUD_OPINION_CODE', 'PM_PERF_INDICATOR', '财政审核意见代码', 'S', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MOF_AUD_OPINION_NAME', '1', '2016', '87', 'FCCFD316AE3D3C1FE0533315A8C071B6', 'MOF_AUD_OPINION_NAME', 'PM_PERF_INDICATOR', '财政审核意见名称', 'S', '60', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MOF_DIV_NAME', '1', '2016', '87', 'E8124E96C7A35BCEE0535064A8C0B0CC', 'MOF_DIV_NAME', 'PM_PERF_INDICATOR', '财政区划名称', 'S', '360', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ORI_DIV_CODE', '1', '2016', '87', 'E8124E96C7A45BCEE0535064A8C0B0CC', 'ORI_DIV_CODE', 'PM_PERF_INDICATOR', '来源方财政区划代码', 'S', '9', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ORI_DIV_NAME', '1', '2016', '87', 'E8124E96C7A55BCEE0535064A8C0B0CC', 'ORI_DIV_NAME', 'PM_PERF_INDICATOR', '来源方财政区划名称', 'S', '360', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERF_OBJ_TYPE_CODE', '1', '2016', '87', 'E8124E96C7A65BCEE0535064A8C0B0CC', 'PERF_OBJ_TYPE_CODE', 'PM_PERF_INDICATOR', '绩效目标类型代码', 'S', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERF_OBJ_TYPE_NAME', '1', '2016', '87', 'E8124E96C7A75BCEE0535064A8C0B0CC', 'PERF_OBJ_TYPE_NAME', 'PM_PERF_INDICATOR', '绩效目标类型名称', 'S', '60', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_NAME', '1', '2016', '87', 'E8124E96C7A85BCEE0535064A8C0B0CC', 'PRO_NAME', 'PM_PERF_INDICATOR', '项目名称', 'S', '180', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SPE_PRO_CODE', '1', '2016', '87', 'E8124E96C7A95BCEE0535064A8C0B0CC', 'SPE_PRO_CODE', 'PM_PERF_INDICATOR', '具体项目代码', 'S', '21', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SPE_PRO_NAME', '1', '2016', '87', 'E8124E96C7AA5BCEE0535064A8C0B0CC', 'SPE_PRO_NAME', 'PM_PERF_INDICATOR', '具体项目名称', 'S', '180', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SUB_MOF_DIV_CODE', '1', '2016', '87', 'E8124E96C7AB5BCEE0535064A8C0B0CC', 'SUB_MOF_DIV_CODE', 'PM_PERF_INDICATOR', '下级财政区划代码', 'S', '9', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SUB_MOF_DIV_NAME', '1', '2016', '87', 'E8124E96C7AC5BCEE0535064A8C0B0CC', 'SUB_MOF_DIV_NAME', 'PM_PERF_INDICATOR', '下级财政区划名称', 'S', '360', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'IS_LAST_INST', '1', '2016', '87', 'FCCFD316AE3E3C1FE0533315A8C071B6', 'IS_LAST_INST', 'PM_PERF_INDICATOR', '是否终审', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_BACKUP', '1', '2016', '87', 'FD9B882272370790E0530A64A8C0F9BB', 'IS_BACKUP', 'PM_PERF_INDICATOR', '1 版本记录 2 日常动态', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'VERSIONTYPE', '1', '2016', '87', 'FD9B8822723B0790E0530A64A8C0F9BB', 'VERSIONTYPE', 'PM_PERF_INDICATOR', '0 日常动态 1 编制 2 批复，3执行', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_ADJ', '1', '2016', '87', 'FDE633376B3A37C6E0533315A8C0C36D', 'IS_ADJ', 'PM_PERF_INDICATOR', '调整是否终审 2终审 1没有终审', 'N', '1', null, 1, 1, null, sysdate);

delete from bus_t_diccolumn t where t.tablecode='PM_PERF_INDICATOR_TEMP' and t.columncode in('SUB_MOF_CODE','KPI_LV1','KPI_LV2','KPI_LV3','AGENCY_NAME','BGT_ID','PRO_NAME','LV1_PERF_IND_CODE','LV1_PERF_IND_NAME','LV2_PERF_IND_CODE','LV2_PERF_IND_NAME','LV3_PERF_IND_CODE','LV3_PERF_IND_NAME','MOF_AUD_OPINION_CODE','MOF_DIV_NAME','ORI_DIV_CODE','ORI_DIV_NAME','PERF_OBJ_TYPE_CODE','PERF_OBJ_TYPE_NAME','SPE_PRO_CODE','SPE_PRO_NAME','SUB_MOF_DIV_CODE','SUB_MOF_DIV_NAME','MOF_AUD_OPINION_NAME','IS_LAST_INST','IS_ADJ');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AGENCY_NAME', '1', '2016', '87', 'E8861ECFB51839C6E0535064A8C0A4FD', 'AGENCY_NAME', 'PM_PERF_INDICATOR_TEMP', '部门（单位）名称', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BGT_ID', '1', '2016', '87', 'E8861ECFB51739C6E0535064A8C0A4FD', 'BGT_ID', 'PM_PERF_INDICATOR_TEMP', '指标主键', 'S', '38', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIFRAME', null, '1', 'LV1_PERF_IND_CODE', '1', '2016', '87', 'E8861ECFB51639C6E0535064A8C0A4FD', 'LV1_PERF_IND_CODE', 'PM_PERF_INDICATOR_TEMP', '一级绩效指标代码', 'S', '20', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LV1_PERF_IND_NAME', '1', '2016', '87', 'E8861ECFB51539C6E0535064A8C0A4FD', 'LV1_PERF_IND_NAME', 'PM_PERF_INDICATOR_TEMP', '一级绩效指标名称', 'S', '1000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIFRAME', null, '1', 'LV2_PERF_IND_CODE', '1', '2016', '87', 'E8861ECFB51439C6E0535064A8C0A4FD', 'LV2_PERF_IND_CODE', 'PM_PERF_INDICATOR_TEMP', '二级绩效指标代码', 'S', '20', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LV2_PERF_IND_NAME', '1', '2016', '87', 'E8861ECFB51339C6E0535064A8C0A4FD', 'LV2_PERF_IND_NAME', 'PM_PERF_INDICATOR_TEMP', '二级绩效指标名称', 'S', '1000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LV3_PERF_IND_CODE', '1', '2016', '87', 'E8861ECFB51239C6E0535064A8C0A4FD', 'LV3_PERF_IND_CODE', 'PM_PERF_INDICATOR_TEMP', '三级绩效指标代码', 'S', '20', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LV3_PERF_IND_NAME', '1', '2016', '87', 'E8861ECFB50A39C6E0535064A8C0A4FD', 'LV3_PERF_IND_NAME', 'PM_PERF_INDICATOR_TEMP', '三级绩效指标名称', 'S', '1000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MOF_AUD_OPINION_CODE', '1', '2016', '87', 'E8861ECFB50939C6E0535064A8C0A4FD', 'MOF_AUD_OPINION_CODE', 'PM_PERF_INDICATOR_TEMP', '财政审核意见代码', 'S', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MOF_AUD_OPINION_NAME', '1', '2016', '87', 'FCCFD316AE403C1FE0533315A8C071B6', 'MOF_AUD_OPINION_NAME', 'PM_PERF_INDICATOR', '财政审核意见名称', 'S', '60', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MOF_DIV_NAME', '1', '2016', '87', 'E8861ECFB50839C6E0535064A8C0A4FD', 'MOF_DIV_NAME', 'PM_PERF_INDICATOR_TEMP', '财政区划名称', 'S', '360', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ORI_DIV_CODE', '1', '2016', '87', 'E8861ECFB50639C6E0535064A8C0A4FD', 'ORI_DIV_CODE', 'PM_PERF_INDICATOR_TEMP', '来源方财政区划代码', 'S', '9', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ORI_DIV_NAME', '1', '2016', '87', 'E8861ECFB50339C6E0535064A8C0A4FD', 'ORI_DIV_NAME', 'PM_PERF_INDICATOR_TEMP', '来源方财政区划名称', 'S', '360', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERF_OBJ_TYPE_CODE', '1', '2016', '87', 'E8861ECFB50139C6E0535064A8C0A4FD', 'PERF_OBJ_TYPE_CODE', 'PM_PERF_INDICATOR_TEMP', '绩效目标类型代码', 'S', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERF_OBJ_TYPE_NAME', '1', '2016', '87', 'E8861ECFB50239C6E0535064A8C0A4FD', 'PERF_OBJ_TYPE_NAME', 'PM_PERF_INDICATOR_TEMP', '绩效目标类型名称', 'S', '60', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_NAME', '1', '2016', '87', 'E8861ECFB50039C6E0535064A8C0A4FD', 'PRO_NAME', 'PM_PERF_INDICATOR_TEMP', '项目名称', 'S', '180', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SPE_PRO_CODE', '1', '2016', '87', 'E8861ECFB4FF39C6E0535064A8C0A4FD', 'SPE_PRO_CODE', 'PM_PERF_INDICATOR_TEMP', '具体项目代码', 'S', '21', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SPE_PRO_NAME', '1', '2016', '87', 'E8861ECFB4FE39C6E0535064A8C0A4FD', 'SPE_PRO_NAME', 'PM_PERF_INDICATOR_TEMP', '具体项目名称', 'S', '180', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SUB_MOF_DIV_CODE', '1', '2016', '87', 'E8861ECFB4FD39C6E0535064A8C0A4FD', 'SUB_MOF_DIV_CODE', 'PM_PERF_INDICATOR_TEMP', '下级财政区划代码', 'S', '9', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SUB_MOF_DIV_NAME', '1', '2016', '87', 'E8861ECFB4FC39C6E0535064A8C0A4FD', 'SUB_MOF_DIV_NAME', 'PM_PERF_INDICATOR_TEMP', '下级财政区划名称', 'S', '360', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'IS_LAST_INST', '1', '2016', '87', 'FCCFD316AF603C1FE0533315A8C071B6', 'IS_LAST_INST', 'PM_PERF_INDICATOR_TEMP', '是否终审', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_ADJ', '1', '2016', '87', 'FDE633376B9637C6E0533315A8C0C36D', 'IS_ADJ', 'PM_PERF_INDICATOR_TEMP', '调整是否终审 2终审 1没有终审', 'N', '1', null, 1, 1, null, sysdate);
