begin

delete from bus_t_diccolumn t where t.tablecode='PERF_PROVISION_INDICATOR' and t.columncode in('SUB_MOF_CODE','KPI_LV1','KPI_LV2','KPI_LV3','AGENCY_NAME','BGT_ID','PRO_NAME','LV1_PERF_IND_CODE','LV1_PERF_IND_NAME','LV2_PERF_IND_CODE','LV2_PERF_IND_NAME','LV3_PERF_IND_CODE','LV3_PERF_IND_NAME','MOF_AUD_OPINION_CODE','MOF_DIV_NAME','ORI_DIV_CODE','ORI_DIV_NAME','PERF_OBJ_TYPE_CODE','PERF_OBJ_TYPE_NAME','SPE_PRO_CODE','SPE_PRO_NAME','SUB_MOF_DIV_CODE','SUB_MOF_DIV_NAME','MOF_AUD_OPINION_NAME','IS_LAST_INST');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AGENCY_NAME', '1', '2016', '87', 'E8861ECFB4C239C6E0535064A8C0A4FD', 'AGENCY_NAME', 'PERF_PROVISION_INDICATOR', '部门（单位）名称', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BGT_ID', '1', '2016', '87', 'E8861ECFB4C339C6E0535064A8C0A4FD', 'BGT_ID', 'PERF_PROVISION_INDICATOR', '指标主键', 'S', '38', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIFRAME', null, '1', 'LV1_PERF_IND_CODE', '1', '2016', '87', 'E8861ECFB4C439C6E0535064A8C0A4FD', 'LV1_PERF_IND_CODE', 'PERF_PROVISION_INDICATOR', '一级绩效指标代码', 'S', '20', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LV1_PERF_IND_NAME', '1', '2016', '87', 'E8861ECFB4DE39C6E0535064A8C0A4FD', 'LV1_PERF_IND_NAME', 'PERF_PROVISION_INDICATOR', '一级绩效指标名称', 'S', '1000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIFRAME', null, '1', 'LV2_PERF_IND_CODE', '1', '2016', '87', 'E8861ECFB4DD39C6E0535064A8C0A4FD', 'LV2_PERF_IND_CODE', 'PERF_PROVISION_INDICATOR', '二级绩效指标代码', 'S', '20', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LV2_PERF_IND_NAME', '1', '2016', '87', 'E8861ECFB4DC39C6E0535064A8C0A4FD', 'LV2_PERF_IND_NAME', 'PERF_PROVISION_INDICATOR', '二级绩效指标名称', 'S', '1000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LV3_PERF_IND_CODE', '1', '2016', '87', 'E8861ECFB4DA39C6E0535064A8C0A4FD', 'LV3_PERF_IND_CODE', 'PERF_PROVISION_INDICATOR', '三级绩效指标代码', 'S', '20', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LV3_PERF_IND_NAME', '1', '2016', '87', 'E8861ECFB4DB39C6E0535064A8C0A4FD', 'LV3_PERF_IND_NAME', 'PERF_PROVISION_INDICATOR', '三级绩效指标名称', 'S', '1000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MOF_AUD_OPINION_CODE', '1', '2016', '87', 'E8861ECFB4D839C6E0535064A8C0A4FD', 'MOF_AUD_OPINION_CODE', 'PERF_PROVISION_INDICATOR', '财政审核意见代码', 'S', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MOF_AUD_OPINION_NAME', '1', '2016', '87', 'FCCFD316AE9C3C1FE0533315A8C071B6', 'MOF_AUD_OPINION_NAME', 'PERF_PROVISION_INDICATOR', '财政审核意见名称', 'S', '60', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MOF_DIV_NAME', '1', '2016', '87', 'E8861ECFB4D939C6E0535064A8C0A4FD', 'MOF_DIV_NAME', 'PERF_PROVISION_INDICATOR', '财政区划名称', 'S', '360', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ORI_DIV_CODE', '1', '2016', '87', 'E8861ECFB4D739C6E0535064A8C0A4FD', 'ORI_DIV_CODE', 'PERF_PROVISION_INDICATOR', '来源方财政区划代码', 'S', '9', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ORI_DIV_NAME', '1', '2016', '87', 'E8861ECFB4CC39C6E0535064A8C0A4FD', 'ORI_DIV_NAME', 'PERF_PROVISION_INDICATOR', '来源方财政区划名称', 'S', '360', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERF_OBJ_TYPE_CODE', '1', '2016', '87', 'E8861ECFB4CB39C6E0535064A8C0A4FD', 'PERF_OBJ_TYPE_CODE', 'PERF_PROVISION_INDICATOR', '绩效目标类型代码', 'S', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERF_OBJ_TYPE_NAME', '1', '2016', '87', 'E8861ECFB4CA39C6E0535064A8C0A4FD', 'PERF_OBJ_TYPE_NAME', 'PERF_PROVISION_INDICATOR', '绩效目标类型名称', 'S', '60', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_NAME', '1', '2016', '87', 'E8861ECFB4C939C6E0535064A8C0A4FD', 'PRO_NAME', 'PERF_PROVISION_INDICATOR', '项目名称', 'S', '180', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SPE_PRO_CODE', '1', '2016', '87', 'E8861ECFB4C839C6E0535064A8C0A4FD', 'SPE_PRO_CODE', 'PERF_PROVISION_INDICATOR', '具体项目代码', 'S', '21', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SPE_PRO_NAME', '1', '2016', '87', 'E8861ECFB4C739C6E0535064A8C0A4FD', 'SPE_PRO_NAME', 'PERF_PROVISION_INDICATOR', '具体项目名称', 'S', '180', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SUB_MOF_DIV_CODE', '1', '2016', '87', 'E8861ECFB4C639C6E0535064A8C0A4FD', 'SUB_MOF_DIV_CODE', 'PERF_PROVISION_INDICATOR', '下级财政区划代码', 'S', '9', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SUB_MOF_DIV_NAME', '1', '2016', '87', 'E8861ECFB4C539C6E0535064A8C0A4FD', 'SUB_MOF_DIV_NAME', 'PERF_PROVISION_INDICATOR', '下级财政区划名称', 'S', '360', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'IS_LAST_INST', '1', '2016', '87', 'FCCFD316AE9E3C1FE0533315A8C071B6', 'IS_LAST_INST', 'PERF_PROVISION_INDICATOR', '是否终审', 'N', '1', null, 1, 1, null, sysdate);