begin

delete from bus_t_diccolumn t where t.tablecode='PERF_T_ADJUSTGOAL' and t.columncode in('DEPT_NAME','SUB_MOF_CODE','AGENCY_NAME','BGT_ID','PRO_NAME','MOF_AUD_OPINION_CODE','MOF_AUD_OPINION_NAME','MOF_DIV_NAME','ORI_DIV_CODE','ORI_DIV_NAME','PERF_OBJ_TYPE_CODE','PERF_OBJ_TYPE_NAME','SPE_PRO_CODE','SPE_PRO_NAME','SUB_MOF_DIV_CODE','SUB_MOF_DIV_NAME','FIN_PERF_CODE','FIN_PERF_NAME','IS_LAST_INST');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AGENCY_NAME', '1', '2016', '87', 'E8861ECFB52639C6E0535064A8C0A4FD', 'AGENCY_NAME', 'PERF_T_ADJUSTGOAL', '部门（单位）名称', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BGT_ID', '1', '2016', '87', 'E8861ECFB52739C6E0535064A8C0A4FD', 'BGT_ID', 'PERF_T_ADJUSTGOAL', '指标主键', 'S', '38', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MOF_AUD_OPINION_CODE', '1', '2021', '87', 'E8861ECFB52539C6E0535064A8C0A4FD', 'MOF_AUD_OPINION_CODE', 'PERF_T_ADJUSTGOAL', '财政审核意见代码', 'S', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MOF_AUD_OPINION_NAME', '1', '2016', '87', 'E8861ECFB52439C6E0535064A8C0A4FD', 'MOF_AUD_OPINION_NAME', 'PERF_T_ADJUSTGOAL', '财政审核意见名称', 'S', '60', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MOF_DIV_NAME', '1', '2016', '87', 'E8861ECFB52339C6E0535064A8C0A4FD', 'MOF_DIV_NAME', 'PERF_T_ADJUSTGOAL', '财政区划名称', 'S', '360', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ORI_DIV_CODE', '1', '2021', '87', 'E8861ECFB52239C6E0535064A8C0A4FD', 'ORI_DIV_CODE', 'PERF_T_ADJUSTGOAL', '来源方财政区划代码', 'S', '9', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ORI_DIV_NAME', '1', '2016', '87', 'E8861ECFB52139C6E0535064A8C0A4FD', 'ORI_DIV_NAME', 'PERF_T_ADJUSTGOAL', '来源方财政区划名称', 'S', '360', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERF_OBJ_TYPE_CODE', '1', '2016', '87', 'E8861ECFB52039C6E0535064A8C0A4FD', 'PERF_OBJ_TYPE_CODE', 'PERF_T_ADJUSTGOAL', '绩效目标类型代码', 'S', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERF_OBJ_TYPE_NAME', '1', '2021', '87', 'E8861ECFB51F39C6E0535064A8C0A4FD', 'PERF_OBJ_TYPE_NAME', 'PERF_T_ADJUSTGOAL', '绩效目标类型名称', 'S', '60', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_NAME', '1', '2021', '87', 'E8861ECFB51E39C6E0535064A8C0A4FD', 'PRO_NAME', 'PERF_T_ADJUSTGOAL', '项目名称', 'S', '180', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SPE_PRO_CODE', '1', '2016', '87', 'E8861ECFB51D39C6E0535064A8C0A4FD', 'SPE_PRO_CODE', 'PERF_T_ADJUSTGOAL', '具体项目代码', 'S', '21', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SPE_PRO_NAME', '1', '2016', '87', 'E8861ECFB51C39C6E0535064A8C0A4FD', 'SPE_PRO_NAME', 'PERF_T_ADJUSTGOAL', '具体项目名称', 'S', '180', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SUB_MOF_DIV_CODE', '1', '2021', '87', 'E8861ECFB51B39C6E0535064A8C0A4FD', 'SUB_MOF_DIV_CODE', 'PERF_T_ADJUSTGOAL', '下级财政区划代码', 'S', '9', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'SUB_MOF_DIV_NAME', '1', '2016', '87', 'E8861ECFB51A39C6E0535064A8C0A4FD', 'SUB_MOF_DIV_NAME', 'PERF_T_ADJUSTGOAL', '下级财政区划名称', 'S', '360', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'DEPT_NAME', '1', '2016', '87', 'E8861ECFB51939C6E0535064A8C0A4FD', 'DEPT_NAME', 'PERF_T_ADJUSTGOAL', '部门名称', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FIN_PERF_CODE', '1', '2021', '87', 'FCCFD316AF033C1FE0533315A8C071B6', 'FIN_PERF_CODE', 'PERF_T_ADJUSTGOAL', '财政绩效目标审核结果代码', 'S', '4', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FIN_PERF_NAME', '1', '2016', '87', 'FCCFD316AF043C1FE0533315A8C071B6', 'FIN_PERF_NAME', 'PERF_T_ADJUSTGOAL', '财政绩效目标审核结果', 'S', '100', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_LAST_INST', '1', '2016', '87', 'FCCFD316AF063C1FE0533315A8C071B6', 'IS_LAST_INST', 'PERF_T_ADJUSTGOAL', '是否终审', 'N', '1', null, 1, 0, null, sysdate);