begin

delete from bus_t_dictable t where t.tablecode in('PAY_PERF_MONITOR_TASK','PAY_PERF_MONITOR_INFO','PAY_PERF_MONITOR_ATTACH');
insert into bus_t_dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2022', '87', 'PAY_PERF_MONITOR_TASK', '绩效运行监控任务表', '绩效运行监控任务表', 1, 1, 'PAY_PERF_MONITOR_TASK', 'pmkpi', null, '0', 1, '0', 1, 1, 'V_PAY_PERF_MONITOR_TASK', sysdate, 1, 1, null, '1');

insert into bus_t_dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2022', '87', 'PAY_PERF_MONITOR_INFO', '绩效运行监控信息表', '绩效运行监控信息表', 2, 1, 'PAY_PERF_MONITOR_INFO', 'pmkpi', null, '0', 1, '0', 0, 1, 'V_PAY_PERF_MONITOR_INFO', sysdate, 1, 1, null, '1');

insert into bus_t_dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2016', '87', 'PAY_PERF_MONITOR_ATTACH', '绩效运行监控关联附件表', '绩效运行监控关联附件表', 2, 1, 'PAY_PERF_MONITOR_ATTACH', 'pmkpi', null, '0', 1, '0', 0, 1, 'V_PAY_PERF_MONITOR_ATTACH', sysdate, 1, 1, null, '1');

delete from bus_t_diccolumn t where t.tablecode in('PAY_PERF_MONITOR_TASK','PAY_PERF_MONITOR_INFO','PAY_PERF_MONITOR_ATTACH');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATE_TIME', '1', '2023', '87', 'FB3FFEF3311D62D9E0535064A8C022AF', 'CREATE_TIME', 'PAY_PERF_MONITOR_ATTACH', '创建时间', 'S', '17', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FILE_NAME', '1', '2023', '87', 'FB3FFEF3312762D9E0535064A8C022AF', 'FILE_NAME', 'PAY_PERF_MONITOR_ATTACH', '附件名称', 'S', '50', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FISCAL_YEAR', '1', '2023', '87', 'FB3FFEF3312262D9E0535064A8C022AF', 'FISCAL_YEAR', 'PAY_PERF_MONITOR_ATTACH', '年度', 'S', '4', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FULL_PATH', '1', '2023', '87', 'FB3FFEF3312862D9E0535064A8C022AF', 'FULL_PATH', 'PAY_PERF_MONITOR_ATTACH', '附件路径', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_DELETED', '1', '2023', '87', 'FB3FFEF3311E62D9E0535064A8C022AF', 'IS_DELETED', 'PAY_PERF_MONITOR_ATTACH', '是否删除', 'N', '1', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_LAST_INST', '1', '2023', '87', 'FB3FFEF3311F62D9E0535064A8C022AF', 'IS_LAST_INST', 'PAY_PERF_MONITOR_ATTACH', '是否终审', 'N', '1', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MOF_DIV_CODE', '1', '2023', '87', 'FB3FFEF3312362D9E0535064A8C022AF', 'MOF_DIV_CODE', 'PAY_PERF_MONITOR_ATTACH', '区划', 'S', '9', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MOF_DIV_NAME', '1', '2023', '87', 'FB3FFEF3312462D9E0535064A8C022AF', 'MOF_DIV_NAME', 'PAY_PERF_MONITOR_ATTACH', '财政区划名称', 'S', '360', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERF_ATT_ID', '1', '2023', '87', 'FB3FFEF3312562D9E0535064A8C022AF', 'PERF_ATT_ID', 'PAY_PERF_MONITOR_ATTACH', '附件唯一标识', 'S', '38', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERF_MON_ID', '1', '2023', '87', 'FB3FFEF3312662D9E0535064A8C022AF', 'PERF_MON_ID', 'PAY_PERF_MONITOR_ATTACH', '监控信息主键', 'S', '38', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'REPORT_FILE', '1', '2023', '87', 'FB3FFEF3312962D9E0535064A8C022AF', 'REPORT_FILE', 'PAY_PERF_MONITOR_ATTACH', '附件文件', 'S', '4000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UPDATE_TIME', '1', '2023', '87', 'FB3FFEF3312162D9E0535064A8C022AF', 'UPDATE_TIME', 'PAY_PERF_MONITOR_ATTACH', '修改时间', 'S', '17', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '1', 'AGENCY_CODE', '1', '2022', '87', 'EE49801B7A6F12B8E0535064A8C0BD11', 'AGENCY_CODE', 'PAY_PERF_MONITOR_INFO', '单位', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AGENCY_NAME', '1', '2022', '87', 'EE49801B7A8D12B8E0535064A8C0BD11', 'AGENCY_NAME', 'PAY_PERF_MONITOR_INFO', '单位名称', 'S', '300', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'ANA_DEV_REASONS', '1', '2022', '87', 'EE49801B7AA712B8E0535064A8C0BD11', 'ANA_DEV_REASONS', 'PAY_PERF_MONITOR_INFO', '偏差原因分析', 'S', '2000', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'COMPLETE_RATE', '1', '2022', '87', 'EE49801B7AA812B8E0535064A8C0BD11', 'COMPLETE_RATE', 'PAY_PERF_MONITOR_INFO', '完成目标可能性', 'N', '16', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATE_TIME', '1', '2022', '87', 'EE49801B7A7512B8E0535064A8C0BD11', 'CREATE_TIME', 'PAY_PERF_MONITOR_INFO', '创建时间', 'S', '17', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '1', 'DEPT_CODE', '1', '2022', '87', 'EE49801B7A8E12B8E0535064A8C0BD11', 'DEPT_CODE', 'PAY_PERF_MONITOR_INFO', '部门代码', 'S', '21', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'DEPT_NAME', '1', '2022', '87', 'EE49801B7A8F12B8E0535064A8C0BD11', 'DEPT_NAME', 'PAY_PERF_MONITOR_INFO', '部门名称', 'S', '150', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EST_PERF_ANNUAL', '1', '2022', '87', 'EE49801B7AA612B8E0535064A8C0BD11', 'EST_PERF_ANNUAL', 'PAY_PERF_MONITOR_INFO', '绩效指标全年预计完成情况', 'S', '2000', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EST_PRO_BGT_ANNUAL', '1', '2022', '87', 'EE49801B7AA312B8E0535064A8C0BD11', 'EST_PRO_BGT_ANNUAL', 'PAY_PERF_MONITOR_INFO', '项目预算全年预计执行情况', 'N', '16', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FISCAL_YEAR', '1', '2022', '87', 'EE49801B7A9012B8E0535064A8C0BD11', 'FISCAL_YEAR', 'PAY_PERF_MONITOR_INFO', '年度', 'S', '4', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_DELETED', '1', '2022', '87', 'EE49801B7A7D12B8E0535064A8C0BD11', 'IS_DELETED', 'PAY_PERF_MONITOR_INFO', '是否删除', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_LAST_INST', '1', '2022', '87', 'EE49801B7A9212B8E0535064A8C0BD11', 'IS_LAST_INST', 'PAY_PERF_MONITOR_INFO', '是否终审', 'N', '1', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_PERF_RECTIFY', '1', '2022', '87', 'EE49801B7AAA12B8E0535064A8C0BD11', 'IS_PERF_RECTIFY', 'PAY_PERF_MONITOR_INFO', '是否需要整改', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'KPI_TARGET', '1', '2022', '87', 'EE49801B7AA112B8E0535064A8C0BD11', 'KPI_TARGET', 'PAY_PERF_MONITOR_INFO', '绩效目标', 'S', '2000', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'KPI_VAL', '1', '2022', '87', 'EE49801B7AA412B8E0535064A8C0BD11', 'KPI_VAL', 'PAY_PERF_MONITOR_INFO', '指标值', 'S', '1000', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIFRAME', null, '1', 'LV1_PERF_IND_CODE', '1', '2022', '87', 'EE49801B7A9B12B8E0535064A8C0BD11', 'LV1_PERF_IND_CODE', 'PAY_PERF_MONITOR_INFO', '一级绩效指标代码', 'S', '20', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LV1_PERF_IND_NAME', '1', '2022', '87', 'EE49801B7A9C12B8E0535064A8C0BD11', 'LV1_PERF_IND_NAME', 'PAY_PERF_MONITOR_INFO', '一级绩效指标名称', 'S', '1000', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIFRAME', null, '1', 'LV2_PERF_IND_CODE', '1', '2022', '87', 'EE49801B7A9D12B8E0535064A8C0BD11', 'LV2_PERF_IND_CODE', 'PAY_PERF_MONITOR_INFO', '二级绩效指标代码', 'S', '20', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LV2_PERF_IND_NAME', '1', '2022', '87', 'EE49801B7A9E12B8E0535064A8C0BD11', 'LV2_PERF_IND_NAME', 'PAY_PERF_MONITOR_INFO', '二级绩效指标名称', 'S', '1000', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LV3_PERF_IND_CODE', '1', '2022', '87', 'EE49801B7A9F12B8E0535064A8C0BD11', 'LV3_PERF_IND_CODE', 'PAY_PERF_MONITOR_INFO', '三级绩效指标代码', 'S', '20', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LV3_PERF_IND_NAME', '1', '2022', '87', 'EE49801B7AA012B8E0535064A8C0BD11', 'LV3_PERF_IND_NAME', 'PAY_PERF_MONITOR_INFO', '三级绩效指标名称', 'S', '1000', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MOF_DIV_CODE', '1', '2022', '87', 'EE49801B7A8012B8E0535064A8C0BD11', 'MOF_DIV_CODE', 'PAY_PERF_MONITOR_INFO', '区划', 'S', '9', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MOF_DIV_NAME', '1', '2022', '87', 'EE49801B7A9412B8E0535064A8C0BD11', 'MOF_DIV_NAME', 'PAY_PERF_MONITOR_INFO', '财政区划名称', 'S', '360', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERF_COMP', '1', '2022', '87', 'EE49801B7AA512B8E0535064A8C0BD11', 'PERF_COMP', 'PAY_PERF_MONITOR_INFO', '绩效指标完成情况', 'S', '2000', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERF_MON_ID', '1', '2022', '87', 'EEBCE86476EB652FE0535064A8C0BBB8', 'PERF_MON_ID', 'PAY_PERF_MONITOR_INFO', '监控信息主建', 'S', '38', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERF_MON_NO', '1', '2022', '87', 'EE49801B7A9612B8E0535064A8C0BD11', 'PERF_MON_NO', 'PAY_PERF_MONITOR_INFO', '监控任务编号', 'S', '100', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERF_SEND_DATE', '1', '2022', '87', 'EE49801B7AA912B8E0535064A8C0BD11', 'PERF_SEND_DATE', 'PAY_PERF_MONITOR_INFO', '报送日期', 'S', '17', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERF_TASK_ID', '1', '2022', '87', 'EE49801B7A9512B8E0535064A8C0BD11', 'PERF_TASK_ID', 'PAY_PERF_MONITOR_INFO', '监控任务主键', 'S', '38', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERF_TYPE_CODE', '1', '2022', '87', 'EE49801B7A9712B8E0535064A8C0BD11', 'PERF_TYPE_CODE', 'PAY_PERF_MONITOR_INFO', '绩效监控类型编码', 'S', '1', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERF_TYPE_NAME', '1', '2022', '87', 'EE49801B7A9812B8E0535064A8C0BD11', 'PERF_TYPE_NAME', 'PAY_PERF_MONITOR_INFO', '绩效监控类型名称', 'S', '40', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_BGT_COMP', '1', '2022', '87', 'EE49801B7AA212B8E0535064A8C0BD11', 'PRO_BGT_COMP', 'PAY_PERF_MONITOR_INFO', '项目预算执行情况', 'N', '16', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_CODE', '1', '2022', '87', 'EE49801B7A9912B8E0535064A8C0BD11', 'PRO_CODE', 'PAY_PERF_MONITOR_INFO', '项目编码', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_NAME', '1', '2022', '87', 'EE49801B7A9A12B8E0535064A8C0BD11', 'PRO_NAME', 'PAY_PERF_MONITOR_INFO', '项目名称', 'S', '180', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'RECTIFY_ADVISE', '1', '2022', '87', 'EE49801B7AAB12B8E0535064A8C0BD11', 'RECTIFY_ADVISE', 'PAY_PERF_MONITOR_INFO', '整改要求和建议', 'S', '2000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'RECTIFY_EPILOG', '1', '2022', '87', 'EE49801B7AAC12B8E0535064A8C0BD11', 'RECTIFY_EPILOG', 'PAY_PERF_MONITOR_INFO', '整改结果和结论', 'S', '2000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UPDATE_TIME', '1', '2022', '87', 'EE49801B7A8A12B8E0535064A8C0BD11', 'UPDATE_TIME', 'PAY_PERF_MONITOR_INFO', '修改时间', 'S', '17', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '1', 'AGENCY_CODE', '1', '2022', '87', 'EE4874C718DC3F8EE0535064A8C03652', 'AGENCY_CODE', 'PAY_PERF_MONITOR_TASK', '单位', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AGENCY_NAME', '1', '2022', '87', 'EE4874C719103F8EE0535064A8C03652', 'AGENCY_NAME', 'PAY_PERF_MONITOR_TASK', '单位名称', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATE_TIME', '1', '2022', '87', 'EE4874C718E43F8EE0535064A8C03652', 'CREATE_TIME', 'PAY_PERF_MONITOR_TASK', '创建时间', 'S', '17', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '1', 'DEPT_CODE', '1', '2022', '87', 'EE4874C7190E3F8EE0535064A8C03652', 'DEPT_CODE', 'PAY_PERF_MONITOR_TASK', '部门代码', 'S', '21', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'DEPT_NAME', '1', '2022', '87', 'EE4874C7190F3F8EE0535064A8C03652', 'DEPT_NAME', 'PAY_PERF_MONITOR_TASK', '部门名称', 'S', '150', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FISCAL_YEAR', '1', '2022', '87', 'EE4874C718E93F8EE0535064A8C03652', 'FISCAL_YEAR', 'PAY_PERF_MONITOR_TASK', '年度', 'S', '4', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_DELETED', '1', '2022', '87', 'EE4874C718F13F8EE0535064A8C03652', 'IS_DELETED', 'PAY_PERF_MONITOR_TASK', '是否删除', 'N', '1', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_LAST_INST', '1', '2022', '87', 'EE4874C719123F8EE0535064A8C03652', 'IS_LAST_INST', 'PAY_PERF_MONITOR_TASK', '是否终审', 'N', '1', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MOF_DIV_CODE', '1', '2022', '87', 'EE4874C718F63F8EE0535064A8C03652', 'MOF_DIV_CODE', 'PAY_PERF_MONITOR_TASK', '区划', 'S', '9', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MOF_DIV_NAME', '1', '2022', '87', 'EE4874C719073F8EE0535064A8C03652', 'MOF_DIV_NAME', 'PAY_PERF_MONITOR_TASK', '财政区划名称', 'S', '360', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERF_TASK_DSEC', '1', '2022', '87', 'EE4874C7190C3F8EE0535064A8C03652', 'PERF_TASK_DSEC', 'PAY_PERF_MONITOR_TASK', '监控任务内容', 'S', '2000', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERF_TASK_ID', '1', '2022', '87', 'EE4874C719063F8EE0535064A8C03652', 'PERF_TASK_ID', 'PAY_PERF_MONITOR_TASK', '监控任务主键', 'S', '38', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERF_TASK_NO', '1', '2022', '87', 'EE4874C719083F8EE0535064A8C03652', 'PERF_TASK_NO', 'PAY_PERF_MONITOR_TASK', '监控任务编号', 'S', '100', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERF_TASK_TITLE', '1', '2022', '87', 'EE4874C7190B3F8EE0535064A8C03652', 'PERF_TASK_TITLE', 'PAY_PERF_MONITOR_TASK', '监控任务标题', 'S', '200', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERF_TYPE_CODE', '1', '2022', '87', 'EE4874C719093F8EE0535064A8C03652', 'PERF_TYPE_CODE', 'PAY_PERF_MONITOR_TASK', '绩效监控类型编码', 'S', '1', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PERF_TYPE_NAME', '1', '2022', '87', 'EE4874C7190A3F8EE0535064A8C03652', 'PERF_TYPE_NAME', 'PAY_PERF_MONITOR_TASK', '绩效监控类型名称', 'S', '40', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_CODE', '1', '2022', '87', 'EE4874C718FC3F8EE0535064A8C03652', 'PRO_CODE', 'PAY_PERF_MONITOR_TASK', '项目编码', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_NAME', '1', '2022', '87', 'EE4874C719113F8EE0535064A8C03652', 'PRO_NAME', 'PAY_PERF_MONITOR_TASK', '项目名称', 'S', '180', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TASK_END_DATE', '1', '2022', '87', 'EE4874C7190D3F8EE0535064A8C03652', 'TASK_END_DATE', 'PAY_PERF_MONITOR_TASK', '报送截止日期', 'S', '17', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UPDATE_TIME', '1', '2022', '87', 'EE4874C719023F8EE0535064A8C03652', 'UPDATE_TIME', 'PAY_PERF_MONITOR_TASK', '修改时间', 'S', '17', null, 1, 0, null, sysdate);
