begin
  --绩效部门评价表
delete from bus_t_dictable where tablecode ='PM_PERF_DEPT_EVAL';
insert into bus_t_dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2022', '87', 'PM_PERF_DEPT_EVAL', '绩效部门评价表', '绩效部门评价表', 1, 1, 'PM_PERF_DEPT_EVAL', 'pmkpi', null, '0', 1, '0', 1, 1, 'V_PM_PERF_DEPT_EVAL', sysdate, 1, 1, null, '1');

delete from bus_t_diccolumn where tablecode ='PM_PERF_GOV_EVAL';
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '1', 'AGENCY_CODE', '1', '2016', '87', 'FB528D4EF7102F22E0535064A8C0543A', 'AGENCY_CODE', 'PM_PERF_GOV_EVAL', '单位代码', 'S', '21', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AGENCY_NAME', '1', '2016', '87', 'FB528D4EF7112F22E0535064A8C0543A', 'AGENCY_NAME', 'PM_PERF_GOV_EVAL', '单位名称', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BGT_MOF_DEP_CODE', '1', '2016', '87', 'FB528D4EF7122F22E0535064A8C0543A', 'BGT_MOF_DEP_CODE', 'PM_PERF_GOV_EVAL', '资金管理处室代码', 'S', '6', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'BGT_MOF_DEP_NAME', '1', '2016', '87', 'FB528D4EF7132F22E0535064A8C0543A', 'BGT_MOF_DEP_NAME', 'PM_PERF_GOV_EVAL', '资金管理处室名称', 'S', '60', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATE_TIME', '1', '2016', '87', 'FB528D4EF7142F22E0535064A8C0543A', 'CREATE_TIME', 'PM_PERF_GOV_EVAL', '创建时间', 'S', '17', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '1', 'DEPT_CODE', '1', '2016', '87', 'FB528D4EF7152F22E0535064A8C0543A', 'DEPT_CODE', 'PM_PERF_GOV_EVAL', '部门代码', 'S', '21', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'DEPT_NAME', '1', '2016', '87', 'FB528D4EF7162F22E0535064A8C0543A', 'DEPT_NAME', 'PM_PERF_GOV_EVAL', '部门名称', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EVAL_ID', '1', '2016', '87', 'FB528D4EF7172F22E0535064A8C0543A', 'EVAL_ID', 'PM_PERF_GOV_EVAL', '财政评价表主键', 'S', '38', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EVAL_REPORT', '1', '2016', '87', 'FB528D4EF7182F22E0535064A8C0543A', 'EVAL_REPORT', 'PM_PERF_GOV_EVAL', '财政评价报告', 'S', '2000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EXIST_PROBLEMS', '1', '2016', '87', 'FB528D4EF7192F22E0535064A8C0543A', 'EXIST_PROBLEMS', 'PM_PERF_GOV_EVAL', '存在问题', 'S', '2000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FISCAL_YEAR', '1', '2016', '87', 'FB528D4EF71A2F22E0535064A8C0543A', 'FISCAL_YEAR', 'PM_PERF_GOV_EVAL', '评价年度', 'S', '4', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_DELETED', '1', '2016', '87', 'FB528D4EF71B2F22E0535064A8C0543A', 'IS_DELETED', 'PM_PERF_GOV_EVAL', '是否删除', 'N', '1', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_LAST_INST', '1', '2016', '87', 'FB528D4EF71C2F22E0535064A8C0543A', 'IS_LAST_INST', 'PM_PERF_GOV_EVAL', '是否终审', 'N', '1', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MOF_DIV_CODE', '1', '2016', '87', 'FB528D4EF71D2F22E0535064A8C0543A', 'MOF_DIV_CODE', 'PM_PERF_GOV_EVAL', '财政区划代码', 'S', '9', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MOF_DIV_NAME', '1', '2016', '87', 'FB528D4EF71E2F22E0535064A8C0543A', 'MOF_DIV_NAME', 'PM_PERF_GOV_EVAL', '财政区划名称', 'S', '360', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'POLICY_NAME', '1', '2016', '87', 'FB528D4EF71F2F22E0535064A8C0543A', 'POLICY_NAME', 'PM_PERF_GOV_EVAL', '政策名称', 'S', '180', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_CODE', '1', '2016', '87', 'FB528D4EF7202F22E0535064A8C0543A', 'PRO_CODE', 'PM_PERF_GOV_EVAL', '项目代码', 'S', '21', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_NAME', '1', '2016', '87', 'FB528D4EF7212F22E0535064A8C0543A', 'PRO_NAME', 'PM_PERF_GOV_EVAL', '项目名称', 'S', '180', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'RECTIFY_SITUATION', '1', '2016', '87', 'FB528D4EF7222F22E0535064A8C0543A', 'RECTIFY_SITUATION', 'PM_PERF_GOV_EVAL', '整改落实情况', 'S', '2000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'RECTIFY_STEP', '1', '2016', '87', 'FB528D4EF7232F22E0535064A8C0543A', 'RECTIFY_STEP', 'PM_PERF_GOV_EVAL', '整改建议', 'S', '2000', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UPDATE_TIME', '1', '2016', '87', 'FB528D4EF7242F22E0535064A8C0543A', 'UPDATE_TIME', 'PM_PERF_GOV_EVAL', '修改时间', 'S', '17', null, 1, 0, null, sysdate);


--绩效财政评价表
delete from bus_t_dictable where tablecode ='PM_PERF_GOV_EVAL';
insert into bus_t_dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2022', '87', 'PM_PERF_GOV_EVAL', '绩效财政评价表', '绩效财政评价表', 1, 1, 'PM_PERF_GOV_EVAL', 'pmkpi', null, '0', 1, '0', 1, 1, 'V_PM_PERF_GOV_EVAL', sysdate, 1, 1, null, '1');

delete from bus_t_diccolumn where tablecode ='PM_PERF_DEPT_EVAL';
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '1', 'AGENCY_CODE', '1', '2016', '87', 'FB52539D96082C4DE0535064A8C04A23', 'AGENCY_CODE', 'PM_PERF_DEPT_EVAL', '单位代码', 'S', '21', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AGENCY_NAME', '1', '2016', '87', 'FB52539D96092C4DE0535064A8C04A23', 'AGENCY_NAME', 'PM_PERF_DEPT_EVAL', '单位名称', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATE_TIME', '1', '2016', '87', 'FB52539D960A2C4DE0535064A8C04A23', 'CREATE_TIME', 'PM_PERF_DEPT_EVAL', '创建时间', 'S', '17', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '1', 'DEPT_CODE', '1', '2016', '87', 'FB52539D960B2C4DE0535064A8C04A23', 'DEPT_CODE', 'PM_PERF_DEPT_EVAL', '部门代码', 'S', '21', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'DEPT_NAME', '1', '2016', '87', 'FB52539D960C2C4DE0535064A8C04A23', 'DEPT_NAME', 'PM_PERF_DEPT_EVAL', '部门名称', 'S', '300', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EVAL_ID', '1', '2016', '87', 'FB52539D960D2C4DE0535064A8C04A23', 'EVAL_ID', 'PM_PERF_DEPT_EVAL', '部门评价表主键', 'S', '38', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'EVAL_REPORT', '1', '2016', '87', 'FB52539D960E2C4DE0535064A8C04A23', 'EVAL_REPORT', 'PM_PERF_DEPT_EVAL', '部门评价报告', 'S', '2000', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'FISCAL_YEAR', '1', '2016', '87', 'FB52539D960F2C4DE0535064A8C04A23', 'FISCAL_YEAR', 'PM_PERF_DEPT_EVAL', '评价年度', 'S', '4', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_DELETED', '1', '2016', '87', 'FB52539D96102C4DE0535064A8C04A23', 'IS_DELETED', 'PM_PERF_DEPT_EVAL', '是否删除', 'N', '1', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_LAST_INST', '1', '2016', '87', 'FB52539D96112C4DE0535064A8C04A23', 'IS_LAST_INST', 'PM_PERF_DEPT_EVAL', '是否终审', 'N', '1', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MOF_AUD_OPINION', '1', '2016', '87', 'FB52539D96122C4DE0535064A8C04A23', 'MOF_AUD_OPINION', 'PM_PERF_DEPT_EVAL', '财政审核意见', 'S', '2000', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MOF_DIV_CODE', '1', '2016', '87', 'FB52539D96132C4DE0535064A8C04A23', 'MOF_DIV_CODE', 'PM_PERF_DEPT_EVAL', '财政区划代码', 'S', '9', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MOF_DIV_NAME', '1', '2016', '87', 'FB52539D96142C4DE0535064A8C04A23', 'MOF_DIV_NAME', 'PM_PERF_DEPT_EVAL', '财政区划名称', 'S', '360', null, 1, 0, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_CODE', '1', '2016', '87', 'FB52539D96152C4DE0535064A8C04A23', 'PRO_CODE', 'PM_PERF_DEPT_EVAL', '项目编码', 'S', '21', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PRO_NAME', '1', '2016', '87', 'FB52539D96162C4DE0535064A8C04A23', 'PRO_NAME', 'PM_PERF_DEPT_EVAL', '项目名称', 'S', '180', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UPDATE_TIME', '1', '2016', '87', 'FB52539D96172C4DE0535064A8C04A23', 'UPDATE_TIME', 'PM_PERF_DEPT_EVAL', '修改时间', 'S', '17', null, 1, 0, null, sysdate);

