begin

--2、评价成果上传，增加“第三方信息”页签，发版隐藏
--表注册
delete from bus_t_dictable where tablecode = 'PERF_THIRD_PARTY_INFO';
insert into bus_t_dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2016', '87', 'PERF_THIRD_PARTY_INFO', '部门评价第三方信息表', '部门评价第三方信息表', 2, 1, 'PERF_THIRD_PARTY_INFO', 'pmkpi', null, '0', 1, '0', 0, 1, 'V_PERF_THIRD_PARTY_INFO', sysdate, 1, 1, null, '1');
--表字段注册
delete from bus_t_diccolumn where tablecode = 'PERF_THIRD_PARTY_INFO';
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', '2016', '87', 'EED47FE19AA40202E0533315A8C02FDB', 'GUID', 'PERF_THIRD_PARTY_INFO', '主键', 'S', '32', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'MAINGUID', '1', '2016', '87', 'EED47FE19AAD0202E0533315A8C02FDB', 'MAINGUID', 'PERF_THIRD_PARTY_INFO', '主单guid', 'S', '40', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'INSTITUTION_NAME', '1', '2016', '87', 'EED47FE19AA50202E0533315A8C02FDB', 'INSTITUTION_NAME', 'PERF_THIRD_PARTY_INFO', '第三方机构名称', 'S', '255', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'LEADER_NAME', '1', '2016', '87', 'EED47FE19AA60202E0533315A8C02FDB', 'LEADER_NAME', 'PERF_THIRD_PARTY_INFO', '负责人名称', 'S', '255', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATER', '1', '2016', '87', 'EED47FE19AA70202E0533315A8C02FDB', 'CREATER', 'PERF_THIRD_PARTY_INFO', '创建人', 'S', '40', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'CREATE_TIME', '1', '2016', '87', 'EED47FE19AA80202E0533315A8C02FDB', 'CREATE_TIME', 'PERF_THIRD_PARTY_INFO', '创建时间', 'S', '40', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'UPDATE_TIME', '1', '2016', '87', 'EED47FE19AA90202E0533315A8C02FDB', 'UPDATE_TIME', 'PERF_THIRD_PARTY_INFO', '修改时间', 'S', '40', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'IS_DELETED', '1', '2016', '87', 'EED47FE19AAA0202E0533315A8C02FDB', 'IS_DELETED', 'PERF_THIRD_PARTY_INFO', '是否删除', 'S', '1', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', '2016', '87', 'EED47FE19AAB0202E0533315A8C02FDB', 'YEAR', 'PERF_THIRD_PARTY_INFO', '年度', 'S', '40', null, 1, 1, null, sysdate);
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', '2016', '87', 'EED47FE19AAC0202E0533315A8C02FDB', 'PROVINCE', 'PERF_THIRD_PARTY_INFO', '区划', 'S', '40', null, 1, 1, null, sysdate);

--1、评价成果上传-评估结论页面增加“是否委托第三方开展”，值集为“是、否”，必填，发版隐藏
delete from bus_t_diccolumn where tablecode = 'PERF_T_DEPTEVALUATION' and columncode = 'ISENTRUST';
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00001', null, '1', 'ISENTRUST', '1', '2016', '87', 'BDPP532C9E8177B9E053B11FA8C041F0', 'ISENTRUST', 'PERF_T_DEPTEVALUATION', '是否委托', 'S', '40', null, null, 1, null, sysdate);

