begin

delete from bus_t_diccolumn where tablecode = 'V_PERF_PROJECT_REVIEW';
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'VD00010', null, '0', 'AGENCYGUID', '1', '2020', '87', 'B2B87E5FA502B60BE053B11FA8C02292', 'AGENCYGUID', 'V_PERF_PROJECT_REVIEW', '单位', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIWFSTATUS', null, '0', 'BDMWFSTATUS', '1', '2020', '87', 'B8B83E5FA612B11BE052B11FA8C02292', 'BDMWFSTATUS', 'V_PERF_PROJECT_REVIEW', '预算状态', 'S', '100', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'creater0001', null, '0', 'CREATER', '1', '2020', '87', 'B9B82E7FA606B10BE053B11FA8C02292', 'CREATER', 'V_PERF_PROJECT_REVIEW', '创建人', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'CREATE_TIME', '1', '2020', '87', 'B5B84E0FA607B10BE053B11FA8C02292', 'CREATE_TIME', 'V_PERF_PROJECT_REVIEW', '创建时间', 'S', '20', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '96B5961EBFF244559FD06E940FB7324A', null, '0', 'FININTORGGUID', '1', '2020', '87', 'B1B28E5FA608B11BE053B11FA8C02292', 'FININTORGGUID', 'V_PERF_PROJECT_REVIEW', '管理处室', 'S', '50', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_NAME', '1', '2020', '87', 'B3B86E5FA613B11BE353B13FA8C06692', 'PRO_NAME', 'V_PERF_PROJECT_REVIEW', '项目名称', 'S', '200', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'PMKPIWFSTATUS', null, '0', 'WFSTATUS', '1', '2020', '87', 'B4B85E5FA612B11BE052B11FA8C02292', 'WFSTATUS', 'V_PERF_PROJECT_REVIEW', '工作流状态', 'S', '100', null, null, 1, null, sysdate);


delete from bus_t_dictable where tablecode = 'V_PERF_PROJECT_REVIEW';
insert into bus_t_dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2019', '87', 'V_PERF_PROJECT_REVIEW', '绩效处项目绩效目标审核表', null, 2, 1, 'V_PERF_PROJECT_REVIEW', 'pmkpi', null, null, 1, null, 1, 1, 'V_PERF_PROJECT_REVIEW', sysdate, null, null, null, '1');






delete from bus_t_diccolumn where tablecode = 'V_PERF_PROJECT_INFODPVIEW';
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'ACTION', '1', null, null, '2D3E1F2D4EE84CF59759608AB468BAFD', 'ACTION', 'V_PERF_PROJECT_INFODPVIEW', '流程方向', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values ('DE03002', 'PDMAGENCYALL', null, '0', 'AGENCYGUID', '1', null, null, 'BCB3D38C43B791CBE053470A050A6189', 'AGENCYGUID', 'V_PERF_PROJECT_INFODPVIEW', '单位代码', 'S', '21', null, 1, 0, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values ('DE03002', 'PDMAGENCYALL', null, '0', 'AGENCY_CODE', '1', null, null, 'BCB4D3DC43B791CBE053470A050A6189', 'AGENCY_CODE', 'V_PERF_PROJECT_INFODPVIEW', '单位代码', 'S', '21', null, 1, 0, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values ('092006', '61006100UEw5VQ8y', null, '0', 'AUDITOR', '1', null, null, 'BCB5D3DC43B892CBE053470A050A6189', 'AUDITOR', 'V_PERF_PROJECT_INFODPVIEW', '审核人', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values ('092004', '092004', null, '0', 'BDMBEFWF', '1', null, null, '8736916E9A3B45C18E0A6BD5DFA5341B', 'BDMBEFWF', 'V_PERF_PROJECT_INFODPVIEW', '单位前状态', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values ('092004', '092004', null, '0', 'BDMLASTWF', '1', null, null, '6AF75F101CDB46BB93CB2E1395109769', 'BDMLASTWF', 'V_PERF_PROJECT_INFODPVIEW', '单位后状态', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'CREATER', '1', null, null, 'BCB8D3DC43BA93CBE053470A050A6189', 'CREATER', 'V_PERF_PROJECT_INFODPVIEW', '建单人', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'CREATE_TIME', '1', null, null, 'BCB933DC43BB96CBE053470A050A6189', 'CREATE_TIME', 'V_PERF_PROJECT_INFODPVIEW', '创建时间', 'S', '14', null, 1, 0, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'GUID', '1', null, null, 'BCB043DC43C597CBE053470A050A6189', 'GUID', 'V_PERF_PROJECT_INFODPVIEW', '业务主键', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'ISLAST', '1', null, null, 'D657212575034C649A1BBE5B91D98AD1', 'ISLAST', 'V_PERF_PROJECT_INFODPVIEW', '是否最后', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'IS_DELETED', '1', null, null, 'AD7322C370AD4D46A9D55CDB1601418B', 'IS_DELETED', 'V_PERF_PROJECT_INFODPVIEW', '是否删除', 'N', '1', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'LASTUPDATETIME', '1', null, null, 'BCB216DC43BB94CBE053470A050A6189', 'LASTUPDATETIME', 'V_PERF_PROJECT_INFODPVIEW', '最后更新时间', 'S', '14', null, 1, 0, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'MOF_DEP_CODE', '1', null, null, 'BCB289DC43FC9tCBE053470A050A6189', 'MOF_DEP_CODE', 'V_PERF_PROJECT_INFODPVIEW', '区划', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'PROVINCE', '1', null, null, 'BCB2D42C442D9ECB4053470A050A6189', 'PROVINCE', 'V_PERF_PROJECT_INFODPVIEW', '区划', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_CODE', '1', null, null, 'BCB265DC43F399CBE053470A050A6189', 'PRO_CODE', 'V_PERF_PROJECT_INFODPVIEW', '项目代码', 'S', '21', null, 1, 0, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_ID', '1', null, null, 'BCB256DC43F398CBE053470A050A6189', 'PRO_ID', 'V_PERF_PROJECT_INFODPVIEW', '项目编码', 'S', '21', null, 1, 0, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_LEV', '1', null, null, 'BCB277DC43F890CBE053470A050A6189', 'PRO_LEV', 'V_PERF_PROJECT_INFODPVIEW', '项目级次', 'S', '2', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'PRO_NAME', '1', null, null, 'BCB288DC43FC9tCBE053470A050A6189', 'PRO_NAME', 'V_PERF_PROJECT_INFODPVIEW', '项目名称', 'S', '180', null, 1, 0, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'REMARK', '1', null, null, 'BCB2D03C442D9ECB5053470A09016189', 'REMARK', 'V_PERF_PROJECT_INFODPVIEW', '备注', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'TASKFLAG', '1', null, null, 'BCB2D33C142D9ECB5053470A050A6189', 'TASKFLAG', 'V_PERF_PROJECT_INFODPVIEW', '一上二上', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'UPDATE_TIME', '1', null, null, 'BCB223DC23BB95CBE053470A050A6189', 'UPDATE_TIME', 'V_PERF_PROJECT_INFODPVIEW', '更新时间', 'S', '14', null, 1, 0, '0', sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'WFID', '1', null, null, 'BCB293DC342D9ECB1053470A050A6189', 'WFID', 'V_PERF_PROJECT_INFODPVIEW', '流程编码', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values ('092004', '099076', null, '0', 'WFSTATUS', '1', null, null, 'BCB203DC542E9ECB2053470A050A6189', 'WFSTATUS', 'V_PERF_PROJECT_INFODPVIEW', '流程状态', 'S', '32', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'YEAR', '1', null, null, 'BCB2D31C742D9ECB3053470A050A6189', 'YEAR', 'V_PERF_PROJECT_INFODPVIEW', '年度', 'S', '32', null, 1, 1, null, sysdate);



delete from bus_t_dictable where tablecode = 'V_PERF_PROJECT_INFODPVIEW';
insert into bus_t_dictable (YEAR, PROVINCE, TABLECODE, NAME, REMARK, TABLETYPE, VERSION, DBTABNAME, APPID, EXP, TABLEPART, ISSHOW, DBIMPFLAG, ISSYS, ISUSES, VIEWTABLENAME, DBVERSION, DATASYNC, HASTRIGGER, SYNCCLASSNAME, STATUS)
values ('2016', '87', 'V_PERF_PROJECT_INFODPVIEW', '双流程项目表', '双流程项目表', 2, 1, 'V_PERF_PROJECT_INFODPVIEW', 'pmkpi', null, '0', 1, '0', 0, 1, 'V_PERF_PROJECT_INFODPVIEW', sysdate, 1, 1, null, '1');
