 BEGIN
--BAS_PERF_INDICATOR
delete from CFS_LTABLE_FIELD where TABLE_NAME ='BAS_PERF_INDICATOR' and FIELD_NAME in('PERF_IND_CODE','BIZ_KEY','PERF_IND_NAME');
--PERF_IND_CODE 
INSERT INTO CFS_LTABLE_FIELD("LTABLE_FIELD", "TABLE_NAME", "FIELD_CN_NAME", "LT_ELE_CODE", "CHANGE_TYPE", "CREATE_TIME", "MANDATORY", "VERSION", "LTABLE_ID", "SEQ_NO", "FIELD_NAME", "DATA_TYPE", "DATA_LENGTH", "FIELD_DES", "CHANGE_CONTENT", "UPDATE_TIME", "IS_DELETED", "IS_FULL", "IS_SYS") VALUES ('AE7A505693F42B55E0530603A8C08935', 'BAS_PERF_INDICATOR', '绩效指标代码', 'BE09101', NULL, SYSDATE, NULL, 'v1', 'AE7A505687852B55E0530603A8C08935', NULL, 'PERF_IND_CODE', 'NString', '300', NULL, NULL,SYSDATE, '0', '1', '0');
--PERF_IND_NAME
INSERT INTO CFS_LTABLE_FIELD("LTABLE_FIELD", "TABLE_NAME", "FIELD_CN_NAME", "LT_ELE_CODE", "CHANGE_TYPE", "CREATE_TIME", "MANDATORY", "VERSION", "LTABLE_ID", "SEQ_NO", "FIELD_NAME", "DATA_TYPE", "DATA_LENGTH", "FIELD_DES", "CHANGE_CONTENT", "UPDATE_TIME", "IS_DELETED", "IS_FULL", "IS_SYS") VALUES ('AE7A505693F52B55E0530603A8C08935', 'BAS_PERF_INDICATOR', '绩效指标名称', 'BE09102', NULL,SYSDATE, NULL, 'v1', 'AE7A505687852B55E0530603A8C08935', NULL, 'PERF_IND_NAME', 'GBString', '1000', NULL, NULL,SYSDATE, '0', '1', '0');
--BIZ_KEY
INSERT INTO CFS_LTABLE_FIELD("LTABLE_FIELD", "TABLE_NAME", "FIELD_CN_NAME", "LT_ELE_CODE", "CHANGE_TYPE", "CREATE_TIME", "MANDATORY", "VERSION", "LTABLE_ID", "SEQ_NO", "FIELD_NAME", "DATA_TYPE", "DATA_LENGTH", "FIELD_DES", "CHANGE_CONTENT", "UPDATE_TIME", "IS_DELETED", "IS_FULL", "IS_SYS") VALUES ('C3700BF92F5A50A9E053B11FA8C0DBF1', 'BAS_PERF_INDICATOR', '业务唯一标识', 'BE00001', NULL, SYSDATE, NULL, 'v1', 'C3700BF92F5A50A9E053B11FA8C0DBF1', NULL, 'BIZ_KEY', 'GBString', '38', NULL, NULL,SYSDATE, '0', '1', '0');


---BGT_PERF_INDICATOR
delete from  CFS_LTABLE_FIELD where TABLE_NAME ='BGT_PERF_INDICATOR' and FIELD_NAME in('KPI_LV1','KPI_LV2','KPI_LV3','KPI_VAL','BUSI_TYPE_CODE','ADJ_BATCH_NO','BUSI_TYPE');
 --kpi_vl1
INSERT INTO CFS_LTABLE_FIELD("LTABLE_FIELD", "TABLE_NAME", "FIELD_CN_NAME", "LT_ELE_CODE", "CHANGE_TYPE", "CREATE_TIME", "MANDATORY", "VERSION", "LTABLE_ID", "SEQ_NO", "FIELD_NAME", "DATA_TYPE", "DATA_LENGTH", "FIELD_DES", "CHANGE_CONTENT", "UPDATE_TIME", "IS_DELETED", "IS_FULL", "IS_SYS") VALUES ('AE7A505689552B55E0530603A8C08935', 'BGT_PERF_INDICATOR', '一级指标', 'BE09101', NULL, SYSDATE, NULL, 'v1', 'AE7A5056879F2B55E0530603A8C08935', NULL, 'KPI_LV1', 'NString', '300', 'BE09101的一级代码', NULL, SYSDATE, '0', '1', '0');
--kpi_kl2
 INSERT INTO CFS_LTABLE_FIELD("LTABLE_FIELD", "TABLE_NAME", "FIELD_CN_NAME", "LT_ELE_CODE", "CHANGE_TYPE", "CREATE_TIME", "MANDATORY", "VERSION", "LTABLE_ID", "SEQ_NO", "FIELD_NAME", "DATA_TYPE", "DATA_LENGTH", "FIELD_DES", "CHANGE_CONTENT", "UPDATE_TIME", "IS_DELETED", "IS_FULL", "IS_SYS") VALUES ('AE7A505689562B55E0530603A8C08935', 'BGT_PERF_INDICATOR', '二级指标', 'BE09101', NULL, SYSDATE, NULL, 'v1', 'AE7A5056879F2B55E0530603A8C08935', NULL, 'KPI_LV2', 'NString', '300', 'BE09101的二级代码', NULL, SYSDATE, '0', '1', '0');
 --kpi_kl3
INSERT INTO CFS_LTABLE_FIELD("LTABLE_FIELD", "TABLE_NAME", "FIELD_CN_NAME", "LT_ELE_CODE", "CHANGE_TYPE", "CREATE_TIME", "MANDATORY", "VERSION", "LTABLE_ID", "SEQ_NO", "FIELD_NAME", "DATA_TYPE", "DATA_LENGTH", "FIELD_DES", "CHANGE_CONTENT", "UPDATE_TIME", "IS_DELETED", "IS_FULL", "IS_SYS") VALUES ('AE7A505689572B55E0530603A8C08935', 'BGT_PERF_INDICATOR', '三级指标', 'BE09101', NULL,SYSDATE, NULL, 'v1', 'AE7A5056879F2B55E0530603A8C08935', NULL, 'KPI_LV3', 'NString', '300', 'BE09101的三级代码', NULL, SYSDATE, '0', '1', '0');
--kpi_val
INSERT INTO CFS_LTABLE_FIELD("LTABLE_FIELD", "TABLE_NAME", "FIELD_CN_NAME", "LT_ELE_CODE", "CHANGE_TYPE", "CREATE_TIME", "MANDATORY", "VERSION", "LTABLE_ID", "SEQ_NO", "FIELD_NAME", "DATA_TYPE", "DATA_LENGTH", "FIELD_DES", "CHANGE_CONTENT", "UPDATE_TIME", "IS_DELETED", "IS_FULL", "IS_SYS") VALUES ('AE7A5056895A2B55E0530603A8C08935', 'BGT_PERF_INDICATOR', '指标值', 'BE10033', NULL, SYSDATE, NULL, 'v1', 'AE7A5056879F2B55E0530603A8C08935', NULL, 'KPI_VAL', 'String', '1000', NULL, NULL, SYSDATE, '0', '1', '0');
 --BUSI_TYPE_CODE
INSERT INTO CFS_LTABLE_FIELD("LTABLE_FIELD", "TABLE_NAME", "FIELD_CN_NAME", "LT_ELE_CODE", "CHANGE_TYPE", "CREATE_TIME", "MANDATORY", "VERSION", "LTABLE_ID", "SEQ_NO", "FIELD_NAME", "DATA_TYPE", "DATA_LENGTH", "FIELD_DES", "CHANGE_CONTENT", "UPDATE_TIME", "IS_DELETED", "IS_FULL", "IS_SYS") VALUES ('C3700BF92F6250A9E053B11FA8C0DBF1', 'BGT_PERF_INDICATOR', '业务类型代码', 'BE10029', NULL, SYSDATE, NULL, 'v1', 'C3700BF92F6250A9E053B11FA8C0DBF1', NULL, 'BUSI_TYPE_CODE', 'String', '6', NULL, NULL, SYSDATE, '0', '1', '0');
--ADJ_BATCH_NO
INSERT INTO CFS_LTABLE_FIELD("LTABLE_FIELD", "TABLE_NAME", "FIELD_CN_NAME", "LT_ELE_CODE", "CHANGE_TYPE", "CREATE_TIME", "MANDATORY", "VERSION", "LTABLE_ID", "SEQ_NO", "FIELD_NAME", "DATA_TYPE", "DATA_LENGTH", "FIELD_DES", "CHANGE_CONTENT", "UPDATE_TIME", "IS_DELETED", "IS_FULL", "IS_SYS") VALUES ('C3700BF92F6450A9E053B11FA8C0DBF1', 'BGT_PERF_INDICATOR', '调整批次号', 'BE11055', NULL, SYSDATE, NULL, 'v1', 'C3700BF92F6450A9E053B11FA8C0DBF1', NULL, 'ADJ_BATCH_NO', 'String', '6', NULL, NULL, SYSDATE, '0', '1', '0');

 --PM_PERF_INDICATOR
 delete from CFS_LTABLE_FIELD where TABLE_NAME ='PM_PERF_INDICATOR' and FIELD_NAME in('KPI_LV1','KPI_LV2','KPI_LV3','KPI_VAL','BUSI_TYPE','BUSI_TYPE_CODE','AGENCY_CODE');
 --kpi_vl1
INSERT INTO CFS_LTABLE_FIELD("LTABLE_FIELD", "TABLE_NAME", "FIELD_CN_NAME", "LT_ELE_CODE", "CHANGE_TYPE", "CREATE_TIME", "MANDATORY", "VERSION", "LTABLE_ID", "SEQ_NO", "FIELD_NAME", "DATA_TYPE", "DATA_LENGTH", "FIELD_DES", "CHANGE_CONTENT", "UPDATE_TIME", "IS_DELETED", "IS_FULL", "IS_SYS") VALUES ('AE7A505688172B55E0530603A8C08935', 'PM_PERF_INDICATOR', '一级指标', 'BE09101', NULL, SYSDATE, NULL, 'v1', 'AE7A505688172B55E0530603A8C08935', NULL, 'KPI_LV1', 'NString', '300', 'BE09101的一级代码', NULL, SYSDATE, '0', '1', '0');
--kpi_val2
INSERT INTO CFS_LTABLE_FIELD("LTABLE_FIELD", "TABLE_NAME", "FIELD_CN_NAME", "LT_ELE_CODE", "CHANGE_TYPE", "CREATE_TIME", "MANDATORY", "VERSION", "LTABLE_ID", "SEQ_NO", "FIELD_NAME", "DATA_TYPE", "DATA_LENGTH", "FIELD_DES", "CHANGE_CONTENT", "UPDATE_TIME", "IS_DELETED", "IS_FULL", "IS_SYS") VALUES ('AE7A505688372B55E0530603A8C08935', 'PM_PERF_INDICATOR', '二级指标', 'BE09101', NULL, SYSDATE, NULL, 'v1', 'AE78C179432027ABE0530603A8C0DF3C', NULL, 'KPI_LV2', 'NString', '300', 'BE09101的二级代码', NULL, SYSDATE, '0', '1', '0');
--kpi_val3
INSERT INTO CFS_LTABLE_FIELD("LTABLE_FIELD", "TABLE_NAME", "FIELD_CN_NAME", "LT_ELE_CODE", "CHANGE_TYPE", "CREATE_TIME", "MANDATORY", "VERSION", "LTABLE_ID", "SEQ_NO", "FIELD_NAME", "DATA_TYPE", "DATA_LENGTH", "FIELD_DES", "CHANGE_CONTENT", "UPDATE_TIME", "IS_DELETED", "IS_FULL", "IS_SYS") VALUES ('AE7A505688382B55E0530603A8C08935', 'PM_PERF_INDICATOR', '三级指标', 'BE09101', NULL, SYSDATE, NULL, 'v1', 'AE78C179432027ABE0530603A8C0DF3C', NULL, 'KPI_LV3', 'NString', '300', 'BE09101的三级代码', NULL, SYSDATE, '0', '1', '0');
--kpi_val
INSERT INTO CFS_LTABLE_FIELD("LTABLE_FIELD", "TABLE_NAME", "FIELD_CN_NAME", "LT_ELE_CODE", "CHANGE_TYPE", "CREATE_TIME", "MANDATORY", "VERSION", "LTABLE_ID", "SEQ_NO", "FIELD_NAME", "DATA_TYPE", "DATA_LENGTH", "FIELD_DES", "CHANGE_CONTENT", "UPDATE_TIME", "IS_DELETED", "IS_FULL", "IS_SYS") VALUES ('AE7A5056883B2B55E0530603A8C08935', 'PM_PERF_INDICATOR', '指标值', 'BE10033', NULL, SYSDATE, NULL, 'v1', 'AE78C179432027ABE0530603A8C0DF3C', NULL, 'KPI_VAL', 'String', '1000', NULL, NULL, SYSDATE, '0', '1', '0');
--BUSI_TYPE_CODE
INSERT INTO CFS_LTABLE_FIELD("LTABLE_FIELD", "TABLE_NAME", "FIELD_CN_NAME", "LT_ELE_CODE", "CHANGE_TYPE", "CREATE_TIME", "MANDATORY", "VERSION", "LTABLE_ID", "SEQ_NO", "FIELD_NAME", "DATA_TYPE", "DATA_LENGTH", "FIELD_DES", "CHANGE_CONTENT", "UPDATE_TIME", "IS_DELETED", "IS_FULL", "IS_SYS") VALUES ('AE7A5056883D2B55E0530603A8C08935', 'PM_PERF_INDICATOR', '业务类型代码', 'BE10029', NULL, SYSDATE, NULL, 'v1', 'AE78C179432027ABE0530603A8C0DF3C', NULL, 'BUSI_TYPE_CODE', 'NString', '6', NULL, NULL, SYSDATE, '0', '1', '0');
--AGENCY_CODE
INSERT INTO CFS_LTABLE_FIELD("LTABLE_FIELD", "TABLE_NAME", "FIELD_CN_NAME", "LT_ELE_CODE", "CHANGE_TYPE", "CREATE_TIME", "MANDATORY", "VERSION", "LTABLE_ID", "SEQ_NO", "FIELD_NAME", "DATA_TYPE", "DATA_LENGTH", "FIELD_DES", "CHANGE_CONTENT", "UPDATE_TIME", "IS_DELETED", "IS_FULL", "IS_SYS") VALUES ('C4C48C461F391249E053B11FA8C01AA9', 'PM_PERF_INDICATOR', '单位代码', 'BE10029', NULL, SYSDATE, NULL, 'v1', 'C4C48C461F391249E053B11FA8C01AA9', NULL, 'AGENCY_CODE', 'GBString', '21', NULL, NULL,SYSDATE, '0', '1', '0');

--PM_PERF_GOAL_INFO
delete from CFS_LTABLE_FIELD where TABLE_NAME ='PM_PERF_GOAL_INFO' and FIELD_NAME in('BUSI_TYPE','BUSI_TYPE_CODE','AGENCY_CODE');
--BUSI_TYPE_CODE
INSERT INTO CFS_LTABLE_FIELD("LTABLE_FIELD", "TABLE_NAME", "FIELD_CN_NAME", "LT_ELE_CODE", "CHANGE_TYPE", "CREATE_TIME", "MANDATORY", "VERSION", "LTABLE_ID", "SEQ_NO", "FIELD_NAME", "DATA_TYPE", "DATA_LENGTH", "FIELD_DES", "CHANGE_CONTENT", "UPDATE_TIME", "IS_DELETED", "IS_FULL", "IS_SYS") VALUES ('C3700BF92F5C50A9E053B11FA8C0DBF1', 'PM_PERF_GOAL_INFO', '业务类型代码', 'BE10029', NULL, SYSDATE, NULL, 'v1', 'C3700BF92F5C50A9E053B11FA8C0DBF1', NULL, 'BUSI_TYPE_CODE', 'GBString', '6', NULL, NULL,SYSDATE, '0', '1', '0');
--AGENCY_CODE
INSERT INTO CFS_LTABLE_FIELD("LTABLE_FIELD", "TABLE_NAME", "FIELD_CN_NAME", "LT_ELE_CODE", "CHANGE_TYPE", "CREATE_TIME", "MANDATORY", "VERSION", "LTABLE_ID", "SEQ_NO", "FIELD_NAME", "DATA_TYPE", "DATA_LENGTH", "FIELD_DES", "CHANGE_CONTENT", "UPDATE_TIME", "IS_DELETED", "IS_FULL", "IS_SYS") VALUES ('C3767E6FBE0205FFE053B11FA8C06179', 'PM_PERF_GOAL_INFO', '单位代码', 'BE10029', NULL, SYSDATE, NULL, 'v1', 'C3767E6FBE0205FFE053B11FA8C06179', NULL, 'AGENCY_CODE', 'GBString', '21', NULL, NULL,SYSDATE, '0', '1', '0');

--BGT_PERF_GOAL_INFO
delete from CFS_LTABLE_FIELD where TABLE_NAME ='BGT_PERF_GOAL_INFO' and FIELD_NAME in('BUSI_TYPE_CODE','ADJ_BATCH_NO','BUSI_TYPE');
 --BUSI_TYPE_CODE
INSERT INTO CFS_LTABLE_FIELD("LTABLE_FIELD", "TABLE_NAME", "FIELD_CN_NAME", "LT_ELE_CODE", "CHANGE_TYPE", "CREATE_TIME", "MANDATORY", "VERSION", "LTABLE_ID", "SEQ_NO", "FIELD_NAME", "DATA_TYPE", "DATA_LENGTH", "FIELD_DES", "CHANGE_CONTENT", "UPDATE_TIME", "IS_DELETED", "IS_FULL", "IS_SYS") VALUES ('C3700BF92F5E50A9E053B11FA8C0DBF1', 'BGT_PERF_GOAL_INFO', '业务类型代码', 'BE10029', NULL, SYSDATE, NULL, 'v1', 'C3700BF92F5E50A9E053B11FA8C0DBF1', NULL, 'BUSI_TYPE_CODE', 'String', '6', NULL, NULL, SYSDATE, '0', '1', '0');
--ADJ_BATCH_NO
INSERT INTO CFS_LTABLE_FIELD("LTABLE_FIELD", "TABLE_NAME", "FIELD_CN_NAME", "LT_ELE_CODE", "CHANGE_TYPE", "CREATE_TIME", "MANDATORY", "VERSION", "LTABLE_ID", "SEQ_NO", "FIELD_NAME", "DATA_TYPE", "DATA_LENGTH", "FIELD_DES", "CHANGE_CONTENT", "UPDATE_TIME", "IS_DELETED", "IS_FULL", "IS_SYS") VALUES ('C3700BF92F6050A9E053B11FA8C0DBF1', 'BGT_PERF_GOAL_INFO', '调整批次号', 'BE11055', NULL, SYSDATE, NULL, 'v1', 'C3700BF92F6050A9E053B11FA8C0DBF1', NULL, 'ADJ_BATCH_NO', 'String', '6', NULL, NULL, SYSDATE, '0', '1', '0');

--BAS_PERF_INDICATOR
delete from bus_t_diccolumn  where TABLECODE='BAS_PERF_INDICATOR' and COLUMNCODE in('CODE','NAME','FINDEX','SINDEX','TARGETVALUE');
--CODE
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'CODE', '1', '2016', '87', 'B412538AA08E62E3E0535164A8C0C98B', 'CODE', 'BAS_PERF_INDICATOR', '编码', 'S', '300', NULL, '1', '1', NULL, sysdate);
--NAME
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'NAME', '1', '2016', '87', 'B412538AA09062E3E0535164A8C0C98B', 'NAME', 'BAS_PERF_INDICATOR', '指标名称', 'S', '1000', NULL, '1', '1', NULL, SYSDATE);

INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, 'PMKPIFRAME', NULL, '1', 'FINDEX', '1', '2016', '87', 'B412538AA08B62E3E0535164A8C0C98B', 'FINDEX', 'BAS_PERF_INDICATOR', '一级指标', 'S', '300', NULL, '1', '1', NULL, SYSDATE);

INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, 'PMKPIFRAME', NULL, '1', 'SINDEX', '1', '2016', '87', 'B412538AA08C62E3E0535164A8C0C98B', 'SINDEX', 'BAS_PERF_INDICATOR', '二级指标', 'S', '300', NULL, '1', '1', NULL,SYSDATE);

INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'TARGETVALUE', '1', '2016', '87', '3B249CB8B84C4A39AEF51EBCB9C1433C', 'TARGETVALUE', 'BAS_PERF_INDICATOR', '目标值', 'S', '1000', NULL, '1', '1', NULL, SYSDATE);

--PM_PERF_GOAL_TEMP
delete from bus_t_diccolumn  where TABLECODE='PM_PERF_GOAL_TEMP' and COLUMNCODE in('BUSI_TYPE','BUSI_TYPE_CODE','AGENCY_CODE');
--BUSI_TYPE_CODE
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'BUSI_TYPE_CODE', '1', '2016', '87', 'C376FC8632E20AF0E053B11FA8C07B95', 'BUSI_TYPE_CODE', 'PM_PERF_GOAL_TEMP', '业务类型代码', 'S', '6', NULL, '1', '1', NULL, SYSDATE);
--AGENCY_CODE
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'AGENCY_CODE', '1', '2016', '87', 'C376FC8632E40AF0E053B11FA8C07B95', 'AGENCY_CODE', 'PM_PERF_GOAL_TEMP', '单位', 'S', '21', NULL, '1', '1', NULL, SYSDATE);

--PM_PERF_INDICATOR
delete from bus_t_diccolumn  where TABLECODE='PM_PERF_INDICATOR' and COLUMNCODE in('FINDEX','SINDEX','TINDEX', 'INDEXVAL','TARGETVALUE','AGENCY_CODE','NAME','CODE');
--findex
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, 'PMKPIFRAME', NULL, '1', 'FINDEX', '1', '2016', '87', 'B412538AA09862E3E0535164A8C0C98B', 'FINDEX', 'PM_PERF_INDICATOR', '一级指标', 'S', '300', NULL, '1', '1', NULL, SYSDATE);
--sindex
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, 'PMKPIFRAME', NULL, '1', 'SINDEX', '1', '2016', '87', 'B412538AA09B62E3E0535164A8C0C98B', 'SINDEX', 'PM_PERF_INDICATOR', '二级指标', 'S', '300', NULL, '1', '1', NULL, SYSDATE);
--tindex
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'TINDEX', '1', '2016', '87', '11A254CBC3C746F1B6708BDA2BF6C060', 'TINDEX', 'PM_PERF_INDICATOR', '模板/案例三级指标', 'S', '300', NULL, '1', '0', NULL, SYSDATE);
--indexVal
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'INDEXVAL', '1', '2016', '87', 'B412538AA09A62E3E0535164A8C0C98B', 'INDEXVAL', 'PM_PERF_INDICATOR', '指标值', 'S', '1000', NULL, '1', '1', NULL, SYSDATE);
--targetval
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'TARGETVALUE', '1', '2016', '87', 'E6A679EF96D847DE877F10BFE672EFF3', 'TARGETVALUE', 'PM_PERF_INDICATOR', '目标值', 'S', '1000', NULL, '1', '0', NULL, SYSDATE);
--CODE
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'CODE', '1', '2021', '87', '650A32AE488C464FA915076D01EFB3B4', 'CODE', 'PM_PERF_INDICATOR', '编码', 'S', '300', NULL, '1', '0', NULL, SYSDATE);
--NAME
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'NAME', '1', '2016', '87', 'B412538AA09962E3E0535164A8C0C98B', 'NAME', 'PM_PERF_INDICATOR', '三级指标名称', 'S', '1000', NULL, '1', '1', NULL,SYSDATE);
--AGENCY_CODE
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'AGENCY_CODE', '1', '2016', '87', 'C4C48C461F3B1249E053B11FA8C01AA9', 'AGENCY_CODE', 'PM_PERF_INDICATOR', '单位', 'S', '21', NULL, '1', '1', NULL, SYSDATE);


--PM_PERF_INDICATOR_TEMP
delete from bus_t_diccolumn  where TABLECODE='PM_PERF_INDICATOR_TEMP' and COLUMNCODE in('FINDEX','SINDEX','TINDEX', 'INDEXVAL','TARGETVALUE','BUSI_TYPE','BUSI_TYPE_CODE','AGENCY_CODE','NAME','CODE');
--findex
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, 'PMKPIFRAME', NULL, '1', 'FINDEX', '1', '2016', '87', 'PMPERFINDICATORTEMP0008', 'FINDEX', 'PM_PERF_INDICATOR_TEMP', '一级指标', 'S', '300', NULL, '1', '1', NULL, SYSDATE);
--sindex
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, 'PMKPIFRAME', NULL, '1', 'SINDEX', '1', '2016', '87', 'PMPERFINDICATORTEMP0026', 'SINDEX', 'PM_PERF_INDICATOR_TEMP', '二级指标', 'S', '300', NULL, '1', '1', NULL, SYSDATE);
--tindex
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'TINDEX', '1', '2016', '87', 'PMPERFINDICATORTEMP0035', 'TINDEX', 'PM_PERF_INDICATOR_TEMP', '模板/案例三级指标', 'S', '300', NULL, '1', '0', NULL, SYSDATE);
--indexVal
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'INDEXVAL', '1', '2016', '87', 'PMPERFINDICATORTEMP0012', 'INDEXVAL', 'PM_PERF_INDICATOR_TEMP', '指标值', 'S', '1000', NULL, '1', '1', NULL, SYSDATE);
--targetval
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'TARGETVALUE', '1', '2016', '87', 'PMPERFINDICATORTEMP0034', 'TARGETVALUE', 'PM_PERF_INDICATOR_TEMP', '目标值', 'S', '1000', NULL, '1', '0', NULL, SYSDATE);
--AGENCY_CODE
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'AGENCY_CODE', '1', '2016', '87', 'PMPERFINDICATORTEMP0002', 'AGENCY_CODE', 'PM_PERF_INDICATOR_TEMP', '单位', 'S', '21', NULL, '1', '0', NULL, SYSDATE);
--BUSI_TYPE_CODE
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'BUSI_TYPE_CODE', '1', '2016', '87', 'C376FC8632E00AF0E053B11FA8C07B95', 'BUSI_TYPE_CODE', 'PM_PERF_INDICATOR_TEMP', '业务类型代码', 'S', '6', NULL, '1', '0', NULL, SYSDATE);
--NAME
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'NAME', '1', '2016', '87', 'PMPERFINDICATORTEMP0017', 'NAME', 'PM_PERF_INDICATOR_TEMP', '三级指标名称', 'S', '1000', NULL, '1', '1', NULL, SYSDATE);
--CODE
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'CODE', '1', '2021', '87', 'PMPERFINDICATORTEMP0003', 'CODE', 'PM_PERF_INDICATOR_TEMP', '编码', 'S', '300', NULL, '1', '0', NULL, SYSDATE);


--BGT_PERF_INDICATOR
delete from bus_t_diccolumn  where TABLECODE='BGT_PERF_INDICATOR' and COLUMNCODE in('FINDEX','SINDEX','TINDEX', 'INDEXVAL','TARGETVALUE');
--FINDEX
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'FINDEX', '1', '2016', '87', 'B47721D4F9CA1010E0535164A8C05EF7', 'FINDEX', 'BGT_PERF_INDICATOR', '一级指标', 'S', '300', NULL, '1', '0', NULL, SYSDATE);
--SINDEX
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'SINDEX', '1', '2016', '87', 'B47721D4F9CB1010E0535164A8C05EF7', 'SINDEX', 'BGT_PERF_INDICATOR', '二级指标', 'S', '300', NULL, '1', '0', NULL,SYSDATE);
--TINDEX
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'TINDEX', '1', '2016', '87', 'F6160E3C5D80426DB99226B579B27330', 'TINDEX', 'BGT_PERF_INDICATOR', '模板/案例三级指标', 'S', '300', NULL, '1', '0', NULL, SYSDATE);
--indexval
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'INDEXVAL', '1', '2016', '87', 'A59312F5B0064EB8B32A9C1116B91E32', 'INDEXVAL', 'BGT_PERF_INDICATOR', '指标值', 'S', '1000', NULL, '1', '0', NULL, SYSDATE);
--TARGETVALUE
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'TARGETVALUE', '1', '2016', '87', 'B686DC99B6F90CCAE0530100007FB3EC', 'TARGETVALUE', 'BGT_PERF_INDICATOR', '目标值', 'S', '1000', NULL, '1', '0', NULL, SYSDATE);


--PERF_T_ADJUSTGOAL
delete from bus_t_diccolumn  where TABLECODE='PERF_T_ADJUSTGOAL' and COLUMNCODE in('BUSI_TYPE_CODE','AGENCY_CODE','BUSI_TYPE');
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'AGENCY_CODE', '1', '2016', '87', 'B9C975E5A863F59EE053B11FA8C05A36', 'AGENCY_CODE', 'PERF_T_ADJUSTGOAL', '单位', 'S', '21', NULL, '1', '1', NULL, SYSDATE);

INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'BUSI_TYPE_CODE', '1', '2016', '87', 'B9C975E5A85BF59EE053B11FA8C05A36', 'BUSI_TYPE_CODE', 'PERF_T_ADJUSTGOAL', '业务类型代码', 'S', '6', NULL, '1', '1', NULL, SYSDATE);

--PERF_T_ADJUSTINDEX
delete from bus_t_diccolumn  where TABLECODE='PERF_T_ADJUSTINDEX' and COLUMNCODE in('CODE','NAME','KPI_LV1','KPI_LV2','KPI_LV3','FINDEX','SINDEX','TINDEX','KPI_VAL','INDEXVAL','TARGETVALUE','AGENCY_CODE','BUSI_TYPE_CODE','BUSI_TYPE');
--AGENCY_CODE
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'AGENCY_CODE', '1', '2021', '87', 'B9C975E5A8C4F59EE053B11FA8C05A36', 'AGENCY_CODE', 'PERF_T_ADJUSTINDEX', '单位', 'S', '21', NULL, '1', '0', NULL, SYSDATE);
--BUSI_TYPE_CODE
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'BUSI_TYPE_CODE', '1', '2021', '87', 'B9C975E5A8BAF59EE053B11FA8C05A36', 'BUSI_TYPE_CODE', 'PERF_T_ADJUSTINDEX', '业务类型代码', 'S', '6', NULL, '1', '1', NULL, SYSDATE);
--CODE
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'CODE', '1', '2021', '87', 'B9C975E5A8C5F59EE053B11FA8C05A36', 'CODE', 'PERF_T_ADJUSTINDEX', '编码', 'S', '300', NULL, '1', '0', NULL,SYSDATE);
--FINDEX
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, 'PMKPIFRAME', NULL, '1', 'FINDEX', '1', '2016', '87', 'B9C975E5A8CAF59EE053B11FA8C05A36', 'FINDEX', 'PERF_T_ADJUSTINDEX', '一级指标', 'S', '300', NULL, '1', '1', NULL, SYSDATE);
--INDEXVAL
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'INDEXVAL', '1', '2016', '87', 'B9C975E5A8CDF59EE053B11FA8C05A36', 'INDEXVAL', 'PERF_T_ADJUSTINDEX', '指标值', 'S', '1000', NULL, '1', '1', NULL, SYSDATE);
--KPI_LV1
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'KPI_LV1', '1', '2021', '87', 'B9C975E5A8B6F59EE053B11FA8C05A36', 'KPI_LV1', 'PERF_T_ADJUSTINDEX', '一级指标', 'S', '300', NULL, '1', '1', NULL, SYSDATE);
--KPI_LV2
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'KPI_LV2', '1', '2021', '87', 'B9C975E5A8B7F59EE053B11FA8C05A36', 'KPI_LV2', 'PERF_T_ADJUSTINDEX', '二级指标', 'S', '300', NULL, '1', '1', NULL, SYSDATE);
--KPI_LV3
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'KPI_LV3', '1', '2021', '87', 'B9C975E5A8B8F59EE053B11FA8C05A36', 'KPI_LV3', 'PERF_T_ADJUSTINDEX', '三级指标', 'S', '300', NULL, '1', '1', NULL, SYSDATE);
--KPI_VAL
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'KPI_VAL', '1', '2021', '87', 'B9C975E5A8B9F59EE053B11FA8C05A36', 'KPI_VAL', 'PERF_T_ADJUSTINDEX', '指标值', 'S', '1000', NULL, '1', '1', NULL,SYSDATE);
--NAME
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'NAME', '1', '2016', '87', 'B9C975E5A8D2F59EE053B11FA8C05A36', 'NAME', 'PERF_T_ADJUSTINDEX', '三级指标名称', 'S', '1000', NULL, '1', '1', NULL, SYSDATE);
--SINDEX
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, 'PMKPIFRAME', NULL, '1', 'SINDEX', '1', '2016', '87', 'B9C975E5A8D7F59EE053B11FA8C05A36', 'SINDEX', 'PERF_T_ADJUSTINDEX', '二级指标', 'S', '300', NULL, '1', '1', NULL,SYSDATE);
--TARGETVALUE
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'TARGETVALUE', '1', '2021', '87', 'B9C975E5A8DAF59EE053B11FA8C05A36', 'TARGETVALUE', 'PERF_T_ADJUSTINDEX', '目标值', 'S', '1000', NULL, '1', '0', NULL, SYSDATE);
--TINDEX
INSERT INTO bus_t_diccolumn("DEID", "CSID", "EXP", "ISSYS", "DBCOLUMNCODE", "ISUSES", "YEAR", "PROVINCE", "COLUMNID", "COLUMNCODE", "TABLECODE", "NAME", "DATATYPE", "DATALENGTH", "SCALE", "VERSION", "NULLABLE", "DEFAULTVALUE", "DBVERSION") VALUES (NULL, NULL, NULL, '1', 'TINDEX', '1', '2021', '87', 'B9C975E5A8DBF59EE053B11FA8C05A36', 'TINDEX','PERF_T_ADJUSTINDEX', '模板/案例三级指标', 'S', '300', NULL, '1', '0', NULL, SYSDATE);
