begin

DELETE FROM bus_t_Diccolumn t where t.tablecode='P#BUSFW_T_UITABPAGE' and t.columncode in ('COMPONENTKEY','COMPONENTCALLBACKFN','DEFAULTFILTER','COMPONENTID','COMPONENTCONFIG','COMPONENTSERVICEID','COMPONENTDRAW');
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'COMPONENTKEY', '1', '2016', '87', 'BFFB5D877106FDC9E053B11FA8C0823E', 'COMPONENTKEY', 'P#BUSFW_T_UITABPAGE', 'COMPONENTKEY', 's', '255', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'COMPONENTCALLBACKFN', '1', '2016', '87', 'BFFB5D877107FDC9E053B11FA8C0823E', 'COMPONENTCALLBACKFN', 'P#BUSFW_T_UITABPAGE', 'COMPONENTCALLBACKFN', 's', '32', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'DEFAULTFILTER', '1', '2016', '87', 'BFFB5D877105FDC9E053B11FA8C0823E', 'DEFAULTFILTER', 'P#BUSFW_T_UITABPAGE', '默认值', 's', '500', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'COMPONENTID', '1', '2016', '87', 'BFFB5D877102FDC9E053B11FA8C0823E', 'COMPONENTID', 'P#BUSFW_T_UITABPAGE', '组件ID', 's', '100', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'COMPONENTCONFIG', '1', '2016', '87', 'BFFB5D877108FDC9E053B11FA8C0823E', 'COMPONENTCONFIG', 'P#BUSFW_T_UITABPAGE', 'COMPONENTCONFIG', 's', '500', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'COMPONENTSERVICEID', '1', '2016', '87', 'BFFB5D877104FDC9E053B11FA8C0823E', 'COMPONENTSERVICEID', 'P#BUSFW_T_UITABPAGE', 'COMPONENTSERVICEID', 's', '100', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'COMPONENTDRAW', '1', '2016', '87', 'BFFB5D877103FDC9E053B11FA8C0823E', 'COMPONENTDRAW', 'P#BUSFW_T_UITABPAGE', 'COMPONENTDRAW', 's', '32', null, 1, 1, null, sysdate);

DELETE FROM bus_t_Diccolumn t where t.tablecode='BUSFW_T_UITABPAGE' and t.columncode in ('COMPONENTKEY','COMPONENTCALLBACKFN','DEFAULTFILTER','COMPONENTID','COMPONENTCONFIG','COMPONENTSERVICEID','COMPONENTDRAW');
insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'COMPONENTKEY', '1', '2016', '87', 'C024A30CA9962308E053B11FA8C0C3B1', 'COMPONENTKEY', 'BUSFW_T_UITABPAGE', 'COMPONENTKEY', 's', '255', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'COMPONENTCALLBACKFN', '1', '2016', '87', 'C024A30CA9982308E053B11FA8C0C3B1', 'COMPONENTCALLBACKFN', 'BUSFW_T_UITABPAGE', 'COMPONENTCALLBACKFN', 's', '32', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'DEFAULTFILTER', '1', '2016', '87', 'C024A30CA9992308E053B11FA8C0C3B1', 'DEFAULTFILTER', 'BUSFW_T_UITABPAGE', '默认值', 's', '500', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'COMPONENTID', '1', '2016', '87', 'C024A30CA99D2308E053B11FA8C0C3B1', 'COMPONENTID', 'BUSFW_T_UITABPAGE', '组件ID', 's', '100', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'COMPONENTCONFIG', '1', '2016', '87', 'C024A30CA9A02308E053B11FA8C0C3B1', 'COMPONENTCONFIG', 'BUSFW_T_UITABPAGE', 'COMPONENTCONFIG', 's', '500', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'COMPONENTSERVICEID', '1', '2016', '87', 'C024A30CA9A22308E053B11FA8C0C3B1', 'COMPONENTSERVICEID', 'BUSFW_T_UITABPAGE', 'COMPONENTSERVICEID', 's', '100', null, 1, 1, null, sysdate);

insert into Bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '0', 'COMPONENTDRAW', '1', '2016', '87', 'C024A30CA9A42308E053B11FA8C0C3B1', 'COMPONENTDRAW', 'BUSFW_T_UITABPAGE', 'COMPONENTDRAW', 's', '32', null, 1, 1, null, sysdate);

DELETE FROM bus_t_Diccolumn t where t.tablecode='BUSFW_T_UICOLUMN' and t.columncode in ('ISEDIT','ISSOURCE','ISVISIABLE','REQUIREMENT','TYPE');
insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '87007Dzvfa09', null, '0', 'ISEDIT', '1', '2015', '87', '86659384A3EF5276E05357FE7B0AE3B9', 'ISEDIT', 'BUSFW_T_UICOLUMN', '是否可编辑', 'n', null, null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '8700I935L0bK', null, '0', 'ISSOURCE', '1', '2015', '87', '86659384A3F95276E05357FE7B0AE3B9', 'ISSOURCE', 'BUSFW_T_UICOLUMN', '是否有来源', 'n', '1', null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '8700I935L0bK', null, '0', 'ISVISIABLE', '1', '2015', '87', '86659384A3EE5276E05357FE7B0AE3B9', 'ISVISIABLE', 'BUSFW_T_UICOLUMN', '是否显示', 'n', null, null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '8700I935L0bK', null, '0', 'REQUIREMENT', '1', '2015', '87', '86659384A3F25276E05357FE7B0AE3B9', 'REQUIREMENT', 'BUSFW_T_UICOLUMN', '校验', 'n', null, null, 1, 1, null, sysdate);

insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '8700vKBAsP9B', null, '0', 'TYPE', '1', '2015', '87', '86659384A3FA5276E05357FE7B0AE3B9', 'TYPE', 'BUSFW_T_UICOLUMN', '来源类型', 's', '50', null, 1, 1, null, sysdate);

DELETE FROM bus_t_Diccolumn t where t.tablecode='BUSFW_T_UIQUERYFORM' and t.columncode='TYPE';
insert into bus_t_Diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, '8700vKBAsP9B', null, '0', 'TYPE', '1', '2015', '87', '86659384A3BD5276E05357FE7B0AE3B9', 'TYPE', 'BUSFW_T_UIQUERYFORM', '类型', 's', '50', null, 1, 1, null, sysdate);
