begin

delete from bus_t_diccolumn where tablecode = 'PERF_T_DEPTEVALUATION' and columncode in ('FUND_TYPE_CODE','FUND_TYPE','AMT1');
insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, null, null, '1', 'AMT1', '1', '2016', '87', '3B824F087834D2F5836B70F361D530B4', 'AMT1', 'PERF_T_DEPTEVALUATION', '预留资金字段', 'S', '40', null, null, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'HBDEPTEVALFUNDTYPE', null, '1', 'FUND_TYPE', '1', '2016', '87', '2C161EF273CE585D0BF28D6C97E33C94', 'FUND_TYPE', 'PERF_T_DEPTEVALUATION', '资金性质(湖北)', 'S', '40', null, 1, 1, null, sysdate);

insert into bus_t_diccolumn (DEID, CSID, EXP, ISSYS, DBCOLUMNCODE, ISUSES, YEAR, PROVINCE, COLUMNID, COLUMNCODE, TABLECODE, NAME, DATATYPE, DATALENGTH, SCALE, VERSION, NULLABLE, DEFAULTVALUE, DBVERSION)
values (null, 'JXFUNDTYPE', null, '1', 'FUND_TYPE_CODE', '1', '2016', '87', '08FF5D9CE3BF5B11E0630A64A8C06A0D', 'FUND_TYPE_CODE', 'PERF_T_DEPTEVALUATION', '资金来源', 'S', '40', null, 1, 1, null, sysdate);

