BEGIN

 execute immediate 'CREATE OR REPLACE VIEW v_perf_eval_indicator
 AS
SELECT 
t.*,
t1.EVAL_VALUE,
t1.DEVI_ANALY,
''1'' as isedit
FROM V_PM_PERF_INDICATOR T LEFT JOIN (select * from V_GD_PERF_EVAL_DTL where is_deleted = 2) T1 ON t.kpi_id = t1.kpi_id
where t.yearflag = ''0'' and t.is_deleted = 2';

 execute immediate 'CREATE OR REPLACE VIEW v_perf_eval_indicator_ind
 AS
SELECT 
t.guid,
    t.code,
    t.explain,
    --t.weight,
	t1.ind_weight as weight,
    t.islinked,
    t.agencyguid,
    t.wfstatus,
    t.status,
    t.createtime,
    t.updatetime,
    t.creater,
    t.province,
    t.year,
    t.ordernum,
    t.finintorgguid,
    t.mainguid,
    t.superid,
    t.levelno,
    t.rule,
    t.computesign,
    t.meterunit,
    t.tindex,
    t.wfid,
    t.proguid,
    t.targetvalue,
    t.kpi_id,
    t.mof_div_code,
    t.fiscal_year,
    t.pro_code,
    t.lv1_perf_ind_code,
    t.lv2_perf_ind_code,
    t.lv3_perf_ind_code,
    t.kpi_content,
    t.kpi_evalstd,
    t.kpi_val,
    t.kpi_remark,
    t.version,
    t.version_name,
    t.sub_mof_div_code,
    t.update_time,
    t.is_deleted,
    t.create_time,
    t.agency_code,
    t.findex,
    t.sindex,
    t.name,
    t.indexval,
    t.fromguid,
    t.yearflag,
    t.kpivalsource,
    t.value_remark,
    t.value_desc,
    t.is_add,
    t.busi_type_code,
    t.opinion_remark,
    t.fromisdel,
    t.goalguid,
    t.indexstandards,
    t.isstandpush,
    t.computetype,
    t.referenceval,
    t.referencestandards,
    t.snindexval,
    t.qnindexval,
    t.endvaltype,
    t.endvalsource,
    t.valrule,
    t.evidencefile,
    t.value_change,
    t.transguid,
    t.isunmod,
    t.mof_div_name,
    t.agency_name,
    t.pro_name,
    t.lv1_perf_ind_name,
    t.lv2_perf_ind_name,
    t.lv3_perf_ind_name,
    t.sub_mof_div_name,
    t.perf_obj_type_code,
    t.perf_obj_type_name,
    t.spe_pro_code,
    t.spe_pro_name,
    t.mof_aud_opinion_code,
    t.mof_aud_opinion_name,
    t.bgt_id,
    t.ori_div_code,
    t.ori_div_name,
    t.is_last_inst,
    t.is_backup,
    t.is_adj,
    t.versiontype,
t1.EVAL_VALUE,
t1.DEVI_ANALY,
''1'' as isedit
FROM V_PM_PERF_INDICATOR T LEFT JOIN (select * from V_GD_PERF_EVAL_DTL where is_deleted = 2) T1 ON t.kpi_id = t1.kpi_id
where t.yearflag = ''0'' and t.is_deleted = 2';
 end;