begin
--update perf_t_warnset t set t.warnsql = 'select to_char(nvl(s.score, 0) + nvl(a.bgtscore,0),''FM990.00'') as value FROM v_perf_t_selfevaltask t left join (select c.mainguid, c.pro_code, sum(c.score) score from V_PERF_T_SELFPERFINDEX c group by c.mainguid, c.pro_code) s on t.pro_code=s.pro_code left join (select nvl(nvl(sum(AMT4),0)/decode(nvl(sum(AMT3),1),0,1,nvl(sum(AMT3),1)) * 10, 0) bgtscore, pro_code from v_perf_t_selfprofund group by pro_code) a on t.pro_code = a.pro_code where t.guid = ''#mainguid#''' where type = 'selfscoreprogram';


update perf_t_warnset t set t.warnsql = 'select to_char(nvl(s.score, 0)) as value FROM v_perf_t_selfevaltask t left join (select c.mainguid, c.pro_code, sum(c.score) score from V_PERF_T_SELFPERFINDEX c group by c.mainguid, c.pro_code) s on t.pro_code=s.pro_code where t.guid = ''#mainguid#''' where type = 'selfscoreprogram';

select fn_altertablecol('perf_t_warnset', 'warnsql', 'VARCHAR2', '4000');

update perf_t_warnset t set t.warnsql = 'select case when (nvl(s.score,0) >= 90 and pro.IS_SCIENTIFIC = 1) or (nvl(s.score,0) >= 90 and a.name = ''其他'') then ''优'' when ((nvl(s.score,0) >= 80 and nvl(s.score,0) < 90) and pro.IS_SCIENTIFIC = 1) or (nvl(s.score,0) >= 80 and nvl(s.score,0) < 90 and a.name = ''其他'') then ''良'' when ((nvl(s.score,0) >= 60 and nvl(s.score,0) < 80) and pro.IS_SCIENTIFIC = 1) or (nvl(s.score,0) >= 60 and nvl(s.score,0) < 80 and a.name = ''其他'') then ''中'' when (nvl(s.score,0) < 60 and pro.IS_SCIENTIFIC = 1) or (nvl(s.score,0) < 60 and a.name = ''其他'') then ''差'' when (nvl(s.score,0) >= 90 and nvl(a.bgtget,0) >= 91 and pro.IS_SCIENTIFIC = 2 and a.name like ''%一般公共预算资金%'') then ''优'' when (nvl(s.score,0) >= 90 and (nvl(a.bgtget,0) < 91 and nvl(a.bgtget,0) >= 50) and pro.IS_SCIENTIFIC = 2 and a.name like ''%一般公共预算资金%'') then ''良'' when (nvl(s.score,0) >= 90 and nvl(a.bgtget,0) < 50 and pro.IS_SCIENTIFIC = 2 and a.name like ''%一般公共预算资金%'') then ''中'' when ((nvl(s.score,0) >= 80 and nvl(s.score,0) < 90) and nvl(a.bgtget,0) >= 50 and pro.IS_SCIENTIFIC = 2 and a.name like ''%一般公共预算资金%'') then ''良'' when ((nvl(s.score,0) >= 80 and nvl(s.score,0) < 90) and nvl(a.bgtget,0) < 50 and pro.IS_SCIENTIFIC = 2 and a.name like ''%一般公共预算资金%'') then ''中'' when (nvl(s.score,0) >= 60 and nvl(s.score,0) < 80 and pro.IS_SCIENTIFIC = 2 and a.name like ''%一般公共预算资金%'') then ''中'' when (nvl(s.score,0) < 60 and pro.IS_SCIENTIFIC = 2 and a.name like ''%一般公共预算资金%'') then ''差'' end as value FROM (select c.mainguid, c.pro_code, sum(c.score) as score from V_PERF_T_SELFPERFINDEX c group by c.mainguid, c.pro_code) s left join (select string_agg(distinct pro_code,'','') as pro_code,string_agg(distinct name,'','') as name,max(bgtget) as bgtget from (select pro_code,sum(bgtget) as bgtget,''一般公共预算资金'' as name from perf_t_selfprofund where  name = ''一般公共预算资金''  group by pro_code union select pro_code,0 as bgtget,''其他'' as name from perf_t_selfprofund where  name != ''一般公共预算资金'' group by pro_code) group by 	pro_code)a on a.pro_code = s.pro_code left join v_perf_project_info pro on pro.pro_code = s.pro_code where s.mainguid = ''#mainguid#''' where type = 'selfresultprogram';


